-- 043_api_tokens.sql — Migration: api_tokens
-- Generated by noctus.dev.scaffold_migration on 2026-07-20
-- Schema: erp
--
-- erp-httponly-cookie-session-2026-07 roadmap, Slice 2: mount the seed
-- auth router's `/api/settings/api-tokens` management endpoints on ERP.
-- `noctusai_seed.auth_router.create_auth_router` reads/writes an
-- `api_tokens` table in the PRODUCT's own schema via `deps.get_admin_client()`
-- (see that module's `create_api_token` / `list_api_tokens` / `revoke_api_token`
-- handlers) — mirrors `products/social-wiring/backend/migrations/
-- 001_social-wiring.sql`'s `social_wiring.api_tokens` shape (byte-identical
-- column set; only the schema + index-name prefix differ). RLS mirrors
-- social-wiring's `011_rls_current_org_id.sql` policy shape, using
-- `erp.current_org_id()` (already defined by migration 032).

-- ============================================================
-- Schema lock — pin name resolution to erp, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = erp, public;

CREATE TABLE erp.api_tokens (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id           UUID NOT NULL,
    label            TEXT NOT NULL,
    token_hash       TEXT NOT NULL UNIQUE,
    token_prefix     TEXT NOT NULL,
    scopes           TEXT[] NOT NULL DEFAULT '{}',
    created_by       UUID,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at     TIMESTAMPTZ,
    revoked_at       TIMESTAMPTZ
);

ALTER TABLE erp.api_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "api_tokens_select_own_org" ON erp.api_tokens
    FOR SELECT TO authenticated
    USING (org_id = current_org_id());

-- INSERT + UPDATE limited to owner/admin org_role (matches the platform's
-- convention for sensitive config; org_role lives in public.noctus_users —
-- the same trusted-DB gate `noctusai_seed.auth_router._require_org_admin`
-- reads via `deps.get_core_client()`).
CREATE POLICY "api_tokens_insert_own_org_admin" ON erp.api_tokens
    FOR INSERT TO authenticated
    WITH CHECK (
        org_id = current_org_id()
        AND EXISTS (
            SELECT 1 FROM public.noctus_users nu
            WHERE nu.id = (SELECT auth.uid())
              AND nu.org_id = erp.api_tokens.org_id
              AND nu.org_role IN ('owner', 'admin')
        )
    );

CREATE POLICY "api_tokens_update_own_org_admin" ON erp.api_tokens
    FOR UPDATE TO authenticated
    USING (
        org_id = current_org_id()
        AND EXISTS (
            SELECT 1 FROM public.noctus_users nu
            WHERE nu.id = (SELECT auth.uid())
              AND nu.org_id = erp.api_tokens.org_id
              AND nu.org_role IN ('owner', 'admin')
        )
    );

CREATE POLICY "api_tokens_service_role" ON erp.api_tokens
    FOR ALL TO service_role
    USING (true) WITH CHECK (true);

CREATE INDEX idx_erp_api_tokens_org ON erp.api_tokens(org_id) WHERE revoked_at IS NULL;
CREATE UNIQUE INDEX idx_erp_api_tokens_hash_active ON erp.api_tokens(token_hash) WHERE revoked_at IS NULL;
