-- ============================================================================
-- MOCK MATCHING SEED DATA
-- Inserts 100 imóveis + 40 permutas with varying similarity levels.
-- All records tagged with [MOCK-MATCHING-TEST] in observacoes for easy cleanup.
--
-- BEFORE RUNNING: Replace the owner_id UUIDs below with real auth.users IDs
-- from your Supabase project. Use 2-3 different users so same-owner filtering
-- is exercised (matches skip same-owner pairs).
-- ============================================================================

-- ─── CONFIG: Set your real user IDs here ────────────────────────────────────
DO $$
DECLARE
  -- Replace these with real auth.users UUIDs from your project
  owner_a UUID := '00000000-0000-0000-0000-000000000001'; -- User A (owns imóveis)
  owner_b UUID := '00000000-0000-0000-0000-000000000002'; -- User B (owns permutas)
  owner_c UUID := '00000000-0000-0000-0000-000000000003'; -- User C (owns some of each)
BEGIN

-- ════════════════════════════════════════════════════════════════════════════
-- PART 1: IMÓVEIS (100 records)
-- All have aceita_permutas = true so they participate in matching.
-- Distributed across São Paulo capital, ABC, Campinas, Santos, Curitiba.
-- ════════════════════════════════════════════════════════════════════════════

-- ─── São Paulo - Zona Sul (20 imóveis, R$400k-1.2M) ────────────────────────
INSERT INTO erp.ativos (owner_id, natureza, valor, status, aceita_permutas, tipo_imovel, cidade, estado, bairro, zona, quartos, suites, banheiros, vagas, area_privativa, area_total, andar, titulo_anuncio, descricao_seo, fotos, pontos_de_interesse, observacoes, interesses, finalidade) VALUES
(owner_a, 'imovel', 450000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Moema', 'Zona Sul', 2, 1, 2, 1, 65, 72, 8, 'Apto 2 quartos Moema próx. metrô', 'Apartamento reformado com 2 quartos em Moema, próximo ao metrô e Ibirapuera. Lazer completo.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Metrô Moema','Parque Ibirapuera','Shopping Ibirapuera'], '[MOCK-MATCHING-TEST] SP-ZS-01', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":300000,"valor_max":600000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 680000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Vila Mariana', 'Zona Sul', 3, 1, 2, 2, 85, 95, 12, 'Apto 3 dorms Vila Mariana vista livre', 'Amplo apartamento 3 dormitórios com vista livre em Vila Mariana. Próximo ao metrô Santa Cruz.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Metrô Santa Cruz','Parque Ibirapuera'], '[MOCK-MATCHING-TEST] SP-ZS-02', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":400000,"valor_max":800000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 520000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Saúde', 'Zona Sul', 2, 1, 1, 1, 58, 64, 5, 'Apto 2 quartos Saúde metrô', 'Apartamento 2 quartos próximo ao metrô Saúde. Condomínio com lazer.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Metrô Saúde'], '[MOCK-MATCHING-TEST] SP-ZS-03', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":350000,"valor_max":700000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 950000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Brooklin', 'Zona Sul', 3, 2, 3, 2, 110, 125, 18, 'Apto alto padrão Brooklin 3 suítes', 'Apartamento de alto padrão no Brooklin com 3 suítes, varanda gourmet e 2 vagas. Prédio novo.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['Shopping Morumbi','Berrini','Ponte Estaiada'], '[MOCK-MATCHING-TEST] SP-ZS-04', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":600000,"valor_max":1200000},{"tipo":"automovel","marca":"BMW","valor_min":150000,"valor_max":300000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 380000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Jabaquara', 'Zona Sul', 2, 0, 1, 1, 50, 55, 3, 'Apto 2 dorms Jabaquara econômico', 'Apartamento 2 dormitórios no Jabaquara, próximo ao metrô. Ótimo custo-benefício.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Metrô Jabaquara'], '[MOCK-MATCHING-TEST] SP-ZS-05', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":250000,"valor_max":500000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 1150000, 'ativo', true, 'casa', 'São Paulo', 'SP', 'Campo Belo', 'Zona Sul', 4, 2, 4, 3, 180, 220, NULL, 'Casa 4 quartos Campo Belo com piscina', 'Sobrado com 4 quartos, piscina e churrasqueira no Campo Belo. Terreno de 220m².', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg','foto6.jpg'], ARRAY['Shopping Campo Belo','Aeroporto Congonhas'], '[MOCK-MATCHING-TEST] SP-ZS-06', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"São Paulo","valor_min":800000,"valor_max":1500000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 420000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Santo Amaro', 'Zona Sul', 2, 1, 1, 1, 55, 60, 6, 'Apto 2 dorms Santo Amaro metro', 'Apartamento 2 dormitórios próximo ao largo de Santo Amaro e metrô.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Metrô Santo Amaro'], '[MOCK-MATCHING-TEST] SP-ZS-07', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":300000,"valor_max":550000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 780000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Moema', 'Zona Sul', 3, 1, 2, 2, 92, 105, 15, 'Apto 3 quartos Moema reformado', 'Apartamento completamente reformado em Moema. 3 quartos, suíte, varanda.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Parque Ibirapuera','Shopping Ibirapuera','Metrô Moema'], '[MOCK-MATCHING-TEST] SP-ZS-08', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":500000,"valor_max":1000000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 550000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Chácara Klabin', 'Zona Sul', 2, 1, 2, 1, 70, 78, 10, 'Apto Chácara Klabin 2 suítes', 'Apartamento com 2 suítes na Chácara Klabin, vista para o parque.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Parque da Aclimação'], '[MOCK-MATCHING-TEST] SP-ZS-09', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":350000,"valor_max":700000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 890000, 'ativo', true, 'cobertura', 'São Paulo', 'SP', 'Vila Mariana', 'Zona Sul', 3, 2, 3, 2, 140, 180, 20, 'Cobertura duplex Vila Mariana terraço', 'Cobertura duplex com terraço gourmet em Vila Mariana. 140m² privativos.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['Metrô Vila Mariana','SESC Vila Mariana'], '[MOCK-MATCHING-TEST] SP-ZS-10', '[{"tipo":"imovel","tipo_imovel":"cobertura","cidade":"São Paulo","valor_min":600000,"valor_max":1200000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 470000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Sacomã', 'Zona Sul', 2, 1, 1, 1, 52, 58, 7, 'Apto 2 dorms Sacomã novo', 'Apartamento novo no Sacomã com lazer completo. Próximo ao metrô.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Metrô Sacomã'], '[MOCK-MATCHING-TEST] SP-ZS-11', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":300000,"valor_max":600000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 620000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Ipiranga', 'Zona Sul', 3, 1, 2, 1, 78, 88, 9, 'Apto 3 dorms Ipiranga próx. museu', 'Apartamento 3 dormitórios no Ipiranga, próximo ao Museu do Ipiranga.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Museu do Ipiranga','Parque da Independência'], '[MOCK-MATCHING-TEST] SP-ZS-12', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":400000,"valor_max":800000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 350000, 'ativo', true, 'studio', 'São Paulo', 'SP', 'Vila Clementino', 'Zona Sul', 1, 0, 1, 1, 35, 38, 14, 'Studio Vila Clementino mobiliado', 'Studio compacto e moderno totalmente mobiliado na Vila Clementino.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Hospital São Paulo','Unifesp'], '[MOCK-MATCHING-TEST] SP-ZS-13', '[{"tipo":"imovel","tipo_imovel":"studio","cidade":"São Paulo","valor_min":200000,"valor_max":450000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 1050000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Itaim Bibi', 'Zona Sul', 3, 2, 3, 2, 120, 135, 22, 'Apto Itaim Bibi 3 suítes lazer completo', 'Apartamento de alto padrão no Itaim Bibi. 3 suítes, varanda gourmet, 2 vagas.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['Parque do Povo','Shopping JK','Faria Lima'], '[MOCK-MATCHING-TEST] SP-ZS-14', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":700000,"valor_max":1400000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 490000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Cursino', 'Zona Sul', 2, 1, 1, 1, 56, 62, 4, 'Apto 2 dorms Cursino reformado', 'Apartamento reformado no Cursino com 2 dormitórios e vaga coberta.', ARRAY['foto1.jpg','foto2.jpg'], NULL, '[MOCK-MATCHING-TEST] SP-ZS-15', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":300000,"valor_max":650000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 720000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Saúde', 'Zona Sul', 3, 1, 2, 2, 88, 98, 11, 'Apto 3 dorms Saúde com varanda', 'Apartamento espaçoso 3 dorms com varanda na Saúde. Condomínio clube.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Metrô Saúde','Shopping Plaza Sul'], '[MOCK-MATCHING-TEST] SP-ZS-16', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":500000,"valor_max":900000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 1200000, 'ativo', true, 'casa', 'São Paulo', 'SP', 'Granja Julieta', 'Zona Sul', 4, 3, 5, 4, 250, 350, NULL, 'Casa Granja Julieta 4 suítes piscina', 'Casa em condomínio fechado na Granja Julieta. 4 suítes, piscina, gourmet.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg','foto6.jpg','foto7.jpg'], ARRAY['Shopping Morumbi'], '[MOCK-MATCHING-TEST] SP-ZS-17', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"São Paulo","valor_min":900000,"valor_max":1800000},{"tipo":"automovel","marca":"Mercedes-Benz","valor_min":200000,"valor_max":500000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 580000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Brooklin', 'Zona Sul', 2, 1, 2, 1, 68, 75, 16, 'Apto 2 suítes Brooklin moderno', 'Apartamento moderno 2 suítes no Brooklin. Prédio com lazer e coworking.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Berrini','Shopping Morumbi'], '[MOCK-MATCHING-TEST] SP-ZS-18', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":400000,"valor_max":750000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 410000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Vila Mascote', 'Zona Sul', 2, 0, 1, 1, 48, 54, 2, 'Apto 2 dorms Vila Mascote térreo', 'Apartamento 2 dormitórios térreo com quintal na Vila Mascote.', ARRAY['foto1.jpg','foto2.jpg'], NULL, '[MOCK-MATCHING-TEST] SP-ZS-19', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":250000,"valor_max":550000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 830000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Campo Belo', 'Zona Sul', 3, 1, 2, 2, 95, 108, 13, 'Apto 3 dorms Campo Belo lazer', 'Amplo 3 dormitórios no Campo Belo com lazer completo e 2 vagas.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Aeroporto Congonhas','Shopping Campo Belo'], '[MOCK-MATCHING-TEST] SP-ZS-20', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":550000,"valor_max":1100000}]'::jsonb, 'venda'),

-- ─── São Paulo - Zona Oeste (15 imóveis, R$500k-1.5M) ──────────────────────
(owner_a, 'imovel', 550000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Pinheiros', 'Zona Oeste', 2, 1, 1, 1, 60, 68, 7, 'Apto 2 dorms Pinheiros boêmio', 'Apartamento charmoso em Pinheiros, bairro boêmio. Próximo ao metrô Fradique Coutinho.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Metrô Fradique Coutinho','Beco do Batman'], '[MOCK-MATCHING-TEST] SP-ZO-01', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":350000,"valor_max":700000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 920000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Vila Madalena', 'Zona Oeste', 3, 1, 2, 2, 95, 108, 10, 'Apto 3 dorms Vila Madalena reformado', 'Apartamento totalmente reformado na Vila Madalena com 3 dormitórios.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Beco do Batman','Praça Benedito Calixto'], '[MOCK-MATCHING-TEST] SP-ZO-02', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":600000,"valor_max":1200000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 750000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Perdizes', 'Zona Oeste', 3, 1, 2, 1, 82, 92, 8, 'Apto 3 dorms Perdizes silencioso', 'Apartamento 3 dormitórios em rua tranquila de Perdizes.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['PUC-SP','SESC Pompeia'], '[MOCK-MATCHING-TEST] SP-ZO-03', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":500000,"valor_max":1000000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 1350000, 'ativo', true, 'casa', 'São Paulo', 'SP', 'Alto de Pinheiros', 'Zona Oeste', 4, 2, 4, 3, 200, 300, NULL, 'Casa Alto de Pinheiros 4 quartos', 'Sobrado com 4 quartos em rua arborizada do Alto de Pinheiros.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['Parque Villa-Lobos','Pico do Jaraguá'], '[MOCK-MATCHING-TEST] SP-ZO-04', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"São Paulo","valor_min":1000000,"valor_max":2000000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 480000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Lapa', 'Zona Oeste', 2, 0, 1, 1, 52, 58, 4, 'Apto 2 dorms Lapa econômico', 'Apartamento 2 dormitórios na Lapa. Próximo à estação de trem.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Estação Lapa'], '[MOCK-MATCHING-TEST] SP-ZO-05', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":300000,"valor_max":600000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 650000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Pompeia', 'Zona Oeste', 2, 1, 2, 1, 72, 80, 11, 'Apto 2 suítes Pompeia moderno', 'Apartamento moderno 2 suítes na Pompeia. Prédio novo com lazer.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['SESC Pompeia','Allianz Parque'], '[MOCK-MATCHING-TEST] SP-ZO-06', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":450000,"valor_max":850000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 1100000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Pinheiros', 'Zona Oeste', 3, 2, 3, 2, 115, 130, 19, 'Apto 3 suítes Pinheiros alto padrão', 'Alto padrão em Pinheiros. 3 suítes, varanda gourmet, 2 vagas.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['Metrô Faria Lima','Shopping Eldorado'], '[MOCK-MATCHING-TEST] SP-ZO-07', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":750000,"valor_max":1500000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 530000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Barra Funda', 'Zona Oeste', 2, 1, 1, 1, 58, 65, 6, 'Apto 2 dorms Barra Funda metro', 'Apartamento 2 dorms próximo ao metrô Barra Funda. Fácil acesso.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Metrô Barra Funda','Memorial da América Latina'], '[MOCK-MATCHING-TEST] SP-ZO-08', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":350000,"valor_max":700000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 870000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Sumaré', 'Zona Oeste', 3, 1, 2, 2, 90, 100, 14, 'Apto 3 dorms Sumaré com vista', 'Apartamento 3 dorms no Sumaré com vista para a cidade.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Praça Vilaboim'], '[MOCK-MATCHING-TEST] SP-ZO-09', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":600000,"valor_max":1100000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 440000, 'ativo', true, 'studio', 'São Paulo', 'SP', 'Vila Leopoldina', 'Zona Oeste', 1, 0, 1, 1, 38, 42, 20, 'Studio Vila Leopoldina novo', 'Studio novo na Vila Leopoldina com vista. Próximo ao CEAGESP.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Villa-Lobos'], '[MOCK-MATCHING-TEST] SP-ZO-10', '[{"tipo":"imovel","tipo_imovel":"studio","cidade":"São Paulo","valor_min":250000,"valor_max":550000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 680000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Água Branca', 'Zona Oeste', 3, 1, 2, 1, 80, 90, 9, 'Apto 3 dorms Água Branca', 'Apartamento 3 dormitórios na Água Branca. Próximo ao parque.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Parque da Água Branca'], '[MOCK-MATCHING-TEST] SP-ZO-11', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":450000,"valor_max":900000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 990000, 'ativo', true, 'cobertura', 'São Paulo', 'SP', 'Perdizes', 'Zona Oeste', 3, 2, 3, 2, 150, 200, 18, 'Cobertura Perdizes 3 suítes terraço', 'Cobertura com terraço panorâmico em Perdizes. 3 suítes, churrasqueira.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['PUC-SP','Allianz Parque'], '[MOCK-MATCHING-TEST] SP-ZO-12', '[{"tipo":"imovel","tipo_imovel":"cobertura","cidade":"São Paulo","valor_min":700000,"valor_max":1300000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 510000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Butantã', 'Zona Oeste', 2, 1, 1, 1, 55, 62, 5, 'Apto 2 dorms Butantã USP', 'Apartamento 2 dorms próximo à USP e ao metrô Butantã.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['USP','Metrô Butantã'], '[MOCK-MATCHING-TEST] SP-ZO-13', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":350000,"valor_max":650000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 1500000, 'ativo', true, 'casa', 'São Paulo', 'SP', 'City Boaçava', 'Zona Oeste', 5, 3, 5, 4, 280, 400, NULL, 'Casa City Boaçava 5 suítes luxo', 'Residência de luxo no City Boaçava. 5 suítes, piscina aquecida, automação.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg','foto6.jpg'], ARRAY['Parque Villa-Lobos'], '[MOCK-MATCHING-TEST] SP-ZO-14', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"São Paulo","valor_min":1000000,"valor_max":2500000},{"tipo":"automovel","marca":"Porsche","valor_min":300000,"valor_max":800000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 600000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Vila Romana', 'Zona Oeste', 2, 1, 2, 1, 65, 72, 8, 'Apto Vila Romana 2 suítes', 'Apartamento com 2 suítes na Vila Romana. Prédio com lazer completo.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Praça Charles Muller'], '[MOCK-MATCHING-TEST] SP-ZO-15', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":400000,"valor_max":800000}]'::jsonb, 'venda'),

-- ─── São Paulo - Zona Norte/Leste (15 imóveis, R$250k-800k) ────────────────
(owner_a, 'imovel', 320000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Santana', 'Zona Norte', 2, 0, 1, 1, 48, 52, 3, 'Apto 2 dorms Santana metrô', 'Apartamento 2 dorms próximo ao metrô Santana.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Metrô Santana'], '[MOCK-MATCHING-TEST] SP-ZN-01', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":200000,"valor_max":450000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 450000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Tucuruvi', 'Zona Norte', 2, 1, 2, 1, 60, 68, 8, 'Apto 2 suítes Tucuruvi novo', 'Apartamento novo 2 suítes no Tucuruvi. Metrô na porta.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Metrô Tucuruvi'], '[MOCK-MATCHING-TEST] SP-ZN-02', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":300000,"valor_max":600000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 580000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Mandaqui', 'Zona Norte', 3, 1, 2, 1, 75, 85, 6, 'Apto 3 dorms Mandaqui família', 'Apartamento 3 dormitórios ideal para família no Mandaqui.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Horto Florestal'], '[MOCK-MATCHING-TEST] SP-ZN-03', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":400000,"valor_max":750000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 280000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Vila Maria', 'Zona Norte', 2, 0, 1, 1, 45, 48, 2, 'Apto 2 dorms Vila Maria econômico', 'Apartamento econômico na Vila Maria. 2 dormitórios.', ARRAY['foto1.jpg'], NULL, '[MOCK-MATCHING-TEST] SP-ZN-04', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":180000,"valor_max":380000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 750000, 'ativo', true, 'casa', 'São Paulo', 'SP', 'Tremembé', 'Zona Norte', 3, 1, 3, 2, 130, 200, NULL, 'Casa Tremembé 3 quartos quintal', 'Casa com 3 quartos e quintal amplo no Tremembé.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Horto Florestal','Parque da Cantareira'], '[MOCK-MATCHING-TEST] SP-ZN-05', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"São Paulo","valor_min":500000,"valor_max":1000000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 380000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Tatuapé', 'Zona Leste', 2, 1, 1, 1, 55, 60, 5, 'Apto 2 dorms Tatuapé metrô', 'Apartamento 2 dorms próximo ao metrô Tatuapé e shopping.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Metrô Tatuapé','Shopping Metrô Tatuapé'], '[MOCK-MATCHING-TEST] SP-ZL-01', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":250000,"valor_max":500000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 520000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Anália Franco', 'Zona Leste', 3, 1, 2, 1, 72, 82, 10, 'Apto 3 dorms Anália Franco', 'Apartamento 3 dormitórios na Anália Franco. Região valorizada.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Shopping Anália Franco','Parque CERET'], '[MOCK-MATCHING-TEST] SP-ZL-02', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":350000,"valor_max":700000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 290000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Penha', 'Zona Leste', 2, 0, 1, 1, 46, 50, 3, 'Apto 2 dorms Penha econômico', 'Apartamento 2 dormitórios na Penha. Bom custo-benefício.', ARRAY['foto1.jpg'], ARRAY['Metrô Penha'], '[MOCK-MATCHING-TEST] SP-ZL-03', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":180000,"valor_max":400000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 650000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Mooca', 'Zona Leste', 3, 1, 2, 2, 85, 95, 12, 'Apto 3 dorms Mooca tradicional', 'Apartamento 3 dormitórios na tradicional Mooca. 2 vagas.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Shopping Mooca Plaza'], '[MOCK-MATCHING-TEST] SP-ZL-04', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":450000,"valor_max":850000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 420000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Vila Formosa', 'Zona Leste', 2, 1, 1, 1, 54, 60, 6, 'Apto 2 dorms Vila Formosa', 'Apartamento 2 dormitórios na Vila Formosa. Próximo ao parque.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Parque CERET'], '[MOCK-MATCHING-TEST] SP-ZL-05', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":280000,"valor_max":550000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 800000, 'ativo', true, 'casa', 'São Paulo', 'SP', 'Tatuapé', 'Zona Leste', 3, 2, 3, 2, 150, 200, NULL, 'Casa Tatuapé 3 suítes sobrado', 'Sobrado no Tatuapé com 3 suítes e espaço gourmet.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['Shopping Anália Franco'], '[MOCK-MATCHING-TEST] SP-ZL-06', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"São Paulo","valor_min":550000,"valor_max":1100000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 350000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Belém', 'Zona Leste', 2, 0, 1, 1, 50, 55, 4, 'Apto 2 dorms Belém estação', 'Apartamento 2 dorms próximo à estação Belém. Região em valorização.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Metrô Belém'], '[MOCK-MATCHING-TEST] SP-ZL-07', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":220000,"valor_max":480000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 470000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Vila Prudente', 'Zona Leste', 2, 1, 2, 1, 62, 70, 9, 'Apto 2 suítes Vila Prudente novo', 'Apartamento novo 2 suítes na Vila Prudente. Metrô próximo.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Metrô Vila Prudente'], '[MOCK-MATCHING-TEST] SP-ZL-08', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":300000,"valor_max":600000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 560000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Carrão', 'Zona Leste', 3, 1, 2, 1, 76, 86, 7, 'Apto 3 dorms Carrão familiar', 'Apartamento 3 dormitórios no Carrão. Ideal para família.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Metrô Carrão'], '[MOCK-MATCHING-TEST] SP-ZL-09', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":380000,"valor_max":720000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 700000, 'ativo', true, 'apartamento', 'São Paulo', 'SP', 'Jardim Anália Franco', 'Zona Leste', 3, 2, 3, 2, 100, 115, 16, 'Apto 3 suítes Jd Anália Franco', 'Apartamento 3 suítes no Jardim Anália Franco. Alto padrão zona leste.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['Shopping Anália Franco','Parque CERET'], '[MOCK-MATCHING-TEST] SP-ZL-10', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Paulo","valor_min":500000,"valor_max":900000}]'::jsonb, 'venda'),

-- ─── ABC Paulista (15 imóveis, R$250k-700k) ─────────────────────────────────
(owner_a, 'imovel', 350000, 'ativo', true, 'apartamento', 'Santo André', 'SP', 'Centro', NULL, 2, 1, 1, 1, 55, 62, 5, 'Apto 2 dorms Santo André centro', 'Apartamento 2 dormitórios no centro de Santo André.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Shopping ABC'], '[MOCK-MATCHING-TEST] ABC-01', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Santo André","valor_min":220000,"valor_max":480000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 480000, 'ativo', true, 'apartamento', 'São Bernardo do Campo', 'SP', 'Centro', NULL, 3, 1, 2, 1, 72, 80, 8, 'Apto 3 dorms SBC centro', 'Apartamento 3 dormitórios no centro de SBC. Próximo ao Paço Municipal.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Golden Square Shopping'], '[MOCK-MATCHING-TEST] ABC-02', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Bernardo do Campo","valor_min":320000,"valor_max":620000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 420000, 'ativo', true, 'apartamento', 'São Caetano do Sul', 'SP', 'Santa Paula', NULL, 2, 1, 2, 1, 65, 72, 10, 'Apto 2 suítes São Caetano', 'Apartamento 2 suítes em São Caetano do Sul. Cidade com melhor IDH.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Parque São Caetano'], '[MOCK-MATCHING-TEST] ABC-03', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Caetano do Sul","valor_min":280000,"valor_max":550000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 580000, 'ativo', true, 'apartamento', 'Santo André', 'SP', 'Jardim', NULL, 3, 1, 2, 2, 85, 95, 12, 'Apto 3 dorms Jardim Santo André', 'Apartamento 3 dormitórios no bairro Jardim de Santo André. 2 vagas.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], NULL, '[MOCK-MATCHING-TEST] ABC-04', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Santo André","valor_min":400000,"valor_max":750000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 300000, 'ativo', true, 'apartamento', 'Diadema', 'SP', 'Centro', NULL, 2, 0, 1, 1, 48, 52, 3, 'Apto 2 dorms Diadema econômico', 'Apartamento 2 dormitórios em Diadema. Ótimo custo-benefício.', ARRAY['foto1.jpg','foto2.jpg'], NULL, '[MOCK-MATCHING-TEST] ABC-05', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Diadema","valor_min":180000,"valor_max":400000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 650000, 'ativo', true, 'casa', 'São Bernardo do Campo', 'SP', 'Rudge Ramos', NULL, 3, 1, 3, 2, 140, 200, NULL, 'Casa SBC Rudge Ramos 3 quartos', 'Casa com 3 quartos em Rudge Ramos, SBC. Quintal com churrasqueira.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], NULL, '[MOCK-MATCHING-TEST] ABC-06', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"São Bernardo do Campo","valor_min":450000,"valor_max":850000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 380000, 'ativo', true, 'apartamento', 'Mauá', 'SP', 'Centro', NULL, 2, 0, 1, 1, 50, 56, 4, 'Apto 2 dorms Mauá centro', 'Apartamento 2 dormitórios no centro de Mauá.', ARRAY['foto1.jpg','foto2.jpg'], NULL, '[MOCK-MATCHING-TEST] ABC-07', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Mauá","valor_min":240000,"valor_max":500000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 520000, 'ativo', true, 'apartamento', 'São Caetano do Sul', 'SP', 'Osvaldo Cruz', NULL, 3, 1, 2, 1, 78, 88, 9, 'Apto 3 dorms São Caetano Osvaldo Cruz', 'Apartamento 3 dorms em São Caetano. Bairro nobre.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Shopping São Caetano'], '[MOCK-MATCHING-TEST] ABC-08', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Caetano do Sul","valor_min":350000,"valor_max":680000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 700000, 'ativo', true, 'cobertura', 'Santo André', 'SP', 'Campestre', NULL, 3, 2, 3, 2, 130, 170, 15, 'Cobertura Santo André Campestre', 'Cobertura duplex no bairro Campestre em Santo André. Terraço com churrasqueira.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], NULL, '[MOCK-MATCHING-TEST] ABC-09', '[{"tipo":"imovel","tipo_imovel":"cobertura","cidade":"Santo André","valor_min":500000,"valor_max":900000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 260000, 'ativo', true, 'apartamento', 'Ribeirão Pires', 'SP', 'Centro', NULL, 2, 0, 1, 1, 45, 48, 2, 'Apto 2 dorms Ribeirão Pires', 'Apartamento 2 dormitórios em Ribeirão Pires. Cidade tranquila.', ARRAY['foto1.jpg'], NULL, '[MOCK-MATCHING-TEST] ABC-10', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Ribeirão Pires","valor_min":160000,"valor_max":350000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 450000, 'ativo', true, 'apartamento', 'São Bernardo do Campo', 'SP', 'Baeta Neves', NULL, 2, 1, 2, 1, 62, 70, 7, 'Apto 2 suítes SBC Baeta Neves', 'Apartamento 2 suítes em Baeta Neves, SBC.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], NULL, '[MOCK-MATCHING-TEST] ABC-11', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Bernardo do Campo","valor_min":300000,"valor_max":580000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 550000, 'ativo', true, 'apartamento', 'São Caetano do Sul', 'SP', 'Barcelona', NULL, 3, 1, 2, 2, 82, 92, 11, 'Apto 3 dorms São Caetano Barcelona', 'Amplo apartamento 3 dorms em São Caetano. Bairro Barcelona.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Shopping São Caetano'], '[MOCK-MATCHING-TEST] ABC-12', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Caetano do Sul","valor_min":380000,"valor_max":720000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 320000, 'ativo', true, 'apartamento', 'Santo André', 'SP', 'Vila Assunção', NULL, 2, 0, 1, 1, 50, 55, 4, 'Apto 2 dorms Santo André Assunção', 'Apartamento 2 dorms na Vila Assunção, Santo André.', ARRAY['foto1.jpg','foto2.jpg'], NULL, '[MOCK-MATCHING-TEST] ABC-13', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Santo André","valor_min":200000,"valor_max":430000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 680000, 'ativo', true, 'casa', 'São Caetano do Sul', 'SP', 'Olímpico', NULL, 3, 2, 3, 2, 160, 220, NULL, 'Casa São Caetano 3 suítes', 'Casa com 3 suítes em São Caetano do Sul. Rua tranquila.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Estádio Anacleto Campanella'], '[MOCK-MATCHING-TEST] ABC-14', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"São Caetano do Sul","valor_min":480000,"valor_max":880000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 400000, 'ativo', true, 'apartamento', 'São Bernardo do Campo', 'SP', 'Nova Petrópolis', NULL, 2, 1, 1, 1, 58, 65, 6, 'Apto 2 dorms SBC Nova Petrópolis', 'Apartamento 2 dorms em Nova Petrópolis, SBC.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Shopping Metrópole'], '[MOCK-MATCHING-TEST] ABC-15', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Bernardo do Campo","valor_min":260000,"valor_max":530000}]'::jsonb, 'venda'),

-- ─── Campinas (15 imóveis, R$280k-900k) ─────────────────────────────────────
(owner_a, 'imovel', 380000, 'ativo', true, 'apartamento', 'Campinas', 'SP', 'Cambuí', NULL, 2, 1, 1, 1, 58, 65, 7, 'Apto 2 dorms Cambuí Campinas', 'Apartamento 2 dorms no Cambuí, bairro nobre de Campinas.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Shopping Cambuí'], '[MOCK-MATCHING-TEST] CPS-01', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Campinas","valor_min":250000,"valor_max":500000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 550000, 'ativo', true, 'apartamento', 'Campinas', 'SP', 'Taquaral', NULL, 3, 1, 2, 2, 80, 90, 10, 'Apto 3 dorms Taquaral Campinas', 'Apartamento 3 dorms no Taquaral. Próximo à Lagoa.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Lagoa do Taquaral'], '[MOCK-MATCHING-TEST] CPS-02', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Campinas","valor_min":380000,"valor_max":720000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 450000, 'ativo', true, 'apartamento', 'Campinas', 'SP', 'Barão Geraldo', NULL, 2, 1, 2, 1, 65, 72, 8, 'Apto 2 suítes Barão Geraldo Unicamp', 'Apartamento 2 suítes em Barão Geraldo, próximo à Unicamp.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Unicamp'], '[MOCK-MATCHING-TEST] CPS-03', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Campinas","valor_min":300000,"valor_max":600000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 780000, 'ativo', true, 'casa', 'Campinas', 'SP', 'Sousas', NULL, 4, 2, 3, 3, 180, 300, NULL, 'Casa Sousas Campinas 4 quartos', 'Casa em Sousas com 4 quartos e amplo jardim. Região nobre.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], NULL, '[MOCK-MATCHING-TEST] CPS-04', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"Campinas","valor_min":550000,"valor_max":1000000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 320000, 'ativo', true, 'apartamento', 'Campinas', 'SP', 'Centro', NULL, 2, 0, 1, 1, 50, 55, 4, 'Apto 2 dorms Centro Campinas', 'Apartamento 2 dorms no centro de Campinas.', ARRAY['foto1.jpg','foto2.jpg'], NULL, '[MOCK-MATCHING-TEST] CPS-05', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Campinas","valor_min":200000,"valor_max":430000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 650000, 'ativo', true, 'apartamento', 'Campinas', 'SP', 'Nova Campinas', NULL, 3, 1, 2, 2, 88, 100, 14, 'Apto 3 dorms Nova Campinas', 'Apartamento 3 dorms em Nova Campinas. Bairro nobre.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Shopping Iguatemi Campinas'], '[MOCK-MATCHING-TEST] CPS-06', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Campinas","valor_min":450000,"valor_max":850000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 280000, 'ativo', true, 'apartamento', 'Campinas', 'SP', 'Jardim Chapadão', NULL, 2, 0, 1, 1, 46, 50, 2, 'Apto 2 dorms Chapadão econômico', 'Apartamento econômico no Jardim Chapadão. 2 dormitórios.', ARRAY['foto1.jpg'], NULL, '[MOCK-MATCHING-TEST] CPS-07', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Campinas","valor_min":180000,"valor_max":380000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 900000, 'ativo', true, 'casa', 'Campinas', 'SP', 'Gramado', NULL, 4, 2, 4, 3, 200, 350, NULL, 'Casa Condomínio Gramado 4 suítes', 'Casa em condomínio fechado no Gramado. 4 suítes, piscina aquecida.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg','foto6.jpg'], NULL, '[MOCK-MATCHING-TEST] CPS-08', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"Campinas","valor_min":650000,"valor_max":1200000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 420000, 'ativo', true, 'apartamento', 'Valinhos', 'SP', 'Centro', NULL, 2, 1, 2, 1, 62, 70, 6, 'Apto 2 suítes Valinhos', 'Apartamento 2 suítes em Valinhos. Cidade tranquila perto de Campinas.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], NULL, '[MOCK-MATCHING-TEST] CPS-09', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Valinhos","valor_min":280000,"valor_max":560000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 500000, 'ativo', true, 'apartamento', 'Campinas', 'SP', 'Alphaville', NULL, 3, 1, 2, 2, 82, 92, 11, 'Apto 3 dorms Alphaville Campinas', 'Apartamento 3 dorms no Alphaville Campinas. Condomínio seguro.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], NULL, '[MOCK-MATCHING-TEST] CPS-10', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Campinas","valor_min":340000,"valor_max":660000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 350000, 'ativo', true, 'apartamento', 'Sumaré', 'SP', 'Centro', NULL, 2, 0, 1, 1, 52, 58, 3, 'Apto 2 dorms Sumaré', 'Apartamento 2 dorms em Sumaré. Próximo à Campinas.', ARRAY['foto1.jpg','foto2.jpg'], NULL, '[MOCK-MATCHING-TEST] CPS-11', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Sumaré","valor_min":220000,"valor_max":470000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 580000, 'ativo', true, 'apartamento', 'Campinas', 'SP', 'Swift', NULL, 3, 1, 2, 1, 75, 85, 9, 'Apto 3 dorms Swift Campinas', 'Apartamento 3 dorms no Swift. Bairro residencial.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], NULL, '[MOCK-MATCHING-TEST] CPS-12', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Campinas","valor_min":400000,"valor_max":760000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 700000, 'ativo', true, 'cobertura', 'Campinas', 'SP', 'Cambuí', NULL, 3, 2, 3, 2, 140, 180, 18, 'Cobertura Cambuí Campinas', 'Cobertura no Cambuí com vista panorâmica. 3 suítes.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['Centro Campinas'], '[MOCK-MATCHING-TEST] CPS-13', '[{"tipo":"imovel","tipo_imovel":"cobertura","cidade":"Campinas","valor_min":500000,"valor_max":920000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 480000, 'ativo', true, 'apartamento', 'Indaiatuba', 'SP', 'Centro', NULL, 3, 1, 2, 1, 72, 80, 7, 'Apto 3 dorms Indaiatuba', 'Apartamento 3 dorms em Indaiatuba. Cidade com alta qualidade de vida.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], NULL, '[MOCK-MATCHING-TEST] CPS-14', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Indaiatuba","valor_min":320000,"valor_max":630000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 620000, 'ativo', true, 'casa', 'Vinhedo', 'SP', 'Centro', NULL, 3, 1, 3, 2, 150, 250, NULL, 'Casa Vinhedo 3 quartos quintal', 'Casa em Vinhedo com 3 quartos e amplo quintal.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], NULL, '[MOCK-MATCHING-TEST] CPS-15', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"Vinhedo","valor_min":420000,"valor_max":820000}]'::jsonb, 'venda'),

-- ─── Litoral Paulista (10 imóveis, R$300k-900k) ─────────────────────────────
(owner_a, 'imovel', 450000, 'ativo', true, 'apartamento', 'Santos', 'SP', 'Gonzaga', NULL, 2, 1, 1, 1, 60, 68, 8, 'Apto 2 dorms Gonzaga Santos', 'Apartamento 2 dorms na praia do Gonzaga, Santos.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Praia do Gonzaga'], '[MOCK-MATCHING-TEST] LIT-01', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Santos","valor_min":300000,"valor_max":600000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 650000, 'ativo', true, 'apartamento', 'Santos', 'SP', 'Ponta da Praia', NULL, 3, 1, 2, 1, 85, 95, 12, 'Apto 3 dorms Ponta da Praia vista mar', 'Apartamento 3 dorms com vista para o mar na Ponta da Praia.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Aquário de Santos'], '[MOCK-MATCHING-TEST] LIT-02', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Santos","valor_min":450000,"valor_max":850000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 380000, 'ativo', true, 'apartamento', 'Guarujá', 'SP', 'Pitangueiras', NULL, 2, 1, 1, 1, 55, 62, 6, 'Apto 2 dorms Pitangueiras Guarujá', 'Apartamento de praia 2 dorms em Pitangueiras, Guarujá.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Praia de Pitangueiras'], '[MOCK-MATCHING-TEST] LIT-03', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Guarujá","valor_min":250000,"valor_max":500000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 900000, 'ativo', true, 'cobertura', 'Santos', 'SP', 'Boqueirão', NULL, 3, 2, 3, 2, 150, 200, 20, 'Cobertura Boqueirão Santos frente mar', 'Cobertura frente ao mar no Boqueirão. 3 suítes, terraço panorâmico.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['Praia do Boqueirão','Orquidário'], '[MOCK-MATCHING-TEST] LIT-04', '[{"tipo":"imovel","tipo_imovel":"cobertura","cidade":"Santos","valor_min":650000,"valor_max":1200000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 320000, 'ativo', true, 'apartamento', 'Praia Grande', 'SP', 'Boqueirão', NULL, 2, 0, 1, 1, 50, 55, 4, 'Apto 2 dorms Praia Grande', 'Apartamento 2 dorms no Boqueirão, Praia Grande.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Praia do Boqueirão'], '[MOCK-MATCHING-TEST] LIT-05', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Praia Grande","valor_min":200000,"valor_max":430000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 520000, 'ativo', true, 'apartamento', 'Santos', 'SP', 'Embaré', NULL, 3, 1, 2, 1, 78, 88, 10, 'Apto 3 dorms Embaré Santos', 'Apartamento 3 dormitórios no Embaré. A 1 quadra da praia.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Praia do Embaré'], '[MOCK-MATCHING-TEST] LIT-06', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Santos","valor_min":350000,"valor_max":680000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 750000, 'ativo', true, 'casa', 'Bertioga', 'SP', 'Riviera de São Lourenço', NULL, 4, 2, 4, 3, 180, 280, NULL, 'Casa Riviera São Lourenço 4 quartos', 'Casa em condomínio na Riviera de São Lourenço. 4 quartos, piscina.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['Praia Riviera'], '[MOCK-MATCHING-TEST] LIT-07', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"Bertioga","valor_min":530000,"valor_max":1000000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 420000, 'ativo', true, 'apartamento', 'São Vicente', 'SP', 'Itararé', NULL, 2, 1, 1, 1, 58, 65, 7, 'Apto 2 dorms São Vicente praia', 'Apartamento 2 dorms em São Vicente. Vista parcial para o mar.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Praia do Itararé'], '[MOCK-MATCHING-TEST] LIT-08', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São Vicente","valor_min":280000,"valor_max":560000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 580000, 'ativo', true, 'apartamento', 'Guarujá', 'SP', 'Enseada', NULL, 3, 1, 2, 2, 82, 92, 9, 'Apto 3 dorms Enseada Guarujá', 'Apartamento 3 dorms na Enseada, Guarujá. Próximo à praia.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Praia da Enseada'], '[MOCK-MATCHING-TEST] LIT-09', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Guarujá","valor_min":400000,"valor_max":760000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 300000, 'ativo', true, 'apartamento', 'Mongaguá', 'SP', 'Centro', NULL, 2, 0, 1, 1, 48, 52, 3, 'Apto 2 dorms Mongaguá praia', 'Apartamento de praia 2 dorms em Mongaguá.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Praia de Mongaguá'], '[MOCK-MATCHING-TEST] LIT-10', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Mongaguá","valor_min":180000,"valor_max":400000}]'::jsonb, 'venda'),

-- ─── Interior/Curitiba (10 imóveis, R$300k-800k) ───────────────────────────
(owner_c, 'imovel', 420000, 'ativo', true, 'apartamento', 'Curitiba', 'PR', 'Batel', NULL, 2, 1, 2, 1, 65, 72, 10, 'Apto 2 suítes Batel Curitiba', 'Apartamento 2 suítes no Batel, bairro nobre de Curitiba.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], ARRAY['Shopping Crystal'], '[MOCK-MATCHING-TEST] CWB-01', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Curitiba","valor_min":280000,"valor_max":560000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 580000, 'ativo', true, 'apartamento', 'Curitiba', 'PR', 'Água Verde', NULL, 3, 1, 2, 2, 82, 92, 12, 'Apto 3 dorms Água Verde Curitiba', 'Apartamento 3 dorms na Água Verde. Região nobre.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], ARRAY['Praça do Japão'], '[MOCK-MATCHING-TEST] CWB-02', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Curitiba","valor_min":400000,"valor_max":760000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 350000, 'ativo', true, 'apartamento', 'Curitiba', 'PR', 'Centro Cívico', NULL, 2, 0, 1, 1, 52, 58, 5, 'Apto 2 dorms Centro Cívico', 'Apartamento 2 dorms no Centro Cívico de Curitiba.', ARRAY['foto1.jpg','foto2.jpg'], ARRAY['Museu Oscar Niemeyer'], '[MOCK-MATCHING-TEST] CWB-03', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Curitiba","valor_min":220000,"valor_max":470000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 750000, 'ativo', true, 'casa', 'Curitiba', 'PR', 'Santa Felicidade', NULL, 4, 2, 3, 3, 180, 280, NULL, 'Casa Santa Felicidade 4 quartos', 'Casa em Santa Felicidade com 4 quartos e quintal. Bairro italiano.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], ARRAY['Restaurantes italianos'], '[MOCK-MATCHING-TEST] CWB-04', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"Curitiba","valor_min":520000,"valor_max":1000000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 480000, 'ativo', true, 'apartamento', 'Sorocaba', 'SP', 'Campolim', NULL, 3, 1, 2, 1, 75, 85, 8, 'Apto 3 dorms Campolim Sorocaba', 'Apartamento 3 dorms no Campolim, bairro nobre de Sorocaba.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], NULL, '[MOCK-MATCHING-TEST] INT-01', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Sorocaba","valor_min":320000,"valor_max":630000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 380000, 'ativo', true, 'apartamento', 'Jundiaí', 'SP', 'Centro', NULL, 2, 1, 1, 1, 58, 65, 6, 'Apto 2 dorms Jundiaí centro', 'Apartamento 2 dorms no centro de Jundiaí.', ARRAY['foto1.jpg','foto2.jpg'], NULL, '[MOCK-MATCHING-TEST] INT-02', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Jundiaí","valor_min":250000,"valor_max":500000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 550000, 'ativo', true, 'apartamento', 'Ribeirão Preto', 'SP', 'Jardim Botânico', NULL, 3, 1, 2, 2, 85, 95, 10, 'Apto 3 dorms Ribeirão Preto', 'Apartamento 3 dorms no Jardim Botânico de Ribeirão Preto.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg'], NULL, '[MOCK-MATCHING-TEST] INT-03', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Ribeirão Preto","valor_min":380000,"valor_max":720000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 800000, 'ativo', true, 'casa', 'São José dos Campos', 'SP', 'Jardim Aquarius', NULL, 4, 2, 4, 3, 200, 300, NULL, 'Casa Aquarius SJC 4 suítes', 'Casa de alto padrão no Jardim Aquarius em São José dos Campos.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg','foto5.jpg'], NULL, '[MOCK-MATCHING-TEST] INT-04', '[{"tipo":"imovel","tipo_imovel":"casa","cidade":"São José dos Campos","valor_min":550000,"valor_max":1050000}]'::jsonb, 'venda'),
(owner_a, 'imovel', 300000, 'ativo', true, 'apartamento', 'Piracicaba', 'SP', 'Centro', NULL, 2, 0, 1, 1, 50, 55, 4, 'Apto 2 dorms Piracicaba centro', 'Apartamento 2 dorms no centro de Piracicaba.', ARRAY['foto1.jpg','foto2.jpg'], NULL, '[MOCK-MATCHING-TEST] INT-05', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"Piracicaba","valor_min":190000,"valor_max":400000}]'::jsonb, 'venda'),
(owner_c, 'imovel', 650000, 'ativo', true, 'apartamento', 'São José dos Campos', 'SP', 'Vila Adyana', NULL, 3, 1, 2, 2, 88, 100, 14, 'Apto 3 dorms Vila Adyana SJC', 'Apartamento 3 dorms na Vila Adyana. Região nobre de SJC.', ARRAY['foto1.jpg','foto2.jpg','foto3.jpg','foto4.jpg'], NULL, '[MOCK-MATCHING-TEST] INT-06', '[{"tipo":"imovel","tipo_imovel":"apartamento","cidade":"São José dos Campos","valor_min":450000,"valor_max":850000}]'::jsonb, 'venda');


-- ════════════════════════════════════════════════════════════════════════════
-- PART 2: PERMUTAS (40 records)
-- Owned by different users so they can match with the imóveis above.
-- Designed to produce a RANGE of match scores from ~25 to ~90.
-- ════════════════════════════════════════════════════════════════════════════

-- ─── HIGH MATCH permutas (~70-90 score): exact city+bairro, tight price range ─
INSERT INTO erp.ativos (owner_id, natureza, valor, status, tipo_imovel, cidade, estado, bairro, zona, faixa_preco_min, faixa_preco_max, quartos_min, vagas_min, metragem_min, metragem_max, aceita_completar_diferenca, regiao_preferida, observacoes, interesses) VALUES
(owner_b, 'permuta_imovel', 430000, 'ativo', 'apartamento', 'São Paulo', 'SP', 'Moema', 'Zona Sul', 380000, 520000, 2, 1, 50, 80, true, ARRAY['Moema','Vila Mariana'], '[MOCK-MATCHING-TEST] PERM-HIGH-01', '[]'::jsonb),
(owner_b, 'permuta_imovel', 700000, 'ativo', 'apartamento', 'São Paulo', 'SP', 'Vila Mariana', 'Zona Sul', 600000, 800000, 3, 1, 75, 120, true, ARRAY['Vila Mariana','Moema','Saúde'], '[MOCK-MATCHING-TEST] PERM-HIGH-02', '[]'::jsonb),
(owner_b, 'permuta_imovel', 900000, 'ativo', 'apartamento', 'São Paulo', 'SP', 'Brooklin', 'Zona Sul', 800000, 1100000, 3, 2, 90, 140, true, ARRAY['Brooklin','Itaim Bibi'], '[MOCK-MATCHING-TEST] PERM-HIGH-03', '[]'::jsonb),
(owner_b, 'permuta_imovel', 500000, 'ativo', 'apartamento', 'São Paulo', 'SP', 'Pinheiros', 'Zona Oeste', 450000, 650000, 2, 1, 55, 75, true, ARRAY['Pinheiros','Vila Madalena'], '[MOCK-MATCHING-TEST] PERM-HIGH-04', '[]'::jsonb),
(owner_b, 'permuta_imovel', 1100000, 'ativo', 'casa', 'São Paulo', 'SP', 'Campo Belo', 'Zona Sul', 900000, 1300000, 4, 2, 160, 280, true, ARRAY['Campo Belo','Granja Julieta'], '[MOCK-MATCHING-TEST] PERM-HIGH-05', '[]'::jsonb),
(owner_b, 'permuta_imovel', 350000, 'ativo', 'apartamento', 'Santo André', 'SP', 'Centro', NULL, 280000, 420000, 2, 1, 45, 70, true, ARRAY['Santo André','São Bernardo'], '[MOCK-MATCHING-TEST] PERM-HIGH-06', '[]'::jsonb),
(owner_b, 'permuta_imovel', 550000, 'ativo', 'apartamento', 'Campinas', 'SP', 'Taquaral', NULL, 450000, 650000, 3, 1, 70, 100, true, ARRAY['Taquaral','Cambuí'], '[MOCK-MATCHING-TEST] PERM-HIGH-07', '[]'::jsonb),
(owner_b, 'permuta_imovel', 450000, 'ativo', 'apartamento', 'Santos', 'SP', 'Gonzaga', NULL, 380000, 550000, 2, 1, 50, 75, true, ARRAY['Gonzaga','Boqueirão'], '[MOCK-MATCHING-TEST] PERM-HIGH-08', '[]'::jsonb),
(owner_b, 'permuta_imovel', 580000, 'ativo', 'apartamento', 'Curitiba', 'PR', 'Água Verde', NULL, 480000, 680000, 3, 1, 70, 100, true, ARRAY['Água Verde','Batel'], '[MOCK-MATCHING-TEST] PERM-HIGH-09', '[]'::jsonb),
(owner_b, 'permuta_imovel', 1000000, 'ativo', 'apartamento', 'São Paulo', 'SP', 'Itaim Bibi', 'Zona Sul', 850000, 1200000, 3, 2, 100, 150, true, ARRAY['Itaim Bibi','Pinheiros','Brooklin'], '[MOCK-MATCHING-TEST] PERM-HIGH-10', '[]'::jsonb),

-- ─── MEDIUM MATCH permutas (~40-65 score): same city, wider price range ──────
(owner_b, 'permuta_imovel', 600000, 'ativo', 'apartamento', 'São Paulo', 'SP', 'Liberdade', 'Zona Sul', 400000, 750000, 2, 1, 50, 90, false, ARRAY['Liberdade','Aclimação','Vila Mariana'], '[MOCK-MATCHING-TEST] PERM-MED-01', '[]'::jsonb),
(owner_b, 'permuta_imovel', 400000, 'ativo', 'apartamento', 'São Paulo', 'SP', 'Consolação', 'Zona Oeste', 300000, 550000, 2, 0, 40, 70, false, ARRAY['Consolação','Higienópolis','Perdizes'], '[MOCK-MATCHING-TEST] PERM-MED-02', '[]'::jsonb),
(owner_b, 'permuta_imovel', 750000, 'ativo', 'casa', 'São Paulo', 'SP', 'Planalto Paulista', 'Zona Sul', 550000, 900000, 3, 1, 100, 200, false, ARRAY['Planalto Paulista','Moema','Saúde'], '[MOCK-MATCHING-TEST] PERM-MED-03', '[]'::jsonb),
(owner_b, 'permuta_imovel', 500000, 'ativo', 'apartamento', 'São Paulo', 'SP', 'Cambuci', NULL, 350000, 620000, 2, 1, 50, 80, true, ARRAY['Cambuci','Ipiranga','Sacomã'], '[MOCK-MATCHING-TEST] PERM-MED-04', '[]'::jsonb),
(owner_b, 'permuta_imovel', 800000, 'ativo', 'apartamento', 'São Paulo', 'SP', 'Jardins', 'Zona Oeste', 600000, 1000000, 3, 1, 80, 130, false, ARRAY['Jardins','Pinheiros','Itaim'], '[MOCK-MATCHING-TEST] PERM-MED-05', '[]'::jsonb),
(owner_b, 'permuta_imovel', 450000, 'ativo', 'apartamento', 'São Bernardo do Campo', 'SP', 'Planalto', NULL, 320000, 580000, 2, 1, 55, 80, true, ARRAY['São Bernardo','Santo André'], '[MOCK-MATCHING-TEST] PERM-MED-06', '[]'::jsonb),
(owner_b, 'permuta_imovel', 380000, 'ativo', 'apartamento', 'Campinas', 'SP', 'Jardim Proença', NULL, 250000, 500000, 2, 0, 40, 70, false, ARRAY['Campinas'], '[MOCK-MATCHING-TEST] PERM-MED-07', '[]'::jsonb),
(owner_b, 'permuta_imovel', 650000, 'ativo', 'casa', 'Campinas', 'SP', 'Taquaral', NULL, 500000, 850000, 3, 2, 120, 250, true, ARRAY['Campinas','Valinhos'], '[MOCK-MATCHING-TEST] PERM-MED-08', '[]'::jsonb),
(owner_b, 'permuta_imovel', 350000, 'ativo', 'apartamento', 'Santos', 'SP', 'José Menino', NULL, 250000, 480000, 2, 0, 45, 70, false, ARRAY['Santos','São Vicente'], '[MOCK-MATCHING-TEST] PERM-MED-09', '[]'::jsonb),
(owner_b, 'permuta_imovel', 500000, 'ativo', 'apartamento', 'Curitiba', 'PR', 'Portão', NULL, 380000, 650000, 2, 1, 55, 85, true, ARRAY['Curitiba'], '[MOCK-MATCHING-TEST] PERM-MED-10', '[]'::jsonb),

-- ─── LOW MATCH permutas (~20-40 score): different city/state, loose criteria ─
(owner_b, 'permuta_imovel', 500000, 'ativo', 'apartamento', 'Rio de Janeiro', 'RJ', 'Copacabana', NULL, 350000, 700000, 2, 0, 40, 80, false, ARRAY['Rio de Janeiro'], '[MOCK-MATCHING-TEST] PERM-LOW-01', '[]'::jsonb),
(owner_b, 'permuta_imovel', 800000, 'ativo', 'casa', 'Belo Horizonte', 'MG', 'Savassi', NULL, 550000, 1000000, 3, 1, 100, 250, false, ARRAY['Belo Horizonte'], '[MOCK-MATCHING-TEST] PERM-LOW-02', '[]'::jsonb),
(owner_b, 'permuta_imovel', 300000, 'ativo', 'apartamento', 'Florianópolis', 'SC', 'Centro', NULL, 200000, 450000, 2, 0, 40, 65, false, ARRAY['Florianópolis'], '[MOCK-MATCHING-TEST] PERM-LOW-03', '[]'::jsonb),
(owner_b, 'permuta_imovel', 600000, 'ativo', 'apartamento', 'Porto Alegre', 'RS', 'Moinhos de Vento', NULL, 450000, 800000, 3, 1, 70, 110, false, ARRAY['Porto Alegre'], '[MOCK-MATCHING-TEST] PERM-LOW-04', '[]'::jsonb),
(owner_b, 'permuta_imovel', 400000, 'ativo', 'apartamento', 'Recife', 'PE', 'Boa Viagem', NULL, 280000, 550000, 2, 1, 50, 75, true, ARRAY['Recife'], '[MOCK-MATCHING-TEST] PERM-LOW-05', '[]'::jsonb),

-- ─── AUTOMOVEL permutas (5 records): match with imóveis that have auto interests ─
(owner_b, 'permuta_automovel', 250000, 'ativo', NULL, 'São Paulo', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, '[MOCK-MATCHING-TEST] PERM-AUTO-01', '[]'::jsonb),
(owner_b, 'permuta_automovel', 180000, 'ativo', NULL, 'São Paulo', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, '[MOCK-MATCHING-TEST] PERM-AUTO-02', '[]'::jsonb),
(owner_b, 'permuta_automovel', 350000, 'ativo', NULL, 'São Paulo', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, '[MOCK-MATCHING-TEST] PERM-AUTO-03', '[]'::jsonb),
(owner_b, 'permuta_automovel', 500000, 'ativo', NULL, 'São Paulo', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, '[MOCK-MATCHING-TEST] PERM-AUTO-04', '[]'::jsonb),
(owner_b, 'permuta_automovel', 120000, 'ativo', NULL, 'Campinas', 'SP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, NULL, '[MOCK-MATCHING-TEST] PERM-AUTO-05', '[]'::jsonb);

-- Set vehicle-specific fields on automovel permutas
UPDATE erp.ativos SET tipo_veiculo = 'suv', marca = 'BMW', modelo = 'X3', ano = 2023, motor = '2.0 turbo', quilometragem = 25000
WHERE observacoes = '[MOCK-MATCHING-TEST] PERM-AUTO-01';

UPDATE erp.ativos SET tipo_veiculo = 'sedan', marca = 'Mercedes-Benz', modelo = 'C200', ano = 2022, motor = '1.5 turbo', quilometragem = 30000
WHERE observacoes = '[MOCK-MATCHING-TEST] PERM-AUTO-02';

UPDATE erp.ativos SET tipo_veiculo = 'suv', marca = 'Porsche', modelo = 'Macan', ano = 2024, motor = '2.0 turbo', quilometragem = 10000
WHERE observacoes = '[MOCK-MATCHING-TEST] PERM-AUTO-03';

UPDATE erp.ativos SET tipo_veiculo = 'suv', marca = 'Porsche', modelo = 'Cayenne', ano = 2023, motor = '3.0 V6', quilometragem = 15000
WHERE observacoes = '[MOCK-MATCHING-TEST] PERM-AUTO-04';

UPDATE erp.ativos SET tipo_veiculo = 'hatch', marca = 'Toyota', modelo = 'Corolla Cross', ano = 2022, motor = '2.0', quilometragem = 40000
WHERE observacoes = '[MOCK-MATCHING-TEST] PERM-AUTO-05';

RAISE NOTICE '✅ Inserted 100 imóveis + 40 permutas (140 total) tagged [MOCK-MATCHING-TEST]';

END $$;
