from .permuta_imovel_serializer import PermutaImovelSerializer, PermutaImovelListSerializer
from .permuta_automovel_serializer import PermutaAutomovelSerializer, PermutaAutomovelListSerializer
from .match_serializer import MatchSerializer, MatchListSerializer
from .interesse_permuta_imovel_serializer import InteressePermutaImovelSerializer, InteressePermutaImovelListSerializer
from .interesse_permuta_automovel_serializer import InteressePermutaAutomovelSerializer, InteressePermutaAutomovelListSerializer
