"""Website host-split serving (contract §5) — `noctusai.com` gets the
prerendered marketing site; `core.noctusai.com` (and every other host)
keeps today's app shell untouched.

Implemented as **`http` middleware**, not a catch-all route, so it can
intercept `/` (and every other website path) BEFORE the app's own routes
and the seed's `_mount_spa` static mount — none of which need to know the
website exists. Registered in `app/main.py` via
`app.middleware("http")(website_html_middleware)` AFTER
`create_product_app(...)` returns.

Named `website_html.py` (not `website_serving.py`) per the contract's own
file name (`app/routers/website_html.py`) even though its export is
middleware, not an `APIRouter` — kept for doc/traceability parity with
`15-api-contract.md` §5.
"""
from __future__ import annotations

import json
import logging
import re
import time
from pathlib import PurePosixPath
from typing import Optional

from starlette.requests import Request
from starlette.responses import HTMLResponse, PlainTextResponse, RedirectResponse, Response

from app.config import settings
from app.services import website_settings_service
from app.services.website_paths import get_spa_dir

logger = logging.getLogger(__name__)

_MANIFEST_CACHE_TTL_SECONDS = 30.0
_manifest_cache: Optional[dict] = None  # {"expires_at": float, "manifest": dict | None}

# Section-marker / product-marker regexes (contract §4). DOTALL — a section
# body spans many lines. The named-group back-reference (`(?P=key)`) means a
# malformed/unbalanced marker pair never matches, so we only ever strip a
# WELL-FORMED block, never garbage-collapse the rest of the document.
_SECTION_MARKER_RE = re.compile(
    r"<!--nx:section:(?P<key>[A-Za-z0-9_]+)-->.*?<!--/nx:section:(?P=key)-->", re.DOTALL
)
_PRODUCT_MARKER_RE = re.compile(
    r"<!--nx:product:(?P<slug>[A-Za-z0-9_-]+)-->.*?<!--/nx:product:(?P=slug)-->", re.DOTALL
)

_PASSTHROUGH_PREFIXES = ("/api/", "/_site/", "/assets/", "/consent", "/favicon", "/invite/")
_OPS_PASSTHROUGH = ("/docs", "/openapi.json", "/redoc")

# The pt-BR + EN route STEMS declared in the contract (§4 "Routes v1").
# Used ONLY to decide website-404-vs-app-301 for a path that ISN'T an exact
# manifest hit (e.g. a typo'd product slug, or a hidden product's URL after
# the settings toggle). Deriving this from the core FE route table (as the
# contract's §5.6 first choice asks) needs a Node-side export the website
# FE slice doesn't ship yet —
# NOC-REMEDIATE[website-app-path-derivation]: replace this hand-maintained
# tuple with a build-time-emitted list once the FE build can export its
# React Router route table (mirrors `manifest.json`'s own generation step).
# Until then this is the documented fallback the contract explicitly
# sanctions: "If derivation isn't feasible, 301 everything not matched." — 2026-09-23
_WEBSITE_PATH_STEMS = (
    "/produtos", "/solucoes", "/precos", "/contato", "/lista-de-espera", "/sobre", "/404", "/en",
)


def _site_dir() -> Path:
    return get_spa_dir() / "_site"


def get_manifest(*, use_cache: bool = True) -> Optional[dict]:
    """`None` when `_site/manifest.json` doesn't exist or fails to parse —
    the website build isn't present (dev, or a container mid-deploy). The
    middleware degrades to `call_next` (today's app-shell behaviour) in
    that case, mirroring `_mount_spa`'s own race-safe posture toward a
    not-yet-built `dist/`."""
    global _manifest_cache
    now = time.monotonic()
    if use_cache and _manifest_cache is not None and _manifest_cache["expires_at"] > now:
        return _manifest_cache["manifest"]

    manifest_path = _site_dir() / "manifest.json"
    manifest: Optional[dict] = None
    if manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            logger.error("website: failed reading/parsing %s: %s", manifest_path, exc)
            manifest = None

    _manifest_cache = {"expires_at": now + _MANIFEST_CACHE_TTL_SECONDS, "manifest": manifest}
    return manifest


def invalidate_manifest_cache() -> None:
    global _manifest_cache
    _manifest_cache = None


_GENERATED_SURFACES = ("/sitemap.xml", "/robots.txt", "/llms.txt")


def _is_passthrough(path: str) -> bool:
    if path in _GENERATED_SURFACES:
        return False  # generated BY this middleware — never passthrough
    if path.startswith(_PASSTHROUGH_PREFIXES) or path in _OPS_PASSTHROUGH:
        return True
    if path.startswith("/_"):  # ops surfaces (`/_health`, `/_ready`, ...)
        return True
    # A path with a file extension is a real static-asset request (favicon
    # variants, manifest.webmanifest, sw.js, ...) — let it fall through to
    # the SPA static mount, same asset-vs-route heuristic `_mount_spa` uses.
    return bool(PurePosixPath(path).suffix)


def _strip_hidden_sections(html: str, sections: dict) -> str:
    def _repl(match: "re.Match[str]") -> str:
        return "" if sections.get(match.group("key")) is False else match.group(0)

    return _SECTION_MARKER_RE.sub(_repl, html)


def _strip_hidden_products(html: str, visible_slugs: set) -> str:
    def _repl(match: "re.Match[str]") -> str:
        return match.group(0) if match.group("slug") in visible_slugs else ""

    return _PRODUCT_MARKER_RE.sub(_repl, html)


def _inject_settings(html: str, public_data: dict) -> str:
    """Replace the `__NX_SETTINGS__` placeholder inside `<script
    id="nx-settings" type="application/json">` (contract §4). `<` is
    escaped to `\\u003c` (NOT the HTML entity `&lt;` — this is a
    `type="application/json"` payload, not HTML text) so a stored value
    containing a literal `</script>` can never prematurely close the tag."""
    payload = json.dumps(public_data, ensure_ascii=False, default=str).replace("<", "\\u003c")
    return html.replace("__NX_SETTINGS__", payload)


def _visible_product_slugs(public_data: dict) -> set:
    return {p["slug"] for p in (public_data.get("products") or [])}


def _render_route(route: dict, public_data: dict) -> Optional[str]:
    file_path = _site_dir() / route["file"]
    if not file_path.is_file():
        logger.error("website: manifest route %s references missing file %s", route.get("path"), file_path)
        return None
    html = file_path.read_text(encoding="utf-8")
    html = _strip_hidden_sections(html, public_data.get("sections") or {})
    html = _strip_hidden_products(html, _visible_product_slugs(public_data))
    return _inject_settings(html, public_data)


def _website_404(by_path: dict, public_data: dict, *, path: str) -> Response:
    route = by_path.get("/en/404") if path.startswith("/en") else by_path.get("/404")
    route = route or by_path.get("/404") or by_path.get("/en/404")
    if route is None:
        return PlainTextResponse("Not found", status_code=404)
    html = _render_route(route, public_data)
    if html is None:
        return PlainTextResponse("Not found", status_code=404)
    return HTMLResponse(html, status_code=404)


def build_sitemap_xml(manifest: dict, public_data: dict, *, base_url: str = "https://noctusai.com") -> str:
    visible_slugs = _visible_product_slugs(public_data)
    entries = []
    for route in manifest.get("routes", []):
        product = route.get("product")
        if product and product not in visible_slugs:
            continue
        loc = f"{base_url}{route['path']}"
        alt_xml = ""
        alt = route.get("alt")
        if alt:
            alt_lang = "en" if alt.startswith("/en") else "pt-BR"
            alt_xml = f'\n    <xhtml:link rel="alternate" hreflang="{alt_lang}" href="{base_url}{alt}"/>'
        entries.append(f"  <url>\n    <loc>{loc}</loc>{alt_xml}\n  </url>")
    body = "\n".join(entries)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" '
        'xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
        f"{body}\n"
        "</urlset>\n"
    )


def build_robots_txt(*, base_url: str = "https://noctusai.com") -> str:
    return "User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: " + base_url + "/sitemap.xml\n"


def build_llms_txt(manifest: dict, public_data: dict, *, base_url: str = "https://noctusai.com") -> str:
    visible_slugs = _visible_product_slugs(public_data)
    lines = [
        "# NoctusAI",
        "",
        "> Plataforma de produtos de IA para empresas. / AI product platform for businesses.",
        "",
    ]
    for route in manifest.get("routes", []):
        product = route.get("product")
        if product and product not in visible_slugs:
            continue
        lines.append(f"- [{route['path']}]({base_url}{route['path']}) ({route.get('lang', 'pt-BR')})")
    return "\n".join(lines) + "\n"


async def website_html_middleware(request: Request, call_next):
    host = (request.headers.get("host") or "").split(":")[0].lower()
    is_website_host = host in settings.website_hosts_list

    # Dev override — `?__site=1` / `X-NX-Site: 1` — production-gated so it
    # can never be used to spoof host-split behaviour in prod (contract §5).
    if not is_website_host and not settings.is_production:
        if request.query_params.get("__site") == "1" or request.headers.get("x-nx-site") == "1":
            is_website_host = True

    if not is_website_host:
        response = await call_next(request)
        if response.headers.get("content-type", "").startswith("text/html"):
            response.headers.setdefault("X-Robots-Tag", "noindex")
        return response

    path = request.url.path
    query = request.url.query

    # 1 · www → apex 301 (checked first — it applies even to passthrough
    # paths, e.g. `www.noctusai.com/api/...` should still normalize).
    if host.startswith("www."):
        target = f"https://{host[len('www.'):]}" + path + (f"?{query}" if query else "")
        return RedirectResponse(target, status_code=301)

    # 5 · Passthrough — checked early (cheap, no settings read) since its
    # outcome (`call_next`) is identical whether reached via this branch or
    # the kill-switch branch below; contract ordering is documentation, not
    # a behavioural constraint here.
    if _is_passthrough(path):
        return await call_next(request)

    version, current_data = website_settings_service.get_current()
    public_data = website_settings_service.public_subset(current_data)

    # 2 · Kill switch — fall through to today's app-shell + Landing.tsx.
    if not current_data.get("site_enabled", True):
        return await call_next(request)

    manifest = get_manifest()
    if manifest is None:
        # Website build not present (local dev without `npm run build`, or
        # a container mid-rollout) — degrade to today's behaviour rather
        # than 500 every request.
        return await call_next(request)

    # 4 · Generated surfaces.
    if path == "/sitemap.xml":
        return Response(content=build_sitemap_xml(manifest, public_data), media_type="application/xml")
    if path == "/robots.txt":
        return PlainTextResponse(build_robots_txt())
    if path == "/llms.txt":
        return PlainTextResponse(build_llms_txt(manifest, public_data), media_type="text/plain")

    # 3 · Manifest route match.
    normalized = path.rstrip("/") or "/"
    by_path = {route["path"]: route for route in manifest.get("routes", [])}
    route = by_path.get(normalized)

    if route is not None:
        product = route.get("product")
        if product and product not in _visible_product_slugs(public_data):
            return _website_404(by_path, public_data, path=normalized)
        html = _render_route(route, public_data)
        if html is None:
            return _website_404(by_path, public_data, path=normalized)
        response = HTMLResponse(html)
        response.headers["Cache-Control"] = "public, max-age=60"
        return response

    # A path shaped like a website route (a hidden product's URL, a typo'd
    # slug, ...) that isn't an exact manifest hit → the website's own 404,
    # never a 301 into the app.
    if normalized.startswith(_WEBSITE_PATH_STEMS):
        return _website_404(by_path, public_data, path=normalized)

    # 6 · Everything else on a website host is an app path (contract §5.6).
    target = f"{settings.core_app_origin}{path}" + (f"?{query}" if query else "")
    return RedirectResponse(target, status_code=301)


__all__ = [
    "build_llms_txt",
    "build_robots_txt",
    "build_sitemap_xml",
    "get_manifest",
    "invalidate_manifest_cache",
    "website_html_middleware",
]
