# Generated by Django 4.2.1 on 2024-02-17 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Condominio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("cep", models.CharField(max_length=20)),
                ("estado", models.CharField(max_length=50)),
                ("cidade", models.CharField(max_length=50)),
                ("bairro", models.CharField(max_length=50)),
                ("endereco", models.CharField(max_length=100)),
                ("numero", models.PositiveIntegerField()),
                ("km", models.PositiveIntegerField()),
                ("valor_condominio", models.PositiveIntegerField()),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
