# Generated by Django 4.2.9 on 2026-01-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='valor_condominio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
