# Generated by Django 4.2.9 on 2026-01-26 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_alter_condominio_bairro_alter_condominio_cep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominio',
            options={'verbose_name': 'Condomínio', 'verbose_name_plural': 'Condomínios'},
        ),
        migrations.AlterField(
            model_name='condominio',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 12345-678 ou 12345678', regex='^\\d{5}-?\\d{3}$')]),
        ),
        migrations.AddIndex(
            model_name='condominio',
            index=models.Index(fields=['nome'], name='condominio__nome_220578_idx'),
        ),
        migrations.AddIndex(
            model_name='condominio',
            index=models.Index(fields=['estado', 'cidade'], name='condominio__estado_81ca72_idx'),
        ),
    ]
