# Generated by Django 4.2.9 on 2026-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0003_alter_condominio_options_alter_condominio_cep_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominio',
            options={'ordering': ['nome'], 'verbose_name': 'Condomínio', 'verbose_name_plural': 'Condomínios'},
        ),
        migrations.AddIndex(
            model_name='condominio',
            index=models.Index(fields=['bairro'], name='condominio__bairro_ae6cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='condominio',
            index=models.Index(fields=['cidade'], name='condominio__cidade_43d833_idx'),
        ),
    ]
