#!/usr/bin/env bash
# 02-deploy-stack.sh — clone the repo + bring the Docker stack up on the VPS.
#
# Runs AS the deploy user (not root). Idempotent: safe to re-run for
# updates / restarts.
#
# What this does:
#   1. Clones the repo to $APP_DIR (or pulls latest if already there)
#   2. Symlinks noc seed packages into the workspace (sibling-clone shape
#      mirroring the local-dev setup)
#   3. Writes .env from the prod template (uses values passed via env
#      vars — see "Required env vars" below)
#   4. Builds + starts the Docker stack with the tunnel profile
#   5. Health-checks the backend
#
# Required env vars (export before running, or pass inline):
#   GIT_REPO              SSH or HTTPS URL of noctusai-youtube-crawler
#   GIT_BRANCH            integration/oauth-discovery
#   NOC_REPO              SSH or HTTPS URL of the noc repo (for seed/)
#   META_APP_ID           your Meta App ID
#   META_APP_SECRET       your Meta App Secret
#   META_SYSTEM_USER_TOKEN your long-lived System User Token
#   OPENAI_API_KEY        your OpenAI key
#   GOOGLE_OAUTH_CLIENT_ID
#   GOOGLE_OAUTH_CLIENT_SECRET
#   GOOGLE_MAPS_API_KEY
#   SUPABASE_URL / SUPABASE_KEY / SUPABASE_SERVICE_ROLE_KEY
#   ENCRYPTION_KEY        Fernet key
#   VISTA_BASE_URL / VISTA_API_KEY
#   WAHA_API_KEY / WAHA_DASHBOARD_USERNAME / WAHA_DASHBOARD_PASSWORD
#   TUNNEL_HOSTNAME       https://bot.noctusai.com (no trailing slash)
#
# Usage:
#   # Source a secrets file then run:
#   source ~/secrets.env
#   bash 02-deploy-stack.sh

set -euo pipefail

APP_DIR="${APP_DIR:-/opt/noctus}"
GIT_REPO="${GIT_REPO:?set GIT_REPO to the workspace repo URL}"
GIT_BRANCH="${GIT_BRANCH:-integration/oauth-discovery}"
NOC_REPO="${NOC_REPO:?set NOC_REPO to the noc repo URL}"
TUNNEL_HOSTNAME="${TUNNEL_HOSTNAME:?set TUNNEL_HOSTNAME e.g. https://bot.noctusai.com}"

WORKSPACE_DIR="$APP_DIR/noctusai-youtube-crawler"
NOC_DIR="$APP_DIR/noctusai"

echo "==> deploy-stack starting (branch=$GIT_BRANCH, tunnel=$TUNNEL_HOSTNAME)"

# ----- 1. Clone or update repos -----
if [[ ! -d "$NOC_DIR/.git" ]]; then
  echo "==> cloning noc repo"
  git clone "$NOC_REPO" "$NOC_DIR"
else
  echo "==> updating noc repo"
  git -C "$NOC_DIR" fetch --quiet
  git -C "$NOC_DIR" pull --ff-only --quiet || true
fi

if [[ ! -d "$WORKSPACE_DIR/.git" ]]; then
  echo "==> cloning workspace repo (branch $GIT_BRANCH)"
  git clone --branch "$GIT_BRANCH" "$GIT_REPO" "$WORKSPACE_DIR"
else
  echo "==> updating workspace repo"
  git -C "$WORKSPACE_DIR" fetch --quiet
  git -C "$WORKSPACE_DIR" checkout "$GIT_BRANCH"
  git -C "$WORKSPACE_DIR" pull --ff-only --quiet
fi

# ----- 2. Symlink seed/, KB, etc. (mirrors the local-dev workspace shape) -----
cd "$WORKSPACE_DIR"
for link_target in seed KNOWLEDGE-BASE CLAUDE CLAUDE.md .claude templates noctusai_lib mcp; do
  if [[ -L "$link_target" ]]; then
    # If the symlink is broken, fix it; otherwise leave.
    [[ -e "$link_target" ]] || (rm -f "$link_target" && ln -s "$NOC_DIR/$link_target" "$link_target")
  elif [[ ! -e "$link_target" ]]; then
    ln -s "$NOC_DIR/$link_target" "$link_target"
  fi
done

# ----- 3. .env (built from required env vars) -----
echo "==> writing .env from prod template"
cat > .env <<ENV
# ─── Generated by 02-deploy-stack.sh ─────────────────────────────────
NOCTUSAI_HOME=$NOC_DIR

# YouTube OAuth — same redirect URI for all OAuth callbacks goes
# through the tunnel.
YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID:-}
YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET:-}
YOUTUBE_REDIRECT_URI=$TUNNEL_HOSTNAME/api/youtube/oauth/callback
FRONTEND_BASE_URL=$TUNNEL_HOSTNAME

# OpenAI
OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENAI_CHAT_MODEL=${OPENAI_CHAT_MODEL:-gpt-4o-mini}
WHATSAPP_CHATBOT_ENABLED=true

# Encryption
ENCRYPTION_KEY=${ENCRYPTION_KEY:-}

# SMTP
SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
SMTP_PORT=${SMTP_PORT:-465}
SMTP_USER=${SMTP_USER:-}
SMTP_PASSWORD=${SMTP_PASSWORD:-}

# WAHA
WAHA_IMAGE=devlikeapro/waha
WAHA_BASE_URL=http://waha:3000
WAHA_API_KEY=${WAHA_API_KEY:-}
WAHA_SESSION=default
WAHA_DASHBOARD_URL=$TUNNEL_HOSTNAME/waha/dashboard
WAHA_WEBHOOK_URL=$TUNNEL_HOSTNAME/api/whatsapp/webhook
WAHA_WEBHOOK_HMAC_SECRET=${WAHA_WEBHOOK_HMAC_SECRET:-}
WAHA_DASHBOARD_USERNAME=${WAHA_DASHBOARD_USERNAME:-admin}
WAHA_DASHBOARD_PASSWORD=${WAHA_DASHBOARD_PASSWORD:-}

# Database — for production we use Supabase, not SQLite
DATABASE_BACKEND=supabase
SUPABASE_URL=${SUPABASE_URL:-}
SUPABASE_KEY=${SUPABASE_KEY:-}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
LOCAL_DEV_ORG_ID=${LOCAL_DEV_ORG_ID:-00000000-0000-4000-8000-000000000001}
LOCAL_DEV_USER_ID=${LOCAL_DEV_USER_ID:-00000000-0000-4000-8000-000000000001}

# Vista CRM
VISTA_BASE_URL=${VISTA_BASE_URL:-}
VISTA_API_KEY=${VISTA_API_KEY:-}
CRM_BASE_URL=${CRM_BASE_URL:-${VISTA_BASE_URL:-}}
CRM_API_KEY=${CRM_API_KEY:-${VISTA_API_KEY:-}}

# Tunnel
TUNNEL_HOSTNAME=$TUNNEL_HOSTNAME

# Google integrations
GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID:-}
GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET:-}
GOOGLE_OAUTH_REDIRECT_URI=$TUNNEL_HOSTNAME/api/calendar/oauth/callback
GOOGLE_OAUTH_ACCOUNT_EMAIL=${GOOGLE_OAUTH_ACCOUNT_EMAIL:-}
GOOGLE_OAUTH_SCOPES=auto
GOOGLE_SERVICE_ACCOUNT_FILE=${GOOGLE_SERVICE_ACCOUNT_FILE:-}
GOOGLE_CALENDAR_DEFAULT_ID=${GOOGLE_CALENDAR_DEFAULT_ID:-primary}
GOOGLE_CALENDAR_DEFAULT_TIMEZONE=${GOOGLE_CALENDAR_DEFAULT_TIMEZONE:-America/Sao_Paulo}
GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-}

# Meta
META_APP_ID=${META_APP_ID:-}
META_APP_SECRET=${META_APP_SECRET:-}
META_SYSTEM_USER_TOKEN=${META_SYSTEM_USER_TOKEN:-}
META_OAUTH_REDIRECT_URI=$TUNNEL_HOSTNAME/api/meta/oauth/callback
META_GRAPH_API_VERSION=${META_GRAPH_API_VERSION:-v21.0}
META_OAUTH_SCOPES=auto

# WhatsApp authorized numbers
WHATSAPP_AUTHORIZED_NUMBERS=${WHATSAPP_AUTHORIZED_NUMBERS:-}

# Anthropic (LLM fallback)
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
ENV

chmod 600 .env
echo "   .env written ($(wc -l < .env) lines)"

# ----- 4. Build + start the stack (tunnel profile excludes the LOCAL
#         cloudflared since we run cloudflared as a systemd service for
#         the production tunnel instead — see 03-setup-tunnel.sh) -----
echo "==> docker compose up -d --build"
docker compose up -d --build app frontend redis waha proxy

# ----- 5. Health-poll the backend -----
echo "==> waiting for backend at http://localhost:8010/api/health"
for i in $(seq 1 30); do
  if curl -fsS http://localhost:8010/api/health >/dev/null 2>&1; then
    echo "   ✓ healthy after ${i} attempt(s)"
    break
  fi
  sleep 2
done

if ! curl -fsS http://localhost:8010/api/health >/dev/null 2>&1; then
  echo "✗ backend never came up. logs:" >&2
  docker compose logs --tail=80 app >&2
  exit 2
fi

# ----- 6. Summary -----
echo ""
echo "✓ stack up:"
docker compose ps --format "  {{.Service}}\t{{.Status}}" 2>/dev/null
echo ""
echo "Local endpoints (on this VPS):"
echo "  http://localhost:8010/api/health"
echo "  http://localhost:8090/                  (proxy: single-URL view)"
echo "  http://localhost:3000/dashboard         (WAHA dashboard)"
echo ""
echo "Next: run 03-setup-tunnel.sh to expose this stack at $TUNNEL_HOSTNAME"
