-- Ads Manager column dictionary (pt-BR UI label ↔ URL `columns=` token / Graph field ↔ meaning).
-- Observed 2026-10-06 on act_873947475957808, presets Desempenho / Engajamento / Veiculação.
-- URL token = what appears in the Ads Manager `columns=` query param (a deep-linkable column set).
INSERT OR REPLACE INTO ui_column (ui_label_pt, api_field, presets, levels, unit, meaning, gotcha) VALUES
('Campanha / Conjunto de anúncios / Anúncio', 'name', 'all', 'campaign,adset,ad', 'text', 'Object name. Property code ONExxxxx lives in the AD name (and in dedicated lead ad sets).', 'Campaign name never carries the property code.'),
('Veiculação', 'delivery → effective_status', 'all', 'campaign,adset,ad', 'enum', 'Delivery state: Ativo, Desativado (PAUSED), Em análise, Rejeitado, Concluído, Aprendizado...', 'Ad shows "Ativo" only if its ad set and campaign are also active; read effective_status, not status.'),
('Ações', 'recommendations_guidance', 'Desempenho', 'campaign,adset,ad', 'badge', 'Meta recommendations / warnings count (⚠ issues, ⓘ recommendations).', 'UI-only; not in Insights.'),
('Configuração de atribuição', 'attribution_setting (adset.attribution_spec)', 'Desempenho', 'campaign,adset,ad', 'text', 'Window used to credit conversions, e.g. "Clique de 7 dias ou visualização de 1 dia".', 'Differs per ad set (traffic = 1-day click; leads = 7d click/1d view). Totals across objects mix windows.'),
('Resultados', 'results[].indicator / values', 'Desempenho', 'campaign,adset,ad', 'count', 'The objective''s result: Leads (formulário) → actions:leadgen.other; Visitas ao perfil do Instagram → profile_visit_view; Engajamentos → post_engagement.', 'Meaning changes per row ("Múltiplas conversões" when a campaign mixes goals). Never sum Resultados across objectives.'),
('Custo por resultado', 'cost_per_result', 'Desempenho', 'campaign,adset,ad', 'BRL', 'spend / results.', 'Shown "—" when results = 0.'),
('Orçamento', 'daily_budget | lifetime_budget', 'Desempenho', 'campaign,adset', 'BRL (API: centavos)', 'Budget; at ad level shows the PARENT ad set budget ("Conjunto de anúncios" subtitle).', 'API returns minor units: 10000 = R$100,00. "Usando o orçamento do conjunto" = budget lives on ad set (ABO).'),
('Valor gasto', 'spend', 'Desempenho', 'campaign,adset,ad', 'BRL', 'Amount spent in the date range.', 'Campaign row = whole campaign even when the filter is by ad name.'),
('Impressões', 'impressions', 'Desempenho,Veiculação', 'campaign,adset,ad', 'count', 'Times the ad was on screen.', ''),
('Alcance', 'reach', 'Desempenho,Veiculação', 'campaign,adset,ad', 'count', 'Unique Accounts Center accounts reached.', 'Not additive across ads/days (dedup) — never SUM daily reach.'),
('Frequência', 'frequency', 'Desempenho,Veiculação', 'campaign,adset,ad', 'ratio', 'impressions / reach.', 'Recompute from totals; do not average.'),
('CPM (custo por 1.000 impressões)', 'cpm', 'Desempenho,Veiculação', 'campaign,adset,ad', 'BRL', 'spend / impressions × 1000.', ''),
('Custo por 1.000 Contas da Central de Contas alcançadas', 'cpp', 'Veiculação', 'campaign,adset,ad', 'BRL', 'spend / reach × 1000.', ''),
('Cliques no link', 'actions:link_click (= inline_link_clicks)', 'Desempenho,Engajamento', 'campaign,adset,ad', 'count', 'Clicks that go to the destination (form/profile/site).', '`clicks` (Cliques (todos)) is a different, larger number.'),
('CPC (custo por clique no link)', 'cost_per_inline_link_click', 'Engajamento', 'campaign,adset,ad', 'BRL', 'spend / link clicks.', ''),
('Programação', 'schedule (start_time – end_time)', 'Desempenho', 'adset', 'date', 'Run window; "contínua" = no end.', ''),
('Término', 'end_time', 'Desempenho', 'campaign,adset,ad', 'date', 'End date or "Campanhas em andamento".', ''),
('Estratégia de lance', 'bid_strategy', 'Desempenho', 'campaign,adset,ad', 'enum', '"Volume mais alto" = LOWEST_COST_WITHOUT_CAP.', ''),
('Última edição significativa', 'last_significant_edit', 'Desempenho', 'campaign,adset,ad', 'date', 'Last edit that reset learning ("Há 83 dias").', 'Use the activity log for the full history.'),
('Classificação de qualidade', 'quality_ranking (quality_score_organic)', 'Desempenho', 'ad', 'enum', 'Above/below average vs competing ads.', 'UNKNOWN below ~500 impressions per ranking window — ONE10449 ads were all UNKNOWN.'),
('Classificação da taxa de engajamento', 'engagement_rate_ranking (quality_score_ectr)', 'Desempenho', 'ad', 'enum', '', 'Same UNKNOWN rule.'),
('Classificação da taxa de conversão', 'conversion_rate_ranking (quality_score_ecvr)', 'Desempenho', 'ad', 'enum', '', 'Same UNKNOWN rule.'),
('Engajamento com a Página', 'actions:page_engagement', 'Engajamento', 'campaign,adset,ad', 'count', 'All actions on the Page/profile/post attributed to the ad (includes 3-s video views).', 'Inflated by video_view — not a quality signal by itself.'),
('Reações ao post', 'actions:post_reaction', 'Engajamento', 'ad', 'count', 'Reactions/likes attributed to the ad.', 'Differs from the post''s organic like_count (IG likes include non-ad viewers).'),
('Comentários no post', 'actions:comment', 'Engajamento', 'ad', 'count', 'Comments attributed to the ad.', 'Post-level comment count (IG comments_count / FB comments.summary) is a different source — may disagree (e.g. deleted/hidden).'),
('Salvamentos do post', 'actions:onsite_conversion.post_save', 'Engajamento', 'ad', 'count', 'Saves.', ''),
('Compartilhamentos do post', 'actions:post', 'Engajamento', 'ad', 'count', 'Shares.', 'action_type is literally "post".'),
('Curtidas do Facebook', 'actions:like', 'Engajamento', 'ad', 'count', 'Page likes (follows of the FB Page) from the ad.', ''),
('Seguidores no Instagram', 'actions:onsite_conversion.ig_follow (when present)', 'Engajamento', 'ad', 'count', 'Instagram follows attributed to the ad.', 'Absent from the action list when zero.'),
('Leads (formulário)', 'actions:leadgen.other / onsite_conversion.lead_grouped', 'Desempenho', 'ad', 'count', 'Instant-form submissions.', 'actions:lead also counts pixel/offsite leads → can be 2× the form count. Canonical = results (leadgen.other) or lead_grouped.'),
('ThruPlays', 'video_thruplay_watched_actions', '(custom)', 'ad', 'count', 'Video watched to completion or ≥15 s.', 'Can exceed p25 on long videos (15 s < 25% of the video).'),
('Reproduções do vídeo a 25/50/75/100%', 'video_p25..p100_watched_actions', '(custom)', 'ad', 'count', 'Retention funnel.', 'video_play_actions counts autoplay starts — use p25 as "real" views.');
