-- ============================================================================
-- 018_editorial_workflow.sql — agents adopts the seed editorial workflow
-- (project seed-editorial-workflow, slice E5).
--
--   1. the seed `editorial_tables('agents')` template, verbatim (items /
--      versions / events, write-guards, SECURITY DEFINER transition RPCs);
--   2. knowledge_documents.editorial_item_id + knowledge_collections.requer_revisao
--      and the triggers that keep the document ROW = the PUBLISHED version;
--   3. agents.govern_collection — flag a collection + BACKFILL its documents;
--   4. search_knowledge / list_knowledge_documents re-declared with the
--      published-version predicate;
--   5. a self-check that aborts if the predicate would hide a live document.
--
-- Additive + forward-only: every new column is nullable/defaulted, nothing is
-- governed until `govern_collection` is called for a collection, so applying
-- this changes no retrieval result. Apply BEFORE (or with) the image that
-- reads `requer_revisao` / `editorial_item_id`; the previous image keeps
-- working on the migrated schema (it never selects the new columns by name).
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────
-- 1. Seed editorial tables (generated by noctusai_lib.domain.sql_templates.editorial_tables)
-- ────────────────────────────────────────────────────────────────────────
-- Editorial workflow (seed domain/editorial). Three tables, write-once / append-only,
-- every state change through agents.editorial_create_item / editorial_transition.
-- RLS deny-by-default: no policy but service_role_bypass; consumers add an org-scoped
-- SELECT policy only if a client reads directly. The DB re-checks legality + separation
-- of duties; the GRANTS it receives (p_grants) come from the caller (the permissions
-- organ) — the DB cannot see them, so only the service-role API may call these functions.

CREATE TABLE IF NOT EXISTS agents.editorial_items (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id              UUID NOT NULL,
    kind                TEXT NOT NULL,
    ref                 TEXT NOT NULL,
    state               TEXT NOT NULL DEFAULT 'rascunho',
    published_version_n INTEGER NULL,
    current_version_n   INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT editorial_items_state_check CHECK (state IN ('rascunho', 'revisao_editorial', 'revisao_seguranca', 'publicado', 'arquivado')),
    CONSTRAINT editorial_items_org_kind_ref_key UNIQUE (org_id, kind, ref),
    CONSTRAINT editorial_items_version_order_check
        CHECK (published_version_n IS NULL OR published_version_n <= current_version_n)
);

CREATE TABLE IF NOT EXISTS agents.editorial_versions (
    item_id     UUID NOT NULL REFERENCES agents.editorial_items(id) ON DELETE RESTRICT,
    n           INTEGER NOT NULL CHECK (n >= 1),
    content     JSONB NOT NULL,
    content_sha TEXT NOT NULL,
    author_id   UUID NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (item_id, n),
    CONSTRAINT editorial_versions_sha_check CHECK (content_sha ~ '^[0-9a-f]{64}$')
);

CREATE TABLE IF NOT EXISTS agents.editorial_events (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item_id    UUID NOT NULL,
    version_n  INTEGER NOT NULL,
    action     TEXT NOT NULL CHECK (action IN ('create', 'edit', 'submit', 'approve_editorial', 'approve_security', 'publish', 'send_back', 'archive')),
    from_state TEXT NULL,
    to_state   TEXT NOT NULL,
    actor_id   UUID NOT NULL,
    grant_name TEXT NULL,
    motivo     TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (item_id, version_n) REFERENCES agents.editorial_versions(item_id, n) ON DELETE RESTRICT,
    CONSTRAINT editorial_events_motivo_check
        CHECK (action NOT IN ('archive', 'send_back') OR length(btrim(coalesce(motivo, ''))) > 0)
);

CREATE INDEX IF NOT EXISTS idx_editorial_items_org_state ON agents.editorial_items (org_id, state);
CREATE INDEX IF NOT EXISTS idx_editorial_events_item ON agents.editorial_events (item_id, id);

ALTER TABLE agents.editorial_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE agents.editorial_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE agents.editorial_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_bypass" ON agents.editorial_items FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service_role_bypass" ON agents.editorial_versions FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service_role_bypass" ON agents.editorial_events FOR ALL TO service_role USING (true) WITH CHECK (true);
REVOKE ALL ON agents.editorial_items, agents.editorial_versions, agents.editorial_events FROM anon, authenticated;

-- The rule table, GENERATED from the Python workflow (never hand-edited here).
CREATE OR REPLACE FUNCTION agents.editorial_rules()
RETURNS TABLE (action TEXT, from_state TEXT, to_state TEXT, grant_name TEXT, needs_motivo BOOLEAN,
               not_author BOOLEAN, not_editorial_approver BOOLEAN, needs_security_signoff BOOLEAN,
               creates_version BOOLEAN)
LANGUAGE sql IMMUTABLE SET search_path = agents, public
AS $fn$
    SELECT * FROM (VALUES
        ('create', NULL::text, 'rascunho', 'editorial:editar', false, false, false, false, true),
        ('edit', 'rascunho', 'rascunho', 'editorial:editar', false, false, false, false, true),
        ('edit', 'publicado', 'rascunho', 'editorial:editar', false, false, false, false, true),
        ('submit', 'rascunho', 'revisao_editorial', 'editorial:editar', false, false, false, false, false),
        ('approve_editorial', 'revisao_editorial', 'revisao_seguranca', 'editorial:revisar', false, true, false, false, false),
        ('approve_security', 'revisao_seguranca', 'revisao_seguranca', 'editorial:revisar_seguranca', false, true, true, false, false),
        ('publish', 'revisao_seguranca', 'publicado', 'editorial:publicar', false, true, false, true, false),
        ('send_back', 'revisao_editorial', 'rascunho', 'editorial:revisar', true, false, false, false, false),
        ('send_back', 'revisao_seguranca', 'rascunho', 'editorial:revisar_seguranca', true, false, false, false, false),
        ('archive', 'rascunho', 'arquivado', 'editorial:publicar', true, false, false, false, false),
        ('archive', 'revisao_editorial', 'arquivado', 'editorial:publicar', true, false, false, false, false),
        ('archive', 'revisao_seguranca', 'arquivado', 'editorial:publicar', true, false, false, false, false),
        ('archive', 'publicado', 'arquivado', 'editorial:publicar', true, false, false, false, false)
    ) AS r(action, from_state, to_state, grant_name, needs_motivo, not_author,
           not_editorial_approver, needs_security_signoff, creates_version)
$fn$;

-- Immutability: versions are write-once, events append-only. DELETE is refused too.
CREATE OR REPLACE FUNCTION agents.editorial_guard_immutable()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = agents, public
AS $fn$
BEGIN
    IF TG_TABLE_NAME = 'editorial_versions' THEN
        RAISE EXCEPTION 'editorial_version_immutable' USING ERRCODE = 'P0001';
    END IF;
    RAISE EXCEPTION 'editorial_event_append_only' USING ERRCODE = 'P0001';
END;
$fn$;

-- Writes only inside editorial_create_item / editorial_transition (they raise the
-- transaction-local flag). A direct service-role INSERT/UPDATE/DELETE cannot forge a
-- state, a version or an audit event around the legality + separation-of-duties checks.
CREATE OR REPLACE FUNCTION agents.editorial_guard_via_transition()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = agents, public
AS $fn$
BEGIN
    IF current_setting('editorial.in_transition', true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION 'editorial_write_via_transition_only' USING ERRCODE = 'P0001';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'editorial_write_via_transition_only' USING ERRCODE = 'P0001';
    END IF;
    RETURN NEW;
END;
$fn$;

CREATE OR REPLACE FUNCTION agents.editorial_create_item(
    p_org_id UUID, p_kind TEXT, p_ref TEXT, p_actor_id UUID, p_grants TEXT[],
    p_content JSONB, p_content_sha TEXT
) RETURNS UUID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = agents, public
AS $fn$
DECLARE
    v_rule RECORD;
    v_id UUID;
BEGIN
    SELECT * INTO v_rule FROM agents.editorial_rules() r WHERE r.action = 'create';
    IF p_actor_id IS NULL THEN
        RAISE EXCEPTION 'editorial_actor_required' USING ERRCODE = 'P0001';
    END IF;
    IF NOT (v_rule.grant_name = ANY (coalesce(p_grants, ARRAY[]::TEXT[]))) THEN
        RAISE EXCEPTION 'editorial_missing_grant' USING ERRCODE = 'P0001';
    END IF;
    IF p_content IS NULL OR p_content_sha IS NULL THEN
        RAISE EXCEPTION 'editorial_content_required' USING ERRCODE = 'P0001';
    END IF;
    PERFORM set_config('editorial.in_transition', 'on', true);
    INSERT INTO agents.editorial_items (org_id, kind, ref, state, current_version_n)
    VALUES (p_org_id, p_kind, p_ref, v_rule.to_state, 1) RETURNING id INTO v_id;
    INSERT INTO agents.editorial_versions (item_id, n, content, content_sha, author_id)
    VALUES (v_id, 1, p_content, p_content_sha, p_actor_id);
    INSERT INTO agents.editorial_events (item_id, version_n, action, from_state, to_state, actor_id, grant_name)
    VALUES (v_id, 1, 'create', NULL, v_rule.to_state, p_actor_id, v_rule.grant_name);
    PERFORM set_config('editorial.in_transition', 'off', true);
    RETURN v_id;
END;
$fn$;

CREATE OR REPLACE FUNCTION agents.editorial_transition(
    p_org_id UUID, p_item_id UUID, p_action TEXT, p_actor_id UUID, p_grants TEXT[],
    p_motivo TEXT DEFAULT NULL, p_content JSONB DEFAULT NULL, p_content_sha TEXT DEFAULT NULL
) RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = agents, public
AS $fn$
DECLARE
    v_item agents.editorial_items%ROWTYPE;
    v_rule RECORD;
    v_n INTEGER;
    v_new_n INTEGER;
    v_author UUID;
    v_last_submit BIGINT;
    v_ed_approver UUID;
    v_signed BOOLEAN;
    v_published INTEGER;
    v_event BIGINT;
BEGIN
    SELECT * INTO v_item FROM agents.editorial_items
     WHERE id = p_item_id AND org_id = p_org_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'editorial_item_not_found' USING ERRCODE = 'P0001';
    END IF;
    SELECT * INTO v_rule FROM agents.editorial_rules() r
     WHERE r.action = p_action AND r.from_state = v_item.state;
    IF NOT FOUND THEN
        IF NOT EXISTS (SELECT 1 FROM agents.editorial_rules() r WHERE r.action = p_action) THEN
            RAISE EXCEPTION 'editorial_unknown_action' USING ERRCODE = 'P0001';
        END IF;
        RAISE EXCEPTION 'editorial_illegal_transition' USING ERRCODE = 'P0001';
    END IF;

    v_n := v_item.current_version_n;
    SELECT v.author_id INTO v_author FROM agents.editorial_versions v
     WHERE v.item_id = p_item_id AND v.n = v_n;
    SELECT coalesce(max(e.id), 0) INTO v_last_submit FROM agents.editorial_events e
     WHERE e.item_id = p_item_id AND e.version_n = v_n AND e.action = 'submit';
    SELECT e.actor_id INTO v_ed_approver FROM agents.editorial_events e
     WHERE e.item_id = p_item_id AND e.version_n = v_n AND e.action = 'approve_editorial'
       AND e.id > v_last_submit ORDER BY e.id DESC LIMIT 1;
    SELECT EXISTS (SELECT 1 FROM agents.editorial_events e
     WHERE e.item_id = p_item_id AND e.version_n = v_n AND e.action = 'approve_security'
       AND e.id > v_last_submit) INTO v_signed;

    IF p_action = 'approve_security' AND v_signed THEN
        RAISE EXCEPTION 'editorial_illegal_transition' USING ERRCODE = 'P0001';
    END IF;
    IF p_actor_id IS NULL THEN
        RAISE EXCEPTION 'editorial_actor_required' USING ERRCODE = 'P0001';
    END IF;
    IF NOT (v_rule.grant_name = ANY (coalesce(p_grants, ARRAY[]::TEXT[]))) THEN
        RAISE EXCEPTION 'editorial_missing_grant' USING ERRCODE = 'P0001';
    END IF;
    IF v_rule.needs_motivo AND length(btrim(coalesce(p_motivo, ''))) = 0 THEN
        RAISE EXCEPTION 'editorial_motivo_required' USING ERRCODE = 'P0001';
    END IF;
    IF v_rule.creates_version AND (p_content IS NULL OR p_content_sha IS NULL) THEN
        RAISE EXCEPTION 'editorial_content_required' USING ERRCODE = 'P0001';
    END IF;
    IF v_rule.not_author AND p_actor_id = v_author THEN
        RAISE EXCEPTION 'editorial_self_approval' USING ERRCODE = 'P0001';
    END IF;
    IF v_rule.not_editorial_approver AND p_actor_id IS NOT DISTINCT FROM v_ed_approver THEN
        RAISE EXCEPTION 'editorial_same_approver' USING ERRCODE = 'P0001';
    END IF;
    IF v_rule.needs_security_signoff AND NOT v_signed THEN
        RAISE EXCEPTION 'editorial_security_signoff_missing' USING ERRCODE = 'P0001';
    END IF;

    PERFORM set_config('editorial.in_transition', 'on', true);
    v_new_n := v_n;
    IF v_rule.creates_version THEN
        v_new_n := v_n + 1;
        INSERT INTO agents.editorial_versions (item_id, n, content, content_sha, author_id)
        VALUES (p_item_id, v_new_n, p_content, p_content_sha, p_actor_id);
    END IF;
    v_published := v_item.published_version_n;
    IF p_action = 'publish' THEN
        v_published := v_n;
    ELSIF p_action = 'archive' THEN
        v_published := NULL;
    END IF;
    UPDATE agents.editorial_items
       SET state = v_rule.to_state, current_version_n = v_new_n,
           published_version_n = v_published, updated_at = now()
     WHERE id = p_item_id;
    INSERT INTO agents.editorial_events
        (item_id, version_n, action, from_state, to_state, actor_id, grant_name, motivo)
    VALUES (p_item_id, v_new_n, p_action, v_rule.from_state, v_rule.to_state, p_actor_id,
            v_rule.grant_name, nullif(btrim(coalesce(p_motivo, '')), ''))
    RETURNING id INTO v_event;
    PERFORM set_config('editorial.in_transition', 'off', true);
    RETURN v_event;
END;
$fn$;

DROP TRIGGER IF EXISTS editorial_guard_versions_immutable ON agents.editorial_versions;
CREATE TRIGGER editorial_guard_versions_immutable
    BEFORE UPDATE OR DELETE ON agents.editorial_versions
    FOR EACH ROW EXECUTE FUNCTION agents.editorial_guard_immutable();
DROP TRIGGER IF EXISTS editorial_guard_events_append_only ON agents.editorial_events;
CREATE TRIGGER editorial_guard_events_append_only
    BEFORE UPDATE OR DELETE ON agents.editorial_events
    FOR EACH ROW EXECUTE FUNCTION agents.editorial_guard_immutable();
DROP TRIGGER IF EXISTS editorial_guard_items_via_transition ON agents.editorial_items;
CREATE TRIGGER editorial_guard_items_via_transition
    BEFORE INSERT OR UPDATE OR DELETE ON agents.editorial_items
    FOR EACH ROW EXECUTE FUNCTION agents.editorial_guard_via_transition();
DROP TRIGGER IF EXISTS editorial_guard_versions_via_transition ON agents.editorial_versions;
CREATE TRIGGER editorial_guard_versions_via_transition
    BEFORE INSERT ON agents.editorial_versions
    FOR EACH ROW EXECUTE FUNCTION agents.editorial_guard_via_transition();
DROP TRIGGER IF EXISTS editorial_guard_events_via_transition ON agents.editorial_events;
CREATE TRIGGER editorial_guard_events_via_transition
    BEFORE INSERT ON agents.editorial_events
    FOR EACH ROW EXECUTE FUNCTION agents.editorial_guard_via_transition();

-- SECURITY DEFINER EXECUTE LOCKDOWN: Postgres grants EXECUTE to PUBLIC by default.
REVOKE ALL ON FUNCTION agents.editorial_guard_immutable() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION agents.editorial_guard_via_transition() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION agents.editorial_create_item(UUID, TEXT, TEXT, UUID, TEXT[], JSONB, TEXT)
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION agents.editorial_transition(UUID, UUID, TEXT, UUID, TEXT[], TEXT, JSONB, TEXT)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION agents.editorial_create_item(UUID, TEXT, TEXT, UUID, TEXT[], JSONB, TEXT)
    TO service_role;
GRANT EXECUTE ON FUNCTION agents.editorial_transition(UUID, UUID, TEXT, UUID, TEXT[], TEXT, JSONB, TEXT)
    TO service_role;

-- ────────────────────────────────────────────────────────────────────────
-- 2. Knowledge documents ↔ editorial items.
--
-- The `knowledge_documents` ROW always holds the PUBLISHED content (that is
-- what FTS, `kb_ler`, `search_knowledge` and every store read serve), so
-- retrieval never needs a second read path. A governed document is a row
-- + an editorial item; its drafts live in `editorial_versions`, never on the
-- row. Publish copies the published version onto the row (trigger below),
-- archive deactivates it. Until its first publish a governed document is
-- `ativo = false` (invisible to retrieval).
--
-- Governance is per COLLECTION (`requer_revisao`, default false) and applies
-- to documents entering/changing through the store. Agent-package sync
-- collections (`projeto-<slug>`) are never flagged: developer-owned context
-- stays git-is-the-source (Decision Board agents-a1..a5, 2026-10-03).
-- ────────────────────────────────────────────────────────────────────────

ALTER TABLE agents.knowledge_collections
    ADD COLUMN IF NOT EXISTS requer_revisao BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE agents.knowledge_documents
    ADD COLUMN IF NOT EXISTS editorial_item_id UUID NULL
        REFERENCES agents.editorial_items(id) ON DELETE RESTRICT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_agents_knowledge_documents_editorial_item
    ON agents.knowledge_documents (editorial_item_id) WHERE editorial_item_id IS NOT NULL;

-- Write guard on governed documents: content, activation and identity change
-- ONLY through the publish/archive sync below (which raises the
-- transaction-local flag). A direct service-role UPDATE cannot edit live
-- governed content around the review, and cannot activate an unpublished
-- document. Linking an unlinked row (NULL -> item) is the one allowed edge.
CREATE OR REPLACE FUNCTION agents.knowledge_guard_governed()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = agents, public
AS $fn$
DECLARE
    v_published INTEGER;
BEGIN
    IF NEW.editorial_item_id IS NOT NULL AND NEW.ativo THEN
        SELECT i.published_version_n INTO v_published
          FROM agents.editorial_items i WHERE i.id = NEW.editorial_item_id;
        IF v_published IS NULL THEN
            RAISE EXCEPTION 'knowledge_unpublished_cannot_be_active' USING ERRCODE = 'P0001';
        END IF;
    END IF;
    IF TG_OP = 'UPDATE' AND OLD.editorial_item_id IS NOT NULL
       AND current_setting('agents.knowledge_publish_sync', true) IS DISTINCT FROM 'on' THEN
        IF NEW.editorial_item_id IS DISTINCT FROM OLD.editorial_item_id
           OR NEW.titulo IS DISTINCT FROM OLD.titulo
           OR NEW.tipo IS DISTINCT FROM OLD.tipo
           OR NEW.resumo IS DISTINCT FROM OLD.resumo
           OR NEW.conteudo IS DISTINCT FROM OLD.conteudo
           OR NEW.proveniencia IS DISTINCT FROM OLD.proveniencia
           OR NEW.source_sha IS DISTINCT FROM OLD.source_sha
           OR NEW.ativo IS DISTINCT FROM OLD.ativo
           OR NEW.slug IS DISTINCT FROM OLD.slug
           OR NEW.collection_id IS DISTINCT FROM OLD.collection_id THEN
            RAISE EXCEPTION 'knowledge_governed_write_via_editorial' USING ERRCODE = 'P0001';
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS knowledge_guard_governed ON agents.knowledge_documents;
CREATE TRIGGER knowledge_guard_governed
    BEFORE INSERT OR UPDATE ON agents.knowledge_documents
    FOR EACH ROW EXECUTE FUNCTION agents.knowledge_guard_governed();

-- publish / archive -> the document row. AFTER INSERT on the append-only event
-- log (same transaction as the transition), so the row can never disagree with
-- the item's published version.
CREATE OR REPLACE FUNCTION agents.knowledge_sync_published()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = agents, public
AS $fn$
DECLARE
    v_item agents.editorial_items%ROWTYPE;
    v_doc agents.knowledge_documents%ROWTYPE;
    v_content JSONB;
BEGIN
    SELECT * INTO v_item FROM agents.editorial_items WHERE id = NEW.item_id;
    IF NOT FOUND OR v_item.kind <> 'knowledge_document' THEN
        RETURN NEW;
    END IF;
    SELECT * INTO v_doc FROM agents.knowledge_documents WHERE editorial_item_id = NEW.item_id;
    IF NOT FOUND THEN
        RETURN NEW;  -- item exists before its row is linked (create flow): nothing to sync yet
    END IF;
    PERFORM set_config('agents.knowledge_publish_sync', 'on', true);
    IF NEW.action = 'publish' THEN
        SELECT v.content INTO v_content FROM agents.editorial_versions v
         WHERE v.item_id = NEW.item_id AND v.n = NEW.version_n;
        UPDATE agents.knowledge_documents SET
            titulo = v_content->>'titulo',
            tipo = v_content->>'tipo',
            resumo = v_content->>'resumo',
            conteudo = v_content->>'conteudo',
            proveniencia = coalesce(v_content->'proveniencia', '{}'::jsonb),
            source_sha = v_content->>'source_sha',
            ativo = true
         WHERE id = v_doc.id;
        INSERT INTO agents.knowledge_revisions (org_id, document_id, op, snapshot, author_id, motivo)
        VALUES (v_doc.org_id, v_doc.id, 'update',
                jsonb_build_object('editorial_item_id', NEW.item_id, 'version_n', NEW.version_n,
                                   'source_sha', v_content->>'source_sha', 'ativo', true),
                NEW.actor_id, 'editorial:publish');
    ELSIF NEW.action = 'archive' THEN
        UPDATE agents.knowledge_documents SET ativo = false WHERE id = v_doc.id;
        INSERT INTO agents.knowledge_revisions (org_id, document_id, op, snapshot, author_id, motivo)
        VALUES (v_doc.org_id, v_doc.id, 'archive',
                jsonb_build_object('editorial_item_id', NEW.item_id, 'version_n', NEW.version_n, 'ativo', false),
                NEW.actor_id, coalesce(NEW.motivo, 'editorial:archive'));
    END IF;
    PERFORM set_config('agents.knowledge_publish_sync', 'off', true);
    RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS knowledge_sync_published ON agents.editorial_events;
CREATE TRIGGER knowledge_sync_published
    AFTER INSERT ON agents.editorial_events
    FOR EACH ROW WHEN (NEW.action IN ('publish', 'archive'))
    EXECUTE FUNCTION agents.knowledge_sync_published();

REVOKE ALL ON FUNCTION agents.knowledge_guard_governed() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION agents.knowledge_sync_published() FROM PUBLIC, anon, authenticated;

-- ────────────────────────────────────────────────────────────────────────
-- 3. govern_collection — flag a collection `requer_revisao` and BACKFILL every
-- existing document in it: a live document (ativo) becomes the PUBLISHED
-- version 1 of a new item, an archived one an `arquivado` item, so retrieval
-- returns exactly what it returned before the flag (nothing is hidden). One
-- transaction; idempotent (already-linked documents are skipped). The
-- backfill writes through the editorial tables' own write-guard flag with a
-- synthetic, clearly-marked history (one `publish`/`archive` event, motivo
-- "backfill ...") — it is not a review and does not pretend to be one.
-- ────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION agents.govern_collection(
    p_org_id UUID, p_collection_id UUID, p_actor_id UUID
) RETURNS INTEGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = agents, public
AS $fn$
DECLARE
    d agents.knowledge_documents%ROWTYPE;
    v_content JSONB;
    v_item UUID;
    v_n INTEGER := 0;
BEGIN
    IF p_actor_id IS NULL THEN
        RAISE EXCEPTION 'editorial_actor_required' USING ERRCODE = 'P0001';
    END IF;
    PERFORM 1 FROM agents.knowledge_collections c
     WHERE c.id = p_collection_id AND c.org_id = p_org_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'knowledge_collection_not_found' USING ERRCODE = 'P0001';
    END IF;
    FOR d IN SELECT * FROM agents.knowledge_documents x
              WHERE x.collection_id = p_collection_id AND x.org_id = p_org_id
                AND x.editorial_item_id IS NULL ORDER BY x.created_at, x.id LOOP
        v_content := jsonb_build_object(
            'titulo', d.titulo, 'tipo', d.tipo, 'resumo', d.resumo, 'conteudo', d.conteudo,
            'proveniencia', d.proveniencia, 'source_sha', d.source_sha);
        PERFORM set_config('editorial.in_transition', 'on', true);
        INSERT INTO agents.editorial_items
            (org_id, kind, ref, state, published_version_n, current_version_n)
        VALUES (d.org_id, 'knowledge_document', d.agent_id::text || '/' || d.slug,
                CASE WHEN d.ativo THEN 'publicado' ELSE 'arquivado' END,
                CASE WHEN d.ativo THEN 1 ELSE NULL END, 1)
        RETURNING id INTO v_item;
        INSERT INTO agents.editorial_versions (item_id, n, content, content_sha, author_id)
        VALUES (v_item, 1, v_content,
                encode(sha256(convert_to(v_content::text, 'UTF8')), 'hex'), p_actor_id);
        INSERT INTO agents.editorial_events
            (item_id, version_n, action, from_state, to_state, actor_id, grant_name, motivo)
        VALUES (v_item, 1, CASE WHEN d.ativo THEN 'publish' ELSE 'archive' END, NULL,
                CASE WHEN d.ativo THEN 'publicado' ELSE 'arquivado' END, p_actor_id, NULL,
                'backfill: documento ja existente antes do fluxo editorial (migration 018, govern_collection)');
        PERFORM set_config('editorial.in_transition', 'off', true);
        UPDATE agents.knowledge_documents SET editorial_item_id = v_item WHERE id = d.id;
        v_n := v_n + 1;
    END LOOP;
    UPDATE agents.knowledge_collections SET requer_revisao = true WHERE id = p_collection_id;
    RETURN v_n;
END;
$fn$;

REVOKE ALL ON FUNCTION agents.govern_collection(UUID, UUID, UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION agents.govern_collection(UUID, UUID, UUID) TO service_role;

-- ────────────────────────────────────────────────────────────────────────
-- 4. Retrieval reads PUBLISHED only. Same bodies as 013 (search_knowledge /
-- list_knowledge_documents) plus the published-version predicate; the admin
-- list additionally reports the editorial state (it still lists drafts'
-- rows and archived documents — it is not a retrieval path).
-- ────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION agents.search_knowledge(
    p_org_id UUID,
    p_agent_id UUID,
    p_query TEXT,
    p_colecao TEXT DEFAULT NULL,
    p_limite INT DEFAULT 8
) RETURNS TABLE (
    doc_id UUID,
    slug TEXT,
    titulo TEXT,
    colecao TEXT,
    tag TEXT,
    tipo TEXT,
    trecho TEXT,
    rank REAL
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = agents, public
AS $$
BEGIN
    -- L5: bounded query (the router caps it at the same 512).
    IF p_query IS NULL OR length(p_query) > 512 THEN
        RAISE EXCEPTION 'query_too_long' USING ERRCODE = 'P0001';
    END IF;
    RETURN QUERY
    SELECT
        d.id AS doc_id,
        d.slug,
        d.titulo,
        c.slug AS colecao,
        c.tag,
        d.tipo,
        -- L5: ts_headline re-parses its whole input — bound it, a 2 MB
        -- document must not cost a 2 MB headline pass per hit.
        ts_headline(
            'portuguese',
            coalesce(d.resumo, '') || E'\n\n' || left(d.conteudo, 50000),
            websearch_to_tsquery('portuguese', p_query),
            'MaxFragments=2, MinWords=15, MaxWords=40'
        ) AS trecho,
        ts_rank(d.busca, websearch_to_tsquery('portuguese', p_query))::REAL AS rank
    FROM agents.knowledge_documents d
    JOIN agents.knowledge_collections c ON c.id = d.collection_id
    WHERE d.org_id = p_org_id
      AND d.agent_id = p_agent_id
      AND d.ativo = true
      AND (d.editorial_item_id IS NULL OR EXISTS (
            SELECT 1 FROM agents.editorial_items i
             WHERE i.id = d.editorial_item_id AND i.published_version_n IS NOT NULL))
      AND (p_colecao IS NULL OR c.slug = p_colecao)
      AND d.busca @@ websearch_to_tsquery('portuguese', p_query)
    ORDER BY rank DESC, d.updated_at DESC
    LIMIT LEAST(GREATEST(p_limite, 1), 20);
END;
$$;

REVOKE ALL ON FUNCTION agents.search_knowledge(UUID, UUID, TEXT, TEXT, INT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION agents.search_knowledge(UUID, UUID, TEXT, TEXT, INT) TO service_role;

CREATE OR REPLACE FUNCTION agents.list_knowledge_documents(
    p_org_id UUID,
    p_agent_id UUID,
    p_collection_id UUID,
    p_q TEXT DEFAULT NULL,
    p_tipo TEXT DEFAULT NULL,
    p_limit INT DEFAULT 20,
    p_offset INT DEFAULT 0
) RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = agents, public
AS $$
DECLARE
    v_pat TEXT;
    v_total BIGINT;
    v_items JSONB;
BEGIN
    IF p_q IS NOT NULL AND length(p_q) > 200 THEN
        RAISE EXCEPTION 'query_too_long' USING ERRCODE = 'P0001';
    END IF;
    IF p_q IS NOT NULL AND p_q <> '' THEN
        v_pat := '%' || replace(replace(replace(p_q, '\', '\\'), '%', '\%'), '_', '\_') || '%';
    END IF;

    SELECT count(*) INTO v_total
    FROM agents.knowledge_documents d
    WHERE d.org_id = p_org_id AND d.agent_id = p_agent_id AND d.collection_id = p_collection_id
      AND (p_tipo IS NULL OR d.tipo = p_tipo)
      AND (v_pat IS NULL
           OR d.titulo ILIKE v_pat ESCAPE '\'
           OR d.resumo ILIKE v_pat ESCAPE '\'
           OR d.conteudo ILIKE v_pat ESCAPE '\');

    SELECT COALESCE(jsonb_agg(to_jsonb(r) ORDER BY r.updated_at DESC, r.id), '[]'::JSONB) INTO v_items
    FROM (
        SELECT d.id, d.org_id, d.collection_id, d.agent_id, d.slug, d.titulo, d.tipo,
               d.proveniencia, d.resumo, d.conteudo, d.source_sha, d.ativo, d.created_at, d.updated_at,
               d.editorial_item_id,
               (SELECT i.state FROM agents.editorial_items i WHERE i.id = d.editorial_item_id) AS editorial_state
        FROM agents.knowledge_documents d
        WHERE d.org_id = p_org_id AND d.agent_id = p_agent_id AND d.collection_id = p_collection_id
          AND (p_tipo IS NULL OR d.tipo = p_tipo)
          AND (v_pat IS NULL
               OR d.titulo ILIKE v_pat ESCAPE '\'
               OR d.resumo ILIKE v_pat ESCAPE '\'
               OR d.conteudo ILIKE v_pat ESCAPE '\')
        ORDER BY d.updated_at DESC, d.id
        LIMIT LEAST(GREATEST(p_limit, 1), 100)
        OFFSET GREATEST(p_offset, 0)
    ) r;

    RETURN jsonb_build_object('total', v_total, 'items', v_items);
END;
$$;

REVOKE ALL ON FUNCTION agents.list_knowledge_documents(UUID, UUID, UUID, TEXT, TEXT, INT, INT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION agents.list_knowledge_documents(UUID, UUID, UUID, TEXT, TEXT, INT, INT) TO service_role;

-- ────────────────────────────────────────────────────────────────────────
-- 5. Self-check: with nothing governed yet, the published predicate must keep
-- EVERY live document visible. Aborts the migration (and so the deploy step)
-- rather than hiding knowledge.
-- ────────────────────────────────────────────────────────────────────────

DO $check$
DECLARE
    v_live BIGINT;
    v_visible BIGINT;
BEGIN
    SELECT count(*) INTO v_live FROM agents.knowledge_documents WHERE ativo = true;
    SELECT count(*) INTO v_visible FROM agents.knowledge_documents d
     WHERE d.ativo = true
       AND (d.editorial_item_id IS NULL OR EXISTS (
            SELECT 1 FROM agents.editorial_items i
             WHERE i.id = d.editorial_item_id AND i.published_version_n IS NOT NULL));
    IF v_live <> v_visible THEN
        RAISE EXCEPTION 'migration 018 would hide knowledge: % live, % visible', v_live, v_visible;
    END IF;
END
$check$;

NOTIFY pgrst, 'reload schema';
