-- Migration: storage_bucket
-- Generated by noctus.dev.scaffold_migration on 2026-10-02
-- Schema: store


-- ============================================================
-- Schema lock — pin name resolution to store, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = store, public;

-- =======================================================
-- Private bucket for the sold kit (`contrato-blindado/kit.zip`) and the
-- author photo (`autor/foto.<ext>`). PRIVATE by owner directive (no public
-- buckets, platform-wide — predeploy `storage_bucket_public` gate): the
-- backend reads/writes with the service role and serves files only through
-- short-lived signed URLs (`/api/public/download/{token}`,
-- `/api/public/autor/foto`). No storage.objects policy is added: nothing
-- but the service role ever touches this bucket.
-- =======================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('store-produtos', 'store-produtos', false)
ON CONFLICT (id) DO UPDATE SET public = false;
