# Generated by Django 4.2.9 on 2026-01-08 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imovel', '0002_imovel_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(blank=True, null=True)),
                ('regiao', models.CharField(blank=True, choices=[('n', 'Norte'), ('s', 'Sul'), ('l', 'Leste'), ('o', 'Oeste'), ('c', 'Centro')], max_length=1)),
                ('quartos_suites', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_interesse', models.PositiveIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_imoveis_rel', to='imovel.imovel')),
            ],
            options={
                'verbose_name': 'Interesse Imobiliário',
                'verbose_name_plural': 'Interesses Imobiliários',
            },
        ),
        migrations.CreateModel(
            name='InteresseAutomovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('quilometragem', models.PositiveIntegerField(blank=True, null=True)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_automoveis_rel', to='imovel.imovel')),
            ],
            options={
                'verbose_name': 'Interesse de Automóvel',
                'verbose_name_plural': 'Interesses de Automóveis',
            },
        ),
    ]
