# Generated by Django 4.2.9 on 2026-01-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0003_interesseimovel_interesseautomovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='interesses_automoveis',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='interesses_imoveis',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
