# Generated by Django 4.2.9 on 2026-01-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0004_alter_imovel_interesses_automoveis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='interesses_automoveis',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='interesses_imoveis',
        ),
        migrations.RemoveField(
            model_name='interesseimovel',
            name='valor_interesse',
        ),
    ]
