# Generated by Django 4.2.9 on 2026-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0005_remove_imovel_interesses_automoveis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesseautomovel',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='interesseautomovel',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='interesseautomovel',
            name='quilometragem',
        ),
        migrations.RemoveField(
            model_name='interesseautomovel',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='interesseimovel',
            name='quartos_suites',
        ),
        migrations.RemoveField(
            model_name='interesseimovel',
            name='regiao',
        ),
        migrations.RemoveField(
            model_name='interesseimovel',
            name='valor',
        ),
        migrations.AddField(
            model_name='interesseautomovel',
            name='tipo_automovel',
            field=models.CharField(blank=True, choices=[('c', 'Carro'), ('m', 'Moto'), ('cm', 'Caminhão')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='interesseautomovel',
            name='valor_maximo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interesseautomovel',
            name='valor_minimo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interesseimovel',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='interesseimovel',
            name='tipo_imovel',
            field=models.CharField(blank=True, choices=[('a', 'Apartamento'), ('c', 'Casa'), ('t', 'Terreno'), ('ch', 'Chácara'), ('co', 'Comercial')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='interesseimovel',
            name='valor_maximo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interesseimovel',
            name='valor_minimo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interesseimovel',
            name='zona',
            field=models.CharField(blank=True, choices=[('n', 'Norte'), ('s', 'Sul'), ('l', 'Leste'), ('o', 'Oeste')], default='', max_length=1),
        ),
    ]
