# Generated by Django 4.2.9 on 2026-01-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0006_remove_interesseautomovel_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('a', 'Apartamento'), ('c', 'Casa'), ('t', 'Terreno'), ('ch', 'Chácara'), ('co', 'Comercial')], max_length=2),
        ),
    ]
