# Generated by Django 4.2.9 on 2026-01-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0007_update_tipo_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='interesseimovel',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='interesseimovel',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='interesseimovel',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='interesseimovel',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
