# Generated by Django 4.2.9 on 2026-01-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0008_interesseimovel_bairro_interesseimovel_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='ref',
            field=models.CharField(max_length=8),
        ),
    ]
