# Generated by Django 4.2.9 on 2026-01-13 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_imovel', '0001_initial'),
        ('zona', '0002_remove_codigo_field'),
        ('tipo_automovel', '0001_initial'),
        ('imovel', '0009_add_codigo_and_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_imovel.tipoimovel'),
        ),
        migrations.AlterField(
            model_name='interesseautomovel',
            name='tipo_automovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_automovel.tipoautomovel'),
        ),
        migrations.AlterField(
            model_name='interesseimovel',
            name='tipo_imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_imovel.tipoimovel'),
        ),
        migrations.AlterField(
            model_name='interesseimovel',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zona.zona'),
        ),
    ]
