# Generated by Django 4.2.9 on 2026-01-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zona', '0002_remove_codigo_field'),
        ('imovel', '0010_alter_imovel_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zona.zona'),
        ),
    ]
