# Generated by Django 4.2.9 on 2026-01-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0012_alter_imovel_corretor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['tipo', 'zona'], name='imovel_imov_tipo_id_6690e4_idx'),
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['valor_venda'], name='imovel_imov_valor_v_6b9da6_idx'),
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['criado_por'], name='imovel_imov_criado__17f5bf_idx'),
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['corretor'], name='imovel_imov_correto_c60798_idx'),
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['ref'], name='imovel_imov_ref_73a23e_idx'),
        ),
        migrations.AddIndex(
            model_name='interesseautomovel',
            index=models.Index(fields=['imovel'], name='imovel_inte_imovel__58a574_idx'),
        ),
        migrations.AddIndex(
            model_name='interesseautomovel',
            index=models.Index(fields=['tipo_automovel'], name='imovel_inte_tipo_au_0c839c_idx'),
        ),
        migrations.AddIndex(
            model_name='interesseautomovel',
            index=models.Index(fields=['valor_minimo', 'valor_maximo'], name='imovel_inte_valor_m_fa058a_idx'),
        ),
        migrations.AddIndex(
            model_name='interesseimovel',
            index=models.Index(fields=['imovel'], name='imovel_inte_imovel__48ff2a_idx'),
        ),
        migrations.AddIndex(
            model_name='interesseimovel',
            index=models.Index(fields=['tipo_imovel', 'zona'], name='imovel_inte_tipo_im_3a348a_idx'),
        ),
        migrations.AddIndex(
            model_name='interesseimovel',
            index=models.Index(fields=['valor_minimo', 'valor_maximo'], name='imovel_inte_valor_m_36dc55_idx'),
        ),
    ]
