# Generated by Django 4.2.9 on 2026-01-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0013_alter_imovel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['-id'], 'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
    ]
