-- ============================================================================
-- Imobi Scheduling schema — single fresh-start migration
-- Schema: imobi_scheduling
--
-- Convention (`KB § PATTERNS/database-rls.md § Single 001 migration`): one
-- 001 migration per product builds the full schema from scratch. New tables /
-- columns / RLS land as edits to this file (so fresh environments stand up
-- with a single command). Live DBs already past 001 ship additive patches as
-- 002+, kept in lock-step so applying 001 alone to a fresh DB reproduces the
-- final shape exactly.
--
-- Phase 2 baseline: framework skeleton tables only (status_pagina +
-- invitations). Phase 3 ADDS the domain tables IN-PLACE inside this file:
--   users, condominiums, properties, services, crew_skills,
--   appointment_requests, appointment_request_services, route_groups,
--   appointments, conversation_messages, conversation_summaries,
--   pending_chat_identities, oauth_credentials, routes, tool_call_audits.
-- RLS is single-agency v1 (Phase 0 Q4): every org-bound table scopes by
--   ``org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid`` with WITH CHECK
-- on every INSERT/UPDATE; child tables carry an explicit ``org_id`` column
-- and scope via the same predicate (parent-FK denorm trades one column for
-- planner-friendly policies).
--
-- The prelude block below was generated by
-- ``python -c "from noctusai_lib.sql import prelude; print(prelude('imobi_scheduling'))"``
-- per ``feedback_migration_prelude_helpers``. Future authoring re-runs
-- the same helper for consistency.
-- ============================================================================

-- ============================================================
-- Schema lock — pin name resolution to imobi_scheduling, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = imobi_scheduling, public;

CREATE SCHEMA IF NOT EXISTS imobi_scheduling;

-- Grant usage to authenticated users (required for PostgREST)
GRANT USAGE ON SCHEMA imobi_scheduling TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA imobi_scheduling TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA imobi_scheduling TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA imobi_scheduling GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA imobi_scheduling GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;


-- ============================================================================
-- Page status (feature flags)
-- ============================================================================

CREATE TABLE imobi_scheduling.status_pagina (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome_pagina TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'producao' CHECK (status IN ('producao', 'desenvolvimento', 'desativado')),
    descricao TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE imobi_scheduling.status_pagina ENABLE ROW LEVEL SECURITY;

-- Note: this policy intentionally does NOT use `rls_subquery_policy` — that
-- helper always emits `TO authenticated`, but `todos_veem_producao` is an
-- anonymous-readable policy (anon role too).
CREATE POLICY "todos_veem_producao" ON imobi_scheduling.status_pagina
    FOR SELECT USING (status = 'producao');


-- ============================================================================
-- Invitations
-- ============================================================================

CREATE TABLE imobi_scheduling.invitations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    email TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member',
    invited_by UUID NOT NULL,
    token TEXT UNIQUE NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'expired', 'canceled')),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '7 days'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE imobi_scheduling.invitations ENABLE ROW LEVEL SECURITY;

-- Matches `rls_subquery_policy(imobi_scheduling, "invitations", "invitations_select_own_org",
--   "SELECT", using="org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid")`
-- output (whitespace-normalized). The scaffold's regression test enforces this.
CREATE POLICY "invitations_select_own_org" ON imobi_scheduling.invitations
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_scheduling_invitations_org ON imobi_scheduling.invitations(org_id);
CREATE INDEX idx_imobi_scheduling_invitations_token ON imobi_scheduling.invitations(token);


-- ============================================================================
-- updated_at trigger function (declared once per schema, reused per table)
-- Pattern: ``noctusai_lib.sql.updated_at_trigger(..., include_function=False)``
-- for per-table emission after this initial declaration.
-- ============================================================================

CREATE OR REPLACE FUNCTION imobi_scheduling.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = imobi_scheduling, public
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


-- ============================================================================
-- Domain tables (Phase 3) — agency staff + media crew, condos, properties,
-- service catalog, crew skills, appointment lifecycle, conversation memory,
-- pending-chat-identity (LID-aware deferred auth), OAuth credential cache,
-- routing cache, tool-call audit.
-- ----------------------------------------------------------------------------
-- RLS shape per Phase 0 Q4 decision (single-agency v1):
--   * org-binding tables filter by `org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid`
--   * child tables filter via parent FK
--   * INSERT/UPDATE policies pin WITH CHECK on `org_id` (Engineer-D ERP lesson)
--   * subquery `auth.uid()` / `auth.jwt()` form per `KB § PATTERNS/database-rls.md`
-- ============================================================================


-- ── 1. users — agency staff + media crew ──────────────────────────────────
CREATE TABLE imobi_scheduling.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    org_id UUID NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('real_estate_agent', 'media_crew', 'admin')),
    phone_number TEXT NOT NULL,
    email TEXT,
    -- Most-recent WhatsApp `@lid_*` chat ID mapped to this user (sibling parity).
    linked_identity TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (org_id, phone_number)
);

ALTER TABLE imobi_scheduling.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_select_org" ON imobi_scheduling.users
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "users_insert_org" ON imobi_scheduling.users
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "users_update_org" ON imobi_scheduling.users
    FOR UPDATE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid)
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "users_delete_org" ON imobi_scheduling.users
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_users_org ON imobi_scheduling.users(org_id);
CREATE INDEX idx_imobi_users_phone ON imobi_scheduling.users(phone_number);
CREATE INDEX idx_imobi_users_linked_identity ON imobi_scheduling.users(linked_identity);
CREATE INDEX idx_imobi_users_auth ON imobi_scheduling.users(auth_user_id);

CREATE OR REPLACE TRIGGER set_updated_at_users
    BEFORE UPDATE ON imobi_scheduling.users
    FOR EACH ROW EXECUTE FUNCTION imobi_scheduling.set_updated_at();


-- ── 2. condominiums ────────────────────────────────────────────────────────
CREATE TABLE imobi_scheduling.condominiums (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    notes TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (org_id, name)
);

ALTER TABLE imobi_scheduling.condominiums ENABLE ROW LEVEL SECURITY;

CREATE POLICY "condominiums_select_org" ON imobi_scheduling.condominiums
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "condominiums_insert_org" ON imobi_scheduling.condominiums
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "condominiums_update_org" ON imobi_scheduling.condominiums
    FOR UPDATE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid)
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "condominiums_delete_org" ON imobi_scheduling.condominiums
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_condominiums_org ON imobi_scheduling.condominiums(org_id);

CREATE OR REPLACE TRIGGER set_updated_at_condominiums
    BEFORE UPDATE ON imobi_scheduling.condominiums
    FOR EACH ROW EXECUTE FUNCTION imobi_scheduling.set_updated_at();


-- ── 3. properties (units within condominiums) ──────────────────────────────
CREATE TABLE imobi_scheduling.properties (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    condominium_id UUID NOT NULL REFERENCES imobi_scheduling.condominiums(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    unit TEXT,
    address_notes TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (org_id, code)
);

ALTER TABLE imobi_scheduling.properties ENABLE ROW LEVEL SECURITY;

CREATE POLICY "properties_select_org" ON imobi_scheduling.properties
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "properties_insert_org" ON imobi_scheduling.properties
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "properties_update_org" ON imobi_scheduling.properties
    FOR UPDATE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid)
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "properties_delete_org" ON imobi_scheduling.properties
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_properties_org ON imobi_scheduling.properties(org_id);
CREATE INDEX idx_imobi_properties_condo ON imobi_scheduling.properties(condominium_id);
CREATE INDEX idx_imobi_properties_code ON imobi_scheduling.properties(code);

CREATE OR REPLACE TRIGGER set_updated_at_properties
    BEFORE UPDATE ON imobi_scheduling.properties
    FOR EACH ROW EXECUTE FUNCTION imobi_scheduling.set_updated_at();


-- ── 4. services (service catalog: photo / video / drone / etc.) ────────────
CREATE TABLE imobi_scheduling.services (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    -- Default duration in minutes for a single delivery of this service.
    -- Used by scheduling engine to compute slot length.
    default_duration_minutes INTEGER NOT NULL DEFAULT 30 CHECK (default_duration_minutes > 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (org_id, name)
);

ALTER TABLE imobi_scheduling.services ENABLE ROW LEVEL SECURITY;

CREATE POLICY "services_select_org" ON imobi_scheduling.services
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "services_insert_org" ON imobi_scheduling.services
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "services_update_org" ON imobi_scheduling.services
    FOR UPDATE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid)
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "services_delete_org" ON imobi_scheduling.services
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_services_org ON imobi_scheduling.services(org_id);

CREATE OR REPLACE TRIGGER set_updated_at_services
    BEFORE UPDATE ON imobi_scheduling.services
    FOR EACH ROW EXECUTE FUNCTION imobi_scheduling.set_updated_at();


-- ── 5. crew_skills — M2M (media-crew user ↔ service) ───────────────────────
-- Per Engineer E audit: which crew member is qualified to deliver which
-- service. Used by scheduling engine to pick a viable assignee.
CREATE TABLE imobi_scheduling.crew_skills (
    user_id UUID NOT NULL REFERENCES imobi_scheduling.users(id) ON DELETE CASCADE,
    service_id UUID NOT NULL REFERENCES imobi_scheduling.services(id) ON DELETE CASCADE,
    org_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, service_id)
);

ALTER TABLE imobi_scheduling.crew_skills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "crew_skills_select_org" ON imobi_scheduling.crew_skills
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "crew_skills_insert_org" ON imobi_scheduling.crew_skills
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "crew_skills_delete_org" ON imobi_scheduling.crew_skills
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_crew_skills_user ON imobi_scheduling.crew_skills(user_id);
CREATE INDEX idx_imobi_crew_skills_service ON imobi_scheduling.crew_skills(service_id);
CREATE INDEX idx_imobi_crew_skills_org ON imobi_scheduling.crew_skills(org_id);


-- ── 6. appointment_requests ────────────────────────────────────────────────
-- A conversation-driven request that's still gathering details. Promotes to
-- a confirmed `appointment` once the bot + user agree on a slot.
CREATE TABLE imobi_scheduling.appointment_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    requester_user_id UUID NOT NULL REFERENCES imobi_scheduling.users(id) ON DELETE RESTRICT,
    property_id UUID REFERENCES imobi_scheduling.properties(id) ON DELETE SET NULL,
    condominium_id UUID REFERENCES imobi_scheduling.condominiums(id) ON DELETE SET NULL,
    requested_date DATE,
    requested_time_window TEXT,
    status TEXT NOT NULL DEFAULT 'collecting_details' CHECK (status IN (
        'collecting_details', 'pending_confirmation', 'confirmed', 'cancelled', 'expired'
    )),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE imobi_scheduling.appointment_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "appointment_requests_select_org" ON imobi_scheduling.appointment_requests
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "appointment_requests_insert_org" ON imobi_scheduling.appointment_requests
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "appointment_requests_update_org" ON imobi_scheduling.appointment_requests
    FOR UPDATE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid)
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "appointment_requests_delete_org" ON imobi_scheduling.appointment_requests
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_appt_requests_org ON imobi_scheduling.appointment_requests(org_id);
CREATE INDEX idx_imobi_appt_requests_requester ON imobi_scheduling.appointment_requests(requester_user_id);
CREATE INDEX idx_imobi_appt_requests_property ON imobi_scheduling.appointment_requests(property_id);
CREATE INDEX idx_imobi_appt_requests_condominium ON imobi_scheduling.appointment_requests(condominium_id);
CREATE INDEX idx_imobi_appt_requests_status ON imobi_scheduling.appointment_requests(status);

CREATE OR REPLACE TRIGGER set_updated_at_appointment_requests
    BEFORE UPDATE ON imobi_scheduling.appointment_requests
    FOR EACH ROW EXECUTE FUNCTION imobi_scheduling.set_updated_at();


-- ── 7. appointment_request_services — M2M ──────────────────────────────────
CREATE TABLE imobi_scheduling.appointment_request_services (
    appointment_request_id UUID NOT NULL
        REFERENCES imobi_scheduling.appointment_requests(id) ON DELETE CASCADE,
    service_id UUID NOT NULL
        REFERENCES imobi_scheduling.services(id) ON DELETE RESTRICT,
    org_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (appointment_request_id, service_id)
);

ALTER TABLE imobi_scheduling.appointment_request_services ENABLE ROW LEVEL SECURITY;

-- Scope via parent FK: only rows whose parent appointment_request is in the
-- caller's org are visible. Pattern: subquery against the org-bound parent.
CREATE POLICY "appt_req_services_select_via_parent"
    ON imobi_scheduling.appointment_request_services
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "appt_req_services_insert_via_parent"
    ON imobi_scheduling.appointment_request_services
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "appt_req_services_delete_via_parent"
    ON imobi_scheduling.appointment_request_services
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_appt_req_services_request
    ON imobi_scheduling.appointment_request_services(appointment_request_id);
CREATE INDEX idx_imobi_appt_req_services_service
    ON imobi_scheduling.appointment_request_services(service_id);


-- ── 8. route_groups — container for an assignee's day-of routes ────────────
-- One row per (date, media_crew_user). Appointments link back via
-- ``route_group_id`` for daily-bundle routing optimization.
CREATE TABLE imobi_scheduling.route_groups (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    date DATE NOT NULL,
    media_crew_user_id UUID REFERENCES imobi_scheduling.users(id) ON DELETE SET NULL,
    office_start_location TEXT,
    office_end_location TEXT,
    optimization_status TEXT NOT NULL DEFAULT 'not_started' CHECK (optimization_status IN (
        'not_started', 'pending', 'optimized', 'failed'
    )),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (org_id, date, media_crew_user_id)
);

ALTER TABLE imobi_scheduling.route_groups ENABLE ROW LEVEL SECURITY;

CREATE POLICY "route_groups_select_org" ON imobi_scheduling.route_groups
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "route_groups_insert_org" ON imobi_scheduling.route_groups
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "route_groups_update_org" ON imobi_scheduling.route_groups
    FOR UPDATE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid)
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "route_groups_delete_org" ON imobi_scheduling.route_groups
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_route_groups_org ON imobi_scheduling.route_groups(org_id);
CREATE INDEX idx_imobi_route_groups_date ON imobi_scheduling.route_groups(date);
CREATE INDEX idx_imobi_route_groups_crew ON imobi_scheduling.route_groups(media_crew_user_id);

CREATE OR REPLACE TRIGGER set_updated_at_route_groups
    BEFORE UPDATE ON imobi_scheduling.route_groups
    FOR EACH ROW EXECUTE FUNCTION imobi_scheduling.set_updated_at();


-- ── 9. appointments — confirmed bookings ──────────────────────────────────
CREATE TABLE imobi_scheduling.appointments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    appointment_request_id UUID
        REFERENCES imobi_scheduling.appointment_requests(id) ON DELETE SET NULL,
    google_calendar_event_id TEXT,
    property_id UUID NOT NULL REFERENCES imobi_scheduling.properties(id) ON DELETE RESTRICT,
    condominium_id UUID NOT NULL REFERENCES imobi_scheduling.condominiums(id) ON DELETE RESTRICT,
    media_crew_user_id UUID REFERENCES imobi_scheduling.users(id) ON DELETE SET NULL,
    route_group_id UUID REFERENCES imobi_scheduling.route_groups(id) ON DELETE SET NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN (
        'scheduled', 'completed', 'cancelled', 'no_show', 'rescheduled'
    )),
    -- Phase 9 — cancellation + reschedule audit columns.
    -- ``cancellation_reason`` captures free-text rationale from the user
    -- (LLM-summarized when long); ``cancelled_at`` + ``cancelled_by`` close
    -- the LGPD "who/when" trail for the booking lifecycle. Reschedule
    -- captures ``previous_start_at`` / ``previous_end_at`` so the audit
    -- shows the slot that was moved away from + the new value (visible
    -- in ``start_at`` / ``end_at``). ``rescheduled_by`` is the user ID.
    cancellation_reason TEXT,
    cancelled_at TIMESTAMPTZ,
    cancelled_by UUID REFERENCES imobi_scheduling.users(id) ON DELETE SET NULL,
    rescheduled_at TIMESTAMPTZ,
    rescheduled_by UUID REFERENCES imobi_scheduling.users(id) ON DELETE SET NULL,
    previous_start_at TIMESTAMPTZ,
    previous_end_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (end_at > start_at)
);

ALTER TABLE imobi_scheduling.appointments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "appointments_select_org" ON imobi_scheduling.appointments
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "appointments_insert_org" ON imobi_scheduling.appointments
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "appointments_update_org" ON imobi_scheduling.appointments
    FOR UPDATE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid)
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "appointments_delete_org" ON imobi_scheduling.appointments
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_appointments_org ON imobi_scheduling.appointments(org_id);
CREATE INDEX idx_imobi_appointments_start ON imobi_scheduling.appointments(start_at);
CREATE INDEX idx_imobi_appointments_end ON imobi_scheduling.appointments(end_at);
CREATE INDEX idx_imobi_appointments_request ON imobi_scheduling.appointments(appointment_request_id);
CREATE INDEX idx_imobi_appointments_crew ON imobi_scheduling.appointments(media_crew_user_id);
CREATE INDEX idx_imobi_appointments_property ON imobi_scheduling.appointments(property_id);
CREATE INDEX idx_imobi_appointments_condominium ON imobi_scheduling.appointments(condominium_id);
CREATE INDEX idx_imobi_appointments_route_group ON imobi_scheduling.appointments(route_group_id);
CREATE INDEX idx_imobi_appointments_calendar ON imobi_scheduling.appointments(google_calendar_event_id);

CREATE OR REPLACE TRIGGER set_updated_at_appointments
    BEFORE UPDATE ON imobi_scheduling.appointments
    FOR EACH ROW EXECUTE FUNCTION imobi_scheduling.set_updated_at();


-- ── 10. conversation_messages — inbound/outbound WhatsApp history ─────────
CREATE TABLE imobi_scheduling.conversation_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    -- Provider's message ID (WAHA `provider_message_id`); unique-per-provider
    -- supports idempotency on inbound webhook deliveries (sibling parity).
    provider_message_id TEXT UNIQUE,
    user_id UUID REFERENCES imobi_scheduling.users(id) ON DELETE SET NULL,
    -- Chat channel identifier (e.g. WAHA `chat_id`). Indexed for replay.
    chat_id TEXT,
    direction TEXT NOT NULL CHECK (direction IN ('inbound', 'outbound', 'system')),
    message_text TEXT NOT NULL,
    structured_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE imobi_scheduling.conversation_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "conversation_messages_select_org" ON imobi_scheduling.conversation_messages
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "conversation_messages_insert_org" ON imobi_scheduling.conversation_messages
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
-- No UPDATE policy: conversation messages are append-only by design.
CREATE POLICY "conversation_messages_delete_org" ON imobi_scheduling.conversation_messages
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_conv_messages_org ON imobi_scheduling.conversation_messages(org_id);
CREATE INDEX idx_imobi_conv_messages_user ON imobi_scheduling.conversation_messages(user_id);
CREATE INDEX idx_imobi_conv_messages_chat ON imobi_scheduling.conversation_messages(chat_id, created_at);
CREATE INDEX idx_imobi_conv_messages_direction ON imobi_scheduling.conversation_messages(direction);


-- ── 11. conversation_summaries — idle-window summary rolls ────────────────
CREATE TABLE imobi_scheduling.conversation_summaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    user_id UUID REFERENCES imobi_scheduling.users(id) ON DELETE SET NULL,
    conversation_id TEXT NOT NULL,
    summary_text TEXT NOT NULL,
    label JSONB,
    message_count INTEGER NOT NULL DEFAULT 0,
    model_used TEXT,
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE imobi_scheduling.conversation_summaries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "conversation_summaries_select_org" ON imobi_scheduling.conversation_summaries
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "conversation_summaries_insert_org" ON imobi_scheduling.conversation_summaries
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "conversation_summaries_delete_org" ON imobi_scheduling.conversation_summaries
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_conv_summaries_org ON imobi_scheduling.conversation_summaries(org_id);
CREATE INDEX idx_imobi_conv_summaries_user ON imobi_scheduling.conversation_summaries(user_id);
CREATE INDEX idx_imobi_conv_summaries_conv ON imobi_scheduling.conversation_summaries(conversation_id);


-- ── 12. pending_chat_identities — LID-aware deferred auth ─────────────────
-- An inbound chat we couldn't immediately map to an authorized user. Admin
-- resolves via linking (`resolved_to_user_id` + `status='resolved'`) or
-- rejection (`status='rejected'`). Org-scoped via the bot session.
CREATE TABLE imobi_scheduling.pending_chat_identities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    chat_id TEXT NOT NULL,
    push_name TEXT,
    phone_hint TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'rejected')),
    captured_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    resolved_to_user_id UUID REFERENCES imobi_scheduling.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (org_id, chat_id)
);

ALTER TABLE imobi_scheduling.pending_chat_identities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "pending_chat_identities_select_org" ON imobi_scheduling.pending_chat_identities
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "pending_chat_identities_insert_org" ON imobi_scheduling.pending_chat_identities
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "pending_chat_identities_update_org" ON imobi_scheduling.pending_chat_identities
    FOR UPDATE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid)
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "pending_chat_identities_delete_org" ON imobi_scheduling.pending_chat_identities
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_pending_chat_org ON imobi_scheduling.pending_chat_identities(org_id);
CREATE INDEX idx_imobi_pending_chat_status ON imobi_scheduling.pending_chat_identities(status);
CREATE INDEX idx_imobi_pending_chat_resolved_user
    ON imobi_scheduling.pending_chat_identities(resolved_to_user_id);

CREATE OR REPLACE TRIGGER set_updated_at_pending_chat_identities
    BEFORE UPDATE ON imobi_scheduling.pending_chat_identities
    FOR EACH ROW EXECUTE FUNCTION imobi_scheduling.set_updated_at();


-- ── 13. oauth_credentials — provider OAuth refresh-token cache ────────────
-- Per-org stored OAuth credential (e.g. for Google Calendar OAuth flow).
-- `refresh_token` SHOULD be encrypted at rest by the application before
-- INSERT (the seed's planned crypto layer; pre-encryption is an
-- application contract, not a DB enforcement). Marked LGPD-sensitive.
CREATE TABLE imobi_scheduling.oauth_credentials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    provider TEXT NOT NULL,
    account_email TEXT NOT NULL,
    refresh_token TEXT NOT NULL,
    access_token TEXT,
    access_token_expires_at TIMESTAMPTZ,
    scopes TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (org_id, provider, account_email)
);

ALTER TABLE imobi_scheduling.oauth_credentials ENABLE ROW LEVEL SECURITY;

-- OAuth credentials are higher-sensitivity than other org data — narrow
-- the policy to `authenticated` only (no anon).
CREATE POLICY "oauth_credentials_select_org" ON imobi_scheduling.oauth_credentials
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "oauth_credentials_insert_org" ON imobi_scheduling.oauth_credentials
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "oauth_credentials_update_org" ON imobi_scheduling.oauth_credentials
    FOR UPDATE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid)
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "oauth_credentials_delete_org" ON imobi_scheduling.oauth_credentials
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_oauth_org ON imobi_scheduling.oauth_credentials(org_id);
CREATE INDEX idx_imobi_oauth_provider ON imobi_scheduling.oauth_credentials(provider);

CREATE OR REPLACE TRIGGER set_updated_at_oauth_credentials
    BEFORE UPDATE ON imobi_scheduling.oauth_credentials
    FOR EACH ROW EXECUTE FUNCTION imobi_scheduling.set_updated_at();


-- ── 14. routes — Maps routing cache ────────────────────────────────────────
-- Per-direction routing result cache from Google Maps (Routes / Distance
-- Matrix). Keyed by (origin_place_id, destination_place_id) to dedupe.
-- Org-scoped because origin/destination may carry agency-private metadata
-- (office address, condo address) — pessimistic isolation.
CREATE TABLE imobi_scheduling.routes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    origin_place_id TEXT NOT NULL,
    destination_place_id TEXT NOT NULL,
    origin_label TEXT,
    destination_label TEXT,
    distance_meters INTEGER,
    duration_seconds INTEGER,
    -- Free-form payload for the full provider response (e.g. polyline,
    -- traffic-adjusted duration). JSONB to keep query-shape flexible.
    payload JSONB,
    provider TEXT NOT NULL DEFAULT 'google_maps',
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (org_id, origin_place_id, destination_place_id, provider)
);

ALTER TABLE imobi_scheduling.routes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "routes_select_org" ON imobi_scheduling.routes
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "routes_insert_org" ON imobi_scheduling.routes
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "routes_update_org" ON imobi_scheduling.routes
    FOR UPDATE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid)
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "routes_delete_org" ON imobi_scheduling.routes
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_routes_org ON imobi_scheduling.routes(org_id);
CREATE INDEX idx_imobi_routes_origin ON imobi_scheduling.routes(origin_place_id);
CREATE INDEX idx_imobi_routes_dest ON imobi_scheduling.routes(destination_place_id);
CREATE INDEX idx_imobi_routes_expires ON imobi_scheduling.routes(expires_at);

CREATE OR REPLACE TRIGGER set_updated_at_routes
    BEFORE UPDATE ON imobi_scheduling.routes
    FOR EACH ROW EXECUTE FUNCTION imobi_scheduling.set_updated_at();


-- ── 15. tool_call_audits — per-product LLM tool-call audit trail ──────────
-- Source template: seed/lib/backend/noctusai_lib/domain/ai/migrations/
--                  tool_call_audits.sql.template
-- Per `KB § PATTERNS/llm-tool-audit.md`: each product owns its own
-- ``tool_call_audits`` table. RLS scoped to org (single-agency v1).
-- LGPD: `arguments` + `result` JSONB may carry PII — products MUST redact
-- before constructing AuditRecord.
CREATE TABLE imobi_scheduling.tool_call_audits (
    id BIGSERIAL PRIMARY KEY,
    org_id UUID NOT NULL,
    correlation_id VARCHAR(64),
    gpt_call_id VARCHAR(64),
    tool_call_id VARCHAR(64),
    conversation_id VARCHAR(64),
    user_id UUID REFERENCES imobi_scheduling.users(id) ON DELETE SET NULL,
    tool_name VARCHAR(80) NOT NULL,
    status VARCHAR(16) NOT NULL,
    arguments JSONB,
    result JSONB,
    error TEXT,
    duration_ms INTEGER,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE imobi_scheduling.tool_call_audits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tool_call_audits_select_org" ON imobi_scheduling.tool_call_audits
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
CREATE POLICY "tool_call_audits_insert_org" ON imobi_scheduling.tool_call_audits
    FOR INSERT TO authenticated
    WITH CHECK (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);
-- No UPDATE policy: audit rows are append-only.
CREATE POLICY "tool_call_audits_delete_org" ON imobi_scheduling.tool_call_audits
    FOR DELETE TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX ix_imobi_tool_call_audits_org
    ON imobi_scheduling.tool_call_audits(org_id);
CREATE INDEX ix_imobi_tool_call_audits_correlation_id
    ON imobi_scheduling.tool_call_audits(correlation_id);
CREATE INDEX ix_imobi_tool_call_audits_user_started
    ON imobi_scheduling.tool_call_audits(user_id, started_at);
CREATE INDEX ix_imobi_tool_call_audits_tool_name
    ON imobi_scheduling.tool_call_audits(tool_name);
CREATE INDEX ix_imobi_tool_call_audits_status
    ON imobi_scheduling.tool_call_audits(status);
CREATE INDEX ix_imobi_tool_call_audits_conversation
    ON imobi_scheduling.tool_call_audits(conversation_id, started_at);


-- ============================================================================
-- Seed pages
-- ============================================================================

INSERT INTO imobi_scheduling.status_pagina (nome_pagina, status) VALUES
    ('dashboard', 'producao'),
    ('equipe', 'producao')
ON CONFLICT (nome_pagina) DO NOTHING;
