-- ============================================================================
-- Imobi Scheduling schema — single fresh-start migration
-- Schema: imobi_scheduling
--
-- Convention (`KB § PATTERNS/database-rls.md § Single 001 migration`): one
-- 001 migration per product builds the full schema from scratch. New tables /
-- columns / RLS land as edits to this file (so fresh environments stand up
-- with a single command). Live DBs already past 001 ship additive patches as
-- 002+, kept in lock-step so applying 001 alone to a fresh DB reproduces the
-- final shape exactly.
--
-- Phase 2 baseline: framework skeleton tables only (status_pagina +
-- invitations). Phase 3 will add domain tables (condominiums, properties,
-- services, media_crew, appointments, appointment_requests, conversations,
-- conversation_messages, conversation_summaries) IN-PLACE inside this file.
--
-- The prelude block below was generated by
-- ``python -c "from noctusai_lib.sql import prelude; print(prelude('imobi_scheduling'))"``
-- per ``feedback_migration_prelude_helpers``. Future authoring re-runs
-- the same helper for consistency.
-- ============================================================================

-- ============================================================
-- Schema lock — pin name resolution to imobi_scheduling, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = imobi_scheduling, public;

CREATE SCHEMA IF NOT EXISTS imobi_scheduling;

-- Grant usage to authenticated users (required for PostgREST)
GRANT USAGE ON SCHEMA imobi_scheduling TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA imobi_scheduling TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA imobi_scheduling TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA imobi_scheduling GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA imobi_scheduling GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;


-- ============================================================================
-- Page status (feature flags)
-- ============================================================================

CREATE TABLE imobi_scheduling.status_pagina (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome_pagina TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'producao' CHECK (status IN ('producao', 'desenvolvimento', 'desativado')),
    descricao TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE imobi_scheduling.status_pagina ENABLE ROW LEVEL SECURITY;

-- Note: this policy intentionally does NOT use `rls_subquery_policy` — that
-- helper always emits `TO authenticated`, but `todos_veem_producao` is an
-- anonymous-readable policy (anon role too).
CREATE POLICY "todos_veem_producao" ON imobi_scheduling.status_pagina
    FOR SELECT USING (status = 'producao');


-- ============================================================================
-- Invitations
-- ============================================================================

CREATE TABLE imobi_scheduling.invitations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL,
    email TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member',
    invited_by UUID NOT NULL,
    token TEXT UNIQUE NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'expired', 'canceled')),
    expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '7 days'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE imobi_scheduling.invitations ENABLE ROW LEVEL SECURITY;

-- Matches `rls_subquery_policy(imobi_scheduling, "invitations", "invitations_select_own_org",
--   "SELECT", using="org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid")`
-- output (whitespace-normalized). The scaffold's regression test enforces this.
CREATE POLICY "invitations_select_own_org" ON imobi_scheduling.invitations
    FOR SELECT TO authenticated
    USING (org_id = ((SELECT auth.jwt()) ->> 'org_id')::uuid);

CREATE INDEX idx_imobi_scheduling_invitations_org ON imobi_scheduling.invitations(org_id);
CREATE INDEX idx_imobi_scheduling_invitations_token ON imobi_scheduling.invitations(token);


-- ============================================================================
-- Seed pages
-- ============================================================================

INSERT INTO imobi_scheduling.status_pagina (nome_pagina, status) VALUES
    ('dashboard', 'producao'),
    ('equipe', 'producao')
ON CONFLICT (nome_pagina) DO NOTHING;
