# Generated by Django 4.2.1 on 2024-02-17 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("condominio", "0001_initial"),
        ("proprietario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corretor", models.CharField(max_length=50)),
                ("ref", models.CharField(max_length=7)),
                ("valor_venda", models.PositiveIntegerField()),
                ("interesses_imoveis", models.CharField(max_length=1000)),
                ("interesses_automoveis", models.CharField(max_length=1000)),
                (
                    "condominio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="condominio.condominio",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="proprietario.proprietario",
                    ),
                ),
            ],
        ),
    ]
