# Generated by Django 4.2.1 on 2024-02-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imovel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imovel",
            name="tipo",
            field=models.CharField(
                choices=[("a", "Apartamento"), ("c", "Casa"), ("t", "Terreno")],
                default="sem tipo",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
