-- GENERATED by scratchpad/migrate_permutas.py --emit-sql
-- Faithful copy of the legacy One Permutas Django schema
-- (project eourhjahxxkhozxmpyno, schema public) into `permutas`.
-- DDL only: the one-time data backfill is NOT replayed here.

CREATE SCHEMA IF NOT EXISTS "permutas";
CREATE TABLE IF NOT EXISTS "permutas"."auth_group" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" character varying(150) NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."auth_group_permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "group_id" integer NOT NULL,
  "permission_id" integer NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."auth_permission" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" character varying(255) NOT NULL,
  "content_type_id" integer NOT NULL,
  "codename" character varying(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."authsys_profile" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "full_name" character varying(50),
  "image" character varying(100),
  "bio" text,
  "verified" boolean NOT NULL,
  "user_id" bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."authsys_user" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "password" character varying(128) NOT NULL,
  "last_login" timestamp with time zone,
  "is_superuser" boolean NOT NULL,
  "first_name" character varying(150) NOT NULL,
  "last_name" character varying(150) NOT NULL,
  "is_staff" boolean NOT NULL,
  "is_active" boolean NOT NULL,
  "date_joined" timestamp with time zone NOT NULL,
  "username" character varying(20) NOT NULL,
  "email" character varying(254) NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."authsys_user_groups" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" bigint NOT NULL,
  "group_id" integer NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."authsys_user_user_permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" bigint NOT NULL,
  "permission_id" integer NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."condominio_condominio" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome" character varying(100),
  "cep" character varying(50),
  "estado" character varying(100),
  "cidade" character varying(100),
  "bairro" character varying(100),
  "endereco" character varying(200),
  "numero" integer,
  "km" integer,
  "valor_condominio" integer,
  "criado_por_id" bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."corretor_corretor" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome" character varying(100) NOT NULL,
  "telefone" character varying(20) NOT NULL,
  "email" character varying(254) NOT NULL,
  "creci" character varying(20) NOT NULL,
  "criado_em" timestamp with time zone NOT NULL,
  "criado_por_id" bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."django_admin_log" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "action_time" timestamp with time zone NOT NULL,
  "object_id" text,
  "object_repr" character varying(200) NOT NULL,
  "action_flag" smallint NOT NULL,
  "change_message" text NOT NULL,
  "content_type_id" integer,
  "user_id" bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."django_content_type" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app_label" character varying(100) NOT NULL,
  "model" character varying(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."django_migrations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "app" character varying(255) NOT NULL,
  "name" character varying(255) NOT NULL,
  "applied" timestamp with time zone NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."django_session" (
  "session_key" character varying(40) NOT NULL,
  "session_data" text NOT NULL,
  "expire_date" timestamp with time zone NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."imovel_imovel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ref" character varying(8) NOT NULL,
  "valor_venda" integer NOT NULL,
  "condominio_id" bigint NOT NULL,
  "criado_por_id" bigint NOT NULL,
  "proprietario_id" bigint NOT NULL,
  "tipo_id" bigint,
  "zona_id" bigint,
  "corretor_id" bigint
);
CREATE TABLE IF NOT EXISTS "permutas"."imovel_interesseautomovel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "criado_em" timestamp with time zone NOT NULL,
  "atualizado_em" timestamp with time zone NOT NULL,
  "criado_por_id" bigint NOT NULL,
  "imovel_id" bigint NOT NULL,
  "tipo_automovel_id" bigint,
  "valor_maximo" integer,
  "valor_minimo" integer
);
CREATE TABLE IF NOT EXISTS "permutas"."imovel_interesseimovel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "observacoes" text NOT NULL,
  "criado_em" timestamp with time zone NOT NULL,
  "atualizado_em" timestamp with time zone NOT NULL,
  "criado_por_id" bigint NOT NULL,
  "imovel_id" bigint NOT NULL,
  "estado" character varying(50) NOT NULL,
  "tipo_imovel_id" bigint,
  "valor_maximo" integer,
  "valor_minimo" integer,
  "zona_id" bigint,
  "bairro" character varying(50) NOT NULL,
  "cep" character varying(20) NOT NULL,
  "cidade" character varying(50) NOT NULL,
  "endereco" character varying(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."permuta_interessepermutaautomovel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cep" character varying(20) NOT NULL,
  "estado" character varying(50) NOT NULL,
  "cidade" character varying(50) NOT NULL,
  "bairro" character varying(50) NOT NULL,
  "endereco" character varying(100) NOT NULL,
  "valor_minimo" integer,
  "valor_maximo" integer,
  "observacoes" text NOT NULL,
  "criado_em" timestamp with time zone NOT NULL,
  "atualizado_em" timestamp with time zone NOT NULL,
  "criado_por_id" bigint NOT NULL,
  "permuta_automovel_id" bigint NOT NULL,
  "tipo_imovel_id" bigint,
  "zona_id" bigint
);
CREATE TABLE IF NOT EXISTS "permutas"."permuta_interessepermutaimovel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cep" character varying(20) NOT NULL,
  "estado" character varying(50) NOT NULL,
  "cidade" character varying(50) NOT NULL,
  "bairro" character varying(50) NOT NULL,
  "endereco" character varying(100) NOT NULL,
  "valor_minimo" integer,
  "valor_maximo" integer,
  "observacoes" text NOT NULL,
  "criado_em" timestamp with time zone NOT NULL,
  "atualizado_em" timestamp with time zone NOT NULL,
  "criado_por_id" bigint NOT NULL,
  "permuta_imovel_id" bigint NOT NULL,
  "tipo_imovel_id" bigint,
  "zona_id" bigint
);
CREATE TABLE IF NOT EXISTS "permutas"."permuta_match" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "codigo" character varying(7),
  "etapa_do_funil" character varying(20) NOT NULL,
  "observacoes" text NOT NULL,
  "criado_em" timestamp with time zone NOT NULL,
  "atualizado_em" timestamp with time zone NOT NULL,
  "criado_por_id" bigint NOT NULL,
  "imovel_id" bigint,
  "interesse_automovel_id" bigint,
  "interesse_imovel_id" bigint,
  "permuta_automovel_id" bigint,
  "permuta_imovel_id" bigint,
  "ordem" integer NOT NULL,
  "imovel_match_id" bigint,
  "is_bilateral" boolean NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."permuta_permutaautomovel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tipo_id" bigint,
  "marca" character varying(20) NOT NULL,
  "modelo" character varying(20) NOT NULL,
  "motor" character varying(10) NOT NULL,
  "valor" integer NOT NULL,
  "criado_por_id" bigint NOT NULL,
  "proprietario_id" bigint NOT NULL,
  "codigo" character varying(7),
  "corretor_id" bigint
);
CREATE TABLE IF NOT EXISTS "permutas"."permuta_permutaimovel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tipo_id" bigint,
  "condominio" character varying(50),
  "zona_id" bigint,
  "cep" character varying(20) NOT NULL,
  "estado" character varying(50) NOT NULL,
  "cidade" character varying(50) NOT NULL,
  "bairro" character varying(50) NOT NULL,
  "endereco" character varying(100) NOT NULL,
  "valor" integer NOT NULL,
  "criado_por_id" bigint NOT NULL,
  "proprietario_id" bigint NOT NULL,
  "codigo" character varying(7),
  "numero" integer,
  "corretor_id" bigint,
  "ref" character varying(50)
);
CREATE TABLE IF NOT EXISTS "permutas"."proprietario_proprietario" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome" character varying(50) NOT NULL,
  "telefone" character varying(50) NOT NULL,
  "email" character varying(254) NOT NULL,
  "criado_por_id" bigint NOT NULL,
  "corretor_id" bigint
);
CREATE TABLE IF NOT EXISTS "permutas"."tipo_automovel_tipoautomovel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome" character varying(50) NOT NULL,
  "criado_em" timestamp with time zone NOT NULL,
  "criado_por_id" bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."tipo_imovel_tipoimovel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome" character varying(50) NOT NULL,
  "criado_em" timestamp with time zone NOT NULL,
  "criado_por_id" bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."token_blacklist_blacklistedtoken" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "blacklisted_at" timestamp with time zone NOT NULL,
  "token_id" bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."token_blacklist_outstandingtoken" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "token" text NOT NULL,
  "created_at" timestamp with time zone,
  "expires_at" timestamp with time zone NOT NULL,
  "user_id" bigint,
  "jti" character varying(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS "permutas"."zona_zona" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nome" character varying(50) NOT NULL,
  "descricao" text NOT NULL,
  "criado_em" timestamp with time zone NOT NULL,
  "criado_por_id" bigint NOT NULL
);
DO $$ BEGIN ALTER TABLE "permutas"."auth_group" ADD CONSTRAINT "auth_group_name_key" UNIQUE (name); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."auth_group" ADD CONSTRAINT "auth_group_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE (group_id, permission_id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE (content_type_id, codename); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."auth_permission" ADD CONSTRAINT "auth_permission_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_profile" ADD CONSTRAINT "authsys_profile_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_profile" ADD CONSTRAINT "authsys_profile_user_id_key" UNIQUE (user_id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_user" ADD CONSTRAINT "authsys_user_email_key" UNIQUE (email); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_user" ADD CONSTRAINT "authsys_user_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_user_groups" ADD CONSTRAINT "authsys_user_groups_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_user_groups" ADD CONSTRAINT "authsys_user_groups_user_id_group_id_88f767a7_uniq" UNIQUE (user_id, group_id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_user_user_permissions" ADD CONSTRAINT "authsys_user_user_permis_user_id_permission_id_e96a2df5_uniq" UNIQUE (user_id, permission_id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_user_user_permissions" ADD CONSTRAINT "authsys_user_user_permissions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."condominio_condominio" ADD CONSTRAINT "condominio_condominio_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."corretor_corretor" ADD CONSTRAINT "corretor_corretor_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."django_admin_log" ADD CONSTRAINT "django_admin_log_action_flag_check" CHECK ((action_flag >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."django_admin_log" ADD CONSTRAINT "django_admin_log_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE (app_label, model); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."django_content_type" ADD CONSTRAINT "django_content_type_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."django_migrations" ADD CONSTRAINT "django_migrations_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."django_session" ADD CONSTRAINT "django_session_pkey" PRIMARY KEY (session_key); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_imovel" ADD CONSTRAINT "imovel_imovel_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_imovel" ADD CONSTRAINT "imovel_imovel_valor_venda_check" CHECK ((valor_venda >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseautomovel" ADD CONSTRAINT "imovel_interesseautomovel_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseautomovel" ADD CONSTRAINT "imovel_interesseautomovel_valor_maximo_check" CHECK ((valor_maximo >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseautomovel" ADD CONSTRAINT "imovel_interesseautomovel_valor_minimo_check" CHECK ((valor_minimo >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseimovel" ADD CONSTRAINT "imovel_interesseimovel_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseimovel" ADD CONSTRAINT "imovel_interesseimovel_valor_maximo_check" CHECK ((valor_maximo >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseimovel" ADD CONSTRAINT "imovel_interesseimovel_valor_minimo_check" CHECK ((valor_minimo >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaautomovel" ADD CONSTRAINT "permuta_interessepermutaautomovel_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaautomovel" ADD CONSTRAINT "permuta_interessepermutaautomovel_valor_maximo_check" CHECK ((valor_maximo >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaautomovel" ADD CONSTRAINT "permuta_interessepermutaautomovel_valor_minimo_check" CHECK ((valor_minimo >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaimovel" ADD CONSTRAINT "permuta_interessepermutaimovel_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaimovel" ADD CONSTRAINT "permuta_interessepermutaimovel_valor_maximo_check" CHECK ((valor_maximo >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaimovel" ADD CONSTRAINT "permuta_interessepermutaimovel_valor_minimo_check" CHECK ((valor_minimo >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_match" ADD CONSTRAINT "match_exactly_one_source" CHECK ((((imovel_match_id IS NULL) AND (permuta_automovel_id IS NULL) AND (permuta_imovel_id IS NOT NULL)) OR ((imovel_match_id IS NULL) AND (permuta_automovel_id IS NOT NULL) AND (permuta_imovel_id IS NULL)) OR ((imovel_match_id IS NOT NULL) AND (permuta_automovel_id IS NULL) AND (permuta_imovel_id IS NULL)))); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_match" ADD CONSTRAINT "permuta_match_codigo_key" UNIQUE (codigo); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_match" ADD CONSTRAINT "permuta_match_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaautomovel" ADD CONSTRAINT "permuta_permutaautomovel_codigo_key" UNIQUE (codigo); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaautomovel" ADD CONSTRAINT "permuta_permutaautomovel_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaautomovel" ADD CONSTRAINT "permuta_permutaautomovel_valor_check" CHECK ((valor >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaimovel" ADD CONSTRAINT "permuta_permutaimovel_codigo_key" UNIQUE (codigo); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaimovel" ADD CONSTRAINT "permuta_permutaimovel_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaimovel" ADD CONSTRAINT "permuta_permutaimovel_valor_check" CHECK ((valor >= 0)); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."proprietario_proprietario" ADD CONSTRAINT "proprietario_proprietario_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."tipo_automovel_tipoautomovel" ADD CONSTRAINT "tipo_automovel_tipoautomovel_nome_key" UNIQUE (nome); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."tipo_automovel_tipoautomovel" ADD CONSTRAINT "tipo_automovel_tipoautomovel_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."tipo_imovel_tipoimovel" ADD CONSTRAINT "tipo_imovel_tipoimovel_nome_key" UNIQUE (nome); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."tipo_imovel_tipoimovel" ADD CONSTRAINT "tipo_imovel_tipoimovel_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."token_blacklist_blacklistedtoken" ADD CONSTRAINT "token_blacklist_blacklistedtoken_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."token_blacklist_blacklistedtoken" ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_key" UNIQUE (token_id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq" UNIQUE (jti); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outstandingtoken_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."zona_zona" ADD CONSTRAINT "zona_zona_nome_10fc1100_uniq" UNIQUE (nome); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."zona_zona" ADD CONSTRAINT "zona_zona_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object OR invalid_table_definition THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE "permutas"."auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES "permutas"."auth_permission"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES "permutas"."auth_group"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES "permutas"."django_content_type"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_profile" ADD CONSTRAINT "authsys_profile_user_id_9ccfebae_fk_authsys_user_id" FOREIGN KEY (user_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_user_groups" ADD CONSTRAINT "authsys_user_groups_group_id_9eb9980a_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES "permutas"."auth_group"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_user_groups" ADD CONSTRAINT "authsys_user_groups_user_id_dda10c9b_fk_authsys_user_id" FOREIGN KEY (user_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_user_user_permissions" ADD CONSTRAINT "authsys_user_user_pe_permission_id_27dcae61_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES "permutas"."auth_permission"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."authsys_user_user_permissions" ADD CONSTRAINT "authsys_user_user_pe_user_id_bada3fb5_fk_authsys_u" FOREIGN KEY (user_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."condominio_condominio" ADD CONSTRAINT "condominio_condominio_criado_por_id_d14e53f9_fk_authsys_user_id" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."corretor_corretor" ADD CONSTRAINT "corretor_corretor_criado_por_id_d5efe573_fk_authsys_user_id" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES "permutas"."django_content_type"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_authsys_user_id" FOREIGN KEY (user_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_imovel" ADD CONSTRAINT "imovel_imovel_condominio_id_cd4f8a88_fk_condomini" FOREIGN KEY (condominio_id) REFERENCES "permutas"."condominio_condominio"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_imovel" ADD CONSTRAINT "imovel_imovel_corretor_id_d81bbce0_fk_corretor_corretor_id" FOREIGN KEY (corretor_id) REFERENCES "permutas"."corretor_corretor"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_imovel" ADD CONSTRAINT "imovel_imovel_criado_por_id_f5cfa51e_fk_authsys_user_id" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_imovel" ADD CONSTRAINT "imovel_imovel_proprietario_id_925bf181_fk_proprieta" FOREIGN KEY (proprietario_id) REFERENCES "permutas"."proprietario_proprietario"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_imovel" ADD CONSTRAINT "imovel_imovel_tipo_id_cd102fca_fk_tipo_imovel_tipoimovel_id" FOREIGN KEY (tipo_id) REFERENCES "permutas"."tipo_imovel_tipoimovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_imovel" ADD CONSTRAINT "imovel_imovel_zona_id_1efa8d70_fk_zona_zona_id" FOREIGN KEY (zona_id) REFERENCES "permutas"."zona_zona"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseautomovel" ADD CONSTRAINT "imovel_interesseauto_criado_por_id_05ad23b0_fk_authsys_u" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseautomovel" ADD CONSTRAINT "imovel_interesseauto_imovel_id_3afcb580_fk_imovel_im" FOREIGN KEY (imovel_id) REFERENCES "permutas"."imovel_imovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseautomovel" ADD CONSTRAINT "imovel_interesseauto_tipo_automovel_id_15127318_fk_tipo_auto" FOREIGN KEY (tipo_automovel_id) REFERENCES "permutas"."tipo_automovel_tipoautomovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseimovel" ADD CONSTRAINT "imovel_interesseimov_criado_por_id_c694b07c_fk_authsys_u" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseimovel" ADD CONSTRAINT "imovel_interesseimov_tipo_imovel_id_9dbc41d7_fk_tipo_imov" FOREIGN KEY (tipo_imovel_id) REFERENCES "permutas"."tipo_imovel_tipoimovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseimovel" ADD CONSTRAINT "imovel_interesseimovel_imovel_id_ff0a00b3_fk_imovel_imovel_id" FOREIGN KEY (imovel_id) REFERENCES "permutas"."imovel_imovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."imovel_interesseimovel" ADD CONSTRAINT "imovel_interesseimovel_zona_id_691a7f76_fk_zona_zona_id" FOREIGN KEY (zona_id) REFERENCES "permutas"."zona_zona"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaautomovel" ADD CONSTRAINT "permuta_interesseper_criado_por_id_8ad83a9f_fk_authsys_u" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaautomovel" ADD CONSTRAINT "permuta_interesseper_permuta_automovel_id_07fd8a8a_fk_permuta_p" FOREIGN KEY (permuta_automovel_id) REFERENCES "permutas"."permuta_permutaautomovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaautomovel" ADD CONSTRAINT "permuta_interesseper_tipo_imovel_id_4eb3d1b4_fk_tipo_imov" FOREIGN KEY (tipo_imovel_id) REFERENCES "permutas"."tipo_imovel_tipoimovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaautomovel" ADD CONSTRAINT "permuta_interesseper_zona_id_786c7f4b_fk_zona_zona" FOREIGN KEY (zona_id) REFERENCES "permutas"."zona_zona"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaimovel" ADD CONSTRAINT "permuta_interesseper_criado_por_id_34d4d231_fk_authsys_u" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaimovel" ADD CONSTRAINT "permuta_interesseper_permuta_imovel_id_3c9f3280_fk_permuta_p" FOREIGN KEY (permuta_imovel_id) REFERENCES "permutas"."permuta_permutaimovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaimovel" ADD CONSTRAINT "permuta_interesseper_tipo_imovel_id_09511cc5_fk_tipo_imov" FOREIGN KEY (tipo_imovel_id) REFERENCES "permutas"."tipo_imovel_tipoimovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_interessepermutaimovel" ADD CONSTRAINT "permuta_interessepermutaimovel_zona_id_9a8bb475_fk_zona_zona_id" FOREIGN KEY (zona_id) REFERENCES "permutas"."zona_zona"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_match" ADD CONSTRAINT "permuta_match_criado_por_id_165d7b46_fk_authsys_user_id" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_match" ADD CONSTRAINT "permuta_match_imovel_id_d753369e_fk_imovel_imovel_id" FOREIGN KEY (imovel_id) REFERENCES "permutas"."imovel_imovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_match" ADD CONSTRAINT "permuta_match_imovel_match_id_6e2df942_fk_imovel_imovel_id" FOREIGN KEY (imovel_match_id) REFERENCES "permutas"."imovel_imovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_match" ADD CONSTRAINT "permuta_match_interesse_automovel__9e23382a_fk_imovel_in" FOREIGN KEY (interesse_automovel_id) REFERENCES "permutas"."imovel_interesseautomovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_match" ADD CONSTRAINT "permuta_match_interesse_imovel_id_b578b0a4_fk_imovel_in" FOREIGN KEY (interesse_imovel_id) REFERENCES "permutas"."imovel_interesseimovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_match" ADD CONSTRAINT "permuta_match_permuta_automovel_id_75dd64eb_fk_permuta_p" FOREIGN KEY (permuta_automovel_id) REFERENCES "permutas"."permuta_permutaautomovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_match" ADD CONSTRAINT "permuta_match_permuta_imovel_id_3610ea3a_fk_permuta_p" FOREIGN KEY (permuta_imovel_id) REFERENCES "permutas"."permuta_permutaimovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaautomovel" ADD CONSTRAINT "permuta_permutaautom_corretor_id_1d6c820b_fk_corretor_" FOREIGN KEY (corretor_id) REFERENCES "permutas"."corretor_corretor"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaautomovel" ADD CONSTRAINT "permuta_permutaautom_criado_por_id_7d2d54fb_fk_authsys_u" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaautomovel" ADD CONSTRAINT "permuta_permutaautom_proprietario_id_0832b691_fk_proprieta" FOREIGN KEY (proprietario_id) REFERENCES "permutas"."proprietario_proprietario"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaautomovel" ADD CONSTRAINT "permuta_permutaautom_tipo_id_56d904a1_fk_tipo_auto" FOREIGN KEY (tipo_id) REFERENCES "permutas"."tipo_automovel_tipoautomovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaimovel" ADD CONSTRAINT "permuta_permutaimove_corretor_id_6485bf35_fk_corretor_" FOREIGN KEY (corretor_id) REFERENCES "permutas"."corretor_corretor"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaimovel" ADD CONSTRAINT "permuta_permutaimove_proprietario_id_0eb16e45_fk_proprieta" FOREIGN KEY (proprietario_id) REFERENCES "permutas"."proprietario_proprietario"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaimovel" ADD CONSTRAINT "permuta_permutaimove_tipo_id_8a8cadfe_fk_tipo_imov" FOREIGN KEY (tipo_id) REFERENCES "permutas"."tipo_imovel_tipoimovel"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaimovel" ADD CONSTRAINT "permuta_permutaimovel_criado_por_id_2db81ac9_fk_authsys_user_id" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."permuta_permutaimovel" ADD CONSTRAINT "permuta_permutaimovel_zona_id_91952b49_fk_zona_zona_id" FOREIGN KEY (zona_id) REFERENCES "permutas"."zona_zona"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."proprietario_proprietario" ADD CONSTRAINT "proprietario_proprie_corretor_id_4760c4ef_fk_corretor_" FOREIGN KEY (corretor_id) REFERENCES "permutas"."corretor_corretor"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."proprietario_proprietario" ADD CONSTRAINT "proprietario_proprie_criado_por_id_0d551d85_fk_authsys_u" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."tipo_automovel_tipoautomovel" ADD CONSTRAINT "tipo_automovel_tipoa_criado_por_id_fd2f2b0c_fk_authsys_u" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."tipo_imovel_tipoimovel" ADD CONSTRAINT "tipo_imovel_tipoimov_criado_por_id_1a368b70_fk_authsys_u" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."token_blacklist_blacklistedtoken" ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk" FOREIGN KEY (token_id) REFERENCES "permutas"."token_blacklist_outstandingtoken"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_authsys_u" FOREIGN KEY (user_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "permutas"."zona_zona" ADD CONSTRAINT "zona_zona_criado_por_id_5b8de971_fk_authsys_user_id" FOREIGN KEY (criado_por_id) REFERENCES "permutas"."authsys_user"(id) DEFERRABLE INITIALLY DEFERRED; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS auth_group_name_a6ea08ec_like ON "permutas".auth_group USING btree (name varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9 ON "permutas".auth_group_permissions USING btree (group_id);
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e ON "permutas".auth_group_permissions USING btree (permission_id);
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b ON "permutas".auth_permission USING btree (content_type_id);
CREATE INDEX IF NOT EXISTS authsys_user_email_a2bb5913_like ON "permutas".authsys_user USING btree (email varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS authsys_user_groups_group_id_9eb9980a ON "permutas".authsys_user_groups USING btree (group_id);
CREATE INDEX IF NOT EXISTS authsys_user_groups_user_id_dda10c9b ON "permutas".authsys_user_groups USING btree (user_id);
CREATE INDEX IF NOT EXISTS authsys_user_user_permissions_permission_id_27dcae61 ON "permutas".authsys_user_user_permissions USING btree (permission_id);
CREATE INDEX IF NOT EXISTS authsys_user_user_permissions_user_id_bada3fb5 ON "permutas".authsys_user_user_permissions USING btree (user_id);
CREATE INDEX IF NOT EXISTS condominio__bairro_ae6cfc_idx ON "permutas".condominio_condominio USING btree (bairro);
CREATE INDEX IF NOT EXISTS condominio__cidade_43d833_idx ON "permutas".condominio_condominio USING btree (cidade);
CREATE INDEX IF NOT EXISTS condominio__estado_81ca72_idx ON "permutas".condominio_condominio USING btree (estado, cidade);
CREATE INDEX IF NOT EXISTS condominio__nome_220578_idx ON "permutas".condominio_condominio USING btree (nome);
CREATE INDEX IF NOT EXISTS condominio_condominio_criado_por_id_d14e53f9 ON "permutas".condominio_condominio USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS corretor_corretor_criado_por_id_d5efe573 ON "permutas".corretor_corretor USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb ON "permutas".django_admin_log USING btree (content_type_id);
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6 ON "permutas".django_admin_log USING btree (user_id);
CREATE INDEX IF NOT EXISTS django_session_expire_date_a5c62663 ON "permutas".django_session USING btree (expire_date);
CREATE INDEX IF NOT EXISTS django_session_session_key_c0390e0f_like ON "permutas".django_session USING btree (session_key varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS imovel_imov_correto_c60798_idx ON "permutas".imovel_imovel USING btree (corretor_id);
CREATE INDEX IF NOT EXISTS imovel_imov_criado__17f5bf_idx ON "permutas".imovel_imovel USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS imovel_imov_ref_73a23e_idx ON "permutas".imovel_imovel USING btree (ref);
CREATE INDEX IF NOT EXISTS imovel_imov_tipo_id_6690e4_idx ON "permutas".imovel_imovel USING btree (tipo_id, zona_id);
CREATE INDEX IF NOT EXISTS imovel_imov_valor_v_6b9da6_idx ON "permutas".imovel_imovel USING btree (valor_venda);
CREATE INDEX IF NOT EXISTS imovel_imovel_condominio_id_cd4f8a88 ON "permutas".imovel_imovel USING btree (condominio_id);
CREATE INDEX IF NOT EXISTS imovel_imovel_corretor_id_d81bbce0 ON "permutas".imovel_imovel USING btree (corretor_id);
CREATE INDEX IF NOT EXISTS imovel_imovel_criado_por_id_f5cfa51e ON "permutas".imovel_imovel USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS imovel_imovel_proprietario_id_925bf181 ON "permutas".imovel_imovel USING btree (proprietario_id);
CREATE INDEX IF NOT EXISTS imovel_imovel_tipo_id_cd102fca ON "permutas".imovel_imovel USING btree (tipo_id);
CREATE INDEX IF NOT EXISTS imovel_imovel_zona_id_1efa8d70 ON "permutas".imovel_imovel USING btree (zona_id);
CREATE INDEX IF NOT EXISTS imovel_inte_imovel__58a574_idx ON "permutas".imovel_interesseautomovel USING btree (imovel_id);
CREATE INDEX IF NOT EXISTS imovel_inte_tipo_au_0c839c_idx ON "permutas".imovel_interesseautomovel USING btree (tipo_automovel_id);
CREATE INDEX IF NOT EXISTS imovel_inte_valor_m_fa058a_idx ON "permutas".imovel_interesseautomovel USING btree (valor_minimo, valor_maximo);
CREATE INDEX IF NOT EXISTS imovel_interesseautomovel_criado_por_id_05ad23b0 ON "permutas".imovel_interesseautomovel USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS imovel_interesseautomovel_imovel_id_3afcb580 ON "permutas".imovel_interesseautomovel USING btree (imovel_id);
CREATE INDEX IF NOT EXISTS imovel_interesseautomovel_tipo_automovel_id_15127318 ON "permutas".imovel_interesseautomovel USING btree (tipo_automovel_id);
CREATE INDEX IF NOT EXISTS imovel_inte_imovel__48ff2a_idx ON "permutas".imovel_interesseimovel USING btree (imovel_id);
CREATE INDEX IF NOT EXISTS imovel_inte_tipo_im_3a348a_idx ON "permutas".imovel_interesseimovel USING btree (tipo_imovel_id, zona_id);
CREATE INDEX IF NOT EXISTS imovel_inte_valor_m_36dc55_idx ON "permutas".imovel_interesseimovel USING btree (valor_minimo, valor_maximo);
CREATE INDEX IF NOT EXISTS imovel_interesseimovel_criado_por_id_c694b07c ON "permutas".imovel_interesseimovel USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS imovel_interesseimovel_imovel_id_ff0a00b3 ON "permutas".imovel_interesseimovel USING btree (imovel_id);
CREATE INDEX IF NOT EXISTS imovel_interesseimovel_tipo_imovel_id_9dbc41d7 ON "permutas".imovel_interesseimovel USING btree (tipo_imovel_id);
CREATE INDEX IF NOT EXISTS imovel_interesseimovel_zona_id_691a7f76 ON "permutas".imovel_interesseimovel USING btree (zona_id);
CREATE INDEX IF NOT EXISTS permuta_int_permuta_1d4185_idx ON "permutas".permuta_interessepermutaautomovel USING btree (permuta_automovel_id);
CREATE INDEX IF NOT EXISTS permuta_int_tipo_im_e67d99_idx ON "permutas".permuta_interessepermutaautomovel USING btree (tipo_imovel_id, zona_id);
CREATE INDEX IF NOT EXISTS permuta_int_valor_m_3512c5_idx ON "permutas".permuta_interessepermutaautomovel USING btree (valor_minimo, valor_maximo);
CREATE INDEX IF NOT EXISTS permuta_interessepermutaautomovel_criado_por_id_8ad83a9f ON "permutas".permuta_interessepermutaautomovel USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS permuta_interessepermutaautomovel_permuta_automovel_id_07fd8a8a ON "permutas".permuta_interessepermutaautomovel USING btree (permuta_automovel_id);
CREATE INDEX IF NOT EXISTS permuta_interessepermutaautomovel_tipo_imovel_id_4eb3d1b4 ON "permutas".permuta_interessepermutaautomovel USING btree (tipo_imovel_id);
CREATE INDEX IF NOT EXISTS permuta_interessepermutaautomovel_zona_id_786c7f4b ON "permutas".permuta_interessepermutaautomovel USING btree (zona_id);
CREATE INDEX IF NOT EXISTS permuta_int_permuta_1e624b_idx ON "permutas".permuta_interessepermutaimovel USING btree (permuta_imovel_id);
CREATE INDEX IF NOT EXISTS permuta_int_tipo_im_88627c_idx ON "permutas".permuta_interessepermutaimovel USING btree (tipo_imovel_id, zona_id);
CREATE INDEX IF NOT EXISTS permuta_int_valor_m_fb7b64_idx ON "permutas".permuta_interessepermutaimovel USING btree (valor_minimo, valor_maximo);
CREATE INDEX IF NOT EXISTS permuta_interessepermutaimovel_criado_por_id_34d4d231 ON "permutas".permuta_interessepermutaimovel USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS permuta_interessepermutaimovel_permuta_imovel_id_3c9f3280 ON "permutas".permuta_interessepermutaimovel USING btree (permuta_imovel_id);
CREATE INDEX IF NOT EXISTS permuta_interessepermutaimovel_tipo_imovel_id_09511cc5 ON "permutas".permuta_interessepermutaimovel USING btree (tipo_imovel_id);
CREATE INDEX IF NOT EXISTS permuta_interessepermutaimovel_zona_id_9a8bb475 ON "permutas".permuta_interessepermutaimovel USING btree (zona_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_imovel_imovel_match ON "permutas".permuta_match USING btree (imovel_id, imovel_match_id) WHERE (imovel_match_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_imovel_permuta_automovel ON "permutas".permuta_match USING btree (imovel_id, permuta_automovel_id) WHERE (permuta_automovel_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_imovel_permuta_imovel ON "permutas".permuta_match USING btree (imovel_id, permuta_imovel_id) WHERE (permuta_imovel_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS permuta_mat_codigo_5d1510_idx ON "permutas".permuta_match USING btree (codigo);
CREATE INDEX IF NOT EXISTS permuta_mat_criado__c79e7e_idx ON "permutas".permuta_match USING btree (criado_em DESC);
CREATE INDEX IF NOT EXISTS permuta_mat_etapa_d_420274_idx ON "permutas".permuta_match USING btree (etapa_do_funil, ordem);
CREATE INDEX IF NOT EXISTS permuta_mat_etapa_d_b2e2c4_idx ON "permutas".permuta_match USING btree (etapa_do_funil);
CREATE INDEX IF NOT EXISTS permuta_mat_imovel__ab11b1_idx ON "permutas".permuta_match USING btree (imovel_id);
CREATE INDEX IF NOT EXISTS permuta_mat_is_bila_1d7e72_idx ON "permutas".permuta_match USING btree (is_bilateral);
CREATE INDEX IF NOT EXISTS permuta_mat_permuta_1e9908_idx ON "permutas".permuta_match USING btree (permuta_imovel_id);
CREATE INDEX IF NOT EXISTS permuta_mat_permuta_e2a748_idx ON "permutas".permuta_match USING btree (permuta_automovel_id);
CREATE INDEX IF NOT EXISTS permuta_match_codigo_ae1b5e58_like ON "permutas".permuta_match USING btree (codigo varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS permuta_match_criado_por_id_165d7b46 ON "permutas".permuta_match USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS permuta_match_imovel_id_d753369e ON "permutas".permuta_match USING btree (imovel_id);
CREATE INDEX IF NOT EXISTS permuta_match_imovel_match_id_6e2df942 ON "permutas".permuta_match USING btree (imovel_match_id);
CREATE INDEX IF NOT EXISTS permuta_match_interesse_automovel_id_9e23382a ON "permutas".permuta_match USING btree (interesse_automovel_id);
CREATE INDEX IF NOT EXISTS permuta_match_interesse_imovel_id_b578b0a4 ON "permutas".permuta_match USING btree (interesse_imovel_id);
CREATE INDEX IF NOT EXISTS permuta_match_permuta_automovel_id_75dd64eb ON "permutas".permuta_match USING btree (permuta_automovel_id);
CREATE INDEX IF NOT EXISTS permuta_match_permuta_imovel_id_3610ea3a ON "permutas".permuta_match USING btree (permuta_imovel_id);
CREATE UNIQUE INDEX IF NOT EXISTS unique_imovel_imovel_match ON "permutas".permuta_match USING btree (imovel_id, imovel_match_id) WHERE (imovel_match_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS unique_imovel_permuta_automovel ON "permutas".permuta_match USING btree (imovel_id, permuta_automovel_id) WHERE (permuta_automovel_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS unique_imovel_permuta_imovel ON "permutas".permuta_match USING btree (imovel_id, permuta_imovel_id) WHERE (permuta_imovel_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS permuta_per_codigo_8de48d_idx ON "permutas".permuta_permutaautomovel USING btree (codigo);
CREATE INDEX IF NOT EXISTS permuta_per_correto_ebe6d5_idx ON "permutas".permuta_permutaautomovel USING btree (corretor_id);
CREATE INDEX IF NOT EXISTS permuta_per_marca_a2b855_idx ON "permutas".permuta_permutaautomovel USING btree (marca, modelo);
CREATE INDEX IF NOT EXISTS permuta_per_proprie_c09b0f_idx ON "permutas".permuta_permutaautomovel USING btree (proprietario_id);
CREATE INDEX IF NOT EXISTS permuta_per_tipo_id_b26664_idx ON "permutas".permuta_permutaautomovel USING btree (tipo_id);
CREATE INDEX IF NOT EXISTS permuta_per_valor_23c9b9_idx ON "permutas".permuta_permutaautomovel USING btree (valor);
CREATE INDEX IF NOT EXISTS permuta_permutaautomovel_codigo_d8c3a891_like ON "permutas".permuta_permutaautomovel USING btree (codigo varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS permuta_permutaautomovel_corretor_id_1d6c820b ON "permutas".permuta_permutaautomovel USING btree (corretor_id);
CREATE INDEX IF NOT EXISTS permuta_permutaautomovel_criado_por_id_7d2d54fb ON "permutas".permuta_permutaautomovel USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS permuta_permutaautomovel_proprietario_id_0832b691 ON "permutas".permuta_permutaautomovel USING btree (proprietario_id);
CREATE INDEX IF NOT EXISTS permuta_permutaautomovel_tipo_id_56d904a1 ON "permutas".permuta_permutaautomovel USING btree (tipo_id);
CREATE INDEX IF NOT EXISTS permuta_per_bairro_da3347_idx ON "permutas".permuta_permutaimovel USING btree (bairro);
CREATE INDEX IF NOT EXISTS permuta_per_cidade_69aa3a_idx ON "permutas".permuta_permutaimovel USING btree (cidade);
CREATE INDEX IF NOT EXISTS permuta_per_codigo_c1dd06_idx ON "permutas".permuta_permutaimovel USING btree (codigo);
CREATE INDEX IF NOT EXISTS permuta_per_correto_30cb45_idx ON "permutas".permuta_permutaimovel USING btree (corretor_id);
CREATE INDEX IF NOT EXISTS permuta_per_estado_6c4074_idx ON "permutas".permuta_permutaimovel USING btree (estado, cidade);
CREATE INDEX IF NOT EXISTS permuta_per_proprie_2c6e8d_idx ON "permutas".permuta_permutaimovel USING btree (proprietario_id);
CREATE INDEX IF NOT EXISTS permuta_per_tipo_id_6069b3_idx ON "permutas".permuta_permutaimovel USING btree (tipo_id, zona_id);
CREATE INDEX IF NOT EXISTS permuta_per_valor_e7510b_idx ON "permutas".permuta_permutaimovel USING btree (valor);
CREATE INDEX IF NOT EXISTS permuta_permutaimovel_codigo_b42327e7_like ON "permutas".permuta_permutaimovel USING btree (codigo varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS permuta_permutaimovel_corretor_id_6485bf35 ON "permutas".permuta_permutaimovel USING btree (corretor_id);
CREATE INDEX IF NOT EXISTS permuta_permutaimovel_criado_por_id_2db81ac9 ON "permutas".permuta_permutaimovel USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS permuta_permutaimovel_proprietario_id_0eb16e45 ON "permutas".permuta_permutaimovel USING btree (proprietario_id);
CREATE INDEX IF NOT EXISTS permuta_permutaimovel_tipo_id_8a8cadfe ON "permutas".permuta_permutaimovel USING btree (tipo_id);
CREATE INDEX IF NOT EXISTS permuta_permutaimovel_zona_id_91952b49 ON "permutas".permuta_permutaimovel USING btree (zona_id);
CREATE INDEX IF NOT EXISTS proprietari_correto_15c07a_idx ON "permutas".proprietario_proprietario USING btree (corretor_id);
CREATE INDEX IF NOT EXISTS proprietari_email_e81120_idx ON "permutas".proprietario_proprietario USING btree (email);
CREATE INDEX IF NOT EXISTS proprietari_nome_6db4d1_idx ON "permutas".proprietario_proprietario USING btree (nome);
CREATE INDEX IF NOT EXISTS proprietari_telefon_37fe33_idx ON "permutas".proprietario_proprietario USING btree (telefone);
CREATE INDEX IF NOT EXISTS proprietario_proprietario_corretor_id_4760c4ef ON "permutas".proprietario_proprietario USING btree (corretor_id);
CREATE INDEX IF NOT EXISTS proprietario_proprietario_criado_por_id_0d551d85 ON "permutas".proprietario_proprietario USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS tipo_automovel_tipoautomovel_criado_por_id_fd2f2b0c ON "permutas".tipo_automovel_tipoautomovel USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS tipo_automovel_tipoautomovel_nome_96a5f53d_like ON "permutas".tipo_automovel_tipoautomovel USING btree (nome varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS tipo_imovel_tipoimovel_criado_por_id_1a368b70 ON "permutas".tipo_imovel_tipoimovel USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS tipo_imovel_tipoimovel_nome_b650dae8_like ON "permutas".tipo_imovel_tipoimovel USING btree (nome varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON "permutas".token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS token_blacklist_outstandingtoken_user_id_83bc629a ON "permutas".token_blacklist_outstandingtoken USING btree (user_id);
CREATE INDEX IF NOT EXISTS zona_zona_criado_por_id_5b8de971 ON "permutas".zona_zona USING btree (criado_por_id);
CREATE INDEX IF NOT EXISTS zona_zona_nome_10fc1100_like ON "permutas".zona_zona USING btree (nome varchar_pattern_ops);
