-- ============================================================================
-- Migration 012 — Orbity Reports Organ: reports, report_snapshots
--
-- WHY:
--   Implements the "public token report" — agencies generate a shareable
--   frozen-metric link for their end-clients (no login required). The
--   public_token UUID IS the authorization for the public read endpoint;
--   the server validates token + expiry + status=published server-side
--   using the service_role (admin) client — RLS never evaluated for the
--   public path (service_role bypasses it), so cross-org contamination is
--   impossible: the server fetches by token only, returns only the latest
--   snapshot for that report row, and the report_snapshot payload was
--   generated under the owning org's service_role write.
--
-- Tables:
--   orbity.reports          — report definitions per client per org
--   orbity.report_snapshots — frozen metric payloads at generation time
--
-- RLS:
--   - authenticated: scoped to public.current_org_id()
--   - service_role:  bypass (used by public token read + generate)
--
-- IDEMPOTENT: CREATE TABLE IF NOT EXISTS + DROP POLICY IF EXISTS.
-- SEARCH PATH: session-pinned to orbity, public.
-- ============================================================================

SET search_path = orbity, public;


-- ============================================================================
-- 1. reports — report definitions
-- ============================================================================

CREATE TABLE IF NOT EXISTS orbity.reports (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id         UUID NOT NULL,
    client_id      UUID REFERENCES orbity.clients(id) ON DELETE SET NULL,
    name           TEXT NOT NULL,
    public_token   UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    period_start   DATE NOT NULL,
    period_end     DATE NOT NULL,
    config         JSONB NOT NULL DEFAULT '{}',  -- which metrics/sections to include
    status         TEXT NOT NULL DEFAULT 'draft'
                     CHECK (status IN ('draft', 'published')),
    expires_at     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Fast lookup by org (list view)
CREATE INDEX IF NOT EXISTS reports_org_id_idx
  ON orbity.reports (org_id);

-- Fast lookup by org + client (filter view)
CREATE INDEX IF NOT EXISTS reports_org_client_idx
  ON orbity.reports (org_id, client_id);

-- Public token lookup (the hot path for the unauthenticated endpoint)
CREATE INDEX IF NOT EXISTS reports_public_token_idx
  ON orbity.reports (public_token);

-- updated_at trigger (reuses the function defined in 005_crm_core.sql)
DROP TRIGGER IF EXISTS trg_reports_updated_at ON orbity.reports;
CREATE TRIGGER trg_reports_updated_at
  BEFORE UPDATE ON orbity.reports
  FOR EACH ROW EXECUTE FUNCTION orbity.set_updated_at();

-- RLS
ALTER TABLE orbity.reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reports_select_own_org" ON orbity.reports;
CREATE POLICY "reports_select_own_org" ON orbity.reports
  FOR SELECT TO authenticated
  USING (org_id = public.current_org_id());

DROP POLICY IF EXISTS "reports_insert_own_org" ON orbity.reports;
CREATE POLICY "reports_insert_own_org" ON orbity.reports
  FOR INSERT TO authenticated
  WITH CHECK (org_id = public.current_org_id());

DROP POLICY IF EXISTS "reports_update_own_org" ON orbity.reports;
CREATE POLICY "reports_update_own_org" ON orbity.reports
  FOR UPDATE TO authenticated
  USING (org_id = public.current_org_id());

DROP POLICY IF EXISTS "reports_delete_own_org" ON orbity.reports;
CREATE POLICY "reports_delete_own_org" ON orbity.reports
  FOR DELETE TO authenticated
  USING (org_id = public.current_org_id());

-- service_role bypass (seed contract): used by public token read + generate
DROP POLICY IF EXISTS "reports_service_role_all" ON orbity.reports;
CREATE POLICY "reports_service_role_all" ON orbity.reports
  FOR ALL TO service_role USING (true) WITH CHECK (true);


-- ============================================================================
-- 2. report_snapshots — frozen metric payloads at generation time
-- ============================================================================

CREATE TABLE IF NOT EXISTS orbity.report_snapshots (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id         UUID NOT NULL,
    report_id      UUID NOT NULL REFERENCES orbity.reports(id) ON DELETE CASCADE,
    generated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    payload        JSONB NOT NULL DEFAULT '{}'
    -- payload shape (generated by reports_service.generate_snapshot):
    -- {
    --   "period": {"start": "2026-05-01", "end": "2026-05-31"},
    --   "leads": {"total": 42, "hot": 10, "warm": 18, "cold": 14},
    --   "revenues": {"total": 15000.00, "count": 3},
    --   "expenses": {"total": 8000.00, "count": 5},
    --   "generated_at": "2026-06-01T12:00:00+00:00"
    --   -- NOC-REMEDIATE[orbity-reports-metrics-source]: when Meta-ads organ
    --   -- lands, extend with: "spend", "cpl", "campaigns" from
    --   -- orbity.ad_account_metrics / selected_ad_accounts. — 2026-06-03
    -- }
);

-- Fast lookup: latest snapshot for a given report
CREATE INDEX IF NOT EXISTS report_snapshots_report_id_idx
  ON orbity.report_snapshots (report_id, generated_at DESC);

-- Org-scoped lookup
CREATE INDEX IF NOT EXISTS report_snapshots_org_id_idx
  ON orbity.report_snapshots (org_id);

-- RLS
ALTER TABLE orbity.report_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "report_snapshots_select_own_org" ON orbity.report_snapshots;
CREATE POLICY "report_snapshots_select_own_org" ON orbity.report_snapshots
  FOR SELECT TO authenticated
  USING (org_id = public.current_org_id());

DROP POLICY IF EXISTS "report_snapshots_insert_own_org" ON orbity.report_snapshots;
CREATE POLICY "report_snapshots_insert_own_org" ON orbity.report_snapshots
  FOR INSERT TO authenticated
  WITH CHECK (org_id = public.current_org_id());

DROP POLICY IF EXISTS "report_snapshots_delete_own_org" ON orbity.report_snapshots;
CREATE POLICY "report_snapshots_delete_own_org" ON orbity.report_snapshots
  FOR DELETE TO authenticated
  USING (org_id = public.current_org_id());

-- service_role bypass: used by generate endpoint (admin client writes snapshot)
DROP POLICY IF EXISTS "report_snapshots_service_role_all" ON orbity.report_snapshots;
CREATE POLICY "report_snapshots_service_role_all" ON orbity.report_snapshots
  FOR ALL TO service_role USING (true) WITH CHECK (true);
