"""Segundo Cérebro — the 4 Sistema brain templates and their questionnaires
(single Python source of truth).

Migration ``*_cs_cerebro.sql`` seeds ``social_wiring.cs_brain_templates`` and
``social_wiring.cs_brain_questions`` from this module (the SQL is generated by
:func:`seed_sql`; a test asserts the migration file carries exactly that text),
and the questionnaire/synthesis services read the same constants — so the
questions are written ONCE.

Origin (``projects/core-studio/specs/cerebro-contract.md`` §2 and §10):

* questions are verbatim from ``pesquisa-cerebro-spec.md`` §9 /
  ``page-map-v2.md`` §8 (live-verified, wins over the earlier spec sections);
* ``hint`` is captured ONLY for Núcleo de Influência (from the owner's brain
  3081 page, ``captures/crawl-2026-10-06/pages/html__cores_questions_3081.html``)
  — the other three templates have no hints until the owner provides them;
* ``optional`` is DRAFT: Núcleo 02, 04, 07, 13, 15 only (the questions CoreStudio
  words as "se tiver"); the other templates have no optional question yet.

Template ``description`` texts are DRAFT, written here (CoreStudio shows none).
"""
from __future__ import annotations

from typing import NamedTuple, Optional


class BrainQuestionSpec(NamedTuple):
    position: int  # 1..N
    text: str
    hint: Optional[str]
    optional: bool


class BrainTemplateSpec(NamedTuple):
    slug: str
    name: str
    description: str
    sort_order: int
    questions: tuple[BrainQuestionSpec, ...]


def _qs(texts: tuple[str, ...]) -> tuple[BrainQuestionSpec, ...]:
    return tuple(BrainQuestionSpec(i, t, None, False) for i, t in enumerate(texts, start=1))


_NUCLEO_OPTIONAL = frozenset({2, 4, 7, 13, 15})

#: (text, hint) verbatim from the owner's Núcleo de Influência questionnaire.
_NUCLEO: tuple[tuple[str, str], ...] = (
    ("Qual é o seu nome, e o que você faz?",
     "Ex: Meu nome é Elias Maman, Especialista em Atenção Digital"),
    ("Você se autointitula por algum nome/termo?",
     "Ex: O Rei da Creatina; O Barbeiro dos Milionários; O Dentista do SUS"),
    ("Quem você ajuda?",
     "Descreva claramente o tipo de pessoa que você ajuda. Pode ser por profissão, dor, momento de vida ou contexto."),
    ("Você costuma chamar sua audiência por um nome específico?",
     "Ex: Os Remanescentes; Homens da Verdade, etc"),
    ("Qual é a principal dor que você resolve?",
     "O que mais machuca, trava ou impede essa pessoa de avançar?"),
    ("Qual é o inimigo e principal motivo causador dessa dor?",
     "O que está por trás disso tudo? Uma crença? Uma prática comum? Uma negligência?"),
    ("Você costuma dar um nome para esse inimigo?",
     "Ex: Geração Dopamina; Mundo de 3 Segundos; Satanás; etc"),
    ("O que sua audiência está tentando fazer para resolver isso, mas que não está funcionando?",
     "Quais tentativas frustradas seu público já fez?"),
    ("Qual crença errada ou visão limitada você gostaria que as pessoas mudassem?",
     "O que seu público acredita hoje que está atrapalhando mais do que ajudando?"),
    ("Qual problema filosófico existe por trás desse cenário?",
     "O que te indigna no mundo em relação a esse problema? O que não deveria ser como é?"),
    ("Qual é o segredo, atalho ou nova abordagem que resolve essa dor — e que você ensina?",
     "Aquela grande virada que poucas pessoas conhecem, mas faz toda a diferença."),
    ("Qual é a grande transformação que você acredita que seu trabalho gera?",
     "O que muda na vida da pessoa que realmente aplica o que você ensina?"),
    ("Você já criou algum método? Se sim, tem algum nome específico?",
     "Ex: Erupção de Seguidores; etc"),
    ("Quais argumentos fortes você pode usar para defender essa transformação?",
     "Dados, metáforas, analogias, raciocínios lógicos, comparações, etc."),
    ("Você conhece histórias reais de pessoas que saíram do ponto A para o ponto B com sua ajuda?",
     "Conte brevemente essas histórias: de onde elas saíram e onde chegaram."),
)

TEMPLATES: tuple[BrainTemplateSpec, ...] = (
    BrainTemplateSpec(
        slug="historia-de-criacao",
        name="História de Criação",
        description="Como você chegou até aqui: de onde veio, o que te moveu e o que quer deixar.",
        sort_order=1,
        questions=_qs((
            "Como era sua vida antes de trabalhar com o que você trabalha hoje?",
            "O que te motivou a iniciar nessa área?",
            "Qual ou quais foram os maiores desafios que você enfrentou nesse caminho?",
            "Teve um momento em que você pensou em desistir? O que te fez continuar?",
            "Qual foi o ponto de virada que fez tudo mudar?",
            "Quem você se tornou hoje?",
            "O que você aprendeu com tudo isso e quer passar para outras pessoas? Qual é sua missão nessa área?",
            "O que te motiva a continuar todos os dias?",
            "Qual legado você quer deixar por meio do seu trabalho?",
        )),
    ),
    BrainTemplateSpec(
        slug="historias-de-vida",
        name="Histórias de Vida do Especialista",
        description="As histórias reais que forjaram o especialista e que sustentam o conteúdo.",
        sort_order=2,
        questions=_qs((
            "Agora precisamos das histórias que te forjaram na sua jornada.",
            "Agora, conte histórias de grandes descobertas ou ensinamentos que você teve ao longo da sua jornada.",
            "Conte histórias de pessoas que você ajudou.",
            "Agora para finalizar, conte histórias de grandes conquistas que você teve na vida.",
        )),
    ),
    BrainTemplateSpec(
        slug="metodo-do-especialista",
        name="Método do Especialista",
        description="O passo a passo, os pilares e o nome do método que o especialista ensina.",
        sort_order=3,
        questions=_qs((
            "Qual é o passo a passo que você ensina para a pessoa sair do ponto A até o resultado?",
            "Quais são os 3 a 5 pilares que toda pessoa precisa entender ou aplicar pra ter resultado com o que você ensina?",
            "Se alguém seguisse só o essencial do que você faz, o que não poderia faltar?",
            "Existe uma ordem certa ou fases que a pessoa precisa seguir? Quais são elas?",
            "Você tem nomes para cada etapa ou princípio do seu método? Quer criar?",
            "Se você pudesse resumir seu método em uma frase ou nome forte, como ele se chamaria?",
            "Tem alguma parte do processo que as pessoas costumam pular e depois se arrependem? Qual é?",
        )),
    ),
    BrainTemplateSpec(
        slug="nucleo-de-influencia",
        name="Núcleo de Influência",
        description="Quem você é, quem você ajuda, a dor, o inimigo e a transformação: a base de toda a sua comunicação.",
        sort_order=4,
        questions=tuple(
            BrainQuestionSpec(i, text, hint, i in _NUCLEO_OPTIONAL)
            for i, (text, hint) in enumerate(_NUCLEO, start=1)
        ),
    ),
)

TEMPLATES_BY_SLUG: dict[str, BrainTemplateSpec] = {t.slug: t for t in TEMPLATES}
TEMPLATE_SLUGS: frozenset[str] = frozenset(TEMPLATES_BY_SLUG)

#: Questions per group in the progressive reveal (``group = (position-1)//3``).
GROUP_SIZE = 3


def question_id(template_slug: str, position: int) -> str:
    return f"{template_slug}.{position:02d}"


def question_group(position: int) -> int:
    return (position - 1) // GROUP_SIZE


def _q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def seed_sql() -> str:
    """The two ``INSERT … ON CONFLICT`` statements the cerebro migration
    carries verbatim."""
    trows = [
        f"    ({_q(t.slug)}, {_q(t.name)}, {_q(t.description)}, {t.sort_order})"
        for t in TEMPLATES
    ]
    qrows = []
    for t in TEMPLATES:
        for q in t.questions:
            hint = "NULL" if q.hint is None else _q(q.hint)
            qrows.append(
                f"    ({_q(question_id(t.slug, q.position))}, {_q(t.slug)}, {q.position}, "
                f"{_q(q.text)}, {hint}, {'true' if q.optional else 'false'})"
            )
    return (
        "INSERT INTO social_wiring.cs_brain_templates (slug, name, description, sort_order)\n"
        "VALUES\n" + ",\n".join(trows) + "\n"
        "ON CONFLICT (slug) DO UPDATE SET\n"
        "    name = EXCLUDED.name, description = EXCLUDED.description,\n"
        "    sort_order = EXCLUDED.sort_order;\n"
        "\n"
        "INSERT INTO social_wiring.cs_brain_questions\n"
        "    (id, template_slug, position, text, hint, optional)\n"
        "VALUES\n" + ",\n".join(qrows) + "\n"
        "ON CONFLICT (id) DO UPDATE SET\n"
        "    template_slug = EXCLUDED.template_slug, position = EXCLUDED.position,\n"
        "    text = EXCLUDED.text, hint = EXCLUDED.hint, optional = EXCLUDED.optional;\n"
    )
