"""Minha Pesquisa — the 40-variable taxonomy (single Python source of truth).

Migration 217 seeds ``social_wiring.cs_research_variables`` from this list
(the SQL is generated by :func:`seed_sql`; a test asserts the migration file
carries exactly this text), and the classifier prompt table is rendered from
it too — so the taxonomy is written ONCE.

Origin: 29 CoreStudio DB variables (slug as CoreStudio stores it, except the
``LOCAIS-...`` typo), 4 globals, 7 classifier-only concepts
(``projects/core-studio/specs/pesquisa-contract.md`` §2). Descriptions of the
five CoreStudio-classifier variables and the 7 classifier-only ones are
CoreStudio's wording; the rest are written here. All are refinable from real
usage ("first a fully working prototype, then refine").
"""
from __future__ import annotations

from typing import NamedTuple, Optional


class ResearchVariable(NamedTuple):
    slug: str
    label: str
    grupo: str  # publico | especialista | produto | global
    description: str
    corestudio_id: Optional[int]
    classifiable: bool


_P, _E, _R, _G = "publico", "especialista", "produto", "global"


def _v(slug, label, grupo, description, cid=None):
    return ResearchVariable(slug, label, grupo, description, cid, grupo != _G)


#: Ordered: CoreStudio select order, then classifier-only, then globals
#: (the position IS ``sort_order``, starting at 1).
VARIABLES: tuple[ResearchVariable, ...] = (
    _v("DESEJOS-TANGIVEIS-DO-AVATAR", "Desejos do meu público", _P, "Resultados concretos que o avatar quer alcançar", 18),
    _v("DORES-TANGIVEIS-DO-AVATAR", "Dores do meu público", _P, "Problemas concretos que o avatar vive agora", 17),
    _v("CARACTERISTICAS-DEMOGRAFICAS-DO-AVATAR", "Características demográficas do meu público", _P, "Gênero, idade, profissão, estado civil, localização, renda, escolaridade", 16),
    _v("CARACTERISTICAS-POSITIVAS-DO-AVATAR", "Qualidades do meu público", _P, "Qualidades e pontos fortes do avatar", 25),
    _v("CARACTERISTICAS-NEGATIVAS-DO-AVATAR", "Defeitos do meu público", _P, "Defeitos e pontos fracos do avatar", 26),
    _v("ITENS-CONHECIDOS-PELO-AVATAR", "Itens conhecidos pelo meu público", _P, "Objetos, marcas e coisas do dia a dia que o público reconhece", 15),
    _v("INSTITUICOES-CONHECIDAS-PELO-AVATAR", "Instituições conhecidas pelo meu público", _P, "Órgãos, empresas e instituições que o público conhece", 14),
    _v("PESSOAS-PERSONAGENS-CONHECIDOS-PELO-AVATAR", "Pessoas e personagens conhecidos pelo meu público", _P, "Figuras, celebridades, personagens que o público reconhece", 13),
    _v("INIMIGOS-DO-AVATAR", "Inimigos do meu público", _P, "Pessoas, grupos ou coisas que o público considera inimigas", 32),
    _v("FILMES-SERIES-E-MUSICAS-CONHECIDAS-PELO-AVATAR", "Filmes, séries ou músicas conhecidas pelo meu público", _P, "Filmes, séries e músicas que o público reconhece", 11),
    _v("EVENTOS-CONHECIDOS-PELO-AVATAR", "Eventos conhecidos pelo meu público", _P, "Eventos, datas e acontecimentos que o público reconhece", 19),
    _v("LOCAIS-CONHECIDOS-PELO-AVATAR", "Locais conhecidos pelo meu público", _P, "Lugares que o público conhece e frequenta", 20),
    _v("MOMENTO-DE-VIDA-DO-AVATAR", "Momentos de vida do meu público", _P, "Fases e momentos de vida pelos quais o avatar passa", 21),
    _v("OBJECOES-DO-AVATAR", "Objeções do meu público", _P, "Barreiras e dúvidas que impedem ação/compra", 10),
    _v("MEDOS-DO-AVATAR", "Medos do meu público", _P, "Cenários futuros negativos que o avatar teme", 9),
    _v("CRENCAS-DO-AVATAR", "Crenças do meu público", _P, "Crenças do avatar sobre o mundo, o dinheiro e a sociedade", 8),
    _v("DESEJOS-ALCANCADOS-PELO-ESPECIALISTA", "Desejos e conquistas que eu realizei", _E, "Desejos e conquistas que o especialista já realizou", 5),
    _v("PRODUTOS-CONHECIDOS-PELO-AVATAR", "Produtos conhecidos pelo meu público", _P, "Produtos que o público conhece e reconhece", 34),
    _v("SITUACOES-DOLOROSAS-DA-VIDA-DO-ESPECIALISTA", "Situações dolorosas que eu enfrentei", _E, "Situações dolorosas que o especialista viveu", 4),
    _v("HABITOS-DO-ESPECIALISTA", "Meus hábitos e hobbies", _E, "Hábitos e hobbies do especialista", 30),
    _v("FORMACAO-PROFISSAO-DO-ESPECIALISTA", "Minha formação profissional", _E, "Formação e profissão do especialista", 31),
    _v("CARACTERISTICAS-DEMOGRAFICAS-DO-ESPECIALISTA", "Quem eu sou (idade, estado civil, nacionalidade, etc)", _E, "Quem é o especialista: idade, estado civil, nacionalidade", 28),
    _v("CARACTERISTICAS-POSITIVAS-DO-ESPECIALISTA", "Minhas qualidades", _E, "Qualidades do especialista", 7),
    _v("CARACTERISTICAS-NEGATIVAS-DO-ESPECIALISTA", "Meus defeitos", _E, "Defeitos do especialista", 27),
    _v("TECNICAS-E-PROCEDIMENTOS-EFETUADOS-PELO-ESPECIALISTA", "Técnicas, serviços e procedimentos que eu efetuo", _E, "Técnicas, serviços e procedimentos que o especialista efetua", 6),
    _v("TECNICAS-PROCEDIMENTOS-NAO-RECOMENDADOS-PELO-ESPECIALISTA", "Técnicas, serviços e procedimentos que eu não recomendo", _E, "Técnicas, serviços e procedimentos que o especialista não recomenda", 12),
    _v("HABITOS-RECOMENDADOS-PELO-ESPECIALISTA", "Hábitos que eu recomendo para o meu público", _E, "Hábitos que o especialista recomenda ao público", 3),
    _v("HABITOS-NAO-RECOMENDADOS-PELO-ESPECIALISTA", "Hábitos que eu não recomendo para o meu público", _E, "Hábitos que o especialista não recomenda ao público", 2),
    _v("CRENCAS-DO-ESPECIALISTA", "Crenças e ideias que eu defendo", _E, "Crenças e ideias que o especialista defende", 1),
    # classifier-only (no CoreStudio UI variable)
    _v("FRUSTRACOES-DO-AVATAR", "Frustrações do meu público", _P, "Tentativas passadas que falharam"),
    _v("CRENCAS-LIMITANTES-DO-AVATAR", "Crenças limitantes do meu público", _P, "Crenças internas negativas sobre si mesmo"),
    _v("INIMIGO-COMUM", "Inimigo comum", _P, "Vilão externo que o avatar culpa"),
    _v("MECANISMO-UNICO", "Mecanismo único", _R, "Método ou sistema que diferencia a solução"),
    _v("PROMESSA-PRINCIPAL", "Promessa principal", _R, "Transformação central prometida"),
    _v("PROVA-SOCIAL", "Prova social", _R, "Resultados de terceiros, números, autoridade"),
    _v("NICHO-OU-MERCADO", "Nicho ou mercado", _R, "Área ou segmento do produto"),
    # globals (never classified)
    _v("VERBOS-PODEROSOS", "Verbos Poderosos", _G, "Lista global de verbos de impacto", 22),
    _v("ADJETIVOS-PODEROSOS", "Adjetivos Poderosos", _G, "Lista global de adjetivos de impacto", 23),
    _v("MOMENTO-DO-DIA", "Momento do dia", _G, "Momentos do dia (manhã, tarde, noite…)", 24),
    _v("GPT", "GPT", _G, "Lista global GPT (uso a refinar)", 29),
)

VARIABLE_SLUGS: frozenset[str] = frozenset(v.slug for v in VARIABLES)
CLASSIFIABLE: tuple[ResearchVariable, ...] = tuple(v for v in VARIABLES if v.classifiable)
CLASSIFIABLE_SLUGS: frozenset[str] = frozenset(v.slug for v in CLASSIFIABLE)


def _q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def seed_sql() -> str:
    """The ``INSERT … ON CONFLICT`` that migration 217 carries verbatim."""
    rows = []
    for i, v in enumerate(VARIABLES, start=1):
        cid = "NULL" if v.corestudio_id is None else str(v.corestudio_id)
        rows.append(
            f"    ({_q(v.slug)}, {_q(v.label)}, {_q(v.grupo)}, {_q(v.description)}, "
            f"{cid}, {i}, {'true' if v.classifiable else 'false'})"
        )
    return (
        "INSERT INTO social_wiring.cs_research_variables\n"
        "    (slug, label, grupo, description, corestudio_id, sort_order, classifiable)\n"
        "VALUES\n" + ",\n".join(rows) + "\n"
        "ON CONFLICT (slug) DO UPDATE SET\n"
        "    label = EXCLUDED.label, grupo = EXCLUDED.grupo,\n"
        "    description = EXCLUDED.description, corestudio_id = EXCLUDED.corestudio_id,\n"
        "    sort_order = EXCLUDED.sort_order, classifiable = EXCLUDED.classifiable;\n"
    )
