-- ============================================================================
-- Migration 120 · social_wiring: a GENERATED contract version stores its
-- editable `.docx` too, not only the ABNT PDF
--
-- WHAT THIS CHANGES ABOUT CONTRACT §5
-- --------------------------------------
-- `documento.py`'s header (`app/modules/card_hub/contrato_gerador/
-- documento.py`) used to say the rendered `.docx` "never reaches storage" —
-- it was an internal intermediate, converted to PDF and discarded. That
-- changed 2026-09-16 (roadmap `social-wiring-contract-automation-2026-09.md`,
-- question Q-artifact, "store both"): the office wants the editable `.docx`
-- downloadable too, not only the final PDF, so a lawyer can mark it up
-- without re-typing the instrument. Both formats are now real, retrievable
-- artifacts of the SAME generated version — not two versions, one row.
--
-- WHY A SIBLING PAIR OF COLUMNS ON THE SAME ROW, NOT A SECOND VERSION ROW
-- -------------------------------------------------------------------------
-- `numero` (migration 106) identifies ONE generation event, never reused —
-- "versão 3" has to keep meaning the same bytes forever. The PDF and the
-- `.docx` are the SAME rendering, two encodings of it, not two distinct
-- revisions; consuming a second `numero` per generation would double-count
-- versions in every listing and let "REV 3" mean two different files
-- depending which format you asked for. `storage_path`/`mime_type`/
-- `tamanho_bytes` (the row's existing, generic DocumentoStore-owned columns)
-- keep meaning "the PDF, the artifact every version has" unchanged;
-- `docx_storage_path`/`docx_tamanho_bytes` are the docx SIBLING, present
-- only on a 'gerado' row.
--
-- WHY NOT ON UPLOAD ROWS
-- -------------------------
-- An `origem='upload'` row is whatever file the office attached — could be a
-- PDF, could be a `.docx`, is exactly one file with no second rendering of
-- itself sitting anywhere. The CHECK below pins that: only 'gerado' rows may
-- carry the docx sibling, and a NEW 'gerado' row MUST — a generated version
-- missing its `.docx` would be exactly the silent gap this column exists to
-- rule out (same reasoning migration 112 gives `contexto_sha256`).
--
-- 🔴 `NOT VALID`, DELIBERATELY NEVER `VALIDATE CONSTRAINT`ed
-- ---------------------------------------------------------------
-- Unlike migration 112's `contexto_sha256` (every pre-existing row was an
-- upload, so its CHECK validated for free), a 'gerado' row generated by this
-- product BEFORE this migration genuinely has no `.docx` on file — contract
-- §5 said to discard it, so there are nothing to backfill from. `NOT VALID`
-- grandfathers every existing row in (Postgres skips the historical scan)
-- while still enforcing the CHECK on every INSERT/UPDATE from this point
-- forward — an old row is legible as "generated before this feature
-- shipped", never silently corrected into a lie.
--
-- SAME LGPD POSTURE AS THE PDF (KB `PATTERNS/security/lgpd.md` §10)
-- ---------------------------------------------------------------------
-- A contract names CPF/RG and bank data for every party regardless of which
-- of the two encodings you open — "it's the same rendering, only the
-- container differs" is not an LGPD argument for treating it any lighter.
-- The `.docx` lives under the SAME bucket, the SAME org-first storage-key
-- convention, and the SAME `atendimento_contrato_versao_acessos` access log
-- (`documento_id` = this row's own id) as the PDF — see
-- `contratos_service.nova_versao_gerada` / `.url_versao`. No new table, no
-- new retention clock: retention is per-CONTRATO (soft-delete cascades to
-- every artifact of every version), not per-file.
--
-- MIME TYPE NEEDS NO COLUMN
-- ----------------------------
-- The docx sibling is always
-- `application/vnd.openxmlformats-officedocument.wordprocessingml.document`
-- — `contratos_service.MIME_DOCX` — the same constant `_EXTENSAO_GERADA`
-- already names for a generated `.docx` filename fallback. A column that can
-- only ever hold one value would be redundant with the code constant it
-- would have to be kept in sync with.
--
-- FORWARD-ONLY, IDEMPOTENT.
-- 🔴 MIGRATION FILE ONLY — not applied to any database by this change. Apply
-- via `noctus.dev.migrate_product` only after the tech-lead has stated the
-- row counts this will touch and the user has given an explicit go-ahead.
-- See `migrations/APPLIED.md`.
-- ============================================================================

SET search_path = social_wiring, public;

ALTER TABLE social_wiring.atendimento_contrato_versoes
    ADD COLUMN IF NOT EXISTS docx_storage_path  TEXT,
    ADD COLUMN IF NOT EXISTS docx_tamanho_bytes BIGINT
        CHECK (docx_tamanho_bytes IS NULL OR docx_tamanho_bytes >= 0);

COMMENT ON COLUMN social_wiring.atendimento_contrato_versoes.docx_storage_path IS
    'The editable .docx sibling of a gerado version''s PDF — same bucket, '
    'same org-first key convention as storage_path, suffixed ''.docx''. NULL '
    'for an upload. See migration 120 header.';
COMMENT ON COLUMN social_wiring.atendimento_contrato_versoes.docx_tamanho_bytes IS
    'Byte size of docx_storage_path''s object. NULL for an upload. MIME type '
    'is not stored — always contratos_service.MIME_DOCX for a gerado row, '
    'see migration 120 header.';

ALTER TABLE social_wiring.atendimento_contrato_versoes
    DROP CONSTRAINT IF EXISTS atendimento_contrato_versoes_docx_por_origem;
ALTER TABLE social_wiring.atendimento_contrato_versoes
    ADD CONSTRAINT atendimento_contrato_versoes_docx_por_origem
    CHECK (
        (origem = 'gerado' AND docx_storage_path IS NOT NULL AND docx_tamanho_bytes IS NOT NULL)
        OR (origem = 'upload' AND docx_storage_path IS NULL AND docx_tamanho_bytes IS NULL)
    ) NOT VALID;
-- No `VALIDATE CONSTRAINT` follows — see the header's `NOT VALID` note.
-- A pre-existing 'gerado' row with no `.docx` on file is expected, not an
-- error to chase down.
