-- Migration: imovel_documentos_tipo_matricula
-- Generated by noctus.dev.scaffold_migration on 2026-10-04
-- Schema: social_wiring


-- ============================================================
-- Schema lock — pin name resolution to social_wiring, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = social_wiring, public;

-- ============================================================
-- P5 audit B1 (2026-10): the file uploaded as "the matrícula" was the
-- registry's "Visualização de Matrícula" printout on every audited deal —
-- an online VIEW with no certification. The emission-date read took the
-- first ACT's date (1984-2017) and every deal blocked on "certidão
-- vencida", when the real remedy is "upload the Certidão de Matrícula".
--
-- The seed now classifies the document deterministically
-- (`noctusai_lib.integrations.documents.ler_certidao_matricula`) and these
-- two columns carry the verdict to readiness:
--   tipo_documento_matricula — 'certidao' | 'visualizacao' | NULL (no
--                              marker either way; only for tipo matricula)
--   emissao_motivo           — why emitida_em is NULL (seed
--                              `MOTIVOS_EMISSAO`); NULL when it is set
-- Forward-safe: additive, nullable; existing rows read as NULL (unknown)
-- until re-extracted (POST /api/imoveis/{codigo}/documentos/{id}/extrair).
-- ============================================================
ALTER TABLE social_wiring.imovel_documentos
    ADD COLUMN IF NOT EXISTS tipo_documento_matricula TEXT,
    ADD COLUMN IF NOT EXISTS emissao_motivo           TEXT;

-- No CHECK constraint (deliberate): the only writer is
-- imovel_hub.documentos_service.extrair_estrutura, whose values come from
-- the seed's closed vocabularies (TIPOS_DOCUMENTO_MATRICULA /
-- MOTIVOS_EMISSAO). A DB guard would need its own behaviour probe in
-- noctus.dev.verify_db_guards (a fixture imovel_documentos row in prod) —
-- not worth it for two informational, machine-written columns.

COMMENT ON COLUMN social_wiring.imovel_documentos.tipo_documento_matricula IS
    'Kind of a tipo_documento=matricula upload, read deterministically by the '
    'seed: certidao (certifies - inteiro teor / com onus) or visualizacao (an '
    'online view/printout, NO value as a certidao). NULL = no marker either way.';
COMMENT ON COLUMN social_wiring.imovel_documentos.emissao_motivo IS
    'Why emitida_em is NULL for this document (seed MOTIVOS_EMISSAO), so '
    'readiness can say "envie a Certidao de Matricula (o arquivo e uma '
    'visualizacao)" instead of "vencida". NULL whenever emitida_em is set.';
