-- Migration: termos_posse_data_fixa
-- Generated by noctus.dev.scaffold_migration on 2026-10-05
-- Schema: social_wiring


-- ============================================================
-- Schema lock — pin name resolution to social_wiring, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = social_wiring, public;

-- ============================================================
-- Posse on a FIXED CALENDAR DATE (signed corpus deal 859: "na data de 30 de
-- novembro de 2026, com a condição de que todas as parcelas do preço tenham
-- sido ... quitadas"; 1 of ~35 signed contracts).
--
-- 114's `posse_marco` vocabulary counts a prazo FROM an event (assinatura |
-- parcela | protocolo_registro); a fixed date is not an event and has no
-- prazo. It gets its own marco, `data_fixa`, plus the date it names
-- (`posse_data`), PAIRED by a CHECK in the style of 114's parcela pairing:
-- the date is present exactly when the marco is 'data_fixa'. The legacy
-- `atendimento_negociacao.posse_data` (108, free string, other table, other
-- writer) is deliberately NOT reused: a CHECK cannot span two tables, so the
-- pairing could not be guaranteed.
--
-- Only the IMÓVEL's posse gets it; `permuta_posse_marco` keeps its 3 values.
-- Additive and idempotent: existing rows hold none of the new state.
-- ============================================================
ALTER TABLE social_wiring.atendimento_negociacao_termos
    ADD COLUMN IF NOT EXISTS posse_data DATE;

ALTER TABLE social_wiring.atendimento_negociacao_termos
    DROP CONSTRAINT IF EXISTS atendimento_negociacao_termos_posse_marco_check;
ALTER TABLE social_wiring.atendimento_negociacao_termos
    ADD CONSTRAINT atendimento_negociacao_termos_posse_marco_check
    CHECK (posse_marco IS NULL
           OR posse_marco IN ('assinatura', 'parcela', 'protocolo_registro', 'data_fixa'));

ALTER TABLE social_wiring.atendimento_negociacao_termos
    DROP CONSTRAINT IF EXISTS atendimento_negociacao_termos_posse_marco_data;
ALTER TABLE social_wiring.atendimento_negociacao_termos
    ADD CONSTRAINT atendimento_negociacao_termos_posse_marco_data
    CHECK ((posse_marco IS NOT DISTINCT FROM 'data_fixa')
           = (posse_data IS NOT NULL));

COMMENT ON COLUMN social_wiring.atendimento_negociacao_termos.posse_data IS
    'posse_marco = data_fixa: the calendar date the posse is delivered on '
    '(paired with the marco by CHECK). Migration 201.';
COMMENT ON COLUMN social_wiring.atendimento_negociacao_termos.posse_marco IS
    'assinatura | parcela | protocolo_registro | data_fixa — the event '
    'posse_prazo_dias counts from (prazo 0 = concomitant with it); data_fixa '
    'names posse_data instead and ignores the prazo. parcela requires '
    'posse_marco_parcela_id (CHECK). Migration 201 added data_fixa.';
