-- Migration: backfill_processos_valor_negociado
-- Generated by noctus.dev.scaffold_migration on 2026-10-10
-- Schema: social_wiring


-- ============================================================
-- Schema lock — pin name resolution to social_wiring, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = social_wiring, public;

-- Backfill: processos_venda.valor was written from atendimentos.valor_estimado
-- (usually 0) instead of the negotiated price. Align every processo with its
-- atendimento's atendimento_negociacao.valor_negociado. Idempotent: only rows
-- that differ are touched. New writes are kept in step by the application
-- (pipeline.aceite on accept, negociacao_service on later edits).
UPDATE social_wiring.processos_venda p
   SET valor = n.valor_negociado,
       updated_at = now()
  FROM social_wiring.atendimento_negociacao n
 WHERE n.atendimento_id = p.atendimento_id
   AND n.org_id = p.org_id
   AND n.valor_negociado IS NOT NULL
   AND n.valor_negociado > 0
   AND p.valor IS DISTINCT FROM n.valor_negociado;
