/**
 * Conteúdo editorial público da Academia da Reciclagem.
 *
 * Fonte: os documentos em `products/academia-de-reciclagem/projects/content/*.docx`
 * (00–06 = os tópicos do projeto, exibidos em /como-funciona; a Carta às Próximas
 * Gerações, exibida em /a-carta). Cada documento vira uma sequência de blocos na
 * mesma ordem do original: parágrafo ou destaque (parágrafo inteiro em negrito
 * no documento). O infográfico "30 toneladas" NÃO entra aqui: ele é uma peça da
 * landing (`pages/Landing.tsx`, seção `#trinta-toneladas`), não do corpo de
 * leitura — as páginas de texto são só texto, por decisão editorial.
 * Ao revisar um documento, atualize o bloco correspondente aqui.
 */

export type Bloco =
  | { tipo: 'paragrafo'; texto: string }
  | { tipo: 'destaque'; texto: string };

export interface Topico {
  /** Âncora estável (`/como-funciona#<id>`). */
  id: string;
  /** Posição do documento na série (00–06). */
  numero: string;
  titulo: string;
  blocos: Bloco[];
}

export interface Carta {
  titulo: string;
  blocos: Bloco[];
}

export const TOPICOS: Topico[] = [
  {
    id: 'plano-diretor',
    numero: '00',
    titulo: "Plano Diretor do Projeto",
    blocos: [
      { tipo: 'paragrafo', texto: "O Plano Diretor do Projeto Academia da Reciclagem deve funcionar como o documento de visão geral do movimento. Ele reúne o propósito, a estratégia, os caminhos de atuação, os públicos envolvidos e os elementos que poderão transformar uma intenção pessoal em um projeto estruturado, duradouro e capaz de gerar impacto regional." },
      { tipo: 'paragrafo', texto: "Este projeto nasce de um sonho de adolescência e de uma inquietação que permaneceu viva por décadas: deixar um planeta melhor do que encontrei. A imagem de uma reportagem de televisão mostrando que uma pessoa poderia gerar uma verdadeira montanha de contêineres de lixo ao longo da vida ficou gravada na memória e se tornou uma semente de consciência ambiental." },
      { tipo: 'paragrafo', texto: "A visita à Cooperativa de Reciclagem de Cotia, a Nova Cotia, trouxe essa lembrança para o presente. As montanhas de garrafas plásticas e materiais recicláveis mostraram o tamanho do problema, mas também mostraram a força da solução. Ali, o resíduo que poderia poluir o meio ambiente estava recebendo destinação correta. E, ao mesmo tempo, homens e mulheres encontravam na reciclagem uma forma digna de gerar renda e sustentar suas famílias." },
      { tipo: 'paragrafo', texto: "O Plano Diretor parte dessa conexão: o problema ambiental e a oportunidade social caminham juntos." },
      { tipo: 'destaque', texto: "O Projeto Academia da Reciclagem não deve ser tratado apenas como uma campanha de reciclagem. Ele deve ser estruturado como um movimento regional de educação ambiental, responsabilidade social, economia circular e valorização das cooperativas de reciclagem." },
      { tipo: 'paragrafo', texto: "A missão do projeto é transformar resíduos em oportunidade, promovendo preservação ambiental, educação da sociedade e geração de renda digna para famílias que vivem da reciclagem." },
      { tipo: 'paragrafo', texto: "A visão do projeto é tornar a região da Granja Viana e os municípios próximos uma referência em destinação correta de resíduos recicláveis, mobilizando condomínios, empresas, escolas, cooperativas e comunidades." },
      { tipo: 'paragrafo', texto: "O território inicial de atuação mencionado durante a construção do projeto inclui Cotia, Carapicuíba, Embu das Artes e Jandira. A região da Granja Viana aparece como ponto natural de partida, por concentrar condomínios residenciais, famílias, empresas, escolas, síndicos, administradoras e uma rede de relacionamentos que pode ser mobilizada para a causa." },
      { tipo: 'paragrafo', texto: "O projeto deve aproveitar essa rede de relacionamento pessoal, empresarial e institucional para incentivar a coleta de materiais recicláveis, principalmente nos condomínios residenciais. O objetivo é criar uma ponte entre quem gera o resíduo e quem pode dar a ele a destinação correta." },
      { tipo: 'paragrafo', texto: "A primeira grande frente do projeto deve ser o propósito e a comunicação da causa. Antes de pedir adesão, é preciso mostrar por que o projeto existe. As pessoas precisam entender que o lixo não desaparece quando sai de casa. Ele continua existindo, segue um caminho e pode virar problema ou oportunidade." },
      { tipo: 'paragrafo', texto: "A imagem das mais de 30 toneladas de resíduos geradas por uma pessoa ao longo da vida deve ser uma das peças simbólicas do movimento. Ela representa de forma visual aquilo que os números sozinhos não conseguem transmitir." },
      { tipo: 'paragrafo', texto: "A segunda frente deve ser a legislação. O projeto deve caminhar alinhado à Política Nacional de Resíduos Sólidos, à legislação municipal de Cotia e às legislações dos demais municípios envolvidos. Isso dará sustentação institucional ao movimento e ajudará a demonstrar que a destinação correta dos resíduos é uma responsabilidade compartilhada entre poder público, empresas, condomínios e cidadãos." },
      { tipo: 'paragrafo', texto: "Em Cotia, foi identificado que existe legislação específica sobre resíduos sólidos e Plano Municipal de Gestão Integrada de Resíduos Sólidos. Essa base deve ser organizada e ampliada futuramente para Carapicuíba, Embu das Artes e Jandira, permitindo que o projeto dialogue com cada município de forma correta." },
      { tipo: 'paragrafo', texto: "A terceira frente deve ser a relação com as cooperativas. As cooperativas são o coração social do projeto. Elas representam a transformação do resíduo em renda, trabalho e dignidade. A experiência na Cooperativa Nova Cotia mostrou que a reciclagem não é apenas ambiental. Ela é também humana." },
      { tipo: 'paragrafo', texto: "O projeto deve valorizar os cooperados e ajudar a melhorar a qualidade dos materiais que chegam às cooperativas. Quanto melhor a separação nos condomínios e empresas, mais eficiente será o trabalho de triagem, maior poderá ser o aproveitamento dos materiais e melhor poderá ser o resultado social." },
      { tipo: 'paragrafo', texto: "A quarta frente deve ser o Selo Verde. O selo deve ser tratado como um reconhecimento socioambiental privado, e não como uma certificação oficial governamental. Ele poderá reconhecer condomínios, empresas, escolas e instituições que adotarem providências efetivas e comprovadas em favor da destinação correta dos resíduos." },
      { tipo: 'paragrafo', texto: "O selo poderá ter níveis, como Bronze, Prata, Ouro e Diamante, permitindo que cada participante evolua gradualmente. O ponto central será a comprovação. Não basta dizer que recicla. Será preciso demonstrar estrutura, comunicação, rotina, destinação correta e resultados." },
      { tipo: 'paragrafo', texto: "O Selo Verde deve ser um instrumento de mobilização, reconhecimento e educação. Ele deve valorizar quem faz corretamente e estimular outros condomínios e empresas a aderirem ao movimento." },
      { tipo: 'paragrafo', texto: "A quinta frente deve ser a produção de materiais de divulgação. O projeto precisará de imagens, vídeos, apresentações, posts, comunicados para moradores, materiais para síndicos, conteúdos para empresas e peças educativas para escolas. A comunicação deve ser clara, humana e impactante." },
      { tipo: 'paragrafo', texto: "A linguagem deve mostrar que cada embalagem corretamente separada pode representar menos poluição, menos desperdício, mais eficiência para as cooperativas e mais dignidade para famílias que dependem da reciclagem." },
      { tipo: 'paragrafo', texto: "A sexta frente deve ser a organização dos condomínios participantes. Os condomínios residenciais são um dos principais públicos do projeto. Eles concentram grande volume de resíduos domésticos e possuem estrutura interna de comunicação, administração e convivência comunitária." },
      { tipo: 'paragrafo', texto: "O projeto deve criar uma forma simples de cadastrar condomínios, registrar o estágio de adesão, acompanhar as ações implantadas, identificar síndicos e administradoras envolvidas e medir os resultados de cada participante." },
      { tipo: 'paragrafo', texto: "A sétima frente deve ser a criação dos indicadores de impacto. O projeto precisa medir o que gera. Entre os indicadores possíveis estão toneladas recicladas, resíduos desviados de aterros, número de famílias beneficiadas, receita gerada para cooperativas, número de condomínios participantes, empresas engajadas, escolas envolvidas e ações educativas realizadas." },
      { tipo: 'paragrafo', texto: "Esses indicadores serão fundamentais para demonstrar seriedade, prestar contas, fortalecer a comunicação e alimentar relatórios anuais de impacto social e ambiental." },
      { tipo: 'paragrafo', texto: "A oitava frente deve ser imprensa e redes sociais. O projeto tem uma história forte e verdadeira. Essa história deve ser contada. A imprensa local, os canais regionais, os perfis de redes sociais, os vídeos curtos, os eventos e os materiais institucionais podem ajudar a ampliar o alcance da causa." },
      { tipo: 'paragrafo', texto: "A comunicação pública deve sempre preservar a autenticidade do projeto. Ele nasceu de um sonho antigo, de uma memória de adolescência, de uma visita à cooperativa e de uma decisão de agir. Essa origem deve estar presente na narrativa." },
      { tipo: 'paragrafo', texto: "A nona frente deve ser a Carta às Próximas Gerações. Essa carta deve funcionar como documento emocional do projeto. Ela contará por que o movimento existe, de onde nasceu a inquietação, qual foi o impacto da imagem dos contêineres, o que foi visto na Cooperativa Nova Cotia e por que chegou a hora de agir." },
      { tipo: 'paragrafo', texto: "A décima frente deve ser o Manifesto Fundador. O manifesto deve ser uma declaração pública do movimento, afirmando que o Projeto Academia da Reciclagem nasce para transformar resíduos em dignidade, educação ambiental e preservação do planeta." },
      { tipo: 'destaque', texto: "O Plano Diretor deve também orientar as etapas de implantação." },
      { tipo: 'paragrafo', texto: "A primeira etapa pode ser de organização interna, reunindo os documentos, definindo nome, identidade, propósito, narrativa, materiais básicos e possíveis parceiros." },
      { tipo: 'paragrafo', texto: "A segunda etapa pode ser de aproximação com cooperativas, especialmente a Nova Cotia, para entender capacidade operacional, necessidades, rotas, tipos de materiais aceitos, dificuldades e oportunidades." },
      { tipo: 'paragrafo', texto: "A terceira etapa pode ser de escolha dos primeiros condomínios piloto. Esses condomínios devem ser escolhidos com cuidado, preferencialmente entre aqueles onde já exista relacionamento, abertura com síndicos ou administradoras e condições práticas de implantação." },
      { tipo: 'paragrafo', texto: "A quarta etapa pode ser de educação dos moradores. Antes de cobrar resultado, será necessário orientar. Os moradores precisam saber o que separar, como separar, onde depositar e por que isso importa." },
      { tipo: 'paragrafo', texto: "A quinta etapa pode ser de medição dos primeiros resultados. Mesmo que os números sejam simples no início, eles ajudarão a mostrar evolução e criar confiança." },
      { tipo: 'paragrafo', texto: "A sexta etapa pode ser de criação formal do Selo Verde, com critérios, níveis, regulamento, comprovação e comunicação." },
      { tipo: 'paragrafo', texto: "A sétima etapa pode ser de ampliação para novos condomínios, empresas, escolas e parceiros." },
      { tipo: 'paragrafo', texto: "A oitava etapa pode ser de realização de um evento anual do projeto, reunindo participantes, cooperativas, parceiros, imprensa e comunidade para apresentar resultados, reconhecer participantes e fortalecer o movimento." },
      { tipo: 'paragrafo', texto: "O projeto deve sempre preservar uma ideia central: não se trata apenas de lixo. Trata-se de destino." },
      { tipo: 'paragrafo', texto: "O resíduo pode seguir para o abandono, para a poluição e para o desperdício. Ou pode seguir para a reciclagem, para a renda, para a dignidade e para a preservação ambiental." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem nasce para influenciar essa escolha." },
      { tipo: 'paragrafo', texto: "A One Consultoria Imobiliária pode ocupar papel de fundadora, apoiadora e patrocinadora, utilizando sua presença regional, seus relacionamentos e sua capacidade de comunicação para abrir portas e mobilizar pessoas." },
      { tipo: 'paragrafo', texto: "Ao mesmo tempo, o projeto deve ter identidade própria, para que possa crescer além da empresa, atrair parceiros, conquistar legitimidade pública e se transformar em um movimento regional." },
      { tipo: 'paragrafo', texto: "O Plano Diretor também deve reconhecer que este é um projeto de longo prazo. Ele não precisa nascer perfeito. Precisa nascer verdadeiro, organizado e comprometido com a melhoria contínua." },
      { tipo: 'paragrafo', texto: "A cada condomínio participante, o projeto poderá aprender. A cada cooperativa parceira, poderá ajustar processos. A cada campanha, poderá melhorar a comunicação. A cada relatório, poderá aperfeiçoar seus indicadores. A cada evento, poderá ampliar sua rede de apoio." },
      { tipo: 'paragrafo', texto: "O mais importante é que o projeto não perca sua essência." },
      { tipo: 'paragrafo', texto: "A essência é simples: deixar um planeta melhor do que encontrei." },
      { tipo: 'paragrafo', texto: "Essa frase deve orientar decisões, discursos, parcerias, materiais, selos, indicadores e ações." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem deve ser um movimento de legado. Um movimento capaz de unir consciência ambiental, responsabilidade social, educação, cooperação e dignidade humana." },
      { tipo: 'paragrafo', texto: "O Plano Diretor não encerra o projeto. Ele apenas organiza o caminho." },
      { tipo: 'paragrafo', texto: "O caminho começa com uma imagem que marcou um adolescente." },
      { tipo: 'paragrafo', texto: "Passa por uma cooperativa que mostrou a força da solução." },
      { tipo: 'paragrafo', texto: "E segue na direção de uma região mais consciente, mais responsável e mais comprometida com as próximas gerações." },
    ],
  },
  {
    id: 'proposito-e-manifesto',
    numero: '01',
    titulo: "Propósito e Manifesto",
    blocos: [
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem nasce de um propósito pessoal profundo: contribuir para deixar o planeta melhor do que o encontrei." },
      { tipo: 'paragrafo', texto: "Este projeto não começou como uma estratégia de marketing, nem como uma simples ação institucional. Ele tem origem em uma lembrança de adolescência que permaneceu viva por décadas. Em determinado momento da minha juventude, assisti a uma reportagem de televisão que mostrava que uma pessoa de classe média gerava, ao longo de um ano, uma quantidade enorme de lixo. A reportagem traduzia esse volume em contêineres e mostrava visualmente que, ao longo da vida, cada pessoa poderia gerar uma verdadeira montanha de resíduos." },
      { tipo: 'paragrafo', texto: "A imagem de mais de 70 contêineres empilhados nunca mais saiu da minha cabeça." },
      { tipo: 'paragrafo', texto: "Naquele momento, ainda adolescente, compreendi de forma visual e impactante que o lixo produzido por uma única pessoa não desaparece. Ele se acumula. Ele ocupa espaço. Ele gera consequências. Aquela cena plantou em mim uma inquietação que atravessou muitos anos: que tipo de planeta estamos deixando para as próximas gerações?" },
      { tipo: 'paragrafo', texto: "Hoje, aos 57 anos, essa lembrança voltou com força. A imagem dos contêineres da minha adolescência se conectou com uma experiência concreta da vida adulta: a visita à Cooperativa de Reciclagem de Cotia, a Nova Cotia." },
      { tipo: 'paragrafo', texto: "Durante essa visita, fui profundamente impactado por duas imagens." },
      { tipo: 'paragrafo', texto: "A primeira foi a das montanhas de garrafas plásticas e materiais recicláveis. Ao olhar para aquele volume enorme de resíduos, percebi que estava diante de materiais que poderiam ter sido descartados incorretamente, poderiam estar poluindo rios, terrenos, ruas e áreas verdes, mas que, felizmente, estavam recebendo uma destinação correta." },
      { tipo: 'paragrafo', texto: "A segunda imagem foi ainda mais humana: as pessoas que trabalham na cooperativa. Homens e mulheres que, por meio da reciclagem, conseguem gerar renda, sustento e dignidade para suas famílias. Ali compreendi que a reciclagem não é apenas uma pauta ambiental. Ela também é uma pauta social." },
      { tipo: 'paragrafo', texto: "O resíduo, quando descartado de maneira incorreta, torna-se problema. Mas quando separado, coletado, destinado e tratado corretamente, se transforma em matéria-prima, oportunidade, renda e dignidade." },
      { tipo: 'paragrafo', texto: "Essa percepção deu forma ao propósito central do projeto: transformar resíduos em oportunidade, promovendo preservação ambiental, educação da sociedade e geração de renda digna para famílias que vivem da reciclagem." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem pretende nascer como um movimento regional de conscientização e ação prática. A intenção é utilizar relacionamentos pessoais, empresariais e institucionais para incentivar a coleta seletiva e a destinação correta de materiais recicláveis, especialmente em condomínios residenciais e empresas localizadas nos municípios de Cotia, Carapicuíba, Embu das Artes, Vargem Grande e Jandira." },
      { tipo: 'paragrafo', texto: "A região da Granja Viana concentra muitos condomínios residenciais, famílias, empresas, escolas e instituições que produzem diariamente grande volume de resíduos. Parte significativa desse material pode ser reciclada, desde que exista orientação, engajamento e uma ponte eficiente entre quem gera o resíduo e quem pode dar a ele a destinação correta." },
      { tipo: 'paragrafo', texto: "O projeto parte da convicção de que muitas pessoas até desejam agir corretamente, mas não sabem exatamente como separar, armazenar e encaminhar seus resíduos. Por isso, o movimento deve atuar também como instrumento de educação ambiental, mostrando aos moradores, síndicos, administradoras e empresas que cada embalagem separada corretamente pode gerar um impacto positivo real." },
      { tipo: 'paragrafo', texto: "A mensagem central é simples, mas poderosa: cada pessoa produzirá uma grande quantidade de resíduos ao longo da vida. A pergunta não é se vamos gerar resíduos. A pergunta é qual destino daremos a eles." },
      { tipo: 'paragrafo', texto: "Quando uma garrafa plástica é descartada incorretamente, ela pode permanecer por muitos anos no meio ambiente, contribuindo para a poluição e para a degradação dos espaços urbanos e naturais. Mas quando essa mesma garrafa chega a uma cooperativa de reciclagem, ela pode ser transformada em matéria-prima, gerar renda e fortalecer uma cadeia de trabalho que beneficia famílias inteiras." },
      { tipo: 'paragrafo', texto: "Por isso, o projeto não deve falar apenas de lixo. Deve falar de responsabilidade, consciência, educação, oportunidade, dignidade e legado." },
      { tipo: 'paragrafo', texto: "A proposta é construir uma ponte entre os condomínios e empresas da região e as cooperativas de reciclagem, especialmente aquelas que já atuam de forma organizada e socialmente relevante, como a Cooperativa Nova Cotia. Essa ponte pode ajudar a aumentar o volume de materiais recicláveis destinados corretamente, melhorar a qualidade da separação dos resíduos e ampliar o impacto social da reciclagem." },
      { tipo: 'paragrafo', texto: "O projeto também se conecta ao desejo de criar futuramente um Selo Verde ou uma certificação privada de reconhecimento socioambiental para condomínios, empresas e instituições que se engajem de forma efetiva e comprovada na destinação correta de seus resíduos. Esse selo não deve ser tratado como uma certificação governamental, mas como um reconhecimento sério, transparente e baseado em critérios verificáveis." },
      { tipo: 'paragrafo', texto: "A força desse movimento, no entanto, não estará apenas no selo, nos documentos ou nas campanhas. Estará principalmente na autenticidade de sua origem." },
      { tipo: 'paragrafo', texto: "Este projeto nasce de uma imagem que marcou um adolescente e de uma decisão tomada na vida adulta: não permanecer apenas impactado, mas agir." },
      { tipo: 'paragrafo', texto: "A visita à cooperativa funcionou como um despertar. A montanha de contêineres vista na televisão décadas atrás encontrou, na montanha de garrafas plásticas da cooperativa, uma resposta possível. A diferença é que, agora, aquela montanha não representa apenas o problema. Ela representa também a solução." },
      { tipo: 'paragrafo', texto: "Cada quilo de material reciclado significa menos resíduos no meio ambiente. Cada material separado corretamente significa mais eficiência para a cooperativa. Cada condomínio engajado significa maior escala para o impacto ambiental. Cada família beneficiada pela reciclagem significa mais dignidade." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem é, portanto, mais do que uma campanha de reciclagem. É um projeto de legado." },
      { tipo: 'paragrafo', texto: "Seu propósito é mobilizar pessoas, condomínios, empresas, cooperativas, escolas e instituições públicas ou privadas em torno de uma causa comum: reduzir o descarte inadequado de resíduos, aumentar a reciclagem, fortalecer a economia circular e gerar impacto social positivo para famílias que dependem desse trabalho." },
      { tipo: 'paragrafo', texto: "A frase que sintetiza esse propósito é:" },
      { tipo: 'paragrafo', texto: "“Quero deixar um planeta melhor do que encontrei.”" },
      { tipo: 'paragrafo', texto: "Essa frase deve orientar todas as etapas do projeto. Ela representa a origem emocional, ética e humana do movimento." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem nasce para transformar uma preocupação antiga em ação concreta. Nasce para mostrar que o resíduo não precisa ser apenas um problema acumulado ao longo da vida, mas pode ser convertido em oportunidade. Nasce para conectar quem descarta com quem transforma. Nasce para dar visibilidade aos trabalhadores da reciclagem. Nasce para educar comunidades. Nasce para inspirar condomínios e empresas a assumirem responsabilidade efetiva sobre aquilo que produzem e descartam." },
      { tipo: 'paragrafo', texto: "Ao longo dos próximos anos, o objetivo é que esse movimento possa gerar resultados mensuráveis: toneladas de materiais reciclados, redução de resíduos enviados a aterros, aumento da renda das cooperativas, número de famílias beneficiadas, condomínios participantes, empresas engajadas e campanhas educativas realizadas." },
      { tipo: 'paragrafo', texto: "Mas, acima de todos os indicadores, o maior resultado será cultural." },
      { tipo: 'paragrafo', texto: "O projeto pretende ajudar as pessoas a enxergarem que o lixo não termina quando sai de casa. Ele continua existindo. Ele segue um caminho. E esse caminho pode ser de abandono e poluição, ou de reciclagem, renda e dignidade." },
      { tipo: 'paragrafo', texto: "A escolha desse caminho depende de consciência, organização e compromisso." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem nasce para ajudar a construir essa consciência e transformar esse compromisso em ação." },
    ],
  },
  {
    id: 'legislacao',
    numero: '02',
    titulo: "Legislação",
    blocos: [
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem deve caminhar alinhado à legislação existente sobre resíduos sólidos, especialmente porque a destinação correta dos materiais recicláveis não é apenas uma boa prática ambiental, mas também uma obrigação prevista em políticas públicas nacionais e municipais." },
      { tipo: 'paragrafo', texto: "Durante a pesquisa inicial, foi identificado que o Município de Cotia possui legislação específica sobre resíduos sólidos. A principal norma mencionada foi a Lei Municipal nº 1.833/2014, que dispõe sobre a Política Municipal de Resíduos Sólidos de Cotia." },
      { tipo: 'paragrafo', texto: "Essa legislação municipal se conecta diretamente com a Política Nacional de Resíduos Sólidos, instituída pela Lei Federal nº 12.305/2010, que estabelece diretrizes para a gestão adequada dos resíduos no Brasil." },
      { tipo: 'paragrafo', texto: "A existência dessa legislação é importante para o projeto porque demonstra que a preocupação com a coleta seletiva, a reciclagem, a destinação ambientalmente adequada dos resíduos, a educação ambiental e a participação de cooperativas de catadores não são apenas iniciativas voluntárias. Elas fazem parte de uma política pública estruturada." },
      { tipo: 'paragrafo', texto: "No caso de Cotia, foi identificado que o município possui uma Política Municipal de Resíduos Sólidos e também um Plano Municipal de Gestão Integrada de Resíduos Sólidos. Esses instrumentos ajudam a orientar as ações do município em relação à coleta, tratamento, reciclagem e destinação final dos resíduos." },
      { tipo: 'paragrafo', texto: "Isso significa que o Projeto Academia da Reciclagem pode nascer como uma iniciativa da sociedade civil e da iniciativa privada, mas alinhada com aquilo que a legislação já prevê como caminho adequado." },
      { tipo: 'paragrafo', texto: "A legislação reforça a importância da coleta seletiva, da reciclagem, do reaproveitamento de materiais, da responsabilidade compartilhada entre poder público, empresas e cidadãos, da educação ambiental e da inclusão de cooperativas de catadores." },
      { tipo: 'paragrafo', texto: "Esse ponto é fundamental para o projeto, porque a proposta não é apenas incentivar condomínios e empresas a separarem materiais recicláveis. A proposta é contribuir para que aquilo que já está previsto nas políticas públicas seja colocado em prática de forma mais eficiente, organizada e humana." },
      { tipo: 'paragrafo', texto: "O projeto pode se posicionar como um apoio à execução dos objetivos da Política Municipal de Resíduos Sólidos, especialmente em três pilares: educação ambiental da população, aumento da reciclagem e da coleta seletiva, e geração de renda e dignidade para cooperados e famílias de baixa renda que vivem da reciclagem." },
      { tipo: 'paragrafo', texto: "Essa visão fortalece muito a legitimidade do movimento." },
      { tipo: 'paragrafo', texto: "Quando um condomínio residencial, uma empresa ou uma escola adere à coleta seletiva e passa a destinar corretamente seus resíduos, essa instituição não está apenas praticando uma ação ambiental isolada. Ela está contribuindo para uma política pública maior, que envolve responsabilidade ambiental, responsabilidade social e cidadania." },
      { tipo: 'paragrafo', texto: "O projeto deve deixar claro que a destinação correta dos resíduos é uma responsabilidade compartilhada." },
      { tipo: 'paragrafo', texto: "O poder público tem obrigações relacionadas à gestão dos resíduos sólidos, à coleta, à estruturação de programas, à educação ambiental, ao apoio a cooperativas e à destinação adequada dos materiais." },
      { tipo: 'paragrafo', texto: "As empresas também possuem responsabilidade, especialmente quando geram resíduos, comercializam produtos, consomem recursos e desejam comunicar compromisso ambiental e social." },
      { tipo: 'paragrafo', texto: "Os condomínios residenciais, por sua vez, são grandes geradores de resíduos domésticos. Eles podem exercer papel relevante na separação adequada dos materiais, na orientação dos moradores e na criação de uma rotina interna que facilite a coleta seletiva." },
      { tipo: 'paragrafo', texto: "Os cidadãos também fazem parte dessa cadeia. Cada morador, ao separar corretamente uma embalagem, uma garrafa plástica, um papel, um metal ou um vidro, contribui para que o material reciclável chegue em melhores condições às cooperativas." },
      { tipo: 'paragrafo', texto: "A legislação, portanto, ajuda a sustentar uma mensagem importante do projeto: reciclar não deve ser tratado como favor, moda ou ação eventual. Deve ser compreendido como parte de uma responsabilidade coletiva." },
      { tipo: 'paragrafo', texto: "Outro ponto relevante é a inclusão das cooperativas de catadores." },
      { tipo: 'paragrafo', texto: "A Política Nacional de Resíduos Sólidos e as políticas municipais relacionadas ao tema reconhecem a importância da participação de cooperativas e associações de catadores na cadeia da reciclagem. Isso se conecta diretamente com a experiência vivida na visita à Cooperativa de Reciclagem de Cotia, a Nova Cotia." },
      { tipo: 'paragrafo', texto: "A legislação permite que o projeto tenha uma base mais sólida para dialogar com síndicos, administradoras, empresas e até com o poder público. Em vez de apresentar a ideia apenas como uma campanha de boa vontade, o projeto pode ser apresentado como uma iniciativa alinhada às diretrizes legais e às políticas públicas existentes." },
      { tipo: 'paragrafo', texto: "Isso também será importante para a criação futura de um Selo Verde ou de uma certificação privada de reconhecimento socioambiental." },
      { tipo: 'paragrafo', texto: "O selo não deve ser apresentado como uma certificação oficial governamental. Deve ser apresentado como um reconhecimento privado, criado pelo projeto, para condomínios, empresas e instituições que adotem providências efetivas e comprovadas em favor da destinação correta dos resíduos." },
      { tipo: 'paragrafo', texto: "Para que esse selo tenha credibilidade, ele deve ser baseado em critérios objetivos, comprovação documental e transparência. A legislação pode servir como uma referência para esses critérios, especialmente no que se refere à coleta seletiva, à destinação ambientalmente adequada, à educação ambiental e ao apoio à cadeia da reciclagem." },
      { tipo: 'paragrafo', texto: "No futuro, cada município envolvido no projeto deverá ter sua legislação pesquisada e organizada de forma específica." },
      { tipo: 'paragrafo', texto: "Os municípios inicialmente mencionados como área de interesse são Cotia, Carapicuíba, Embu das Artes, Vargem Grande e Jandira. Como o projeto pretende atuar regionalmente, será importante levantar as leis, decretos, planos municipais e programas existentes em cada um desses municípios." },
      { tipo: 'paragrafo', texto: "Essa etapa será fundamental para que o projeto possa dialogar corretamente com cada prefeitura, com as secretarias de meio ambiente, com cooperativas locais e com instituições interessadas em aderir ao movimento." },
      { tipo: 'paragrafo', texto: "Até este momento, a legislação mais explorada na conversa foi a de Cotia, especialmente por causa da visita à Cooperativa Nova Cotia e da intenção inicial de estruturar o projeto a partir da região da Granja Viana." },
      { tipo: 'paragrafo', texto: "O caminho natural será ampliar a pesquisa para os demais municípios, sempre com o cuidado de verificar as normas vigentes, os programas municipais existentes, a presença de cooperativas e as oportunidades de parceria." },
      { tipo: 'paragrafo', texto: "A legislação deve ser tratada como uma das bases do Projeto Academia da Reciclagem." },
      { tipo: 'paragrafo', texto: "Ela não substitui o propósito humano do projeto, mas dá sustentação institucional à iniciativa." },
      { tipo: 'paragrafo', texto: "O propósito nasce de uma inquietação pessoal: deixar um planeta melhor do que encontrei." },
      { tipo: 'paragrafo', texto: "A legislação mostra que essa inquietação também encontra respaldo em políticas públicas e obrigações coletivas." },
      { tipo: 'paragrafo', texto: "Portanto, o Projeto Academia da Reciclagem deve se apresentar como uma ponte entre o propósito pessoal, a responsabilidade social, a consciência ambiental e a legislação existente." },
      { tipo: 'paragrafo', texto: "Essa combinação fortalece a legitimidade do movimento e ajuda a demonstrar que a destinação correta dos resíduos não é apenas uma escolha individual. É uma necessidade ambiental, uma responsabilidade social e um compromisso legal." },
    ],
  },
  {
    id: 'cooperativas',
    numero: '03',
    titulo: "Cooperativas",
    blocos: [
      { tipo: 'paragrafo', texto: "As cooperativas de reciclagem ocupam um papel central no Projeto Academia da Reciclagem." },
      { tipo: 'paragrafo', texto: "Desde o início da construção deste projeto, ficou claro que a reciclagem não deve ser tratada apenas como uma pauta ambiental. Ela também precisa ser compreendida como uma pauta social e humana." },
      { tipo: 'paragrafo', texto: "A visita à Cooperativa de Reciclagem de Cotia, a Nova Cotia, foi um dos momentos mais importantes para dar forma concreta ao propósito do projeto. Durante essa visita, duas imagens causaram profundo impacto." },
      { tipo: 'paragrafo', texto: "A primeira foi a das montanhas de garrafas plásticas e materiais recicláveis. Aquelas montanhas mostravam, de forma visual e direta, o volume de materiais que poderiam estar recebendo destinação incorreta, mas que estavam sendo encaminhados para o processo adequado de reciclagem." },
      { tipo: 'paragrafo', texto: "A segunda imagem foi a das pessoas que trabalham na cooperativa. Homens e mulheres que, por meio da reciclagem, conseguem gerar renda, sustento e dignidade para suas famílias." },
      { tipo: 'paragrafo', texto: "Essa experiência revelou algo essencial: a cooperativa não é apenas um local onde materiais são separados. Ela é um espaço onde resíduos são transformados em oportunidade." },
      { tipo: 'paragrafo', texto: "Quando um material reciclável chega corretamente à cooperativa, ele deixa de ser apenas descarte. Ele passa a fazer parte de uma cadeia de valor que envolve trabalho, renda, inclusão social, preservação ambiental e economia circular." },
      { tipo: 'paragrafo', texto: "Por isso, o Projeto Academia da Reciclagem deve enxergar as cooperativas como parceiras fundamentais." },
      { tipo: 'paragrafo', texto: "O objetivo do projeto não é substituir o trabalho das cooperativas, nem se apropriar dele. Pelo contrário. O objetivo é fortalecer a atuação dessas organizações, ampliando o volume e a qualidade dos materiais recicláveis que chegam até elas." },
      { tipo: 'paragrafo', texto: "Uma das grandes dificuldades da reciclagem é que muitos materiais chegam misturados, contaminados ou separados de forma incorreta. Isso dificulta o trabalho dos cooperados, reduz o valor econômico dos materiais e compromete a eficiência do processo." },
      { tipo: 'paragrafo', texto: "Por essa razão, o projeto deve atuar fortemente na educação dos condomínios, empresas e moradores, para que os materiais sejam separados de maneira adequada antes de chegarem à cooperativa." },
      { tipo: 'paragrafo', texto: "Cada embalagem corretamente separada representa menos esforço desperdiçado, mais eficiência no processo e maior possibilidade de geração de renda." },
      { tipo: 'paragrafo', texto: "A conexão entre os condomínios residenciais e as cooperativas pode ser um dos pilares mais importantes do movimento." },
      { tipo: 'paragrafo', texto: "Os condomínios da região da Granja Viana, Cotia, Carapicuíba, Embu das Artes e Jandira geram diariamente grande quantidade de resíduos. Parte significativa desses materiais pode ser reciclada, desde que exista orientação, organização e destinação correta." },
      { tipo: 'paragrafo', texto: "As cooperativas, por outro lado, precisam de materiais em boas condições, com volume constante e melhor separação na origem." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem pode funcionar como uma ponte entre esses dois mundos: quem gera o resíduo e quem transforma esse resíduo em trabalho e renda." },
      { tipo: 'paragrafo', texto: "Essa ponte tem valor ambiental, porque ajuda a reduzir o descarte incorreto e o envio desnecessário de materiais recicláveis para aterros." },
      { tipo: 'paragrafo', texto: "Mas também tem valor social, porque fortalece famílias que dependem da reciclagem para viver com dignidade." },
      { tipo: 'paragrafo', texto: "Durante a conversa, ficou muito claro que um dos diferenciais do projeto será justamente conectar a reciclagem à dignidade humana." },
      { tipo: 'paragrafo', texto: "Muitos projetos falam apenas sobre meio ambiente. O Projeto Academia da Reciclagem deve falar sobre meio ambiente e sobre pessoas." },
      { tipo: 'paragrafo', texto: "A mensagem central pode ser expressa da seguinte forma: cada quilo reciclado representa menos resíduos no meio ambiente e mais renda para famílias que vivem da reciclagem." },
      { tipo: 'paragrafo', texto: "Essa frase sintetiza a conexão entre a montanha de garrafas plásticas vista na cooperativa e os trabalhadores que atuam diariamente para transformar esses materiais em sustento." },
      { tipo: 'paragrafo', texto: "O projeto deve valorizar a imagem dos cooperados, respeitando suas histórias, sua rotina e sua importância para a cidade." },
      { tipo: 'paragrafo', texto: "É importante que as pessoas dos condomínios compreendam que o material separado dentro de casa não desaparece depois que sai pela portaria. Ele segue um caminho. E, quando esse caminho é bem organizado, pode chegar até uma cooperativa e contribuir para a vida de outras pessoas." },
      { tipo: 'paragrafo', texto: "Essa consciência pode mudar a forma como moradores, síndicos e empresas enxergam seus resíduos." },
      { tipo: 'paragrafo', texto: "Uma garrafa plástica separada corretamente pode parecer um gesto pequeno dentro de uma residência. Mas, quando esse gesto é multiplicado por dezenas de apartamentos, centenas de casas e milhares de pessoas, ele passa a ter impacto real." },
      { tipo: 'paragrafo', texto: "Esse impacto real aparece nas montanhas de materiais recicláveis corretamente destinados e também na renda gerada para quem trabalha na cadeia da reciclagem." },
      { tipo: 'paragrafo', texto: "A Cooperativa Nova Cotia foi mencionada como referência inicial e como inspiração concreta para o projeto." },
      { tipo: 'paragrafo', texto: "A visita a essa cooperativa mostrou que já existem pessoas trabalhando diariamente para resolver parte do problema. O que falta, muitas vezes, é ampliar a conexão entre a sociedade e esse trabalho." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem pode ajudar a dar visibilidade às cooperativas, aproximar moradores e empresas desse universo e mostrar que a reciclagem é feita por pessoas reais, com famílias reais e necessidades reais." },
      { tipo: 'paragrafo', texto: "Esse ponto deve ser tratado com muito cuidado e respeito." },
      { tipo: 'paragrafo', texto: "A cooperativa não deve ser apresentada apenas como beneficiária de uma campanha. Ela deve ser apresentada como parceira, protagonista e parte essencial da solução." },
      { tipo: 'paragrafo', texto: "A atuação das cooperativas também se conecta à legislação sobre resíduos sólidos, especialmente porque as políticas públicas reconhecem a importância de cooperativas e associações de catadores na cadeia da reciclagem." },
      { tipo: 'paragrafo', texto: "Isso reforça a legitimidade do projeto e mostra que apoiar cooperativas não é apenas uma ação de solidariedade. É também uma forma de fortalecer uma estrutura prevista e estimulada pelas políticas de gestão de resíduos." },
      { tipo: 'paragrafo', texto: "No futuro, será importante mapear outras cooperativas da região, além da Nova Cotia, especialmente nos municípios de Carapicuíba, Embu das Artes e Jandira." },
      { tipo: 'paragrafo', texto: "Esse mapeamento poderá identificar quais cooperativas atuam em cada território, quais materiais recebem, qual sua capacidade operacional, quais dificuldades enfrentam e quais oportunidades de parceria podem ser desenvolvidas." },
      { tipo: 'paragrafo', texto: "O projeto também poderá criar indicadores relacionados às cooperativas, como volume de materiais destinados, aumento de renda gerada, número de famílias beneficiadas e melhoria na qualidade dos materiais recebidos." },
      { tipo: 'paragrafo', texto: "Esses indicadores serão importantes para mostrar, de forma concreta, que o movimento gera impacto ambiental e social." },
      { tipo: 'paragrafo', texto: "Ao mesmo tempo, o projeto deve evitar tratar as cooperativas apenas como fonte de dados ou números. O aspecto humano deve permanecer no centro da narrativa." },
      { tipo: 'paragrafo', texto: "O que marcou a visita à Nova Cotia não foram apenas as toneladas de materiais recicláveis. Foram também os trabalhadores que, por meio da reciclagem, conseguem levar vida digna para suas famílias." },
      { tipo: 'paragrafo', texto: "Essa é uma das imagens fundadoras do Projeto Academia da Reciclagem." },
      { tipo: 'paragrafo', texto: "A montanha de plástico representa o problema que recebeu o destino correto." },
      { tipo: 'paragrafo', texto: "As pessoas da cooperativa representam a solução humana e social para esse problema." },
      { tipo: 'paragrafo', texto: "Essa combinação deve orientar toda a relação do projeto com as cooperativas." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem, nasce para incentivar condomínios e empresas a destinarem corretamente seus materiais recicláveis, mas também nasce para reconhecer, valorizar e fortalecer quem está na ponta dessa cadeia." },
      { tipo: 'paragrafo', texto: "Sem as cooperativas, o projeto perderia parte essencial de seu sentido." },
      { tipo: 'paragrafo', texto: "Elas são o elo entre a consciência ambiental e a transformação concreta do resíduo em renda, dignidade e oportunidade." },
      { tipo: 'paragrafo', texto: "Por isso, qualquer plano de ação, campanha educativa, selo verde ou parceria institucional deverá considerar as cooperativas como protagonistas do processo." },
      { tipo: 'paragrafo', texto: "O movimento deve caminhar com elas, ouvi-las, respeitar suas necessidades e construir soluções que realmente facilitem o trabalho de quem vive da reciclagem." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem será mais forte quanto mais conseguir aproximar a sociedade das cooperativas e fazer com que cada pessoa compreenda que a reciclagem não termina na lixeira colorida." },
      { tipo: 'paragrafo', texto: "Ela continua nas mãos de trabalhadores que transformam descarte em futuro." },
    ],
  },
  {
    id: 'selo-verde',
    numero: '04',
    titulo: "Selo Verde",
    blocos: [
      { tipo: 'paragrafo', texto: "Dentro do Projeto Academia da Reciclagem, surgiu a possibilidade de criar uma certificação ou um Selo Verde para condomínios, empresas, escolas e instituições que se engajem de forma efetiva e comprovada no propósito da destinação correta dos resíduos." },
      { tipo: 'paragrafo', texto: "A ideia é muito forte, mas deve ser tratada com responsabilidade." },
      { tipo: 'paragrafo', texto: "O selo não deve ser apresentado como uma certificação oficial governamental. O caminho mais adequado é tratá-lo como um Selo de Reconhecimento Socioambiental privado, baseado em critérios técnicos, auditáveis e transparentes." },
      { tipo: 'paragrafo', texto: "Essa distinção é importante para dar seriedade ao projeto. O objetivo não é substituir o poder público, nem criar uma certificação com aparência de autoridade oficial. O objetivo é reconhecer publicamente aqueles que adotarem providências reais, comprovadas e consistentes em favor da coleta seletiva, da reciclagem, da educação ambiental e da geração de renda por meio das cooperativas." },
      { tipo: 'paragrafo', texto: "O conceito inicial poderia receber nomes como Selo Verde One — Destinação Responsável de Resíduos, Selo Condomínio Amigo da Reciclagem, Selo Economia Circular Granja Viana ou Selo Comunidade Sustentável." },
      { tipo: 'paragrafo', texto: "O nome definitivo ainda poderá ser amadurecido, mas a essência do selo deve permanecer clara: reconhecer quem faz, quem comprova e quem se compromete com uma mudança concreta." },
      { tipo: 'paragrafo', texto: "A certificação poderia ser concedida a condomínios, empresas, escolas e instituições que comprovassem ações efetivas de separação de resíduos, destinação correta dos recicláveis, educação ambiental, apoio à geração de renda de cooperativas e redução do envio de materiais para aterros." },
      { tipo: 'paragrafo', texto: "O ponto central para que o selo tenha credibilidade é a comprovação." },
      { tipo: 'paragrafo', texto: "Não basta dizer que recicla. É preciso demonstrar que existe estrutura, rotina, comunicação, destinação correta e resultado." },
      { tipo: 'paragrafo', texto: "Por isso, o selo deve nascer com critérios objetivos. Esses critérios podem ser organizados em níveis, permitindo que cada condomínio ou empresa evolua gradualmente dentro do programa." },
      { tipo: 'paragrafo', texto: "Um primeiro nível, como o Bronze, poderia reconhecer quem já implantou espaço para coleta seletiva, comunicou os moradores ou colaboradores e passou a destinar os materiais recicláveis para uma cooperativa parceira." },
      { tipo: 'paragrafo', texto: "Um segundo nível, como o Prata, poderia incluir todos os requisitos do Bronze, além de treinamentos periódicos, campanhas educativas e acompanhamento dos indicadores de volume reciclado." },
      { tipo: 'paragrafo', texto: "Um terceiro nível, como o Ouro, poderia reconhecer condomínios e empresas que, além dos requisitos anteriores, estabelecessem metas de reciclagem, relatórios semestrais, campanhas de engajamento e melhoria contínua da separação dos resíduos." },
      { tipo: 'paragrafo', texto: "Um nível superior, como o Diamante, poderia ser reservado para instituições que se tornassem referência regional, com alto índice de reciclagem, ações sociais vinculadas, participação ativa em projetos comunitários e forte contribuição para a cadeia da reciclagem." },
      { tipo: 'paragrafo', texto: "A existência de níveis é importante porque permite que o projeto seja inclusivo. Nem todos os condomínios ou empresas estarão prontos para atingir o nível mais alto logo no início. Mas todos podem começar de algum lugar." },
      { tipo: 'paragrafo', texto: "O selo deve incentivar a evolução, não apenas premiar quem já está avançado." },
      { tipo: 'paragrafo', texto: "O aspecto social pode ser o grande diferencial do projeto." },
      { tipo: 'paragrafo', texto: "Muitos selos ambientais falam apenas de meio ambiente. O Projeto Academia da Reciclagem pode ir além, destacando que cada quilo reciclado representa menos resíduos no meio ambiente e mais renda para famílias que vivem da reciclagem." },
      { tipo: 'paragrafo', texto: "Essa conexão entre sustentabilidade e dignidade humana é uma das marcas mais fortes do movimento." },
      { tipo: 'paragrafo', texto: "Ao receber o selo, o condomínio ou empresa não estará apenas dizendo que separa resíduos. Estará assumindo publicamente um compromisso com o meio ambiente, com a educação da comunidade e com a valorização das pessoas que trabalham na reciclagem." },
      { tipo: 'paragrafo', texto: "Para os condomínios, o selo pode trazer reconhecimento institucional. O síndico poderá comunicar aos moradores que o condomínio participa de um projeto socioambiental sério, com critérios, acompanhamento e impacto social." },
      { tipo: 'paragrafo', texto: "Esse reconhecimento pode fortalecer o orgulho dos moradores, melhorar a cultura interna de separação dos resíduos e até valorizar a imagem do condomínio perante a comunidade." },
      { tipo: 'paragrafo', texto: "Para as empresas, o selo pode ser utilizado em sites, materiais institucionais, relatórios ESG, redes sociais, propostas comerciais e campanhas internas. Muitas empresas buscam formas concretas de demonstrar responsabilidade socioambiental, e o selo pode se tornar um instrumento de comunicação legítimo, desde que sustentado por evidências." },
      { tipo: 'paragrafo', texto: "Por isso, o selo precisa nascer dentro de um programa maior." },
      { tipo: 'paragrafo', texto: "Uma possibilidade é criar o Projeto Academia da Reciclagem como movimento principal e, dentro dele, estruturar quatro frentes: Programa de Educação Ambiental, Programa de Apoio às Cooperativas, Selo Verde Academia da Reciclagem e Relatório Anual de Impacto Social e Ambiental." },
      { tipo: 'paragrafo', texto: "Essa organização ajuda a mostrar que o selo não é uma peça isolada de marketing, mas parte de uma estratégia mais ampla de transformação regional." },
      { tipo: 'paragrafo', texto: "Também foi percebido que o selo deve pertencer ao movimento, e não apenas à imobiliária. A One Consultoria Imobiliária pode aparecer como fundadora, idealizadora e patrocinadora, mas o selo precisa ter identidade própria para ganhar legitimidade diante de condomínios, empresas, cooperativas, escolas, imprensa e poder público." },
      { tipo: 'paragrafo', texto: "Isso não diminui a importância da One. Pelo contrário. Fortalece sua posição como empresa que deu origem a um movimento de impacto real, sem transformar o selo em algo exclusivamente comercial." },
      { tipo: 'paragrafo', texto: "Com o tempo, o Selo Verde pode se tornar um reconhecimento regional de boas práticas ambientais e sociais, reunindo condomínios de Cotia, Carapicuíba, Embu das Artes, Vargem Grande e Jandira, além de empresas, escolas, cooperativas e parceiros institucionais." },
      { tipo: 'paragrafo', texto: "Para isso, será essencial construir um regulamento claro." },
      { tipo: 'paragrafo', texto: "Esse regulamento deverá explicar quem pode participar, quais são os critérios de adesão, quais documentos ou evidências serão exigidos, como será feita a avaliação, quais são os níveis de reconhecimento, por quanto tempo o selo será válido e quais condições podem levar à suspensão ou perda do selo." },
      { tipo: 'paragrafo', texto: "A credibilidade do selo dependerá da transparência." },
      { tipo: 'paragrafo', texto: "Cada participante deverá entender que o reconhecimento não será concedido por relacionamento pessoal, simpatia ou conveniência. Será concedido mediante providências efetivas e comprovadas." },
      { tipo: 'paragrafo', texto: "Esse cuidado é fundamental para proteger o projeto." },
      { tipo: 'paragrafo', texto: "Se o selo for entregue sem critério, perde valor. Se for sério, mensurável e transparente, pode se tornar um poderoso instrumento de mobilização." },
      { tipo: 'paragrafo', texto: "O Selo Verde também pode estimular uma competição positiva entre condomínios e empresas." },
      { tipo: 'paragrafo', texto: "Um condomínio pode desejar melhorar sua classificação. Uma empresa pode querer participar do relatório anual de impacto. Uma escola pode envolver alunos em campanhas de educação ambiental. Um síndico pode se orgulhar de apresentar aos moradores os resultados da reciclagem." },
      { tipo: 'paragrafo', texto: "Essa dinâmica cria movimento, engajamento e continuidade." },
      { tipo: 'paragrafo', texto: "No futuro, os participantes certificados poderão receber materiais de comunicação, como placa física, certificado digital, selo para redes sociais, modelo de comunicado aos moradores, relatório simplificado de impacto e orientações para campanhas internas." },
      { tipo: 'paragrafo', texto: "O selo também poderá fazer parte de eventos anuais do projeto." },
      { tipo: 'paragrafo', texto: "Nesses encontros, seria possível reconhecer publicamente os condomínios e empresas participantes, apresentar os resultados do ano, destacar as cooperativas parceiras, mostrar toneladas recicladas, famílias beneficiadas e novos participantes aderindo ao movimento." },
      { tipo: 'paragrafo', texto: "A entrega do selo pode se tornar um momento simbólico importante." },
      { tipo: 'paragrafo', texto: "Mais do que um certificado, ele representará uma escolha: a escolha de transformar resíduos em oportunidade." },
      { tipo: 'paragrafo', texto: "O Selo Verde deve carregar a essência do projeto: não se trata apenas de separar lixo. Trata-se de assumir responsabilidade sobre aquilo que geramos, reduzir o impacto ambiental e fortalecer uma cadeia de trabalho que gera dignidade para famílias." },
      { tipo: 'paragrafo', texto: "O selo, portanto, será uma ferramenta de reconhecimento, mas também de educação." },
      { tipo: 'paragrafo', texto: "Ele deve ajudar as pessoas a entenderem que a destinação correta dos resíduos precisa ser comprovada, organizada e contínua. Não basta uma ação isolada. É necessário criar cultura." },
      { tipo: 'paragrafo', texto: "Essa cultura começa dentro dos condomínios, das empresas, das escolas e das famílias." },
      { tipo: 'paragrafo', texto: "Ao longo do tempo, o Selo Verde poderá ajudar o Projeto Academia da Reciclagem a se consolidar como um movimento regional de sustentabilidade, economia circular, responsabilidade social e cidadania ambiental." },
      { tipo: 'paragrafo', texto: "O objetivo maior não é distribuir selos. O objetivo maior é transformar comportamento." },
      { tipo: 'paragrafo', texto: "O selo será apenas o símbolo visível de um compromisso mais profundo." },
      { tipo: 'paragrafo', texto: "Um compromisso com o planeta, com a comunidade, com as cooperativas e com as próximas gerações." },
    ],
  },
  {
    id: 'indicadores',
    numero: '05',
    titulo: "Indicadores de Impacto",
    blocos: [
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem deve nascer com propósito, mas também precisa ser capaz de demonstrar resultados concretos." },
      { tipo: 'paragrafo', texto: "Desde o início da construção do projeto, ficou claro que a força da iniciativa estará na união entre impacto ambiental e impacto social. Por isso, os indicadores de impacto serão fundamentais para mostrar que a coleta seletiva e a destinação correta dos resíduos não são apenas ideias bonitas, mas ações capazes de gerar resultados mensuráveis." },
      { tipo: 'paragrafo', texto: "A proposta do projeto é incentivar condomínios residenciais, empresas, escolas e instituições da região de Cotia, Carapicuíba, Embu das Artes, Vargem Grande e Jandira a separarem corretamente seus materiais recicláveis e destinarem esses materiais para cooperativas, especialmente cooperativas que geram renda e dignidade para famílias que vivem da reciclagem." },
      { tipo: 'paragrafo', texto: "Para que isso seja comunicado com seriedade, será necessário medir o que está acontecendo." },
      { tipo: 'paragrafo', texto: "Os indicadores devem ajudar a responder algumas perguntas importantes: quantos quilos de materiais recicláveis foram coletados? Quantas toneladas deixaram de ir para aterros? Quantas famílias foram beneficiadas? Qual valor estimado foi gerado para a cooperativa? Quantos condomínios participaram? Quantas empresas aderiram? Quantas campanhas educativas foram realizadas?" },
      { tipo: 'paragrafo', texto: "Esses dados serão importantes para mostrar aos moradores, síndicos, administradoras, empresas, cooperativas, imprensa e parceiros institucionais que o projeto está produzindo impacto real." },
      { tipo: 'paragrafo', texto: "Um dos primeiros indicadores mencionados na conversa foi o volume de materiais coletados. Esse dado pode ser acompanhado em quilos ou toneladas. A cada mês, o projeto poderá registrar quanto material reciclável saiu dos condomínios e empresas participantes e foi destinado corretamente." },
      { tipo: 'paragrafo', texto: "Esse número tem grande força de comunicação. Quando o projeto mostrar que determinado condomínio destinou corretamente centenas de quilos ou toneladas de materiais recicláveis, os moradores passarão a enxergar que pequenas atitudes individuais, somadas, geram um resultado coletivo expressivo." },
      { tipo: 'paragrafo', texto: "Outro indicador importante será a quantidade de resíduos desviados de aterros ou de destinação inadequada." },
      { tipo: 'paragrafo', texto: "Durante a conversa, ficou muito evidente que o problema não é apenas gerar resíduos, mas o destino que damos a eles. Uma garrafa plástica pode ir para o meio ambiente, pode ir para um aterro ou pode chegar a uma cooperativa, ser reciclada e gerar renda. A garrafa é a mesma. O que muda é a destinação." },
      { tipo: 'paragrafo', texto: "Por isso, o projeto deve medir e divulgar quanto material deixou de seguir para o caminho do desperdício e passou a seguir para o caminho da reciclagem." },
      { tipo: 'paragrafo', texto: "Também foi mencionado que o projeto deve acompanhar o número de famílias beneficiadas." },
      { tipo: 'paragrafo', texto: "Esse talvez seja um dos indicadores mais humanos do movimento. A visita à Cooperativa de Reciclagem de Cotia, a Nova Cotia, mostrou que por trás das montanhas de garrafas plásticas existem pessoas trabalhando. Homens e mulheres que encontram na reciclagem uma forma de gerar renda e sustento para suas famílias." },
      { tipo: 'paragrafo', texto: "Ao divulgar o impacto do projeto, não basta falar apenas em toneladas. É preciso falar também de pessoas." },
      { tipo: 'paragrafo', texto: "Cada quilo reciclado pode representar menos resíduos no meio ambiente, mas também pode representar mais eficiência para a cooperativa, mais renda para os cooperados e mais dignidade para famílias que dependem desse trabalho." },
      { tipo: 'paragrafo', texto: "Outro indicador relevante será o valor estimado gerado para a cooperativa." },
      { tipo: 'paragrafo', texto: "Sempre que possível, o projeto poderá levantar, junto às cooperativas parceiras, o volume recebido e o valor aproximado que aquele material representou para a cadeia da reciclagem. Esse dado ajudará a demonstrar que a destinação correta dos resíduos também movimenta economia, trabalho e renda." },
      { tipo: 'paragrafo', texto: "Esse ponto será muito importante para reforçar que o Projeto Academia da Reciclagem não é apenas ambiental. Ele também tem dimensão social e econômica." },
      { tipo: 'paragrafo', texto: "O projeto também deve acompanhar o número de condomínios participantes." },
      { tipo: 'paragrafo', texto: "Como a proposta inicial é utilizar relacionamentos pessoais, empresariais e institucionais para incentivar principalmente condomínios residenciais, será importante registrar quais condomínios aderiram, em que estágio estão, que ações implementaram e quais resultados alcançaram." },
      { tipo: 'paragrafo', texto: "Com o tempo, esses dados poderão formar um mapa regional de participação, mostrando a expansão do movimento pela Granja Viana e pelos municípios de Cotia, Carapicuíba, Embu das Artes e Jandira." },
      { tipo: 'paragrafo', texto: "Também será importante medir a participação de empresas." },
      { tipo: 'paragrafo', texto: "Empresas que aderirem ao projeto poderão ser acompanhadas de forma semelhante: implantação da separação correta, campanhas internas, destinação para cooperativas, volume coletado, colaboradores envolvidos e eventual reconhecimento por meio do Selo Verde." },
      { tipo: 'paragrafo', texto: "Outro indicador será a quantidade de campanhas educativas realizadas." },
      { tipo: 'paragrafo', texto: "O projeto tem forte componente de educação ambiental. Muitas pessoas desejam agir corretamente, mas não sabem exatamente como separar, armazenar ou destinar os materiais recicláveis. Por isso, campanhas educativas em condomínios, empresas e escolas serão parte essencial da iniciativa." },
      { tipo: 'paragrafo', texto: "Essas campanhas poderão ser medidas por número de ações realizadas, número de pessoas alcançadas, materiais distribuídos, vídeos publicados, reuniões com síndicos, palestras, posts em redes sociais e apresentações institucionais." },
      { tipo: 'paragrafo', texto: "Os indicadores também devem ajudar na construção do futuro Relatório Anual de Impacto Social e Ambiental." },
      { tipo: 'paragrafo', texto: "Esse relatório poderá reunir, ao final de cada ano, os principais resultados do projeto: toneladas recicladas, resíduos desviados de aterros, famílias beneficiadas, cooperativas apoiadas, condomínios participantes, empresas engajadas, campanhas educativas realizadas, selos concedidos e evolução do movimento." },
      { tipo: 'paragrafo', texto: "O Relatório Anual de Impacto será uma ferramenta muito importante para dar transparência ao projeto e fortalecer sua credibilidade." },
      { tipo: 'paragrafo', texto: "Ele também poderá ser utilizado em apresentações para síndicos, empresas, imprensa local, parceiros institucionais e poder público." },
      { tipo: 'paragrafo', texto: "Outro ponto importante é que os indicadores podem fortalecer o futuro Selo Verde." },
      { tipo: 'paragrafo', texto: "Para que o selo tenha valor, ele precisará estar apoiado em critérios objetivos e comprovação. Os indicadores serão parte dessa comprovação. Eles mostrarão que determinado condomínio ou empresa não apenas declarou apoio ao projeto, mas adotou providências efetivas e gerou resultados." },
      { tipo: 'paragrafo', texto: "O selo, portanto, poderá utilizar indicadores como volume reciclado, regularidade da destinação, campanhas educativas, participação dos moradores ou colaboradores, parceria com cooperativas e evolução ao longo do tempo." },
      { tipo: 'paragrafo', texto: "Foi mencionado também que os indicadores poderão ser divulgados mensalmente." },
      { tipo: 'paragrafo', texto: "Essa divulgação mensal pode mostrar, por exemplo, quantos quilos foram coletados, quantas toneladas foram desviadas de aterros, quantas famílias foram beneficiadas e qual valor estimado foi gerado para a cooperativa." },
      { tipo: 'paragrafo', texto: "Essa comunicação constante ajudará a manter o projeto vivo." },
      { tipo: 'paragrafo', texto: "Os moradores e empresas precisam perceber que sua participação gera resultado. Quando as pessoas veem números concretos, tendem a se sentir parte de algo maior." },
      { tipo: 'paragrafo', texto: "Além disso, os indicadores podem criar uma competição positiva entre condomínios e empresas." },
      { tipo: 'paragrafo', texto: "Um condomínio pode se sentir estimulado a melhorar seus resultados. Uma empresa pode querer ampliar sua participação. Uma escola pode mobilizar alunos e famílias para aumentar o volume de recicláveis corretamente destinados." },
      { tipo: 'paragrafo', texto: "Essa dinâmica pode fortalecer o engajamento e ajudar o projeto a crescer." },
      { tipo: 'paragrafo', texto: "Os indicadores também devem preservar a essência do projeto." },
      { tipo: 'paragrafo', texto: "O objetivo não é transformar a reciclagem apenas em números frios. O objetivo é usar os números para contar uma história real de transformação." },
      { tipo: 'paragrafo', texto: "Cada tonelada reciclada deve ser comunicada como menos impacto ambiental. Cada família beneficiada deve ser lembrada como mais dignidade. Cada condomínio participante deve ser visto como uma comunidade que decidiu assumir responsabilidade. Cada empresa engajada deve ser reconhecida como parceira de um movimento regional." },
      { tipo: 'paragrafo', texto: "A imagem das 30 toneladas de resíduos geradas por uma única pessoa ao longo da vida também se conecta aos indicadores." },
      { tipo: 'paragrafo', texto: "Esse dado ajuda a mostrar a dimensão do problema individual. Se uma pessoa pode gerar mais de 30 toneladas de resíduos ao longo da vida, uma família pode gerar muito mais, e um condomínio inteiro pode gerar um volume gigantesco." },
      { tipo: 'paragrafo', texto: "Por isso, o acompanhamento de indicadores será essencial para mostrar que, quando muitas pessoas se organizam, o impacto positivo também pode ser gigantesco." },
      { tipo: 'paragrafo', texto: "O projeto deve transformar a pergunta inicial em ação concreta: vamos transformar esses resíduos em problema ou em oportunidade?" },
      { tipo: 'paragrafo', texto: "Os indicadores ajudarão a mostrar a resposta." },
      { tipo: 'paragrafo', texto: "Se o material for separado corretamente, destinado para cooperativas e acompanhado com seriedade, ele deixa de ser apenas lixo. Passa a ser matéria-prima, renda, dignidade e preservação ambiental." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem deve, portanto, organizar desde o início seus indicadores de impacto." },
      { tipo: 'paragrafo', texto: "Eles serão a memória objetiva do projeto." },
      { tipo: 'paragrafo', texto: "Serão os números que provarão a evolução do movimento." },
      { tipo: 'paragrafo', texto: "Serão a base para os relatórios, para o Selo Verde, para as apresentações, para a comunicação nas redes sociais e para o diálogo com parceiros." },
      { tipo: 'paragrafo', texto: "Mas, acima de tudo, serão a prova de que um sonho de adolescência pode se transformar em resultado concreto para o planeta e para as pessoas." },
    ],
  },
  {
    id: 'manifesto-fundador',
    numero: '06',
    titulo: "Manifesto Fundador",
    blocos: [
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem nasce de um propósito de vida: deixar um planeta melhor do que encontramos." },
      { tipo: 'paragrafo', texto: "Este manifesto nasce de uma lembrança antiga, guardada desde a adolescência, quando uma reportagem de televisão mostrou que uma pessoa de classe média poderia gerar, ao longo de sua vida, uma verdadeira montanha de lixo. A imagem de mais de 70 contêineres empilhados ficou marcada para sempre." },
      { tipo: 'paragrafo', texto: "Naquele momento, ficou claro que o lixo não desaparece quando sai da nossa casa. Ele continua existindo. Ele ocupa espaço. Ele impacta o meio ambiente. Ele revela o modo como vivemos, consumimos e descartamos." },
      { tipo: 'paragrafo', texto: "Durante muitos anos, essa imagem permaneceu adormecida, mas nunca esquecida." },
      { tipo: 'paragrafo', texto: "Aos 57 anos, a visita à Cooperativa de Reciclagem de Cotia, a Nova Cotia, reacendeu essa memória. Ao ver as montanhas de garrafas plásticas recebendo a destinação correta e, ao mesmo tempo, ao conhecer as pessoas que trabalham na cooperativa e conseguem gerar renda digna para suas famílias por meio da reciclagem, ficou evidente que esse projeto não é apenas sobre resíduos." },
      { tipo: 'paragrafo', texto: "É sobre meio ambiente." },
      { tipo: 'paragrafo', texto: "É sobre dignidade." },
      { tipo: 'paragrafo', texto: "É sobre responsabilidade." },
      { tipo: 'paragrafo', texto: "É sobre futuro." },
      { tipo: 'paragrafo', texto: "É sobre transformar aquilo que seria descartado em oportunidade." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem nasce para conectar quem gera resíduos com quem transforma resíduos em valor." },
      { tipo: 'paragrafo', texto: "Nasce para aproximar condomínios residenciais, empresas, escolas, cooperativas, moradores, síndicos, administradoras, parceiros e poder público em torno de um compromisso comum: dar destinação correta aos materiais recicláveis e reduzir o impacto ambiental da nossa forma de viver." },
      { tipo: 'paragrafo', texto: "Acreditamos que o resíduo não precisa ser apenas um problema. Quando separado corretamente, coletado com organização e destinado a cooperativas sérias, ele pode se transformar em matéria-prima, renda, educação, cidadania e dignidade." },
      { tipo: 'paragrafo', texto: "Acreditamos que cada garrafa, cada embalagem, cada papel, cada metal e cada vidro carregam uma escolha." },
      { tipo: 'paragrafo', texto: "Podem seguir para o descarte inadequado, para os aterros, para as ruas, para os córregos e para a degradação ambiental." },
      { tipo: 'paragrafo', texto: "Ou podem seguir para a reciclagem, para a economia circular, para a geração de renda e para a construção de uma cultura mais responsável." },
      { tipo: 'paragrafo', texto: "A escolha desse caminho depende de consciência, organização e ação." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem nasce para transformar consciência em movimento." },
      { tipo: 'paragrafo', texto: "Não queremos apenas falar sobre reciclagem. Queremos criar pontes concretas para que os materiais recicláveis gerados nos condomínios e empresas da região cheguem ao destino correto." },
      { tipo: 'paragrafo', texto: "Não queremos apenas instalar lixeiras. Queremos educar pessoas!!" },
      { tipo: 'paragrafo', texto: "Não queremos apenas medir toneladas recicladas. Queremos mostrar que por trás de cada tonelada existem famílias, trabalhadores, histórias e vidas impactadas!." },
      { tipo: 'paragrafo', texto: "Não queremos apenas criar campanhas. Queremos construir cultura." },
      { tipo: 'paragrafo', texto: "O projeto nasce inicialmente voltado aos municípios de Cotia, Carapicuíba, Embu das Artes, Vargem Grande e Jandira, com atenção especial à região da Granja Viana, onde existem muitos condomínios residenciais, empresas e instituições capazes de exercer papel relevante nessa transformação." },
      { tipo: 'paragrafo', texto: "A região pode se tornar referência em mobilização socioambiental se conseguir unir educação ambiental, coleta seletiva, cooperativas, indicadores de impacto e reconhecimento público aos participantes comprometidos." },
      { tipo: 'paragrafo', texto: "Por isso, o projeto também poderá desenvolver um Selo Verde ou Selo de Reconhecimento Socioambiental privado, destinado a condomínios, empresas, escolas e instituições que adotarem providências efetivas e comprovadas em favor da destinação correta dos resíduos." },
      { tipo: 'paragrafo', texto: "Esse selo não será apenas um símbolo. Ele deverá representar compromisso, comprovação e responsabilidade." },
      { tipo: 'paragrafo', texto: "O reconhecimento só terá valor se estiver apoiado em critérios claros, evidências reais e resultados mensuráveis." },
      { tipo: 'paragrafo', texto: "Acreditamos que condomínios e empresas podem ser grandes agentes de transformação." },
      { tipo: 'paragrafo', texto: "Um condomínio que orienta seus moradores, separa corretamente seus resíduos e encaminha os recicláveis para uma cooperativa não está apenas reduzindo lixo. Está educando uma comunidade inteira." },
      { tipo: 'paragrafo', texto: "Uma empresa que destina corretamente seus materiais recicláveis não está apenas cumprindo uma obrigação ambiental. Está assumindo uma posição de responsabilidade diante da sociedade." },
      { tipo: 'paragrafo', texto: "Uma escola que ensina crianças e jovens sobre reciclagem não está apenas transmitindo informação. Está formando uma geração mais consciente." },
      { tipo: 'paragrafo', texto: "Uma cooperativa que recebe materiais bem separados não está apenas reciclando resíduos. Está fortalecendo uma cadeia de trabalho que gera renda, dignidade e pertencimento." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem reconhece que a reciclagem é uma pauta ambiental e social ao mesmo tempo." },
      { tipo: 'paragrafo', texto: "Cada quilo reciclado significa menos resíduos no meio ambiente." },
      { tipo: 'paragrafo', texto: "Cada material destinado corretamente significa mais eficiência para a cooperativa." },
      { tipo: 'paragrafo', texto: "Cada condomínio engajado significa mais escala para o impacto." },
      { tipo: 'paragrafo', texto: "Cada família beneficiada significa mais dignidade." },
      { tipo: 'paragrafo', texto: "Este manifesto também reconhece que o lixo revela uma verdade desconfortável: todos geramos resíduos. Todos fazemos parte do problema. Mas todos também podemos fazer parte da solução." },
      { tipo: 'paragrafo', texto: "A pergunta não é se vamos gerar resíduos." },
      { tipo: 'paragrafo', texto: "A pergunta é qual destino daremos a eles." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem nasce para ajudar a mudar esse destino." },
      { tipo: 'paragrafo', texto: "Nasce para mostrar que a responsabilidade ambiental começa dentro de casa, mas não termina na porta do condomínio." },
      { tipo: 'paragrafo', texto: "Nasce para lembrar que aquilo que descartamos continua existindo e que cada escolha de descarte pode produzir abandono ou transformação." },
      { tipo: 'paragrafo', texto: "Nasce para aproximar o morador do trabalhador da reciclagem." },
      { tipo: 'paragrafo', texto: "Nasce para dar visibilidade às cooperativas." },
      { tipo: 'paragrafo', texto: "Nasce para fortalecer a economia circular." },
      { tipo: 'paragrafo', texto: "Nasce para criar indicadores de impacto." },
      { tipo: 'paragrafo', texto: "Nasce para inspirar novos hábitos." },
      { tipo: 'paragrafo', texto: "Nasce para deixar um legado!!." },
      { tipo: 'paragrafo', texto: "O compromisso central deste movimento é simples e profundo:" },
      { tipo: 'paragrafo', texto: "“Quero deixar um planeta melhor do que encontrei.”" },
      { tipo: 'paragrafo', texto: "Essa frase é a raiz do projeto." },
      { tipo: 'paragrafo', texto: "Ela nasce de uma lembrança de adolescência, ganha força na visita à Cooperativa Nova Cotia e se transforma agora em um chamado à ação." },
      { tipo: 'paragrafo', texto: "Chamamos moradores, síndicos, administradoras, empresas, escolas, cooperativas, lideranças comunitárias, voluntários e poder público a participarem dessa construção." },
      { tipo: 'paragrafo', texto: "Ninguém muda o mundo sozinho." },
      { tipo: 'paragrafo', texto: "Mas uma comunidade organizada pode mudar o destino de milhares de toneladas de resíduos." },
      { tipo: 'paragrafo', texto: "Uma cidade mobilizada pode transformar descarte em oportunidade." },
      { tipo: 'paragrafo', texto: "Uma região inteira pode se tornar exemplo de consciência ambiental e dignidade social." },
      { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem nasce para isso." },
      { tipo: 'paragrafo', texto: "Para transformar resíduos em oportunidade." },
      { tipo: 'paragrafo', texto: "Para transformar descarte em responsabilidade." },
      { tipo: 'paragrafo', texto: "Para transformar reciclagem em renda." },
      { tipo: 'paragrafo', texto: "Para transformar consciência em cultura." },
      { tipo: 'paragrafo', texto: "Para transformar um sonho de adolescência em legado para as próximas gerações." },
    ],
  },
];

export const CARTA: Carta = {
  titulo: 'Carta às Próximas Gerações',
  blocos: [
    { tipo: 'destaque', texto: "Meu nome é Gilson Tangerino." },
    { tipo: 'paragrafo', texto: "Quando eu era adolescente, assisti a uma reportagem de televisão que nunca mais saiu da minha cabeça." },
    { tipo: 'paragrafo', texto: "A reportagem mostrava que uma pessoa de classe média gerava aproximadamente um contêiner de lixo por ano. Aquilo, por si só, já era impactante. Mas o que ficou gravado em mim foi a imagem que vinha depois: ao longo da vida, cada pessoa poderia formar uma verdadeira montanha de contêineres de lixo." },
    { tipo: 'paragrafo', texto: "Naquele momento, eu vi mais do que resíduos. Eu vi consequência. Vi que aquilo que descartamos não desaparece. O lixo sai da nossa casa, mas continua existindo em algum lugar. Ele ocupa espaço, gera impacto, polui, adoece ambientes e permanece como uma marca da forma como vivemos." },
    { tipo: 'paragrafo', texto: "Aquela imagem de mais de 70 contêineres empilhados nunca mais saiu da minha cabeça." },
    { tipo: 'paragrafo', texto: "Talvez eu ainda não soubesse dar nome ao sentimento que nasceu naquele dia. Mas hoje entendo que ali foi plantada uma inquietação. Uma pergunta silenciosa começou a me acompanhar: que planeta estamos deixando para as próximas gerações?" },
    { tipo: 'paragrafo', texto: "Durante muitos anos, esse sonho ficou guardado. A vida seguiu. Vieram trabalho, família, empresa, responsabilidades, conquistas e desafios. Mas aquela imagem continuou viva em algum lugar dentro de mim." },
    { tipo: 'paragrafo', texto: "Aos 57 anos, essa lembrança voltou com força quando visitei a Cooperativa de Reciclagem de Cotia, a Nova Cotia." },
    { tipo: 'paragrafo', texto: "Na cooperativa, fui impactado por duas imagens muito fortes." },
    { tipo: 'paragrafo', texto: "A primeira foi a das montanhas de garrafas plásticas e materiais recicláveis. Ao olhar para aquele volume enorme, percebi que estava diante de materiais que poderiam estar abandonados em ruas, rios, córregos, terrenos e áreas verdes. Poderiam estar poluindo o meio ambiente. Mas estavam ali, recebendo uma destinação correta." },
    { tipo: 'paragrafo', texto: "A segunda imagem foi ainda mais profunda: as pessoas que trabalham na cooperativa. Homens e mulheres que, por meio da reciclagem, conseguem gerar renda, sustento e dignidade para suas famílias." },
    { tipo: 'paragrafo', texto: "Naquele momento, compreendi que reciclagem não é apenas uma questão ambiental. É também uma questão social e humana." },
    { tipo: 'paragrafo', texto: "As montanhas de plástico representam o problema. As pessoas da cooperativa representam a solução." },
    { tipo: 'paragrafo', texto: "Foi ali que a imagem da adolescência encontrou uma resposta na vida adulta." },
    { tipo: 'paragrafo', texto: "Na adolescência, eu havia visto a montanha de resíduos como um alerta. Na cooperativa, vi que essa montanha também pode ser transformada em oportunidade. O mesmo material que poderia agredir o planeta pode gerar trabalho, renda e dignidade, desde que receba o destino correto." },
    { tipo: 'paragrafo', texto: "Por isso, este projeto nasce de um propósito de vida: deixar um planeta melhor do que encontrei." },
    { tipo: 'paragrafo', texto: "O Projeto Academia da Reciclagem nasce da decisão de não apenas me emocionar com uma causa, mas agir por ela. Nasce da vontade de transformar uma inquietação antiga em movimento concreto. Nasce do desejo de utilizar relacionamentos pessoais, empresariais e institucionais para incentivar a coleta seletiva e a destinação correta dos materiais recicláveis, especialmente em condomínios residenciais e empresas de Cotia, Carapicuíba, Embu das Artes e Jandira." },
    { tipo: 'paragrafo', texto: "A região da Granja Viana pode se tornar referência em consciência ambiental, responsabilidade social e economia circular. Para isso, precisamos aproximar quem gera os resíduos de quem pode transformá-los em nova matéria-prima e em renda digna." },
    { tipo: 'paragrafo', texto: "Cada morador que separa corretamente uma embalagem participa dessa transformação. Cada síndico que organiza a coleta seletiva dentro do condomínio ajuda a construir uma cultura nova. Cada empresa que assume responsabilidade sobre seus resíduos fortalece um compromisso real com a comunidade. Cada cooperado que recebe material em melhores condições tem mais chance de gerar renda para sua família." },
    { tipo: 'paragrafo', texto: "O lixo não termina quando sai de casa. Ele segue um caminho." },
    { tipo: 'paragrafo', texto: "Esse caminho pode ser de abandono, desperdício e poluição. Mas também pode ser de reciclagem, oportunidade e dignidade." },
    { tipo: 'paragrafo', texto: "A escolha desse caminho depende de consciência, organização e compromisso." },
    { tipo: 'paragrafo', texto: "Por isso, esta carta é dirigida às próximas gerações." },
    { tipo: 'paragrafo', texto: "Que vocês possam receber um mundo melhor do que aquele que encontramos. Que possam viver em cidades mais limpas, comunidades mais conscientes e sociedades mais responsáveis. Que possam olhar para trás e perceber que, em algum momento, pessoas decidiram agir antes que fosse tarde." },
    { tipo: 'paragrafo', texto: "Talvez não consigamos eliminar todos os resíduos que produzimos. Mas podemos mudar profundamente o destino deles." },
    { tipo: 'paragrafo', texto: "Podemos reduzir o desperdício. Podemos separar melhor. Podemos reciclar mais. Podemos apoiar cooperativas. Podemos gerar renda. Podemos educar crianças, famílias, condomínios, empresas e comunidades. Podemos transformar o que antes era tratado como lixo em matéria-prima, trabalho e esperança." },
    { tipo: 'paragrafo', texto: "Cada quilo reciclado representa menos impacto ambiental. Cada material destinado corretamente representa uma pequena vitória contra o desperdício. Cada família beneficiada pela reciclagem representa dignidade. Cada condomínio engajado representa escala. Cada empresa comprometida representa responsabilidade." },
    { tipo: 'paragrafo', texto: "Este projeto não nasce apenas para organizar resíduos. Nasce para organizar consciências." },
    { tipo: 'paragrafo', texto: "Não nasce apenas para criar campanhas. Nasce para criar cultura." },
    { tipo: 'paragrafo', texto: "Não nasce apenas para entregar um selo. Nasce para reconhecer atitudes verdadeiras." },
    { tipo: 'paragrafo', texto: "Não nasce apenas para falar de meio ambiente. Nasce para falar de futuro, de pessoas, de dignidade e de legado." },
    { tipo: 'paragrafo', texto: "Um dia, quando eu era adolescente, vi uma pilha de contêineres e entendi que cada vida deixa marcas no planeta." },
    { tipo: 'paragrafo', texto: "Hoje, aos 56 anos, escolho trabalhar para que a minha marca seja diferente." },
    { tipo: 'paragrafo', texto: "Quero que ela seja feita de consciência, mobilização, educação, responsabilidade e amor pelo futuro." },
    { tipo: 'paragrafo', texto: "Quero deixar um planeta melhor do que encontrei." },
    { tipo: 'paragrafo', texto: "Essa é a origem do Projeto Academia da Reciclagem." },
    { tipo: 'paragrafo', texto: "Essa é a razão pela qual decidi agir." },
    { tipo: 'paragrafo', texto: "E essa é a mensagem que desejo deixar às próximas gerações: o planeta que vocês receberão depende das escolhas que fazemos agora." },
    { tipo: 'destaque', texto: "Que as nossas escolhas sejam dignas do futuro que desejamos construir." },
    { tipo: 'destaque', texto: "Gilson Tangerino" },
    { tipo: 'paragrafo', texto: "Idealizador do Projeto Academia da Reciclagem." },
  ],
};
