"""Tests for `mcp/noctusai/workspace.py` — workspace-aware path resolution.

Covers:
- marker discovery via cwd walk-up
- fallback to file-relative noc root when no marker found
- primary vs seed workspace shapes
- key=value parser (comments / blank lines / malformed lines)
- per-workspace state directory creation
"""
from __future__ import annotations

import os
from pathlib import Path

import pytest

from workspace import (
    MARKER_FILENAME,
    WORKSPACE_STATE_DIRNAME,
    WorkspaceContext,
    find_workspace_marker,
    get_noctusai_home,
    get_workspace_context,
    get_workspace_root,
    get_workspace_state_dir,
)


def _write_marker(dir_: Path, kind: str = "template", name: str = "test-ws", noc_home: Path | None = None) -> None:
    lines = [
        "# auto-generated by tests",
        f"workspace_kind={kind}",
        f"workspace_name={name}",
    ]
    if noc_home is not None:
        lines.append(f"noctusai_home={noc_home}")
    lines.append("bootstrap_version=1")
    (dir_ / MARKER_FILENAME).write_text("\n".join(lines) + "\n", encoding="utf-8")


class TestMarkerDiscovery:
    def test_finds_marker_in_cwd(self, tmp_path: Path) -> None:
        _write_marker(tmp_path)
        assert find_workspace_marker(tmp_path) == tmp_path

    def test_walks_up_to_find_marker(self, tmp_path: Path) -> None:
        deep = tmp_path / "a" / "b" / "c"
        deep.mkdir(parents=True)
        _write_marker(tmp_path)
        assert find_workspace_marker(deep) == tmp_path

    def test_returns_none_when_no_marker(self, tmp_path: Path) -> None:
        # tmp_path is unlikely to have a parent marker; isolate by walking
        # only within tmp_path. We test by giving a path outside our project.
        # Use /tmp (or tmp_path's filesystem root) — marker won't exist there.
        # A file-system root walk will return None.
        result = find_workspace_marker(tmp_path)
        assert result is None or not (result / MARKER_FILENAME).is_file() or result == tmp_path
        # If a parent marker IS found (e.g. running tests inside noc), the
        # return is just that parent — not None. Both are valid; we assert
        # the contract: marker_present=True iff the returned dir has the marker.

    def test_finds_nearest_marker_when_nested(self, tmp_path: Path) -> None:
        outer = tmp_path
        inner = tmp_path / "inner"
        inner.mkdir()
        _write_marker(outer, kind="primary", name="outer")
        _write_marker(inner, kind="seed", name="inner")
        deep = inner / "x" / "y"
        deep.mkdir(parents=True)
        # Nearest is inner — walk-up stops at first marker found.
        assert find_workspace_marker(deep) == inner


class TestWorkspaceContext:
    def test_primary_workspace_shape(self, tmp_path: Path) -> None:
        _write_marker(tmp_path, kind="primary", name="primary-ws", noc_home=tmp_path)
        ctx = get_workspace_context(tmp_path)
        assert ctx.kind == "primary"
        assert ctx.name == "primary-ws"
        assert ctx.root == tmp_path
        assert ctx.noctusai_home == tmp_path
        assert ctx.marker_present is True

    def test_seed_workspace_shape(self, tmp_path: Path) -> None:
        ws = tmp_path / "ws"
        noc = tmp_path / "noc"
        ws.mkdir()
        noc.mkdir()
        _write_marker(ws, kind="seed", name="my-template", noc_home=noc)
        ctx = get_workspace_context(ws)
        assert ctx.kind == "seed"
        assert ctx.name == "my-template"
        assert ctx.root == ws
        assert ctx.noctusai_home == noc
        assert ctx.marker_present is True

    def test_seed_marker_without_home_falls_back(self, tmp_path: Path) -> None:
        # A template marker missing `noctusai_home` falls back to file-relative
        # noc root (the in-repo install location). This is defensive — the
        # bootstrap always writes noctusai_home, but corrupted markers
        # shouldn't crash the resolver.
        ws = tmp_path / "ws"
        ws.mkdir()
        _write_marker(ws, kind="seed", name="orphan")  # no noc_home arg
        ctx = get_workspace_context(ws)
        assert ctx.kind == "seed"
        # Falls back to noc-the-actual-noc (workspace.py.parents[2]).
        assert ctx.noctusai_home.exists()
        assert ctx.noctusai_home.name in {"noctusai", "noc"} or (ctx.noctusai_home / "CLAUDE.md").exists()

    def test_no_marker_falls_back_to_file_relative_root(self, tmp_path: Path) -> None:
        # No marker anywhere — context falls back to the file-relative noc
        # root (parents[2] from workspace.py).
        ctx = get_workspace_context(tmp_path)
        assert ctx.kind == "primary"
        # Either we walked up and found noc's marker (tests run inside noc),
        # or we fell back to file-relative noc root. Either way it's a valid
        # noc root.
        assert (ctx.root / "CLAUDE.md").exists() or (ctx.noctusai_home / "CLAUDE.md").exists()


class TestMarkerParsing:
    def test_parses_key_value_pairs(self, tmp_path: Path) -> None:
        _write_marker(tmp_path, kind="seed", name="my-ws", noc_home=Path("/some/noc"))
        ctx = get_workspace_context(tmp_path)
        assert ctx.extra["workspace_kind"] == "seed"
        assert ctx.extra["workspace_name"] == "my-ws"
        assert ctx.extra["noctusai_home"] == "/some/noc"
        assert ctx.extra["bootstrap_version"] == "1"

    def test_ignores_comments_and_blank_lines(self, tmp_path: Path) -> None:
        marker = tmp_path / MARKER_FILENAME
        marker.write_text(
            "# leading comment\n"
            "\n"
            "workspace_kind=seed\n"
            "  # indented comment\n"
            "workspace_name=  spaced-out  \n"
            "\n"
            "noctusai_home=/x\n",
            encoding="utf-8",
        )
        ctx = get_workspace_context(tmp_path)
        assert ctx.kind == "seed"
        assert ctx.name == "spaced-out"
        assert str(ctx.noctusai_home) == "/x"

    def test_malformed_lines_silently_skipped(self, tmp_path: Path) -> None:
        marker = tmp_path / MARKER_FILENAME
        marker.write_text(
            "workspace_kind=seed\n"
            "no-equals-sign-here\n"
            "workspace_name=ws\n",
            encoding="utf-8",
        )
        ctx = get_workspace_context(tmp_path)
        assert ctx.kind == "seed"
        assert ctx.name == "ws"


class TestConvenienceWrappers:
    def test_get_workspace_root_returns_marker_dir(self, tmp_path: Path) -> None:
        _write_marker(tmp_path, kind="seed", name="ws", noc_home=tmp_path / "noc")
        assert get_workspace_root(tmp_path) == tmp_path

    def test_get_noctusai_home_returns_marker_home(self, tmp_path: Path) -> None:
        noc = tmp_path / "noc"
        noc.mkdir()
        _write_marker(tmp_path, kind="seed", name="ws", noc_home=noc)
        assert get_noctusai_home(tmp_path) == noc

    def test_state_dir_created_on_demand(self, tmp_path: Path) -> None:
        _write_marker(tmp_path, kind="seed", name="ws", noc_home=tmp_path)
        state = get_workspace_state_dir(tmp_path)
        assert state == tmp_path / WORKSPACE_STATE_DIRNAME
        assert state.is_dir()


class TestBackCompat:
    def test_existing_noc_resolves_correctly(self) -> None:
        """The actual noc repo (with its planted primary marker) resolves
        as kind=primary and root=noc-root. Guard against the fallback being
        activated when the marker is present.
        """
        # Walk up from this test file's location.
        here = Path(__file__).resolve()
        ctx = get_workspace_context(here)
        # We're either in noc (marker_present=True, kind=primary) or
        # in a tmp install (marker_present=False, fallback to noc root).
        # Both shapes have a valid noc root.
        assert ctx.noctusai_home.is_dir()
        assert (ctx.noctusai_home / "CLAUDE.md").is_file() or (ctx.root / "CLAUDE.md").is_file()
