"""stamp_seed_version — native port parity vs scripts/stamp-seed-version.sh.

Runs against a real throwaway git repo (the script genuinely shells to
git rev-parse) and asserts the stamped file BODY is byte-for-byte the
shell script's heredoc, both target paths are written, and the
git-unavailable path returns the parity failure shape.
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools.noctus.dev import stamp_seed_version as ssv


def _git(repo: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True)


def _init_repo(repo: Path) -> str:
    repo.mkdir(parents=True, exist_ok=True)
    _git(repo, "init", "-q")
    _git(repo, "config", "user.email", "t@t.t")
    _git(repo, "config", "user.name", "t")
    (repo / "f.txt").write_text("x\n", encoding="utf-8")
    _git(repo, "add", "f.txt")
    _git(repo, "commit", "-q", "-m", "init")
    out = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "--short", "HEAD"],
        check=True, capture_output=True, text=True,
    )
    return out.stdout.strip()


def test_stamps_both_targets_with_exact_body(tmp_path, monkeypatch):
    repo = tmp_path / "repo"
    sha = _init_repo(repo)
    monkeypatch.chdir(repo)

    r = ssv.stamp_seed_version()
    assert r["ok"] is True and r["stamped"] is True
    assert r["sha"] == sha
    assert sorted(r["files"]) == sorted(
        [
            "seed/framework/backend/noctusai_seed/_version_static.py",
            "seed/lib/backend/noctusai_lib/_version_static.py",
        ]
    )

    expected_body = (
        "# Auto-generated by scripts/stamp-seed-version.sh.\n"
        "# Reflects git HEAD at stamp time. DO NOT edit by hand.\n"
        "# Re-stamp: run scripts/stamp-seed-version.sh (or commit again — pre-commit does it).\n"
        f'__version__ = "{sha}"\n'
    )
    for rel in r["files"]:
        assert (repo / rel).read_text(encoding="utf-8") == expected_body
    assert f"noctusai_seed stamped: {sha}" in r["message"]
    assert f"noctusai_lib stamped: {sha}" in r["message"]


def test_idempotent(tmp_path, monkeypatch):
    repo = tmp_path / "repo"
    _init_repo(repo)
    monkeypatch.chdir(repo)
    r1 = ssv.stamp_seed_version()
    body1 = (repo / r1["files"][0]).read_text(encoding="utf-8")
    r2 = ssv.stamp_seed_version()
    body2 = (repo / r2["files"][0]).read_text(encoding="utf-8")
    assert body1 == body2
    assert r1["sha"] == r2["sha"]


def test_git_unavailable_returns_parity_failure(tmp_path, monkeypatch):
    # A directory that is NOT inside any git repo → `git rev-parse
    # --show-toplevel` fails → ok=False, stamped=False (exit-1 parity).
    nongit = tmp_path / "plain"
    nongit.mkdir()
    monkeypatch.chdir(nongit)
    # Guard: ensure tmp_path isn't itself inside a repo on this host.
    probe = subprocess.run(
        ["git", "-C", str(nongit), "rev-parse", "--show-toplevel"],
        capture_output=True, text=True,
    )
    if probe.returncode == 0:
        pytest.skip("tmp dir is inside a git repo on this host")
    r = ssv.stamp_seed_version()
    assert r["ok"] is False
    assert r["stamped"] is False
    assert r["sha"] is None
    assert "git not available" in r["message"]
