# Generated by Django 4.2.9 on 2026-01-13 22:22

from django.db import migrations, models
import django.db.models.deletion


def clear_corretor_strings(apps, schema_editor):
    Proprietario = apps.get_model('proprietario', 'Proprietario')
    db_alias = schema_editor.connection.alias
    Proprietario.objects.using(db_alias).update(corretor='')


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0001_initial'),
        ('proprietario', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clear_corretor_strings, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='proprietario',
            name='corretor',
        ),
        migrations.AddField(
            model_name='proprietario',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corretor.corretor'),
        ),
    ]
