# Generated by Django 4.2.9 on 2026-01-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0002_alter_proprietario_corretor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
