# Generated by Django 4.2.9 on 2026-01-26 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0003_alter_proprietario_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proprietario',
            options={'verbose_name': 'Proprietário', 'verbose_name_plural': 'Proprietários'},
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='telefone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Telefone deve estar em formato brasileiro válido', regex='^\\+?55?\\s?\\(?[1-9]{2}\\)?\\s?[9]?\\d{4}-?\\d{4}$')]),
        ),
        migrations.AddIndex(
            model_name='proprietario',
            index=models.Index(fields=['nome'], name='proprietari_nome_6db4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='proprietario',
            index=models.Index(fields=['corretor'], name='proprietari_correto_15c07a_idx'),
        ),
    ]
