# Generated by Django 4.2.9 on 2026-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proprietario', '0004_alter_proprietario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proprietario',
            options={'ordering': ['nome'], 'verbose_name': 'Proprietário', 'verbose_name_plural': 'Proprietários'},
        ),
        migrations.AddIndex(
            model_name='proprietario',
            index=models.Index(fields=['telefone'], name='proprietari_telefon_37fe33_idx'),
        ),
        migrations.AddIndex(
            model_name='proprietario',
            index=models.Index(fields=['email'], name='proprietari_email_e81120_idx'),
        ),
    ]
