/**
 * Coleta de lixo — página da Secretaria de Serviços Municipais de Barueri.
 * Transcribed 2026-09-29 from the official document (names kept as the source spells them).
 * GENERATED from the transcription — edit the rows by hand when the source changes.
 */
import type { Rota } from '../tipos';

export const ROTAS: Rota[] = [
  { bairros: ["Condomínio Nova Barueri", "Jd. Alberto", "Jd. Audir", "Jd. Belval", "Jd. Flórida", "Jd. Itaquiti", "Jd. Maria Cristina", "Jd. Santa Mônica", "Jd. São José", "Jd. Silveira", "Jd. Tupã", "Parque dos Camargos", "Aldeia da Serra", "Recanto Phrynéa", "Parque das Nações", "Parque Ribeiro de Lima", "Vale do Sol", "Vila Ceres", "Vila Iracema", "Vila Márcia", "Vila Militar", "Vila Nova", "Vila São Francisco", "Vila Universal"], dias: ["seg", "qua", "sex"], periodo: "diurno (a partir das 7h)", tipo: 'comum', nota: "Exceto as ruas Barão do Rio Branco, Vinte e Cinco de Janeiro, Campo de Marte, Aquário e parte da Capitão Salinas (Vila Universal), que têm coleta ter/qui/sáb." },
  { bairros: ["Alpha Conde", "Alpha Plus", "Alpha Zero", "Alpha I", "Alpha II", "Chácaras Marco", "Chácaras Valparaíso", "Conjunto Industrial Cápia", "Jd. Califórnia", "Jd. Esperança", "Jd. Graziela", "Jd. Santo Antônio", "Jd. São Silvestre", "Jd. Tupanci", "Núcleo Industrial Célia Mota", "Pq. Imperial", "Pq. Industrial Bazoli Saviano", "Recreio Cachoeira", "Vila Engenho Novo", "Vila Industrial", "Vila Morellato", "Vila Pindorama", "Vila São Luís", "Vila São Silvestre"], dias: ["ter", "qui", "sab"], periodo: "diurno (a partir das 7h)", tipo: 'comum' },
  { bairros: ["Alphaville Industrial", "Bethaville", "Centro", "Condomínio Verte Ville", "Dezoito do Forte Empresarial", "Jd. São Pedro", "Melville Empresarial", "Parque Santa Luzia", "Vila Conceição", "Vila Creti", "Vila Nilva", "Vila Osmany", "Vila Pouso Alegre", "Vila São João", "Vila São Jorge", "Vila São Miguel"], dias: ["seg", "ter", "qua", "qui", "sex", "sab"], periodo: "noturno (a partir das 19h)", tipo: 'comum' },
  { bairros: ["Aldeia de Barueri", "Jd. Ana Cristina", "Chácaras do Peroba", "Granja Militar", "Jd. Do Líbano", "Jd. Gabriela", "Jd. Iracema", "Jd. Itaparica", "Jd. Júlio", "Jd. Maria Helena", "Jd. Paulista", "Jd. San Diego", "Jd. Tatiana", "Jd. Timbauhl", "Outeiro do São Fernando", "Parque Esmeralda", "Parque Viana", "São Fernando Residencial", "Vila dos Sargentos", "Vila do Conde"], dias: ["seg", "qua", "sex"], periodo: "noturno (a partir das 19h)", tipo: 'comum' },
  { bairros: ["Centro Empresarial Jubran", "Centro Empresarial Tamboré", "Cidade Industrial Maria Elisa", "Cidade Munhoz Junior", "Fazenda Tamboré Residencial", "Jd. Barueri", "Jd. dos Camargos", "Jd. Maria Tereza", "Jd. Mutinga", "Jd. Santa Cecília", "Jd. Paraíso", "Cruz Preta", "Jd. Reginalice", "Jd. São Vicente de Paula", "Vila Barros", "Vila Boa Vista", "Vila Dom José", "Vila Porto", "Vila São Luiz", "Vila Silveira", "Vila Solaia"], dias: ["ter", "qui", "sab"], periodo: "noturno (a partir das 19h)", tipo: 'comum' },
  { bairros: ["Vila Universal"], dias: ["ter", "qui", "sab"], periodo: "diurno (a partir das 7h)", tipo: 'comum', nota: "Somente as ruas Barão do Rio Branco, Vinte e Cinco de Janeiro, Campo de Marte, Aquário e parte da Capitão Salinas." },
];
