/**
 * Coleta de lixo (Regula Ita, 2025-02) e coleta seletiva (Prefeitura de Itapevi, 2024-04).
 * Transcribed 2026-09-29 from the official document (names kept as the source spells them).
 * GENERATED from the transcription — edit the rows by hand when the source changes.
 */
import type { Rota } from '../tipos';

export const ROTAS: Rota[] = [
  { bairros: ["Divisa de São Roque", "Bloco A", "Jd Alabama", "Vila Das Flores", "Jd Cruzeiro", "Jacucai", "Jd São Judas", "Jd Dorotéia", "Jd Amador Bueno", "Jd São Benedito", "Chácaras Mont Serrat", "Chácaras Goiapá", "Estrela Dalva", "Capela Nova", "Vila Iracema", "Vila Jurema", "Jd Rute", "Chacara Angelina Mariani", "B.João Augusto R Peixoto", "Recanto Camargo Ribeiro", "Chacara Vitápolis", "Vila Olympia", "Sagrado Coração", "Quinta dos Garcias", "Takaoka", "Parque Santo Antônio", "Jardim Maristela", "Jardim Itapuã", "Jardim Paulista", "Morro do Quiabo", "Chacara Rua Primo Alpi", "Areião", "Jardim Rainha", "Parque Wey", "Bela Vista Baixa", "Bela Vista Alta", "Vale do Sol", "Parque Suburbano 2", "Rua Sergipanos", "Rua Chui", "Divisa de Cotia", "Jd Santa Rosa", "Chácara Clara", "Rua Benedito Araujo Novães", "Chácara Lucila", "Parque Miraflores", "Morada das Nuvens", "Jardim Jurema", "Rua José P. Gomes", "Rua Heloisa Hideko Koba", "Rua Ari Barroso", "Rua Ardivina Barbosa Rodrigues", "Avenida Presidente Vargas", "Rua Prof Dimaraes Antonio Sandei", "Rua Samuel Rocha Galvão", "Viaduto Santos Novaes", "Rua Geraldina Chaluppe", "Rua Felipe Challupe Filho", "Rua Prof° Irineu Chaluppe", "Travessa Claudio Chaluppe", "Rua Leopoldina de Camargo", "Rua Escolástica Chaluppe", "Rua Joaquim Nunes", "Rua Luis Manfrinato", "Rua Manoel Alves Filho", "Avenida Cezario de Abreu", "Praça Carlos de Castro", "Avenida Rubenz Caramez", "Praça Lyons Clube (18 de Fevereiro)", "Rotatória", "Estrada Lucinda de Jesus", "Rua Japurá", "Avenida Pedro Paulino", "Rua Maestro Gilberto Pinto", "Estrada da Roselandia", "Corredor Oeste", "Rod Eng Renê Benedito da Silva"], dias: ["ter", "qui", "sab"], periodo: "diurno", tipo: 'comum' },
  { bairros: ["CDHU Vila Gioia", "Vila Esperança", "Chacara Alagoinha", "Vila Belmira", "Fazenda Terra Grande", "Pesqueiro Navarro", "Estrada Yoshiro Wahashi", "Bairro Sapiantã", "Sitio Maciel", "Sitio São Benedito", "Chacara Selva da Pedra", "Condomínio Transurb", "Chacara São José", "Chacara Recanto da Paz", "Granja Carolina", "Santa Flora", "Chacara Santa Rita", "Ambuitá", "Jardim Gióia", "Chacara Cilene", "Vila Rica", "Vila Iracema Pora", "Estancia São Francisco", "Jardim São Francisco", "Vila da Chacaras", "Jardim Santo Antônio", "Jardim Santa Maria", "Sitio Jacucai Quinhão", "Vila Montolinho", "Vila Aureá", "Granja LTDA", "Residencial das Flores", "Chacara Santa Maria", "Jardim Briquet", "Chacara Santa Cecilia", "Chacara Nossa Senhora Aparecida", "Jardim Rosemary", "Rua Serra Balaiada", "Divisa de Cotia", "Rua Francisco Correia", "Parque Suburbano 1", "Rua dos Sergipanos", "Rua Chui", "Vila Aurora", "Av.Ferez Nacif Chaluppe", "Terminal Rodoviário", "Acesso ao Viaduto", "Rotatória", "Rua Geraldina Chaluppe", "Rua Felipe Chaluppe Filho", "Rua Prof° Irineu Chaluppe", "Rua Leopoldina de Camargo", "Rua Escolástica Chaluppe", "Av. Cezario de Abreu", "Av. Rubens Caramez", "Praça Carlos de Castro", "Praça Lyons Clube (18 de Fevereiro)", "Av. Pedro Paulino", "Rod Eng Renê Benedito da Silva", "Rua Prof Dimaraes Antonio Sandei", "Rua Osvaldo Francisco", "Viaduto Almerindia", "Rua Nelson Ferreira da Costa", "Estrada Lucinda de jesus", "Bairro do Itaqui", "Polo Industrial", "Nova São Paulo"], dias: ["seg", "qua", "sex"], periodo: "diurno", tipo: 'comum' },
  { bairros: ["Vila Nova Esperança", "Vila Santa Rita", "Jardim Santa Rita", "Jardim Itaguaçu", "Jardim Boa Vista", "Jardim Paetrucci", "Sitio Itaguaçu", "Jardim Itacolomi", "Jardim Marina", "Vila São Carlos", "Jardim São Carlos", "Jardim Sorocabano", "Chacara Jardim Nova Itapevi", "Cohab Setor A", "Cohab Setor B", "Vila da Paz", "Recanto da Paz", "Alto da Colina", "Cohab Luiz Belli", "Vila Licia", "Recanto Paulistano", "Cohab", "Av. Pedro Paulino", "Lazaro Toledo de Queiroz", "Hospital Geral de Itapevi", "Nova Itapevi", "Vila Olinda", "Jardim Cristianópolis", "Vila Dolores", "Vila Maria de Jesus", "Jardim Portela", "Jardim Itapevi", "Vila Aurora", "Centro de Itapevi", "Estrada Lucinda de Jesus", "Rubens Caramez", "AME"], dias: ["ter", "qui", "sab"], periodo: "noturno", tipo: 'comum' },
  { bairros: ["Bairro da Pitas", "Jardim Maria Judite", "Vila Olinda", "Parque Boa Esperança", "Jardim Santo Américo", "Vila Dona Paulina", "Jardim São Paulo", "Jardim São Luiz", "Vila Santo Antônio da Boa Vista", "Jardim Nossa Senhora de Fatima", "Jardim Hokaido", "Vila Doutor Cardoso", "Parque Ciras", "Vila Aparecida", "Vila Romina", "Vila São Francisco", "Jardim Beatriz", "Jardim Aurora", "Jardim Itaparica", "Condominio Vale do Sol", "Bairro dos Abreus", "Vila Santa Clara", "Vila São Joao", "Res Pq Itamarati", "Jardim Julieta", "Jardim Rainha", "Vila Nova Itapevi", "Vila Garcia", "Cidade da Saúde", "Jardim Vitápolis", "Jardim Dona Elvira", "Cohab", "Av. Pedro Paulino", "Lazaro Toledo de Queiroz", "Hospital Geral de Itapevi", "Nova Itapevi", "Vila Olinda", "Jardim Cristianópolis", "Vila Dolores", "Vila Maria de Jesus", "Jardim Portela", "Jardim Itapevi", "Vila Aurora", "Centro de Itapevi", "Estrada Lucinda de Jesus", "Rubens Caramez", "AME"], dias: ["seg", "qua", "sex"], periodo: "noturno", tipo: 'comum' },
  { bairros: ["Jardim São Carlos", "Rua Maria Nazaré Reis", "Av Rubens Caramez-Centro"], dias: ["seg"], periodo: "06h–16h", tipo: 'seletiva' },
  { bairros: ["Jardim Julieta", "Jardim Rainha", "Av Irineu José Chaluppe", "Av Cesario de Abreu", "Av Rubens Caramez-Centro"], dias: ["ter"], periodo: "06h–16h", tipo: 'seletiva' },
  { bairros: ["Jardim Marina", "Jardim Santa Rita", "Av Rubens Caramez- Centro"], dias: ["qua"], periodo: "06h–16h", tipo: 'seletiva' },
  { bairros: ["Vila Dr Cardoso", "Jardim Itaparica", "Vila São Francisco", "Vila Aparecida", "Av Rubens Caramez-Centro"], dias: ["qui"], periodo: "06h–16h", tipo: 'seletiva' },
  { bairros: ["Jardim Itacolomi", "Vila Santa Rita", "Av Jose Chaluppe", "Av Rubens Caramez-Centro"], dias: ["sex"], periodo: "06h–16h", tipo: 'seletiva' },
  { bairros: ["Parque Boa Esperança", "Colinas São José", "Jardim São Luis", "Jardim Hokaido", "Avenida Carolina de Abreu", "Vila Dr Cardoso", "Av Rubens Caramez-Centro"], dias: ["sab"], periodo: "06h–16h", tipo: 'seletiva' },
];
