"""SessionStore Protocol + in-memory Fake.

The ``SessionStore`` is the server-side persistence layer for human-user
auth sessions. In production (Wave 2) the real implementation is
Redis-backed, keyed by an opaque session id minted at login time, with
the Supabase refresh token stored server-side so the browser only ever
sees an HttpOnly ``Cookie: nai_session=<session_id>``.

Wave 1 (this module) ships **Protocol + Fake only** — the real Redis
adapter is owned by the consumer-side ``E-SW-AUTH`` project. See
``KB § PATTERNS/seed-fake-real-adapter.md``.
"""

from __future__ import annotations

import secrets
import time
from typing import Protocol
from uuid import UUID

from noctusai_lib.api.auth.session.types import AuthContext


class SessionStore(Protocol):
    """Server-side session-record persistence.

    Concrete implementations (Wave 2): Redis-backed
    ``RedisSessionStore``. Wave 1 ships ``FakeSessionStore`` only.

    Sessions are identified by an opaque ``session_id`` string (URL-safe
    base64-encoded random bytes) generated by ``create(...)``. The
    cookie's value IS the ``session_id``. The store maps
    ``session_id -> AuthContext`` (plus the Supabase refresh token,
    which is held server-side to refresh upstream access tokens on
    demand — never returned to callers).

    All methods are ``async`` to permit Redis transports; the Fake
    satisfies the Protocol with ``async def`` no-ops over an in-memory
    dict.
    """

    async def create(
        self,
        *,
        user_id: UUID,
        org_id: UUID,
        supabase_refresh_token: str,
        ttl_seconds: int = 86400,
    ) -> str:
        """Mint a new session and return the opaque ``session_id``.

        The default TTL is 24h (matching common session-cookie
        defaults). Wave-2 real implementations should also stamp a
        creation timestamp so an admin "kill all sessions older than
        X" sweep is possible.
        """
        ...

    async def lookup(self, session_id: str) -> AuthContext | None:
        """Resolve ``session_id`` to an ``AuthContext``.

        Returns ``None`` if the session is absent OR expired (the
        store is responsible for honouring TTL — callers should not
        have to check). Concrete implementations may also raise
        ``ExpiredSessionError`` for metric-distinguishing purposes;
        the dep treats both the same (401).
        """
        ...

    async def refresh_ttl(self, session_id: str, ttl_seconds: int = 86400) -> None:
        """Reset the session's TTL to ``ttl_seconds`` from now.

        Called by the dep on each successful auth resolution to
        implement "sliding session" semantics (active users stay
        logged in; idle sessions expire). No-op when the session is
        already absent.
        """
        ...

    async def delete(self, session_id: str) -> None:
        """Hard-delete a session (logout). No-op when absent."""
        ...


class FakeSessionStore:
    """Deterministic in-memory ``SessionStore``.

    Suitable for dev + tests; not durable across process restarts.

    TTL is honoured against ``time.monotonic()``; ``lookup`` returns
    ``None`` for expired entries and lazily evicts them. ``create``
    uses ``secrets.token_urlsafe(32)`` so session ids are
    cryptographically random even in the Fake (consumers should
    never need to "see through" the id during tests — assert via
    ``lookup`` instead).

    Tests can drive the TTL clock by passing tiny ``ttl_seconds``
    values; the implementation does NOT expose a clock-injection
    seam in v1 because the entire monotonic clock is process-local.
    """

    def __init__(self) -> None:
        # session_id -> (AuthContext, expires_at_monotonic, refresh_token)
        self._entries: dict[str, tuple[AuthContext, float, str]] = {}

    async def create(
        self,
        *,
        user_id: UUID,
        org_id: UUID,
        supabase_refresh_token: str,
        ttl_seconds: int = 86400,
    ) -> str:
        session_id = secrets.token_urlsafe(32)
        ctx = AuthContext(
            org_id=org_id,
            caller_kind="user",
            user_id=user_id,
            scopes=[],  # Wave 2 populates from user role mapping
            raw_token=session_id,
            api_token_id=None,
        )
        expires_at = time.monotonic() + ttl_seconds
        self._entries[session_id] = (ctx, expires_at, supabase_refresh_token)
        return session_id

    async def lookup(self, session_id: str) -> AuthContext | None:
        entry = self._entries.get(session_id)
        if entry is None:
            return None
        ctx, expires_at, _refresh = entry
        if time.monotonic() > expires_at:
            # Lazy eviction so the dict doesn't grow unbounded under
            # long-running test sessions.
            self._entries.pop(session_id, None)
            return None
        return ctx

    async def refresh_ttl(self, session_id: str, ttl_seconds: int = 86400) -> None:
        entry = self._entries.get(session_id)
        if entry is None:
            return
        ctx, _old_expiry, refresh = entry
        self._entries[session_id] = (
            ctx,
            time.monotonic() + ttl_seconds,
            refresh,
        )

    async def delete(self, session_id: str) -> None:
        self._entries.pop(session_id, None)


__all__ = [
    "FakeSessionStore",
    "SessionStore",
]
