"""SessionStore Protocol + in-memory Fake.

The ``SessionStore`` is the server-side persistence layer for human-user
auth sessions. In production (Wave 2) the real implementation is
Redis-backed, keyed by an opaque session id minted at login time, with
the Supabase refresh token stored server-side so the browser only ever
sees an HttpOnly ``Cookie: nai_session=<session_id>``.

Wave 1 (this module) ships **Protocol + Fake only** — the real Redis
adapter is owned by the consumer-side ``E-SW-AUTH`` project. See
``KB § PATTERNS/seed-fake-real-adapter.md``.
"""

from __future__ import annotations

import secrets
import time
from typing import NamedTuple, Protocol
from uuid import UUID

from noctusai_lib.api.auth.session.types import AuthContext, SessionTokens


class _Entry(NamedTuple):
    """In-memory session record for :class:`FakeSessionStore`.

    Mirrors the ``RedisSessionStore`` JSON record so the two stores are
    behaviourally interchangeable under the exchanger's read/write-tokens
    path. ``expires_at`` is a ``time.monotonic()`` deadline (process-local,
    dev/test only).
    """

    ctx: AuthContext
    expires_at: float
    refresh_token: str
    access_token: str | None
    access_expires_at: int | None


class SessionStore(Protocol):
    """Server-side session-record persistence.

    Concrete implementations (Wave 2): Redis-backed
    ``RedisSessionStore``. Wave 1 ships ``FakeSessionStore`` only.

    Sessions are identified by an opaque ``session_id`` string (URL-safe
    base64-encoded random bytes) generated by ``create(...)``. The
    cookie's value IS the ``session_id``. The store maps
    ``session_id -> AuthContext`` (plus the Supabase refresh token,
    which is held server-side to refresh upstream access tokens on
    demand — never returned to callers).

    All methods are ``async`` to permit Redis transports; the Fake
    satisfies the Protocol with ``async def`` no-ops over an in-memory
    dict.
    """

    async def create(
        self,
        *,
        user_id: UUID,
        org_id: UUID,
        supabase_refresh_token: str,
        ttl_seconds: int = 86400,
    ) -> str:
        """Mint a new session and return the opaque ``session_id``.

        The default TTL is 24h (matching common session-cookie
        defaults). Wave-2 real implementations should also stamp a
        creation timestamp so an admin "kill all sessions older than
        X" sweep is possible.
        """
        ...

    async def lookup(self, session_id: str) -> AuthContext | None:
        """Resolve ``session_id`` to an ``AuthContext``.

        Returns ``None`` if the session is absent OR expired (the
        store is responsible for honouring TTL — callers should not
        have to check). Concrete implementations may also raise
        ``ExpiredSessionError`` for metric-distinguishing purposes;
        the dep treats both the same (401).
        """
        ...

    async def refresh_ttl(self, session_id: str, ttl_seconds: int = 86400) -> None:
        """Reset the session's TTL to ``ttl_seconds`` from now.

        Called by the dep on each successful auth resolution to
        implement "sliding session" semantics (active users stay
        logged in; idle sessions expire). No-op when the session is
        already absent.
        """
        ...

    async def delete(self, session_id: str) -> None:
        """Hard-delete a session (logout). No-op when absent."""
        ...

    async def read_tokens(self, session_id: str) -> SessionTokens | None:
        """Return the SERVER-SIDE token bundle for a session, or ``None``.

        Unlike ``lookup`` (which returns the caller-facing ``AuthContext``
        and deliberately withholds the Supabase tokens), this hands the
        :class:`~noctusai_lib.api.auth.session.token_exchange.TokenExchanger`
        the decrypted refresh token + cached access token so it can mint an
        RLS-scoped Supabase client. NEVER call this from a route handler or
        surface its result to the browser — it exists only for the
        server-side token-exchange path.

        Returns ``None`` when the session is absent or expired (same
        semantics as ``lookup``). Real implementations decrypt at-rest
        ciphertext (SEC-3) before returning.
        """
        ...

    async def write_tokens(
        self,
        session_id: str,
        *,
        refresh_token: str,
        access_token: str | None,
        access_expires_at: int | None,
    ) -> None:
        """Persist a freshly-minted access token + rotated refresh token.

        Called by the exchanger after a successful upstream refresh (SEC-2):
        Supabase rotates the refresh token on every refresh and runs
        reuse-detection, so the rotated value MUST be written back or the
        next refresh replays a revoked token and kills the whole session
        family. The access token is cached alongside so subsequent requests
        skip the upstream call until near expiry.

        Preserves the session's existing TTL (does not extend or reset it —
        sliding-TTL is ``refresh_ttl``'s job). No-op when the session is
        absent (a race with logout/expiry — the caller re-resolves and 401s).
        Real implementations encrypt the tokens at rest (SEC-3).
        """
        ...


class FakeSessionStore:
    """Deterministic in-memory ``SessionStore``.

    Suitable for dev + tests; not durable across process restarts.

    TTL is honoured against ``time.monotonic()``; ``lookup`` returns
    ``None`` for expired entries and lazily evicts them. ``create``
    uses ``secrets.token_urlsafe(32)`` so session ids are
    cryptographically random even in the Fake (consumers should
    never need to "see through" the id during tests — assert via
    ``lookup`` instead).

    Tests can drive the TTL clock by passing tiny ``ttl_seconds``
    values; the implementation does NOT expose a clock-injection
    seam in v1 because the entire monotonic clock is process-local.
    """

    def __init__(self) -> None:
        # session_id -> _Entry (see below). The access-token cache fields
        # mirror the RedisSessionStore record so the exchanger behaves
        # identically against the Fake (dev/tests) and the Real (prod).
        self._entries: dict[str, _Entry] = {}

    async def create(
        self,
        *,
        user_id: UUID,
        org_id: UUID,
        supabase_refresh_token: str,
        ttl_seconds: int = 86400,
    ) -> str:
        session_id = secrets.token_urlsafe(32)
        ctx = AuthContext(
            org_id=org_id,
            caller_kind="user",
            user_id=user_id,
            scopes=[],  # Wave 2 populates from user role mapping
            raw_token=session_id,
            api_token_id=None,
        )
        expires_at = time.monotonic() + ttl_seconds
        self._entries[session_id] = _Entry(
            ctx=ctx,
            expires_at=expires_at,
            refresh_token=supabase_refresh_token,
            access_token=None,
            access_expires_at=None,
        )
        return session_id

    async def lookup(self, session_id: str) -> AuthContext | None:
        entry = self._get_live(session_id)
        return entry.ctx if entry is not None else None

    async def refresh_ttl(self, session_id: str, ttl_seconds: int = 86400) -> None:
        entry = self._entries.get(session_id)
        if entry is None:
            return
        self._entries[session_id] = entry._replace(
            expires_at=time.monotonic() + ttl_seconds
        )

    async def delete(self, session_id: str) -> None:
        self._entries.pop(session_id, None)

    async def read_tokens(self, session_id: str) -> SessionTokens | None:
        entry = self._get_live(session_id)
        if entry is None:
            return None
        return SessionTokens(
            refresh_token=entry.refresh_token,
            access_token=entry.access_token,
            access_expires_at=entry.access_expires_at,
        )

    async def write_tokens(
        self,
        session_id: str,
        *,
        refresh_token: str,
        access_token: str | None,
        access_expires_at: int | None,
    ) -> None:
        entry = self._entries.get(session_id)
        if entry is None:
            return  # raced with logout/expiry — no-op, matches Protocol.
        self._entries[session_id] = entry._replace(
            refresh_token=refresh_token,
            access_token=access_token,
            access_expires_at=access_expires_at,
        )

    def _get_live(self, session_id: str) -> "_Entry | None":
        """Return the entry if present and un-expired; lazily evict if aged."""
        entry = self._entries.get(session_id)
        if entry is None:
            return None
        if time.monotonic() > entry.expires_at:
            # Lazy eviction so the dict doesn't grow unbounded under
            # long-running test sessions.
            self._entries.pop(session_id, None)
            return None
        return entry


__all__ = [
    "FakeSessionStore",
    "SessionStore",
]
