-- Migration: status_pagina_dedupe
-- Generated by noctus.dev.scaffold_migration on 2026-10-01
-- Schema: community


-- ============================================================
-- Schema lock — pin name resolution to community, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = community, public;

-- Migration 009 seeded the underscore forms; the nav (App.tsx) and
-- page-status.ts use the hyphen forms (added later), leaving duplicate
-- rows in prod. Drop the unused underscore rows. Idempotent: a no-op once
-- they are gone; the hyphen rows are guaranteed present first.
INSERT INTO community.status_pagina (nome_pagina, status) VALUES
    ('whatsapp-sincronizacao', 'producao'),
    ('whatsapp-transmissoes', 'producao')
ON CONFLICT (nome_pagina) DO NOTHING;

DELETE FROM community.status_pagina
WHERE nome_pagina IN ('whatsapp_sincronizacao', 'whatsapp_transmissoes');
