-- Migration: status_pagina_moderacao
-- Generated by noctus.dev.scaffold_migration on 2026-10-01
-- Schema: community


-- ============================================================
-- Schema lock — pin name resolution to community, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = community, public;

-- Moderation queue page (/whatsapp/moderacao). Idempotent.
INSERT INTO community.status_pagina (nome_pagina, status) VALUES
    ('whatsapp-moderacao', 'producao')
ON CONFLICT (nome_pagina) DO NOTHING;
