"""``noctus.dev.certidoes_emissao_aprendizado`` — what InfoSimples really does.

social-wiring records EVERY InfoSimples certidão call in
``social_wiring.certidao_emissao_observacoes`` (migration 186) and reclassifies
failure signatures into ``certidao_emissao_aprendizados`` events (the learned
trigger behind the Receita 2ª-via fallback). This tool turns that record into
knowledge:

* ``mode='report'`` (default, READ-ONLY): per tipo — call counts, success rate,
  failure signatures with count + class (pcen / transitoria / desconhecida) +
  masked examples, cost of the fallback retries, suggested trigger changes —
  plus ``novos_aprendizados`` (classification events newer than the last
  ``sync``).
* ``mode='sync'`` (dev-side; the caller commits the result): idempotently
  regenerates (a) the ``[observado]`` entries of the sidecar
  ``certidoes/infosimples.knowledge.yaml`` (build-learn-cache mindset —
  known_facts / errors_encountered / drifts_surfaced) and (b) the
  "Comportamento observado (vs documentação oficial)" section of
  ``KNOWLEDGE-BASE/CONTEXT/INTEGRATIONS/infosimples-certidoes.md`` between its
  BEGIN/END markers. Output is derived ONLY from the data (no wall-clock), so a
  re-run on unchanged data writes nothing (``changed=False``).

The classification logic is NOT re-implemented here: this module loads the
product's own pure ``aprendizado.py`` by path, so the report can never drift
from what the product acts on.

Credentials: the same SqlExecutor seam as ``noctus.dev.schema_drift`` (Supabase
Management API, PAT resolved DB-first); none ⇒ ``not_configured`` (never a
faked empty report). No PII is read: observations store no token/name/document
(only an HMAC key).

KB § INTEGRATIONS/infosimples-certidoes.md · KB § PATTERNS/common/build-learn-cache-mindset.md.
"""
from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path
from typing import Any, Optional

import yaml

from . import migrate_product as _mp

_APRENDIZADO_REL = "products/social-wiring/backend/app/modules/certidoes/aprendizado.py"
SIDECAR_REL = "products/social-wiring/backend/app/modules/certidoes/infosimples.knowledge.yaml"
KB_REL = "KNOWLEDGE-BASE/CONTEXT/INTEGRATIONS/infosimples-certidoes.md"
BEGIN = "<!-- BEGIN observed-behaviour (generated by noctus.dev.certidoes_emissao_aprendizado) -->"
END = "<!-- END observed-behaviour -->"
PREFIXO = "[observado] "
LIMITE_LINHAS = 20000

_OBS_SQL = (
    "SELECT id, org_id, tipo, sucesso, assinatura, preferencia_emissao, fallback_de, "
    "data_tipo, documento_hash, created_at, tentativa, code, code_message, errors, "
    "price_brl, billable, validade FROM social_wiring.certidao_emissao_observacoes "
    f"ORDER BY created_at LIMIT {LIMITE_LINHAS};"
)
_EVT_SQL = (
    "SELECT org_id, tipo, assinatura, classe, classe_anterior, evidencia, "
    "primeira_obs_em, ultima_obs_em, decidido_em "
    "FROM social_wiring.certidao_emissao_aprendizados ORDER BY decidido_em;"
)


def _carregar_aprendizado(root: Path):
    """The product's pure module, loaded by path (stdlib-only by contract)."""
    path = root / _APRENDIZADO_REL
    spec = importlib.util.spec_from_file_location("_sw_certidoes_aprendizado", path)
    if spec is None or spec.loader is None:  # pragma: no cover
        raise ImportError(f"cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _ts(valor: Any) -> str:
    return str(valor or "")


def _sidecar(root: Path) -> dict:
    p = root / SIDECAR_REL
    if not p.exists():
        return {}
    return yaml.safe_load(p.read_text(encoding="utf-8")) or {}


def _novos(eventos: list[dict], desde: str) -> list[dict]:
    return [
        {k: e.get(k) for k in ("tipo", "assinatura", "classe", "classe_anterior", "evidencia", "decidido_em")}
        for e in eventos if _ts(e.get("decidido_em")) > desde
    ]


def _ultimos(eventos: list[dict]) -> list[dict]:
    """Latest event per (org, tipo, assinatura) — the class in force."""
    out: dict[tuple, dict] = {}
    for e in sorted(eventos, key=lambda e: _ts(e.get("decidido_em"))):
        out[(e.get("org_id"), e.get("tipo"), e.get("assinatura"))] = e
    return list(out.values())


# ---------------------------------------------------------------------------
# generated knowledge (pure, deterministic)
# ---------------------------------------------------------------------------


def _entradas_sidecar(relatorio: dict, vigentes: list[dict]) -> dict[str, list]:
    facts: list[str] = []
    errors: list[dict] = []
    drifts: list[dict] = []
    for tipo, t in sorted(relatorio["tipos"].items()):
        taxa = t["taxa_sucesso"]
        facts.append(
            f"{PREFIXO}{tipo}: {t['chamadas']} chamadas, {t['sucessos']} com sucesso"
            f" ({'—' if taxa is None else f'{taxa:.0%}'}); {t['retries_2via']} retentativas 2ª via"
            f" (R$ {t['custo_retries_brl']})."
        )
    for e in sorted(vigentes, key=lambda e: (e["tipo"], e["assinatura"])):
        ev = e.get("evidencia") or {}
        quando = _ts(e.get("decidido_em"))[:10]
        if e["classe"] == "pcen":
            drifts.append({
                "drift": f"{PREFIXO}{e['tipo']}: a documentação da InfoSimples não dá código/mensagem para a recusa de "
                         f"emissão nova (PCEN); observado: assinatura '{e['assinatura']}' seguida de 2ª via PCEN "
                         f"({ev.get('pcen', '?')} casos).",
                "surfaced_during": "emission watcher", "resolved": True,
                "resolution": f"gatilho aprendido em {quando}: pede 2ª via",
            })
        elif e["classe"] == "transitoria":
            errors.append({
                "when": quando,
                "error": f"{PREFIXO}{e['tipo']}: assinatura '{e['assinatura']}' é transitória "
                         f"({ev.get('transitoria', '?')} casos: a 2ª via também falhou ou a nova voltou a funcionar).",
                "resolution": "gatilho aprendido: não repete a chamada como 2ª via (economiza a chamada cobrada)",
                "avoidable_by": "não tratar essa falha como PCEN",
            })
    return {"known_facts": facts, "errors_encountered": errors, "drifts_surfaced": drifts}


def _markdown(relatorio: dict, vigentes: list[dict]) -> str:
    linhas = [
        "Gerado a partir de `certidao_emissao_observacoes` / `certidao_emissao_aprendizados` "
        "(`noctus.dev.certidoes_emissao_aprendizado mode=sync`). Não editar à mão.",
        "",
        f"Observações analisadas: **{relatorio['total_observacoes']}** "
        f"(limiar de confirmação: {relatorio['limiar_confirmacao']}, margem: {relatorio['margem_confirmacao']}×).",
        "",
    ]
    if not relatorio["tipos"]:
        linhas.append("_Ainda sem observações._")
    for tipo, t in sorted(relatorio["tipos"].items()):
        taxa = "—" if t["taxa_sucesso"] is None else f"{t['taxa_sucesso']:.0%}"
        linhas += [
            f"### `{tipo}`",
            "",
            f"- Chamadas: {t['chamadas']} · sucesso: {t['sucessos']} ({taxa}) · emissões PCEN: {t['emissoes_pcen']}",
            f"- Retentativas 2ª via: {t['retries_2via']} (sem sucesso: {t['retries_2via_sem_sucesso']}) · "
            f"custo: R$ {t['custo_retries_brl']} (sem sucesso: R$ {t['custo_retries_sem_sucesso_brl']})",
        ]
        if t["assinaturas_de_falha"]:
            linhas += ["", "| Assinatura da falha | Ocorrências | Classe |", "|---|---:|---|"]
            for s in t["assinaturas_de_falha"]:
                linhas.append(f"| `{s['assinatura']}` | {s['ocorrencias']} | {s['classe']} |")
        linhas.append("")
    if vigentes:
        linhas += ["### Aprendizados em vigor", ""]
        for e in sorted(vigentes, key=lambda e: (e["tipo"], e["assinatura"])):
            linhas.append(
                f"- `{e['tipo']}` · `{e['assinatura']}` → **{e['classe']}** "
                f"(desde {_ts(e.get('decidido_em'))[:10]})"
            )
        linhas.append("")
    if relatorio["sugestoes"]:
        linhas += ["### Sugestões", ""] + [f"- {s}" for s in relatorio["sugestoes"]] + [""]
    return "\n".join(linhas).rstrip() + "\n"


def _substituir_regiao(texto: str, novo: str) -> str:
    bloco = f"{BEGIN}\n{novo}{END}"
    padrao = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if padrao.search(texto):
        return padrao.sub(lambda _m: bloco, texto)
    return texto.rstrip("\n") + "\n\n" + bloco + "\n"


def _mesclar_sidecar(atual: dict, gerado: dict[str, list], ate: str) -> dict:
    novo = dict(atual)
    for campo, entradas in gerado.items():
        chave = "drift" if campo == "drifts_surfaced" else ("error" if campo == "errors_encountered" else None)
        manuais = []
        for item in atual.get(campo) or []:
            texto = item if isinstance(item, str) else str(item.get(chave, ""))
            if not texto.startswith(PREFIXO):
                manuais.append(item)
        novo[campo] = manuais + entradas
    novo["aprendizados_ate"] = ate
    return novo


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------


def certidoes_emissao_aprendizado(
    mode: str = "report",
    *,
    executor: "_mp.SqlExecutor | None" = None,
    repo_root: Optional[Path] = None,
    project_ref: str = "nyplttplcoyiiqjrvtiw",
    worktree_path: Optional[str] = None,
) -> dict[str, Any]:
    """See module docstring. Never raises — every failure is a typed ``status``."""

    def _res(status: str, **kw: Any) -> dict[str, Any]:
        base: dict[str, Any] = {
            "ok": status in ("ok", "synced", "unchanged"), "status": status, "mode": mode,
            "observacoes": 0, "relatorio": None, "novos_aprendizados": [],
            "aprendizados_ate": None, "wrote": [], "changed": False, "error": None,
        }
        base.update(kw)
        return base

    if mode not in ("report", "sync"):
        return _res("error", error=f"unknown mode {mode!r} (report | sync)")
    try:
        if repo_root is None:
            from workspace import resolve_caller_root
            repo_root = resolve_caller_root(worktree_path)
        ap = _carregar_aprendizado(repo_root)
    except Exception as exc:  # noqa: BLE001 — typed status, never raises
        return _res("error", error=f"cannot load aprendizado module: {exc}")

    if executor is None:
        executor = _mp.make_sql_executor(project_ref=project_ref)
    if executor is None:
        return _res(
            "not_configured",
            error="NOC-REMEDIATE[credentials]: no supabase_access_token resolved — cannot read "
                  "the observations. Same resolution path as noctus.dev.migrate_product.",
        )
    obs_r = executor.execute(_OBS_SQL)
    if not obs_r.get("ok"):
        return _res("error", error="could not read certidao_emissao_observacoes: " + str(obs_r.get("error")))
    evt_r = executor.execute(_EVT_SQL)
    if not evt_r.get("ok"):
        return _res("error", error="could not read certidao_emissao_aprendizados: " + str(evt_r.get("error")))
    observacoes = obs_r.get("rows") or []
    eventos = evt_r.get("rows") or []
    for o in observacoes:  # PostgREST/Mgmt API hands JSONB back parsed, but be safe
        if isinstance(o.get("errors"), str):
            try:
                o["errors"] = json.loads(o["errors"])
            except ValueError:
                o["errors"] = []

    relatorio = ap.relatorio(observacoes)
    vigentes = _ultimos(eventos)
    ate = max((_ts(e.get("decidido_em")) for e in eventos), default="")
    sidecar = _sidecar(repo_root)
    desde = _ts(sidecar.get("aprendizados_ate"))
    novos = _novos(eventos, desde)

    if mode == "report":
        return _res("ok", observacoes=len(observacoes), relatorio=relatorio,
                    novos_aprendizados=novos, aprendizados_ate=ate or None)

    # ---- sync (idempotent, deterministic) ----
    try:
        gerado = _entradas_sidecar(relatorio, vigentes)
        novo_sidecar = _mesclar_sidecar(sidecar, gerado, ate)
        sidecar_path = repo_root / SIDECAR_REL
        sidecar_txt = yaml.safe_dump(novo_sidecar, allow_unicode=True, sort_keys=False, width=100)
        kb_path = repo_root / KB_REL
        kb_atual = kb_path.read_text(encoding="utf-8") if kb_path.exists() else ""
        if not kb_atual:
            return _res("error", error=f"{KB_REL} does not exist — it carries the generated section markers",
                        observacoes=len(observacoes))
        kb_novo = _substituir_regiao(kb_atual, _markdown(relatorio, vigentes))
        wrote: list[str] = []
        if not sidecar_path.exists() or sidecar_path.read_text(encoding="utf-8") != sidecar_txt:
            sidecar_path.write_text(sidecar_txt, encoding="utf-8")
            wrote.append(SIDECAR_REL)
        if kb_novo != kb_atual:
            kb_path.write_text(kb_novo, encoding="utf-8")
            wrote.append(KB_REL)
    except OSError as exc:
        return _res("error", error=f"could not write the sidecar/KB: {exc}", observacoes=len(observacoes))
    return _res(
        "synced" if wrote else "unchanged", observacoes=len(observacoes), relatorio=relatorio,
        novos_aprendizados=novos, aprendizados_ate=ate or None, wrote=wrote, changed=bool(wrote),
    )


def register(server) -> None:
    @server.tool(
        name="noctus.dev.certidoes_emissao_aprendizado",
        description=(
            "What InfoSimples REALLY does with certidão emissions (vs its docs): reads the "
            "social-wiring emission watcher (certidao_emissao_observacoes + certidao_emissao_"
            "aprendizados, migration 186) via the Supabase Management API and returns, per "
            "tipo, call counts, success rate, failure signatures (count, class pcen/"
            "transitoria/desconhecida, masked examples), the cost of 2ª-via retries, suggested "
            "trigger changes, and 'novos_aprendizados' since the last sync. mode='report' "
            "(default) is read-only; mode='sync' idempotently regenerates the [observado] "
            "entries of certidoes/infosimples.knowledge.yaml and the 'Comportamento observado' "
            "section of KB INTEGRATIONS/infosimples-certidoes.md (dev-side files — commit the "
            "result). Pass worktree_path from inside a git worktree. No PAT ⇒ not_configured. "
            "KB § INTEGRATIONS/infosimples-certidoes.md."
        ),
    )
    def _certidoes_emissao_aprendizado(
        mode: str = "report",
        project_ref: str = "nyplttplcoyiiqjrvtiw",
        worktree_path: Optional[str] = None,
    ) -> dict:
        return certidoes_emissao_aprendizado(mode, project_ref=project_ref, worktree_path=worktree_path)


__all__ = ["certidoes_emissao_aprendizado", "register", "SIDECAR_REL", "KB_REL", "BEGIN", "END"]
