"""noctus.dev.stamp_seed_version — native port of scripts/stamp-seed-version.sh.

Writes the current git short SHA into the seed packages'
``_version_static.py`` files. Each seed consumer reads this at
import-time via ``noctusai_seed.__seed_version__`` /
``noctusai_lib.__lib_version__``. The keeper detector
``check_seed_version_propagation`` compares the stamped value to current
``git rev-parse --short HEAD`` to surface drift.

Behaviour-preserving: identical file BODY (byte-for-byte, including the
``unknown`` fallback when ``git rev-parse --short HEAD`` fails) and the
same two targets:

  * seed/framework/backend/noctusai_seed/_version_static.py
  * seed/lib/backend/noctusai_lib/_version_static.py

Exit-code parity: the shell exits 1 only when git is unavailable
(no toplevel) — surfaced here as ``ok=False`` with ``stamped=False``.
"""
from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

_STAMP_TEMPLATE = (
    "# Auto-generated by scripts/stamp-seed-version.sh.\n"
    "# Reflects git HEAD at stamp time. DO NOT edit by hand.\n"
    "# Re-stamp: run scripts/stamp-seed-version.sh (or commit again — pre-commit does it).\n"
    '__version__ = "{sha}"\n'
)

_TARGETS = [
    ("seed/framework/backend/noctusai_seed/_version_static.py", "noctusai_seed"),
    ("seed/lib/backend/noctusai_lib/_version_static.py", "noctusai_lib"),
]


def stamp_seed_version() -> dict[str, Any]:
    """Stamp the current short SHA into both seed _version_static.py files.

    Returns ``{ok, stamped, sha, files, message}``.
    """
    try:
        proc = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
        )
        repo_root = proc.stdout.strip() if proc.returncode == 0 else ""
    except OSError:
        repo_root = ""

    if not repo_root:
        return {
            "ok": False,
            "stamped": False,
            "sha": None,
            "files": [],
            "message": "[stamp-seed-version] git not available — skipping stamp.",
        }

    root = Path(repo_root)
    try:
        sha_proc = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
        )
        sha = sha_proc.stdout.strip() if sha_proc.returncode == 0 else "unknown"
    except OSError:
        sha = "unknown"
    if not sha:
        sha = "unknown"

    body = _STAMP_TEMPLATE.format(sha=sha)
    written: list[str] = []
    messages: list[str] = []
    for rel, package_name in _TARGETS:
        target = root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
        written.append(rel)
        messages.append(f"[stamp-seed-version] {package_name} stamped: {sha}")

    return {
        "ok": True,
        "stamped": True,
        "sha": sha,
        "files": written,
        "message": "\n".join(messages),
    }


def register(server) -> None:
    @server.tool(
        name="noctus.dev.stamp_seed_version",
        description=(
            "Native stamp of the current git short SHA into the two seed "
            "_version_static.py files (no shell subprocess; ports "
            "scripts/stamp-seed-version.sh byte-for-byte). Keeps the "
            "check_seed_version_propagation keeper honest. Idempotent; "
            "output is gitignored. Pre-commit invokes this every commit."
        ),
    )
    def _stamp_seed_version() -> dict:
        return stamp_seed_version()


__all__ = ["stamp_seed_version", "register"]
