"""noctus.dev.stamp_seed_version — native port of scripts/stamp-seed-version.sh.

Writes both the current git short SHA and the SemVer (from `/VERSION`) into
the seed packages' ``_version_static.py`` files. Each seed consumer reads
this at import-time via ``noctusai_seed.__seed_version__`` /
``noctusai_lib.__lib_version__`` (the SHA — keeper compatibility) and via
``noctusai_seed.__semver__`` / ``noctusai_lib.__semver__`` (the SemVer —
the v4.0+ surface). The keeper ``check_seed_version_propagation`` compares
the stamped SHA to current ``git rev-parse --short HEAD`` to surface drift.

Two targets stamped (gitignored output):
  * seed/framework/backend/noctusai_seed/_version_static.py
  * seed/lib/backend/noctusai_lib/_version_static.py

Behaviour-preserving: ``__version__ = "<sha>"`` still ships (keeper contract
unchanged). The NEW ``__semver__`` line is additive — reads `/VERSION` (the
single source of truth per KB § PATTERNS/common/versioning.md) and stamps
it alongside. Missing/empty VERSION falls back to ``unknown`` (same shape as
the SHA fallback).

Exit-code parity: ``ok=False`` only when git is unavailable.
"""
from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

_STAMP_TEMPLATE = (
    "# Auto-generated by noctus.dev.stamp_seed_version (formerly scripts/stamp-seed-version.sh).\n"
    "# Reflects git HEAD + /VERSION at stamp time. DO NOT edit by hand.\n"
    "# Re-stamp: noctus.dev.stamp_seed_version (or commit again — pre-commit does it).\n"
    '__version__ = "{sha}"\n'
    '__semver__ = "{semver}"\n'
)

_TARGETS = [
    ("seed/framework/backend/noctusai_seed/_version_static.py", "noctusai_seed"),
    ("seed/lib/backend/noctusai_lib/_version_static.py", "noctusai_lib"),
]


def _read_semver(root: Path) -> str:
    """Read /VERSION at repo root. Single line, trimmed. `unknown` on miss."""
    version_file = root / "VERSION"
    if not version_file.exists():
        return "unknown"
    try:
        semver = version_file.read_text(encoding="utf-8").strip()
    except OSError:
        return "unknown"
    return semver or "unknown"


def stamp_seed_version() -> dict[str, Any]:
    """Stamp current short SHA + /VERSION SemVer into both seed _version_static.py.

    Returns ``{ok, stamped, sha, semver, files, message}``.
    """
    try:
        proc = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
        )
        repo_root = proc.stdout.strip() if proc.returncode == 0 else ""
    except OSError:
        repo_root = ""

    if not repo_root:
        return {
            "ok": False,
            "stamped": False,
            "sha": None,
            "semver": None,
            "files": [],
            "message": "[stamp-seed-version] git not available — skipping stamp.",
        }

    root = Path(repo_root)
    try:
        sha_proc = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
        )
        sha = sha_proc.stdout.strip() if sha_proc.returncode == 0 else "unknown"
    except OSError:
        sha = "unknown"
    if not sha:
        sha = "unknown"

    semver = _read_semver(root)

    body = _STAMP_TEMPLATE.format(sha=sha, semver=semver)
    written: list[str] = []
    messages: list[str] = []
    for rel, package_name in _TARGETS:
        target = root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
        written.append(rel)
        messages.append(f"[stamp-seed-version] {package_name} stamped: sha={sha} semver={semver}")

    return {
        "ok": True,
        "stamped": True,
        "sha": sha,
        "semver": semver,
        "files": written,
        "message": "\n".join(messages),
    }


def register(server) -> None:
    @server.tool(
        name="noctus.dev.stamp_seed_version",
        description=(
            "Native stamp of the current git short SHA AND /VERSION SemVer into "
            "the two seed _version_static.py files. Keeps the "
            "check_seed_version_propagation keeper honest (the SHA contract) "
            "AND ships the SemVer (the v4.0+ surface — readable as "
            "noctusai_seed.__semver__ / noctusai_lib.__semver__). Idempotent; "
            "output is gitignored. Pre-commit invokes this every commit."
        ),
    )
    def _stamp_seed_version() -> dict:
        return stamp_seed_version()


__all__ = ["stamp_seed_version", "register"]
