"""
NoctusAI Therapy Platform — FastAPI Backend

Entry point for the API server.
Run with: uvicorn app.main:app --reload --port 8003
"""
from noctusai_seed import create_product_app
from app.config import settings
from app.rate_limit import limiter
from app.routers import (
    admin,
    admin_financials,
    anamnese,
    appointments,
    attachments,
    auth,
    availability,
    clinic_financials,
    clinics,
    crisis,
    dashboard_bi,
    evolution_notes,
    homework,
    invitations,
    invoices,
    lgpd,
    longitudinal,
    messaging,
    mood,
    observations,
    patient_notes,
    patients,
    payments,
    recurring,
    refunds,
    reviews,
    rooms,
    session_journal,
    sessions,
    settings as settings_router,
    support,
    therapeutic_journal,
    therapists,
    therapy_matching,
    transactions,
    wallets,
    whatsapp_therapy,
    treatment_plans,
)

app = create_product_app(
    name="Therapy Platform",
    schema="therapy",
    settings=settings,
    routers=[
        auth.router,
        therapists.router,
        patients.router,
        clinics.router,
        reviews.router,
        admin.router,
        availability.router,
        appointments.router,
        recurring.router,
        sessions.router,
        observations.router,
        patient_notes.router,
        session_journal.router,
        longitudinal.router,
        wallets.router,
        payments.router,
        transactions.router,
        clinic_financials.router,
        admin_financials.router,
        refunds.router,
        messaging.router,
        support.router,
        attachments.router,
        settings_router.router,
        lgpd.router,
        anamnese.router,
        treatment_plans.router,
        evolution_notes.router,
        mood.router,
        therapeutic_journal.router,
        homework.router,
        rooms.router,
        therapy_matching.router,
        invoices.router,
        dashboard_bi.router,
        whatsapp_therapy.router,
        crisis.router,
        invitations.router,
    ],
    version="0.1.0",
    limiter=limiter,
)
