# Generated by Django 4.2.9 on 2026-01-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zona',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='zona',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
