# Generated by Django 4.2.1 on 2024-02-17 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proprietario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermutaImovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corretor", models.CharField(max_length=20)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("a", "Apartamento"), ("c", "Casa"), ("t", "Terreno")],
                        max_length=1,
                    ),
                ),
                ("condominio", models.CharField(max_length=50)),
                (
                    "zona",
                    models.CharField(
                        choices=[
                            ("n", "Norte"),
                            ("s", "Sul"),
                            ("l", "Leste"),
                            ("o", "Oeste"),
                        ],
                        max_length=1,
                    ),
                ),
                ("cep", models.CharField(max_length=20)),
                ("estado", models.CharField(max_length=2)),
                ("cidade", models.CharField(max_length=50)),
                ("bairro", models.CharField(max_length=50)),
                ("endereco", models.CharField(max_length=100)),
                ("numero", models.PositiveIntegerField(blank=True, null=True)),
                ("valor", models.PositiveIntegerField()),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="proprietario.proprietario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PermutaAutomovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corretor", models.CharField(max_length=20)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("c", "Carro"), ("m", "Moto"), ("s", "SUV")],
                        max_length=1,
                    ),
                ),
                ("marca", models.CharField(max_length=20)),
                ("modelo", models.CharField(max_length=20)),
                (
                    "motor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("g", "Gasolina"),
                            ("a", "Álcool"),
                            ("f", "Flex"),
                            ("e", "Elétrico"),
                            ("h", "Híbrido"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("valor", models.PositiveIntegerField()),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proprietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="proprietario.proprietario",
                    ),
                ),
            ],
        ),
    ]
