# Generated by Django 4.2.9 on 2026-01-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permutaautomovel',
            name='corretor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='permutaautomovel',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='permutaautomovel',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='permutaautomovel',
            name='motor',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='permutaautomovel',
            name='tipo',
            field=models.CharField(choices=[('c', 'Carro'), ('m', 'Moto'), ('cm', 'Caminhão')], max_length=2),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='condominio',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='corretor',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='tipo',
            field=models.CharField(choices=[('a', 'Apartamento'), ('c', 'Casa'), ('t', 'Terreno'), ('ch', 'Chácara'), ('co', 'Comercial')], max_length=2),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='zona',
            field=models.CharField(blank=True, choices=[('n', 'Norte'), ('s', 'Sul'), ('l', 'Leste'), ('o', 'Oeste')], default='', max_length=1),
        ),
    ]
