# Generated by Django 4.2.9 on 2026-01-10 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imovel', '0009_add_codigo_and_match'),
        ('permuta', '0002_alter_permutaautomovel_corretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permutaautomovel',
            name='codigo',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='permutaimovel',
            name='codigo',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('etapa_do_funil', models.CharField(choices=[('gerado', 'Gerado'), ('contato', 'Contato Inicial'), ('proposta', 'Proposta Enviada'), ('negociacao', 'Em Negociação'), ('concluido', 'Concluído'), ('perdido', 'Perdido')], default='gerado', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_criados', to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='imovel.imovel')),
                ('interesse_automovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='imovel.interesseautomovel')),
                ('interesse_imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='imovel.interesseimovel')),
                ('permuta_automovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='permuta.permutaautomovel')),
                ('permuta_imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='permuta.permutaimovel')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-criado_em'],
            },
        ),
    ]
