# Generated by Django 4.2.9 on 2026-01-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuta', '0003_add_codigo_and_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='etapa_do_funil',
            field=models.CharField(choices=[('novo', 'Novo Match'), ('avaliacao', 'Avaliação'), ('negociacao', 'Negociação'), ('fechado', 'Fechado')], default='novo', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('permuta_imovel__isnull', False)), fields=('imovel', 'permuta_imovel'), name='unique_imovel_permuta_imovel'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('permuta_automovel__isnull', False)), fields=('imovel', 'permuta_automovel'), name='unique_imovel_permuta_automovel'),
        ),
    ]
