# Generated by Django 4.2.9 on 2026-01-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuta', '0004_update_match_etapas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['ordem', '-criado_em'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='condominio',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
