# Generated by Django 4.2.9 on 2026-01-13 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_automovel', '0001_initial'),
        ('tipo_imovel', '0001_initial'),
        ('zona', '0002_remove_codigo_field'),
        ('permuta', '0005_add_ordem_to_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permutaautomovel',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_automovel.tipoautomovel'),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_imovel.tipoimovel'),
        ),
        migrations.AlterField(
            model_name='permutaimovel',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zona.zona'),
        ),
    ]
