# Generated by Django 4.2.9 on 2026-01-13 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0011_add_zona_to_imovel'),
        ('permuta', '0006_alter_permutaautomovel_tipo_alter_permutaimovel_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='imovel_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_match', to='imovel.imovel'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('imovel_match__isnull', False)), fields=('imovel', 'imovel_match'), name='unique_imovel_imovel_match'),
        ),
    ]
