# Generated by Django 4.2.9 on 2026-01-13 22:22

from django.db import migrations, models
import django.db.models.deletion


def clear_corretor_strings(apps, schema_editor):
    PermutaImovel = apps.get_model('permuta', 'PermutaImovel')
    PermutaAutomovel = apps.get_model('permuta', 'PermutaAutomovel')
    db_alias = schema_editor.connection.alias
    PermutaImovel.objects.using(db_alias).update(corretor='')
    PermutaAutomovel.objects.using(db_alias).update(corretor='')


class Migration(migrations.Migration):

    dependencies = [
        ('corretor', '0001_initial'),
        ('permuta', '0007_add_imovel_match_to_match'),
    ]

    operations = [
        migrations.RunPython(clear_corretor_strings, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='permutaautomovel',
            name='corretor',
        ),
        migrations.RemoveField(
            model_name='permutaimovel',
            name='corretor',
        ),
        migrations.AddField(
            model_name='permutaautomovel',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corretor.corretor'),
        ),
        migrations.AddField(
            model_name='permutaimovel',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corretor.corretor'),
        ),
    ]
