# Generated by Django 4.2.9 on 2026-01-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuta', '0008_alter_permutaautomovel_corretor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permutaautomovel',
            options={'verbose_name': 'Permuta de Automóvel', 'verbose_name_plural': 'Permutas de Automóveis'},
        ),
        migrations.AlterModelOptions(
            name='permutaimovel',
            options={'verbose_name': 'Permuta de Imóvel', 'verbose_name_plural': 'Permutas de Imóveis'},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['imovel'], name='permuta_mat_imovel__ab11b1_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['etapa_do_funil'], name='permuta_mat_etapa_d_b2e2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['etapa_do_funil', 'ordem'], name='permuta_mat_etapa_d_420274_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['-criado_em'], name='permuta_mat_criado__c79e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaautomovel',
            index=models.Index(fields=['tipo'], name='permuta_per_tipo_id_b26664_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaautomovel',
            index=models.Index(fields=['valor'], name='permuta_per_valor_23c9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaautomovel',
            index=models.Index(fields=['corretor'], name='permuta_per_correto_ebe6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaautomovel',
            index=models.Index(fields=['marca', 'modelo'], name='permuta_per_marca_a2b855_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaimovel',
            index=models.Index(fields=['tipo', 'zona'], name='permuta_per_tipo_id_6069b3_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaimovel',
            index=models.Index(fields=['valor'], name='permuta_per_valor_e7510b_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaimovel',
            index=models.Index(fields=['corretor'], name='permuta_per_correto_30cb45_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaimovel',
            index=models.Index(fields=['estado', 'cidade'], name='permuta_per_estado_6c4074_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('imovel_match__isnull', True), ('permuta_automovel__isnull', True), ('permuta_imovel__isnull', False)), models.Q(('imovel_match__isnull', True), ('permuta_automovel__isnull', False), ('permuta_imovel__isnull', True)), models.Q(('imovel_match__isnull', False), ('permuta_automovel__isnull', True), ('permuta_imovel__isnull', True)), _connector='OR'), name='match_exactly_one_source'),
        ),
    ]
