# Generated by Django 4.2.9 on 2026-01-26 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zona', '0002_remove_codigo_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipo_imovel', '0001_initial'),
        ('permuta', '0009_alter_permutaautomovel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteressePermutaImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, default='', max_length=20)),
                ('estado', models.CharField(blank=True, default='', max_length=50)),
                ('cidade', models.CharField(blank=True, default='', max_length=50)),
                ('bairro', models.CharField(blank=True, default='', max_length=50)),
                ('endereco', models.CharField(blank=True, default='', max_length=100)),
                ('valor_minimo', models.PositiveIntegerField(blank=True, help_text='Valor mínimo aceito (null = sem mínimo)', null=True)),
                ('valor_maximo', models.PositiveIntegerField(blank=True, help_text='Valor máximo aceito (null = sem máximo)', null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('permuta_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_permuta', to='permuta.permutaimovel')),
                ('tipo_imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_imovel.tipoimovel', verbose_name='Tipo de Imóvel Desejado')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zona.zona', verbose_name='Zona Desejada')),
            ],
            options={
                'verbose_name': 'Interesse de Permuta - Imóvel',
                'verbose_name_plural': 'Interesses de Permuta - Imóveis',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['permuta_imovel'], name='permuta_int_permuta_1e624b_idx'), models.Index(fields=['tipo_imovel', 'zona'], name='permuta_int_tipo_im_88627c_idx'), models.Index(fields=['valor_minimo', 'valor_maximo'], name='permuta_int_valor_m_fb7b64_idx')],
            },
        ),
        migrations.CreateModel(
            name='InteressePermutaAutomovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, default='', max_length=20)),
                ('estado', models.CharField(blank=True, default='', max_length=50)),
                ('cidade', models.CharField(blank=True, default='', max_length=50)),
                ('bairro', models.CharField(blank=True, default='', max_length=50)),
                ('endereco', models.CharField(blank=True, default='', max_length=100)),
                ('valor_minimo', models.PositiveIntegerField(blank=True, help_text='Valor mínimo aceito (null = sem mínimo)', null=True)),
                ('valor_maximo', models.PositiveIntegerField(blank=True, help_text='Valor máximo aceito (null = sem máximo)', null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('permuta_automovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_permuta', to='permuta.permutaautomovel')),
                ('tipo_imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_imovel.tipoimovel', verbose_name='Tipo de Imóvel Desejado')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zona.zona', verbose_name='Zona Desejada')),
            ],
            options={
                'verbose_name': 'Interesse de Permuta - Automóvel',
                'verbose_name_plural': 'Interesses de Permuta - Automóveis',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['permuta_automovel'], name='permuta_int_permuta_1d4185_idx'), models.Index(fields=['tipo_imovel', 'zona'], name='permuta_int_tipo_im_e67d99_idx'), models.Index(fields=['valor_minimo', 'valor_maximo'], name='permuta_int_valor_m_3512c5_idx')],
            },
        ),
    ]
