# Generated by Django 4.2.9 on 2026-01-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuta', '0010_create_interesse_permuta_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_bilateral',
            field=models.BooleanField(default=False, help_text='True if match was created by bilateral matching system'),
        ),
    ]
