# Generated by Django 4.2.9 on 2026-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuta', '0011_add_is_bilateral_to_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permutaautomovel',
            options={'ordering': ['-id'], 'verbose_name': 'Permuta de Automóvel', 'verbose_name_plural': 'Permutas de Automóveis'},
        ),
        migrations.AlterModelOptions(
            name='permutaimovel',
            options={'ordering': ['-id'], 'verbose_name': 'Permuta de Imóvel', 'verbose_name_plural': 'Permutas de Imóveis'},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['codigo'], name='permuta_mat_codigo_5d1510_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['permuta_imovel'], name='permuta_mat_permuta_1e9908_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['permuta_automovel'], name='permuta_mat_permuta_e2a748_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['is_bilateral'], name='permuta_mat_is_bila_1d7e72_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaautomovel',
            index=models.Index(fields=['codigo'], name='permuta_per_codigo_8de48d_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaautomovel',
            index=models.Index(fields=['proprietario'], name='permuta_per_proprie_c09b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaimovel',
            index=models.Index(fields=['codigo'], name='permuta_per_codigo_c1dd06_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaimovel',
            index=models.Index(fields=['bairro'], name='permuta_per_bairro_da3347_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaimovel',
            index=models.Index(fields=['cidade'], name='permuta_per_cidade_69aa3a_idx'),
        ),
        migrations.AddIndex(
            model_name='permutaimovel',
            index=models.Index(fields=['proprietario'], name='permuta_per_proprie_2c6e8d_idx'),
        ),
    ]
