# Generated by Django 4.2.9 on 2026-01-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuta', '0012_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='permutaimovel',
            name='ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
