# Generated by Django 4.2.9 on 2026-02-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permuta', '0013_permutaimovel_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='etapa_do_funil',
            field=models.CharField(choices=[('novo', 'Novo Match'), ('avaliacao', 'Avaliação'), ('negociacao', 'Negociação'), ('fechado', 'Fechado'), ('rejeitado', 'Rejeitado')], default='novo', max_length=20),
        ),
    ]
