-- PROPOSED (NOT APPLIED) — media_scheduling schema RLS fix
-- DO NOT APPLY without explicit tech-lead authorization.
--
-- Fixes 1 authenticated policies that still use the broken
-- auth.jwt() ->> 'org_id' top-level claim (always NULL in Supabase).
-- Replaces with public.current_org_id() — the SECURITY DEFINER
-- trusted-table resolver applied to social_wiring on 2026-06-02.
--
-- PREREQUISITE: public.current_org_id() must exist (see
-- social-wiring 011_rls_current_org_id.sql Section 1).
--
-- Generated by sweep in feat/rls-codify-org-fn on 2026-06-02.
-- Source of truth: pg_policies on nyplttplcoyiiqjrvtiw.

-- ----- media_scheduling.invitations -----
DROP POLICY IF EXISTS "invitations_select_own_org" ON media_scheduling.invitations;
CREATE POLICY "invitations_select_own_org" ON media_scheduling.invitations
  FOR SELECT TO {, a, u, t, h, e, n, t, i, c, a, t, e, d, }
  USING ((org_id = current_org_id()));
