-- PROPOSED (NOT APPLIED) — storage schema RLS fix
-- DO NOT APPLY without explicit tech-lead authorization.
--
-- Fixes 4 authenticated policies that still use the broken
-- auth.jwt() ->> 'org_id' top-level claim (always NULL in Supabase).
-- Replaces with public.current_org_id() — the SECURITY DEFINER
-- trusted-table resolver applied to social_wiring on 2026-06-02.
--
-- PREREQUISITE: public.current_org_id() must exist (see
-- social-wiring 011_rls_current_org_id.sql Section 1).
--
-- Generated by sweep in feat/rls-codify-org-fn on 2026-06-02.
-- Source of truth: pg_policies on nyplttplcoyiiqjrvtiw.

-- ----- storage.objects -----
DROP POLICY IF EXISTS "erp_storage_delete" ON storage.objects;
CREATE POLICY "erp_storage_delete" ON storage.objects
  FOR DELETE TO {, a, u, t, h, e, n, t, i, c, a, t, e, d, }
  USING (((bucket_id ~~ 'erp-%'::text) AND ((storage.foldername(name))[1] = ((SELECT org_id FROM public.noctus_users WHERE id = (SELECT auth.uid()))))));

DROP POLICY IF EXISTS "erp_storage_insert" ON storage.objects;
CREATE POLICY "erp_storage_insert" ON storage.objects
  FOR INSERT TO {, a, u, t, h, e, n, t, i, c, a, t, e, d, }
  WITH CHECK (((bucket_id ~~ 'erp-%'::text) AND ((storage.foldername(name))[1] = ((SELECT org_id FROM public.noctus_users WHERE id = (SELECT auth.uid()))))));

DROP POLICY IF EXISTS "erp_storage_select" ON storage.objects;
CREATE POLICY "erp_storage_select" ON storage.objects
  FOR SELECT TO {, a, u, t, h, e, n, t, i, c, a, t, e, d, }
  USING (((bucket_id ~~ 'erp-%'::text) AND ((storage.foldername(name))[1] = ((SELECT org_id FROM public.noctus_users WHERE id = (SELECT auth.uid()))))));

DROP POLICY IF EXISTS "erp_storage_update" ON storage.objects;
CREATE POLICY "erp_storage_update" ON storage.objects
  FOR UPDATE TO {, a, u, t, h, e, n, t, i, c, a, t, e, d, }
  USING (((bucket_id ~~ 'erp-%'::text) AND ((storage.foldername(name))[1] = ((SELECT org_id FROM public.noctus_users WHERE id = (SELECT auth.uid()))))));
