#!/usr/bin/env python3
"""render-project-history.py — render the NDJSON ledger to PROJECT-HISTORY.md.

Reads ``project-history/ledger.ndjson`` (canonical structured store written
by ``noctus.dev.history_record`` + ``noctus.dev.archive``) and emits the
human-readable view at ``project-history/PROJECT-HISTORY.md``.

Behavior:

- One NDJSON line per project-stamping event. The ledger is append-only,
  so a single slug may have multiple records (e.g. split / historical
  backfill / live close). The renderer dedupes-by-slug-keep-latest by
  ``dates.closed`` so the human view shows one row per project.
- Rows sort by ``dates.closed`` DESC (most-recent at top).
- Table columns: Date | Slug | Scope | Status | Total Tokens | Short Summary.
- Idempotent — re-running on unchanged ledger produces byte-identical
  output (stable ordering: ties broken by slug ASC; pipe-character escape
  in summary cells; total-tokens formatted without thousands-separators).
- Replaces existing PROJECT-HISTORY.md content. Writes a placeholder
  header above the table; the placeholder warns against hand-editing.
- Invalid NDJSON raises ``ValueError`` with the line number — no silent
  swallow per the no-silent-errors rule.

Usage:
    python scripts/render-project-history.py                # render
    python scripts/render-project-history.py --check        # exit 1 if drifted
    python scripts/render-project-history.py --ledger PATH  # custom ledger
    python scripts/render-project-history.py --output PATH  # custom output

The pre-commit hook calls this without arguments when
``project-history/ledger.ndjson`` is staged or has been modified by an
archive-step earlier in the hook chain — the rendered output is then
``git add``-staged so the human view never drifts from the structured
source.

References:
- ``projects/project-history-ledger/PROJECT.md § 6 Phase 3``
- ``project-history/README.md``
- ``mcp/noctusai/tools/noctus/dev/history.py``
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

# Repo root resolved from this file's location — script lives at
# ``scripts/render-project-history.py``; parent's parent is the repo root.
REPO = Path(__file__).resolve().parents[1]

DEFAULT_LEDGER = REPO / "project-history" / "ledger.ndjson"
DEFAULT_OUTPUT = REPO / "project-history" / "PROJECT-HISTORY.md"

# The placeholder banner sits above the table in PROJECT-HISTORY.md. Its
# wording warns hand-editors away — the table below is generated.
_HEADER = (
    "# Project History\n"
    "\n"
    "_Auto-generated by scripts/render-project-history.py — do not edit by hand._\n"
    "_Source of truth: `project-history/ledger.ndjson` (see "
    "`projects/project-history-ledger/PROJECT.md`)._\n"
    "\n"
)

# Empty-ledger marker — the human-readable view still needs to render
# stably when the ledger has zero rows (fresh repo / pre-Phase-2 state).
_EMPTY_FOOTER = "_No project records yet — the ledger is empty._\n"

# Table column headers + alignment. Order matches the §6 Phase 3 spec.
_COLUMNS = [
    ("Date", ":---"),
    ("Slug", ":---"),
    ("Scope", ":---"),
    ("Status", ":---"),
    ("Total Tokens", "---:"),
    ("Short Summary", ":---"),
]


def parse_ledger(ledger_path: Path) -> list[dict[str, Any]]:
    """Parse the NDJSON ledger, raising on any malformed line.

    Returns the list of records in file order (caller dedupes/sorts).

    Raises:
        ValueError: malformed JSON, with the line number quoted.
        FileNotFoundError: ledger does not exist (caller may treat as empty).
    """
    if not ledger_path.exists():
        raise FileNotFoundError(f"ledger not found: {ledger_path}")
    records: list[dict[str, Any]] = []
    with ledger_path.open("r", encoding="utf-8") as fh:
        for lineno, raw in enumerate(fh, start=1):
            stripped = raw.strip()
            if not stripped:
                # Blank lines are tolerated (trailing newline at EOF; no
                # silent error — the line carries no data, so there's
                # nothing to swallow).
                continue
            try:
                rec = json.loads(stripped)
            except json.JSONDecodeError as e:
                raise ValueError(
                    f"invalid NDJSON at {ledger_path}:{lineno}: {e.msg} "
                    f"(line content: {stripped[:120]!r})"
                ) from e
            if not isinstance(rec, dict):
                raise ValueError(
                    f"NDJSON record at {ledger_path}:{lineno} is not a JSON "
                    f"object: {type(rec).__name__}"
                )
            records.append(rec)
    return records


def dedupe_latest_by_slug(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Collapse multi-stamping per slug → keep latest by ``dates.closed``.

    Ties on ``dates.closed`` resolve to file order (later line wins) —
    the ledger is append-only so a later line is the more recent event.

    Records lacking a ``dates.closed`` are kept under the empty-string key
    so they still surface in the rendered table (sorted last). They never
    silently disappear.
    """
    by_slug: dict[str, dict[str, Any]] = {}
    for rec in records:
        slug = rec.get("slug", "")
        if not slug:
            # No slug → use a synthetic key per-record so the row still
            # appears. Empty-slug rows are an upstream bug; we surface
            # them rather than swallow.
            slug = f"__no_slug__{id(rec)}"
        closed = (rec.get("dates") or {}).get("closed", "")
        prior = by_slug.get(slug)
        if prior is None:
            by_slug[slug] = rec
            continue
        prior_closed = (prior.get("dates") or {}).get("closed", "")
        # Lexicographic comparison on ISO YYYY-MM-DD is correct DESC sort
        # ordering; on tie, latest line (this `rec`) wins per append-only
        # convention (later = newer).
        if closed >= prior_closed:
            by_slug[slug] = rec
    return list(by_slug.values())


def _row_sort_key(rec: dict[str, Any]) -> tuple:
    """Sort key: closed-date DESC, then slug ASC (for stable idempotency).

    Python sorts ASC by default; we invert ``closed`` by negating its
    sort-position. The trick: tuples sort lexicographically, so wrapping
    ``closed`` in a class-less reverser is overkill — we just sort the
    full list once with ``reverse=True`` on a *composite* tuple, then
    apply a second pass for the slug ascending tiebreak.

    Easier: sort ASC by slug first (stable), then sort by closed DESC.
    Python's sort is stable, so the slug-ASC order is preserved within
    each ``closed`` group.
    """
    closed = (rec.get("dates") or {}).get("closed") or ""
    return closed


def sort_rows(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Sort DESC by ``dates.closed``, ASC by ``slug`` on tie. Stable."""
    # First pass: ASC slug. Second pass: DESC closed. Python's `sorted`
    # is stable so the slug order survives the second sort within each
    # closed-date group.
    by_slug = sorted(records, key=lambda r: r.get("slug", ""))
    return sorted(by_slug, key=_row_sort_key, reverse=True)


def _escape_cell(text: str) -> str:
    """Make a string safe for a Markdown table cell.

    Replaces newlines (would break the row) and escapes pipe characters
    (would break the column). Keep the original content; just neutralize
    the table-breaking chars.
    """
    if not text:
        return ""
    # Newlines → spaces; tabs → spaces; pipe → escaped pipe.
    cleaned = text.replace("\r\n", " ").replace("\n", " ").replace("\t", " ")
    cleaned = cleaned.replace("|", "\\|")
    # Collapse runs of spaces so the column stays tight.
    while "  " in cleaned:
        cleaned = cleaned.replace("  ", " ")
    return cleaned.strip()


def _format_tokens(rec: dict[str, Any]) -> str:
    """Return the total-tokens cell as a stable string."""
    tc = rec.get("token_count") or {}
    total = tc.get("total", 0)
    if not isinstance(total, (int, float)):
        return str(total)
    # Plain int formatting — no thousands-separators (locale-stable).
    return str(int(total))


def render_table(records: list[dict[str, Any]]) -> str:
    """Render the list of records into the Markdown table body.

    Returns the table text (header row + separator + data rows), no
    leading/trailing blank lines beyond the trailing newline.
    """
    if not records:
        return ""
    header = "| " + " | ".join(name for name, _ in _COLUMNS) + " |"
    sep = "| " + " | ".join(align for _, align in _COLUMNS) + " |"
    lines = [header, sep]
    for rec in records:
        closed = _escape_cell((rec.get("dates") or {}).get("closed") or "")
        slug = _escape_cell(rec.get("slug", ""))
        scope = _escape_cell(rec.get("scope", ""))
        status = _escape_cell(rec.get("status_at_close", ""))
        tokens = _format_tokens(rec)
        summary = _escape_cell(rec.get("short_summary", ""))
        lines.append(
            f"| {closed} | {slug} | {scope} | {status} | {tokens} | {summary} |"
        )
    return "\n".join(lines) + "\n"


def render_history(ledger_path: Path) -> str:
    """Compose the full PROJECT-HISTORY.md body from the ledger.

    Returns the string to write. Trailing newline included.
    """
    try:
        records = parse_ledger(ledger_path)
    except FileNotFoundError:
        # An absent ledger is the "empty" case (fresh repo / scaffold).
        # Phase 0 creates an empty marker file; absent file shouldn't
        # crash the renderer or block commits.
        records = []
    deduped = dedupe_latest_by_slug(records)
    rows = sort_rows(deduped)
    if not rows:
        return _HEADER + _EMPTY_FOOTER
    return _HEADER + render_table(rows)


def write_history(ledger_path: Path, output_path: Path) -> bool:
    """Render and write. Returns True if the file content changed."""
    rendered = render_history(ledger_path)
    existing = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
    if rendered == existing:
        return False
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    return True


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    p.add_argument(
        "--ledger",
        type=Path,
        default=DEFAULT_LEDGER,
        help=f"Path to NDJSON ledger (default: {DEFAULT_LEDGER.relative_to(REPO)})",
    )
    p.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Path to output Markdown (default: {DEFAULT_OUTPUT.relative_to(REPO)})",
    )
    p.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the rendered output differs from disk (no write).",
    )
    args = p.parse_args(argv)

    if args.check:
        rendered = render_history(args.ledger)
        existing = (
            args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        )
        if rendered != existing:
            print(
                f"[render-project-history] DRIFT: {args.output} would change",
                file=sys.stderr,
            )
            return 1
        return 0

    changed = write_history(args.ledger, args.output)
    if changed:
        print(f"[render-project-history] wrote {args.output}")
    else:
        print(f"[render-project-history] {args.output} unchanged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
