#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# stamp-seed-version.sh
#
# Writes the current git short SHA into the seed packages' `_version_static.py`
# files. Each seed consumer reads this at import-time via `noctusai_seed.__seed_version__`
# and `noctusai_lib.__lib_version__`. The MCP keeper detector
# `check_seed_version_propagation` compares the stamped value to current
# `git rev-parse --short HEAD` to surface drift.
#
# When to run:
#   - Automatically invoked by `scripts/pre-commit` (once per commit).
#   - Automatically invoked by `start.sh` (once per dev-server boot).
#   - Manually: run this script after a `git pull` if you did not re-run
#     `pip install -e seed/backend/...`. The keeper will tell you if you
#     forgot.
#
# Exit codes:
#   0 — stamped (or files already reflect the current SHA).
#   1 — git not available; keeper will see a `runtime:<sha>` or `unknown`
#       reading and flag accordingly.
# ──────────────────────────────────────────────────────────────
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo '')"
if [[ -z "$REPO_ROOT" ]]; then
    echo "[stamp-seed-version] git not available — skipping stamp." >&2
    exit 1
fi

SHA="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo 'unknown')"

_write_stamp() {
    local target="$1"
    local package_name="$2"
    cat >"$target" <<EOF
# Auto-generated by scripts/stamp-seed-version.sh.
# Reflects git HEAD at stamp time. DO NOT edit by hand.
# Re-stamp: run scripts/stamp-seed-version.sh (or commit again — pre-commit does it).
__version__ = "${SHA}"
EOF
    echo "[stamp-seed-version] ${package_name} stamped: ${SHA}"
}

_write_stamp \
    "$REPO_ROOT/seed/backend/framework/noctusai_seed/_version_static.py" \
    "noctusai_seed"

_write_stamp \
    "$REPO_ROOT/seed/backend/lib/noctusai_lib/_version_static.py" \
    "noctusai_lib"
