#!/usr/bin/env bash
# GENERATED by noctus.dev.agent_pull install_hook=true — do not edit; re-run agent_pull to update.
# Agent Packages (CONTRACT A5): on every push, sync this repo's project context (agent_context_sync) and
# learnings (agent_learnings_push) to Agent Studio. NEVER blocks the push and is never silent: on any
# failure it prints a loud message on stderr, writes `.agents-sync-pending` and exits 0; the next push
# retries and clears the marker on success.
# Needs ~/.config/noctus/agents.env (or the same names exported):
#   NOCTUS_HOME=<path to your noctusai checkout>
#   NOCTUS_AGENTS_URL=https://agents.noctusai.com
#   NOCTUS_AGENTS_TOKEN=pk_...
cat >/dev/null   # discard the ref lines git pipes to pre-push

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
MARKER="$ROOT/.agents-sync-pending"

fail() {
    echo "" >&2
    echo "🔴 agents-sync: $1" >&2
    echo "   The push is NOT blocked. Studio is behind this repo until the next successful push" >&2
    echo "   (marker: .agents-sync-pending — retried automatically on the next push)." >&2
    msg="$(printf '%s' "$1" | tr -d '"\\' | tr '\n' ' ')"
    printf '{"ts":"%s","failures":[{"step":"hook","errors":["%s"]}]}\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$msg" > "$MARKER"
    exit 0
}

# NOCTUS_HOME may live in the same env file as the token (a git hook does not see your shell's exports
# when pushed from an IDE or GUI client); an exported value wins.
ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/noctus/agents.env"
if [ -z "${NOCTUS_HOME:-}" ] && [ -f "$ENV_FILE" ]; then
    NOCTUS_HOME="$(sed -n 's/^NOCTUS_HOME=//p' "$ENV_FILE" | tail -1)"
fi
[ -n "${NOCTUS_HOME:-}" ] || fail "NOCTUS_HOME is not set (export it, or add NOCTUS_HOME=<noctusai checkout> to $ENV_FILE)"
PY="$NOCTUS_HOME/mcp/noctusai/.venv/bin/python"
RUNNER="$NOCTUS_HOME/scripts/agent-hooks/agent_sync_runner.py"
[ -x "$PY" ] && [ -f "$RUNNER" ] || fail "noctusai toolkit not found under NOCTUS_HOME=$NOCTUS_HOME (need $PY and $RUNNER)"

"$PY" "$RUNNER" consumer --repo "$ROOT" || fail "agent_sync_runner crashed (exit $?)"
exit 0
