-- Migration: store_live_scope
-- Generated by noctus.dev.scaffold_migration on 2026-10-02
-- Schema: public


-- ============================================================
-- Schema lock — pin name resolution to public, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = public, public;

-- store goes live (owner consent 2026-10-02, deploy/consent/store.prod.yml;
-- roadmap project-history/roadmaps/store-launch-2026-10.md M5).
UPDATE public.products
   SET deploy_scope = 'live',
       url_base     = 'https://store.noctusai.com'
 WHERE slug = 'store';
