-- Migration: mfa_policy
-- Generated by noctus.dev.scaffold_migration on 2026-10-04
-- Schema: public


-- ============================================================
-- Schema lock — pin name resolution to public, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = public, public;

-- =======================================================
-- TODO: Add your DDL here. Patterns available:
--   updated_at_function(schema)     -- emit once per schema
--   updated_at_trigger(schema, table) -- per table that has updated_at
--   rls_subquery_policy(table, ...)  -- per RLS-enabled table
-- See seed/lib/backend/noctusai_lib/domain/sql_templates.py
-- =======================================================

-- ============================================================
-- public.mfa_policy — admin-MFA mode per scope (platform-admin-mfa M3)
-- Scope is 'fleet' (the default for every product) or a product slug
-- (override). Read by the seed's MfaPolicy (service role); the
-- `require_admin_assurance` gate treats a missing row as 'off'.
-- Break-glass / off-switch: UPDATE this row (or the Supabase dashboard).
-- SERVICE-ROLE ONLY: RLS on, NO policies, and anon/authenticated are
-- REVOKEd — an admin who can write this table could switch MFA off for
-- themselves. Guarded by verify_db_guards probes (mfa_policy.*).
-- ============================================================
CREATE TABLE IF NOT EXISTS public.mfa_policy (
    scope      text PRIMARY KEY,
    mode       text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by uuid,
    CONSTRAINT mfa_policy_mode_check CHECK (mode IN ('off', 'warn', 'enforce'))
);

ALTER TABLE public.mfa_policy ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.mfa_policy FROM anon, authenticated;

-- The fleet default ships OFF: applying this migration changes nothing.
INSERT INTO public.mfa_policy (scope, mode)
VALUES ('fleet', 'off')
ON CONFLICT (scope) DO NOTHING;
