-- Migration: sso_token_redemptions
-- Generated by noctus.dev.scaffold_migration on 2026-10-06
-- Schema: public


-- ============================================================
-- Schema lock — pin name resolution to public, public
-- WHY:
--   * RLS isolation: every product's tables live in its own
--     schema; un-locked search_path leaks resolution to
--     whatever the caller's session set.
--   * Cross-product safety: prevents accidental shadowing
--     when two products define identically-named helpers
--     (e.g. `current_org_id()`) in different schemas.
-- IDEMPOTENT: session-level setting; no DDL emitted.
-- ============================================================
SET search_path = public, public;

-- ============================================================
-- public.sso_token_redemptions — single-use SSO bridge tokens
-- /api/sso/session inserts the token's `jti`; a duplicate (PK) means the
-- token was already redeemed -> 401. SERVICE-ROLE ONLY: RLS on, NO
-- policies, anon/authenticated REVOKEd.
-- ============================================================
CREATE TABLE IF NOT EXISTS public.sso_token_redemptions (
    jti         text PRIMARY KEY,
    user_id     uuid,
    product     text NOT NULL,
    redeemed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sso_token_redemptions_redeemed_at
    ON public.sso_token_redemptions (redeemed_at);

ALTER TABLE public.sso_token_redemptions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.sso_token_redemptions FROM anon, authenticated;
