-- ============================================================================
-- IgIg — card hub tables for Cliente + Negócio (roadmap cardhub-igig-crm-2026-09)
--
-- 🔴 GENERATED — do not hand-edit. Regenerate with:
--     python -c "from app.card_hub import gerar_migration_card_hub as g; \
--                open('migrations/019_card_hub.sql','w').write(g())"
-- (run from products/igig/backend). `tests/test_card_hub_wiring.py` fails if
-- this file drifts from `noctusai_lib.domain.card_hub.card_hub_migration` for
-- the configs in `app/card_hub.py`.
--
-- No SQLite mirror, by design (like 013/014/016, this file is not named
-- `*_igig_*`): the card hub is reached ONLY through PostgREST (decision D-A1,
-- `NOC-REMEDIATE[card-hub-recordstore]` in the seed package).
--
-- Both sections emit the same `igig` bucket statements; every one of them is
-- idempotent (ON CONFLICT DO NOTHING / DROP POLICY IF EXISTS), so the repeat is
-- a no-op. Prerequisites: 006 (cliente), 008 (profissional), 017
-- (pipeline_stages), 018 (negocio).
-- ============================================================================

-- Card hub (cliente) -- generated by noctusai_lib.domain.card_hub.sql

SET search_path = igig, public;

-- Notes: one `descricao` per card (partial unique index) + many `comentario`.
-- Soft-delete only: a deleted note leaves a tombstone.
CREATE TABLE IF NOT EXISTS igig.cliente_notas (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      UUID NOT NULL,
    cliente_id UUID NOT NULL REFERENCES igig.cliente(id) ON DELETE CASCADE,
    autor_id    UUID,
    tipo        TEXT NOT NULL DEFAULT 'comentario' CHECK (tipo IN ('descricao', 'comentario')),
    corpo       TEXT NOT NULL,
    editado_em  TIMESTAMPTZ,
    deleted_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cliente_notas_entity ON igig.cliente_notas (cliente_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cliente_notas_org ON igig.cliente_notas (org_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_cliente_notas_one_descricao
    ON igig.cliente_notas (cliente_id)
    WHERE tipo = 'descricao' AND deleted_at IS NULL;
ALTER TABLE igig.cliente_notas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cliente_notas_select_own_org" ON igig.cliente_notas;
CREATE POLICY "cliente_notas_select_own_org" ON igig.cliente_notas FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.cliente_notas;
CREATE POLICY "service_role_bypass" ON igig.cliente_notas FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ONE org tag catalogue (case-insensitive unique name) + per-card links.
CREATE TABLE IF NOT EXISTS igig.cliente_tags (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      UUID NOT NULL,
    nome        TEXT NOT NULL,
    cor         TEXT NOT NULL CHECK (cor ~ '^#[0-9a-fA-F]{6}$'),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_cliente_tags_org_nome ON igig.cliente_tags (org_id, lower(nome));
ALTER TABLE igig.cliente_tags ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cliente_tags_select_own_org" ON igig.cliente_tags;
CREATE POLICY "cliente_tags_select_own_org" ON igig.cliente_tags FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.cliente_tags;
CREATE POLICY "service_role_bypass" ON igig.cliente_tags FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS igig.cliente_tag_links (
    cliente_id UUID NOT NULL REFERENCES igig.cliente(id) ON DELETE CASCADE,
    tag_id      UUID NOT NULL REFERENCES igig.cliente_tags(id) ON DELETE CASCADE,
    org_id      UUID NOT NULL,
    criado_por  UUID,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (cliente_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_cliente_tag_links_tag ON igig.cliente_tag_links (tag_id);
CREATE INDEX IF NOT EXISTS idx_cliente_tag_links_org ON igig.cliente_tag_links (org_id);
ALTER TABLE igig.cliente_tag_links ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cliente_tag_links_select_own_org" ON igig.cliente_tag_links;
CREATE POLICY "cliente_tag_links_select_own_org" ON igig.cliente_tag_links FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.cliente_tag_links;
CREATE POLICY "service_role_bypass" ON igig.cliente_tag_links FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Assignment: points at the member source's id, NEVER at a name.
CREATE TABLE IF NOT EXISTS igig.cliente_membros (
    cliente_id UUID NOT NULL REFERENCES igig.cliente(id) ON DELETE CASCADE,
    profissional_id UUID NOT NULL REFERENCES igig.profissional(id) ON DELETE CASCADE,
    org_id      UUID NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (cliente_id, profissional_id)
);
CREATE INDEX IF NOT EXISTS idx_cliente_membros_member ON igig.cliente_membros (profissional_id);
CREATE INDEX IF NOT EXISTS idx_cliente_membros_org ON igig.cliente_membros (org_id);
ALTER TABLE igig.cliente_membros ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cliente_membros_select_own_org" ON igig.cliente_membros;
CREATE POLICY "cliente_membros_select_own_org" ON igig.cliente_membros FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.cliente_membros;
CREATE POLICY "service_role_bypass" ON igig.cliente_membros FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Trello "Datas" on the entity row.
ALTER TABLE igig.cliente
    ADD COLUMN IF NOT EXISTS data_inicio             TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS data_entrega            TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS entrega_concluida       BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS lembrete_minutos_antes  INTEGER,
    ADD COLUMN IF NOT EXISTS recorrencia             TEXT;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cliente_recorrencia_valid') THEN
        ALTER TABLE igig.cliente
            ADD CONSTRAINT cliente_recorrencia_valid
            CHECK (recorrencia IS NULL OR recorrencia IN ('diaria', 'semanal', 'mensal', 'anual'));
    END IF;
END $$;

-- One row per scheduled reminder fire; the partial index is the drain path.
CREATE TABLE IF NOT EXISTS igig.cliente_lembretes (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        UUID NOT NULL,
    cliente_id UUID NOT NULL REFERENCES igig.cliente(id) ON DELETE CASCADE,
    dispara_em    TIMESTAMPTZ NOT NULL,
    enviado_em    TIMESTAMPTZ,
    cancelado_em  TIMESTAMPTZ,
    destinatarios JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cliente_lembretes_pending ON igig.cliente_lembretes (dispara_em)
    WHERE enviado_em IS NULL AND cancelado_em IS NULL;
CREATE INDEX IF NOT EXISTS idx_cliente_lembretes_entity ON igig.cliente_lembretes (cliente_id, created_at DESC);
ALTER TABLE igig.cliente_lembretes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cliente_lembretes_select_own_org" ON igig.cliente_lembretes;
CREATE POLICY "cliente_lembretes_select_own_org" ON igig.cliente_lembretes FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.cliente_lembretes;
CREATE POLICY "service_role_bypass" ON igig.cliente_lembretes FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Checklists (ad-hoc or stage-instantiated; many per card) + items.
CREATE TABLE IF NOT EXISTS igig.cliente_checklists (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      UUID NOT NULL,
    cliente_id UUID NOT NULL REFERENCES igig.cliente(id) ON DELETE CASCADE,
    titulo      TEXT NOT NULL,
    posicao     INTEGER NOT NULL DEFAULT 0,
    origem      TEXT NOT NULL CHECK (origem IN ('ad_hoc', 'etapa')),
    etapa_id    UUID REFERENCES igig.pipeline_stages(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cliente_checklists_entity ON igig.cliente_checklists (cliente_id, posicao);
ALTER TABLE igig.cliente_checklists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cliente_checklists_select_own_org" ON igig.cliente_checklists;
CREATE POLICY "cliente_checklists_select_own_org" ON igig.cliente_checklists FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.cliente_checklists;
CREATE POLICY "service_role_bypass" ON igig.cliente_checklists FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS igig.cliente_checklist_itens (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id         UUID NOT NULL,
    checklist_id   UUID NOT NULL REFERENCES igig.cliente_checklists(id) ON DELETE CASCADE,
    texto          TEXT NOT NULL,
    concluido      BOOLEAN NOT NULL DEFAULT false,
    concluido_em   TIMESTAMPTZ,
    concluido_por  UUID,
    posicao        INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cliente_checklist_itens_checklist ON igig.cliente_checklist_itens (checklist_id, posicao);
ALTER TABLE igig.cliente_checklist_itens ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cliente_checklist_itens_select_own_org" ON igig.cliente_checklist_itens;
CREATE POLICY "cliente_checklist_itens_select_own_org" ON igig.cliente_checklist_itens FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.cliente_checklist_itens;
CREATE POLICY "service_role_bypass" ON igig.cliente_checklist_itens FOR ALL TO service_role USING (true) WITH CHECK (true);

-- The table-driven retention + upload allow-list (platform-wide, no org_id).
CREATE TABLE IF NOT EXISTS igig.cliente_documento_tipos (
    tipo_documento  TEXT PRIMARY KEY,
    categoria_lgpd  TEXT NOT NULL,
    retencao_dias   INTEGER,
    identidade      BOOLEAN NOT NULL DEFAULT false,
    ativo           BOOLEAN NOT NULL DEFAULT true,
    descricao       TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE igig.cliente_documento_tipos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cliente_documento_tipos_select_authenticated" ON igig.cliente_documento_tipos;
CREATE POLICY "cliente_documento_tipos_select_authenticated" ON igig.cliente_documento_tipos FOR SELECT TO authenticated
  USING (true);
DROP POLICY IF EXISTS "service_role_bypass" ON igig.cliente_documento_tipos;
CREATE POLICY "service_role_bypass" ON igig.cliente_documento_tipos FOR ALL TO service_role USING (true) WITH CHECK (true);
INSERT INTO igig.cliente_documento_tipos
    (tipo_documento, categoria_lgpd, retencao_dias, identidade, ativo, descricao)
VALUES
    ('contrato', 'contratual', 1825, false, true, 'Contratos e aditivos'),
    ('proposta', 'contratual', 1095, false, true, 'Propostas comerciais'),
    ('comprovante_pagamento', 'financeiro', 1825, false, true, 'Comprovantes de pagamento'),
    ('comprovante_endereco', 'cadastral', 730, false, true, 'Comprovante de endereço'),
    ('outro', 'nao_classificado', 365, false, true, 'Outro documento não classificado'),
    ('rg', 'identidade', 1825, true, false, 'RG (retenção pendente de intake LGPD)'),
    ('cpf', 'identidade', 1825, true, false, 'CPF (retenção pendente de intake LGPD)')
ON CONFLICT (tipo_documento) DO NOTHING;

-- Documents (soft delete with reason) + the append-only access log.
CREATE TABLE IF NOT EXISTS igig.cliente_documentos (
    id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id                 UUID NOT NULL,
    cliente_id UUID NOT NULL REFERENCES igig.cliente(id) ON DELETE CASCADE,
    storage_path           TEXT NOT NULL,
    nome_original          TEXT NOT NULL,
    mime_type              TEXT NOT NULL,
    tamanho_bytes          BIGINT NOT NULL CHECK (tamanho_bytes >= 0),
    tipo_documento         TEXT NOT NULL REFERENCES igig.cliente_documento_tipos(tipo_documento),
    categoria_lgpd         TEXT NOT NULL,
    retencao_ate           DATE,
    enviado_por            UUID,
    deleted_at             TIMESTAMPTZ,
    delete_motivo          TEXT,
    delete_solicitado_por  UUID,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cliente_documentos_entity ON igig.cliente_documentos (cliente_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cliente_documentos_org ON igig.cliente_documentos (org_id);
CREATE INDEX IF NOT EXISTS idx_cliente_documentos_retencao ON igig.cliente_documentos (retencao_ate)
    WHERE deleted_at IS NULL AND retencao_ate IS NOT NULL;
ALTER TABLE igig.cliente_documentos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cliente_documentos_select_own_org" ON igig.cliente_documentos;
CREATE POLICY "cliente_documentos_select_own_org" ON igig.cliente_documentos FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.cliente_documentos;
CREATE POLICY "service_role_bypass" ON igig.cliente_documentos FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS igig.cliente_documento_acessos (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        UUID NOT NULL,
    documento_id  UUID NOT NULL REFERENCES igig.cliente_documentos(id) ON DELETE CASCADE,
    usuario_id    UUID,
    acao          TEXT NOT NULL CHECK (acao IN ('view', 'download', 'delete')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_cliente_documento_acessos_documento ON igig.cliente_documento_acessos (documento_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cliente_documento_acessos_org ON igig.cliente_documento_acessos (org_id);
ALTER TABLE igig.cliente_documento_acessos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cliente_documento_acessos_select_own_org" ON igig.cliente_documento_acessos;
CREATE POLICY "cliente_documento_acessos_select_own_org" ON igig.cliente_documento_acessos FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.cliente_documento_acessos;
CREATE POLICY "service_role_bypass" ON igig.cliente_documento_acessos FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Private document bucket; object RLS keys on the org_id first path segment.
INSERT INTO storage.buckets (id, name, public)
VALUES ('igig', 'igig', false)
ON CONFLICT (id) DO NOTHING;
DROP POLICY IF EXISTS "igig_storage_select" ON storage.objects;
CREATE POLICY "igig_storage_select" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'igig' AND (storage.foldername(name))[1] = (SELECT public.current_org_id())::text);
DROP POLICY IF EXISTS "igig_storage_insert" ON storage.objects;
CREATE POLICY "igig_storage_insert" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'igig' AND (storage.foldername(name))[1] = (SELECT public.current_org_id())::text);
DROP POLICY IF EXISTS "igig_storage_update" ON storage.objects;
CREATE POLICY "igig_storage_update" ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'igig' AND (storage.foldername(name))[1] = (SELECT public.current_org_id())::text);
DROP POLICY IF EXISTS "igig_storage_delete" ON storage.objects;
CREATE POLICY "igig_storage_delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'igig' AND (storage.foldername(name))[1] = (SELECT public.current_org_id())::text);
DROP POLICY IF EXISTS "igig_storage_service" ON storage.objects;
CREATE POLICY "igig_storage_service" ON storage.objects FOR ALL TO service_role
  USING (bucket_id = 'igig')
  WITH CHECK (bucket_id = 'igig');

-- Operator-authored checklist lines. NO `concluido` column: completion is
-- DERIVED (valor_texto / a live documento_id). Deleting the file keeps the line.
CREATE TABLE IF NOT EXISTS igig.cliente_checklist_extras (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        UUID NOT NULL,
    cliente_id UUID NOT NULL REFERENCES igig.cliente(id) ON DELETE CASCADE,
    label         TEXT NOT NULL,
    tipo          TEXT NOT NULL CHECK (tipo IN ('texto', 'arquivo')),
    valor_texto   TEXT,
    documento_id  UUID REFERENCES igig.cliente_documentos(id) ON DELETE SET NULL,
    ordem         INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_cliente_checklist_extras_entity ON igig.cliente_checklist_extras (cliente_id, ordem, created_at)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_cliente_checklist_extras_org ON igig.cliente_checklist_extras (org_id);
CREATE INDEX IF NOT EXISTS idx_cliente_checklist_extras_documento ON igig.cliente_checklist_extras (documento_id)
    WHERE documento_id IS NOT NULL;
ALTER TABLE igig.cliente_checklist_extras ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "cliente_checklist_extras_select_own_org" ON igig.cliente_checklist_extras;
CREATE POLICY "cliente_checklist_extras_select_own_org" ON igig.cliente_checklist_extras FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.cliente_checklist_extras;
CREATE POLICY "service_role_bypass" ON igig.cliente_checklist_extras FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Card hub (negocio) -- generated by noctusai_lib.domain.card_hub.sql

SET search_path = igig, public;

-- Notes: one `descricao` per card (partial unique index) + many `comentario`.
-- Soft-delete only: a deleted note leaves a tombstone.
CREATE TABLE IF NOT EXISTS igig.negocio_notas (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      UUID NOT NULL,
    negocio_id UUID NOT NULL REFERENCES igig.negocio(id) ON DELETE CASCADE,
    autor_id    UUID,
    tipo        TEXT NOT NULL DEFAULT 'comentario' CHECK (tipo IN ('descricao', 'comentario')),
    corpo       TEXT NOT NULL,
    editado_em  TIMESTAMPTZ,
    deleted_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_negocio_notas_entity ON igig.negocio_notas (negocio_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_negocio_notas_org ON igig.negocio_notas (org_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_negocio_notas_one_descricao
    ON igig.negocio_notas (negocio_id)
    WHERE tipo = 'descricao' AND deleted_at IS NULL;
ALTER TABLE igig.negocio_notas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "negocio_notas_select_own_org" ON igig.negocio_notas;
CREATE POLICY "negocio_notas_select_own_org" ON igig.negocio_notas FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.negocio_notas;
CREATE POLICY "service_role_bypass" ON igig.negocio_notas FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ONE org tag catalogue (case-insensitive unique name) + per-card links.
CREATE TABLE IF NOT EXISTS igig.negocio_tags (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      UUID NOT NULL,
    nome        TEXT NOT NULL,
    cor         TEXT NOT NULL CHECK (cor ~ '^#[0-9a-fA-F]{6}$'),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_negocio_tags_org_nome ON igig.negocio_tags (org_id, lower(nome));
ALTER TABLE igig.negocio_tags ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "negocio_tags_select_own_org" ON igig.negocio_tags;
CREATE POLICY "negocio_tags_select_own_org" ON igig.negocio_tags FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.negocio_tags;
CREATE POLICY "service_role_bypass" ON igig.negocio_tags FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS igig.negocio_tag_links (
    negocio_id UUID NOT NULL REFERENCES igig.negocio(id) ON DELETE CASCADE,
    tag_id      UUID NOT NULL REFERENCES igig.negocio_tags(id) ON DELETE CASCADE,
    org_id      UUID NOT NULL,
    criado_por  UUID,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (negocio_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_negocio_tag_links_tag ON igig.negocio_tag_links (tag_id);
CREATE INDEX IF NOT EXISTS idx_negocio_tag_links_org ON igig.negocio_tag_links (org_id);
ALTER TABLE igig.negocio_tag_links ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "negocio_tag_links_select_own_org" ON igig.negocio_tag_links;
CREATE POLICY "negocio_tag_links_select_own_org" ON igig.negocio_tag_links FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.negocio_tag_links;
CREATE POLICY "service_role_bypass" ON igig.negocio_tag_links FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Assignment: points at the member source's id, NEVER at a name.
CREATE TABLE IF NOT EXISTS igig.negocio_membros (
    negocio_id UUID NOT NULL REFERENCES igig.negocio(id) ON DELETE CASCADE,
    profissional_id UUID NOT NULL REFERENCES igig.profissional(id) ON DELETE CASCADE,
    org_id      UUID NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (negocio_id, profissional_id)
);
CREATE INDEX IF NOT EXISTS idx_negocio_membros_member ON igig.negocio_membros (profissional_id);
CREATE INDEX IF NOT EXISTS idx_negocio_membros_org ON igig.negocio_membros (org_id);
ALTER TABLE igig.negocio_membros ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "negocio_membros_select_own_org" ON igig.negocio_membros;
CREATE POLICY "negocio_membros_select_own_org" ON igig.negocio_membros FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.negocio_membros;
CREATE POLICY "service_role_bypass" ON igig.negocio_membros FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Trello "Datas" on the entity row.
ALTER TABLE igig.negocio
    ADD COLUMN IF NOT EXISTS data_inicio             TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS data_entrega            TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS entrega_concluida       BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS lembrete_minutos_antes  INTEGER,
    ADD COLUMN IF NOT EXISTS recorrencia             TEXT;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'negocio_recorrencia_valid') THEN
        ALTER TABLE igig.negocio
            ADD CONSTRAINT negocio_recorrencia_valid
            CHECK (recorrencia IS NULL OR recorrencia IN ('diaria', 'semanal', 'mensal', 'anual'));
    END IF;
END $$;

-- One row per scheduled reminder fire; the partial index is the drain path.
CREATE TABLE IF NOT EXISTS igig.negocio_lembretes (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        UUID NOT NULL,
    negocio_id UUID NOT NULL REFERENCES igig.negocio(id) ON DELETE CASCADE,
    dispara_em    TIMESTAMPTZ NOT NULL,
    enviado_em    TIMESTAMPTZ,
    cancelado_em  TIMESTAMPTZ,
    destinatarios JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_negocio_lembretes_pending ON igig.negocio_lembretes (dispara_em)
    WHERE enviado_em IS NULL AND cancelado_em IS NULL;
CREATE INDEX IF NOT EXISTS idx_negocio_lembretes_entity ON igig.negocio_lembretes (negocio_id, created_at DESC);
ALTER TABLE igig.negocio_lembretes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "negocio_lembretes_select_own_org" ON igig.negocio_lembretes;
CREATE POLICY "negocio_lembretes_select_own_org" ON igig.negocio_lembretes FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.negocio_lembretes;
CREATE POLICY "service_role_bypass" ON igig.negocio_lembretes FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Checklists (ad-hoc or stage-instantiated; many per card) + items.
CREATE TABLE IF NOT EXISTS igig.negocio_checklists (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      UUID NOT NULL,
    negocio_id UUID NOT NULL REFERENCES igig.negocio(id) ON DELETE CASCADE,
    titulo      TEXT NOT NULL,
    posicao     INTEGER NOT NULL DEFAULT 0,
    origem      TEXT NOT NULL CHECK (origem IN ('ad_hoc', 'etapa')),
    etapa_id    UUID REFERENCES igig.pipeline_stages(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_negocio_checklists_entity ON igig.negocio_checklists (negocio_id, posicao);
ALTER TABLE igig.negocio_checklists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "negocio_checklists_select_own_org" ON igig.negocio_checklists;
CREATE POLICY "negocio_checklists_select_own_org" ON igig.negocio_checklists FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.negocio_checklists;
CREATE POLICY "service_role_bypass" ON igig.negocio_checklists FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS igig.negocio_checklist_itens (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id         UUID NOT NULL,
    checklist_id   UUID NOT NULL REFERENCES igig.negocio_checklists(id) ON DELETE CASCADE,
    texto          TEXT NOT NULL,
    concluido      BOOLEAN NOT NULL DEFAULT false,
    concluido_em   TIMESTAMPTZ,
    concluido_por  UUID,
    posicao        INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_negocio_checklist_itens_checklist ON igig.negocio_checklist_itens (checklist_id, posicao);
ALTER TABLE igig.negocio_checklist_itens ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "negocio_checklist_itens_select_own_org" ON igig.negocio_checklist_itens;
CREATE POLICY "negocio_checklist_itens_select_own_org" ON igig.negocio_checklist_itens FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.negocio_checklist_itens;
CREATE POLICY "service_role_bypass" ON igig.negocio_checklist_itens FOR ALL TO service_role USING (true) WITH CHECK (true);

-- The table-driven retention + upload allow-list (platform-wide, no org_id).
CREATE TABLE IF NOT EXISTS igig.negocio_documento_tipos (
    tipo_documento  TEXT PRIMARY KEY,
    categoria_lgpd  TEXT NOT NULL,
    retencao_dias   INTEGER,
    identidade      BOOLEAN NOT NULL DEFAULT false,
    ativo           BOOLEAN NOT NULL DEFAULT true,
    descricao       TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE igig.negocio_documento_tipos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "negocio_documento_tipos_select_authenticated" ON igig.negocio_documento_tipos;
CREATE POLICY "negocio_documento_tipos_select_authenticated" ON igig.negocio_documento_tipos FOR SELECT TO authenticated
  USING (true);
DROP POLICY IF EXISTS "service_role_bypass" ON igig.negocio_documento_tipos;
CREATE POLICY "service_role_bypass" ON igig.negocio_documento_tipos FOR ALL TO service_role USING (true) WITH CHECK (true);
INSERT INTO igig.negocio_documento_tipos
    (tipo_documento, categoria_lgpd, retencao_dias, identidade, ativo, descricao)
VALUES
    ('contrato', 'contratual', 1825, false, true, 'Contratos e aditivos'),
    ('proposta', 'contratual', 1095, false, true, 'Propostas comerciais'),
    ('comprovante_pagamento', 'financeiro', 1825, false, true, 'Comprovantes de pagamento'),
    ('comprovante_endereco', 'cadastral', 730, false, true, 'Comprovante de endereço'),
    ('outro', 'nao_classificado', 365, false, true, 'Outro documento não classificado'),
    ('rg', 'identidade', 1825, true, false, 'RG (retenção pendente de intake LGPD)'),
    ('cpf', 'identidade', 1825, true, false, 'CPF (retenção pendente de intake LGPD)')
ON CONFLICT (tipo_documento) DO NOTHING;

-- Documents (soft delete with reason) + the append-only access log.
CREATE TABLE IF NOT EXISTS igig.negocio_documentos (
    id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id                 UUID NOT NULL,
    negocio_id UUID NOT NULL REFERENCES igig.negocio(id) ON DELETE CASCADE,
    storage_path           TEXT NOT NULL,
    nome_original          TEXT NOT NULL,
    mime_type              TEXT NOT NULL,
    tamanho_bytes          BIGINT NOT NULL CHECK (tamanho_bytes >= 0),
    tipo_documento         TEXT NOT NULL REFERENCES igig.negocio_documento_tipos(tipo_documento),
    categoria_lgpd         TEXT NOT NULL,
    retencao_ate           DATE,
    enviado_por            UUID,
    deleted_at             TIMESTAMPTZ,
    delete_motivo          TEXT,
    delete_solicitado_por  UUID,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_negocio_documentos_entity ON igig.negocio_documentos (negocio_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_negocio_documentos_org ON igig.negocio_documentos (org_id);
CREATE INDEX IF NOT EXISTS idx_negocio_documentos_retencao ON igig.negocio_documentos (retencao_ate)
    WHERE deleted_at IS NULL AND retencao_ate IS NOT NULL;
ALTER TABLE igig.negocio_documentos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "negocio_documentos_select_own_org" ON igig.negocio_documentos;
CREATE POLICY "negocio_documentos_select_own_org" ON igig.negocio_documentos FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.negocio_documentos;
CREATE POLICY "service_role_bypass" ON igig.negocio_documentos FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS igig.negocio_documento_acessos (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        UUID NOT NULL,
    documento_id  UUID NOT NULL REFERENCES igig.negocio_documentos(id) ON DELETE CASCADE,
    usuario_id    UUID,
    acao          TEXT NOT NULL CHECK (acao IN ('view', 'download', 'delete')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_negocio_documento_acessos_documento ON igig.negocio_documento_acessos (documento_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_negocio_documento_acessos_org ON igig.negocio_documento_acessos (org_id);
ALTER TABLE igig.negocio_documento_acessos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "negocio_documento_acessos_select_own_org" ON igig.negocio_documento_acessos;
CREATE POLICY "negocio_documento_acessos_select_own_org" ON igig.negocio_documento_acessos FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.negocio_documento_acessos;
CREATE POLICY "service_role_bypass" ON igig.negocio_documento_acessos FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Private document bucket; object RLS keys on the org_id first path segment.
INSERT INTO storage.buckets (id, name, public)
VALUES ('igig', 'igig', false)
ON CONFLICT (id) DO NOTHING;
DROP POLICY IF EXISTS "igig_storage_select" ON storage.objects;
CREATE POLICY "igig_storage_select" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'igig' AND (storage.foldername(name))[1] = (SELECT public.current_org_id())::text);
DROP POLICY IF EXISTS "igig_storage_insert" ON storage.objects;
CREATE POLICY "igig_storage_insert" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'igig' AND (storage.foldername(name))[1] = (SELECT public.current_org_id())::text);
DROP POLICY IF EXISTS "igig_storage_update" ON storage.objects;
CREATE POLICY "igig_storage_update" ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'igig' AND (storage.foldername(name))[1] = (SELECT public.current_org_id())::text);
DROP POLICY IF EXISTS "igig_storage_delete" ON storage.objects;
CREATE POLICY "igig_storage_delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'igig' AND (storage.foldername(name))[1] = (SELECT public.current_org_id())::text);
DROP POLICY IF EXISTS "igig_storage_service" ON storage.objects;
CREATE POLICY "igig_storage_service" ON storage.objects FOR ALL TO service_role
  USING (bucket_id = 'igig')
  WITH CHECK (bucket_id = 'igig');

-- Operator-authored checklist lines. NO `concluido` column: completion is
-- DERIVED (valor_texto / a live documento_id). Deleting the file keeps the line.
CREATE TABLE IF NOT EXISTS igig.negocio_checklist_extras (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        UUID NOT NULL,
    negocio_id UUID NOT NULL REFERENCES igig.negocio(id) ON DELETE CASCADE,
    label         TEXT NOT NULL,
    tipo          TEXT NOT NULL CHECK (tipo IN ('texto', 'arquivo')),
    valor_texto   TEXT,
    documento_id  UUID REFERENCES igig.negocio_documentos(id) ON DELETE SET NULL,
    ordem         INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_negocio_checklist_extras_entity ON igig.negocio_checklist_extras (negocio_id, ordem, created_at)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_negocio_checklist_extras_org ON igig.negocio_checklist_extras (org_id);
CREATE INDEX IF NOT EXISTS idx_negocio_checklist_extras_documento ON igig.negocio_checklist_extras (documento_id)
    WHERE documento_id IS NOT NULL;
ALTER TABLE igig.negocio_checklist_extras ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "negocio_checklist_extras_select_own_org" ON igig.negocio_checklist_extras;
CREATE POLICY "negocio_checklist_extras_select_own_org" ON igig.negocio_checklist_extras FOR SELECT TO authenticated
  USING (org_id = (SELECT public.current_org_id()));
DROP POLICY IF EXISTS "service_role_bypass" ON igig.negocio_checklist_extras;
CREATE POLICY "service_role_bypass" ON igig.negocio_checklist_extras FOR ALL TO service_role USING (true) WITH CHECK (true);
